### ISSUE TITLE
Room name can be blank if you add a ZWJ

### ISSUE THREAD

**Issue by jonaskuske** [benawad/dogehouse#1]
If the name only has spaces you'll get a "Name can't be blank" error, if it only has ZWJs it errors with "Must have at least 2 characters", but if you use a ZWJ (so it's not blank) as well as spaces (to match the character requirement) you can circumvent the validation and create rooms with no name.

No showstopper I guess, but given that the "mustn't be blank" error is already in place, I figure you'd prefer it if all rooms have actual names? 😄

Edit: wohoo, #1!! 🚀

**Comment by samarmohan** [comment]
Reference to #35

**Comment by goldyydev** [comment]
This is already patched
