### ISSUE TITLE
Cannot scroll down

### ISSUE THREAD

**Issue by bekbull** [benawad/dogehouse#1001]
**Describe the bug**
When I am in a room I cannot scroll down and see users in the last row

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Room'
2. Try to scroll down

**Expected behavior**
I had to see users in the last row.

**Screenshots**
![Screenshot from 2021-03-15 11-53-09](https://user-images.githubusercontent.com/40839494/111114513-2a320d80-8585-11eb-8975-fcd2a3b32cd9.png)

**What device are you on?**
Ubuntu 20.04 and Firefox last version
**Additional context**

**Comment by yummyweb** [comment]
I cannot reproduce this issue, please put the device information.

**Comment by edumorlom** [comment]
I am able to reproduce the Issue on the latest Firefox version on MacOS 11.3 Beta.

I can't reproduce on Safari nor Chrome.

<img width="453" alt="Screen Shot 2021-03-15 at 10 35 21 AM" src="https://user-images.githubusercontent.com/11444894/111132877-28af1800-857a-11eb-8e7a-bb5b9fb05ece.png">
