### ISSUE TITLE
INSTRUCTIONS: Build the electron wrapper (still WIP but functional)

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#1002]
Below are the steps to build the electron wrapper from source
> **NOTE:** The wrapper is still WIP so there ~~may be~~ are many bugs. So run it with that in mind. And please please open an issue on github if you run into one.

- Pull [staging](https://github.com/benawad/dogehouse/tree/staging) branch
- Follow steps mentioned in https://github.com/benawad/dogehouse/blob/staging/baklava/HOW_TO_RUN.md
- Run the command `npm run build:%YOUR_PLATFORM_CODE%` 
- Install the app from the built file located in `/builds`

**Comment by amitojsingh366** [comment]
I think this should be pinned for now

**Comment by amitojsingh366** [comment]
also should i attach a zip with all the builds in it?

**Comment by TheOtterlord** [comment]
Instructions are in [baklava/README.md](https://github.com/benawad/dogehouse/blob/staging/baklava/README.md), current builds are available in [releases](https://github.com/benawad/dogehouse/releases).
