### ISSUE TITLE
emoji to high

### ISSUE THREAD

**Issue by abdpro300** [benawad/dogehouse#1003]
![image](https://user-images.githubusercontent.com/79415304/111119956-d3740600-857b-11eb-83f8-38df035e7a74.png)
thats it
emoji to high

**Comment by Rexogamer** [comment]
Can't reproduce, can you share your device and browser info?

**Comment by edumorlom** [comment]
Can't reproduce either on latest Firefox, Chrome and Safari on MacOS 11.3

**Comment by yummyweb** [comment]
I also can't reproduce. Please provide proper information i.e. device information or steps to reproduce, otherwise I suggest to close this issue.

**Comment by navidmafi** [comment]
Can't reproduce 

![image](https://user-images.githubusercontent.com/46371349/111351930-ea5c4a80-8698-11eb-9e72-80e7a483d4e2.png)

please provide more info

**Comment by A-Yamout** [comment]
@abdpro300 Could you please tell us what browser and the version of it that you are using?

**Comment by ghost** [comment]
This just seems extremely stale, considering we switched to a completely new design. I would recommend closing this.
