### ISSUE TITLE
No Sign Up to Join Room

### ISSUE THREAD

**Issue by edumorlom** [benawad/dogehouse#1008]
Currently, anyone who joins a chat needs to login, but I think one should be able to join calls without having o sign up.
This is how Twitch, Twitter, and Instagram, Youtube do it.

One should be able to listen in a public room without needing to login. If they don't log in, they are limited to just listening and can't chat or even talk. They need to create an account to do that.

**Comment by augielavin** [comment]
Yea we should

**Comment by overlisted** [comment]
this is planned
