### ISSUE TITLE
Null displayed when person invites you to a room

### ISSUE THREAD

**Issue by DiamondMiner88** [benawad/dogehouse#103]
![fsdflkjsdflsd](https://user-images.githubusercontent.com/33725716/107842615-8f71c380-6d79-11eb-83d9-8a21ebf437b8.PNG)
Could replicate on mobile & desktop Firefox

**Comment by benawad** [comment]
What do you do to replicate?

**Comment by DiamondMiner88** [comment]
1. Create a room (In this case I used a private room)
2. Get the creator of the room to invite you to the room
3. You will see "null invited you to a room, would you like to join?"
Initially I found this while testing with a friend, however to test again I created an alt and followed it but it did not appear online for me and as such I could not invite it to a room.
I had to drag my friend back to test; issue still present.

**Comment by benawad** [comment]
I think this should be fixed
