### ISSUE TITLE
refresh button is not at the top

### ISSUE THREAD

**Issue by boorah** [benawad/dogehouse#1039]
**Describe the bug**

The refresh button in the home page is displayed below the joined room. Is this the intended behavior?

**To Reproduce**

1. Join a room
2. Go to the home page

**Expected behavior**

The expected behavior would be that the button remains at the top.

**Screenshots**

![Screenshot from 2021-03-15 22-17-32](https://user-images.githubusercontent.com/39365143/111190281-eec32d80-85dc-11eb-9609-e53236440877.png)

![Screenshot from 2021-03-15 22-17-21](https://user-images.githubusercontent.com/39365143/111190346-fbe01c80-85dc-11eb-90c7-c886815755f0.png)

**What device are you on?**

Ubuntu 18.04
Same thing happens on my Android device

**Comment by fahadfarooqmurawat** [comment]
Can I work on this?

**Comment by fahadfarooqmurawat** [comment]
Although, after going through the code, I am pretty sure this is the intended behavior and not a bug.

**Comment by boorah** [comment]
> Although, after going through the code, I am pretty sure this is the intended behavior and not a bug.

yea, I know. But doesn't this look weird? Maybe they'll change it in the new design

**Comment by daloes** [comment]
> > Although, after going through the code, I am pretty sure this is the intended behavior and not a bug.
> 
> yea, I know. But doesn't this look weird? Maybe they'll change it in the new design

Well if you think about it, refresh action is tied to list of available rooms. When you are in room already it doesn't make sense to refresh it eg. put it in same group below button
