### ISSUE TITLE
Unimportant: ask to speak button is slightly off center

### ISSUE THREAD

**Issue by DeanHuffnagle** [benawad/dogehouse#104]
The ask to speak button appears to be slightly to the left of where it should be. I hope not many programmers have OCD. 

![Screenshot_20210213-005605](https://user-images.githubusercontent.com/78249916/107843160-c4d8da00-6d96-11eb-990c-3ff4d2503fc2.png)

**Comment by SuperSonicHub1** [comment]
![Screenshot](https://user-images.githubusercontent.com/25624882/111015823-a86d9480-8378-11eb-9136-c69c227f9dcb.png)
@DeanHuffnagle Seems that this issue has already been resolved. Consider closing it.

**Comment by DeanHuffnagle** [comment]
I didn't know it was up to me to close the issue. I am new to github, My apologies.

**Comment by SuperSonicHub1** [comment]
@DeanHuffnagle No problem.
