### ISSUE TITLE
Title changes to changes to header.title for a time while loading

### ISSUE THREAD

**Issue by HarryAllen1** [benawad/dogehouse#1044]
**Describe the bug**
When the website loads, for a short amount of time, instead of DogeHouse being the title, "header.title" becomes the title for a few milliseconds
**To Reproduce**
1. Go to http://dogehouse.tv
2. Watch the website name in the tabs
3. Notice the title change to "header.title" for a time

**Expected behavior**
The title stays as DogeHouse the entire time

**What device are you on?**
Microsoft Edge Beta Version 89.0.774.54

**Comment by ermalsh** [comment]
@benawad can we make the header title static as "DogeHouse"? This might cause issues when muted, since `muted | DogeHouse` is what the title becomes.

**Comment by benawad** [comment]
@ermalsh we can make the default title static and then wait to update it until translation is loaded
