### ISSUE TITLE
a way to follow someone by username

### ISSUE THREAD

**Issue by justinjordan1** [benawad/dogehouse#1045]
Currently, if you want to create a private room, you have to invite them via the follow page. However, in order to follow someone you have to go through the extra step of both people being in a public room. Making the ability to follow people more clear would probably greatly increase the use cases for the program

**Comment by nadirabbas** [comment]
@benawad are you currently working on the search users page? I saw it is half done.

**Comment by benawad** [comment]
I'm probably going to wait and finish search with new-design, but someone is working on creating the route `/user/:username` which should help with this some what

**Comment by xiuxiu62** [comment]
Would it be feasible to have a separate friend list to accomplish this?  It'd definitely be overkill but could open up room for other features down the line.  I don't know if it would make sense to have both a friend list and a following list though.

**Comment by nadirabbas** [comment]
fixed by #1143
