### ISSUE TITLE
CSS Height off when many listeners

### ISSUE THREAD

**Issue by wes337** [benawad/dogehouse#1050]
**Describe the bug**
If there are enough listeners to necessitate a scrollbar, the height of the container will go off (see screenshot)

**To Reproduce**
1. Go to a room with many listeners (or create mock listeners to simulate)
2. Open the "Chat" menu

**Expected behavior**
Should be aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/9464690/111204956-56727c00-85cf-11eb-9421-2cfe67d70a6c.png)
![](http://g.recordit.co/iA1U3oFmbU.gif)

**What device are you on?**
Windows, Firefox and Chrome.
Only reproduced on Chrome when scrolling (see gif)

**Comment by ysfBenali** [comment]
@wes337 Yeah, I'm using Chrome on Mac and I'm getting the same behavior.

@benawad I tried to add vertical scrolling and it just solved the issue. (See GIF)


![ScreenShots](https://user-images.githubusercontent.com/26151852/111322428-35f70000-8669-11eb-943f-8cdcb8b894a2.png)

**Comment by benawad** [comment]
pr welcome :)

**Comment by ysfBenali** [comment]
I'm working on it :-)

**Comment by TheOtterlord** [comment]
Closed as Kofta is deprecated
