### ISSUE TITLE
DogeAmbassadors

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#1067]
problem: there are developers that want to contribute to DogeHouse but don't know how / need someone to ask questions to

I'd like to have some `DogeAmbassadors` that help onboard new contributors.

If you are interested in helping, make sure you are on the discord https://discord.gg/EvdprcXZ3q , grab the `DogeAmbassador` role and I'm going to start directing new people to the `#help` channel

**Comment by ghost** [comment]
If anyone of you are facing issues finding the role, 
Then head over to #rules [ID - 821189028858298410] and click on the respective emoji below the message to obtain the role !

**Comment by ajmnz** [comment]
@benawad do we close this?
