### ISSUE TITLE
Cant hear or speak unless coming in from a new tab

### ISSUE THREAD

**Issue by Rudrava** [benawad/dogehouse#1068]
While today I tried to join today in a room I was a speaker in I couldn't speak or hear then I went to a different channel and there I was just a listener but couldn't hear anything.
I then tried to refresh or regrant permissions but didn't work. So I tried it from a new tab with the old one still there, no work
finally had to shut down the browser and reopen and opened dogeHouse in a new tab, it worked finally, I heard in a room that someone else had a similar bug for which I can say it is a bug.
I don't know how to reproduce.

**Comment by benawad** [comment]
next time this happens, click on the persons profile you can't hear, then tap on their avatar 5 times and copy/paste the console in devtools

**Comment by yummyweb** [comment]
This is probably due to websockets. As @benawad suggested, click on the person's avatar and paste the info here.

**Comment by Rudrava** [comment]
did not get any error like such since

**Comment by ajmnz** [comment]
@Rudrava I believe this has been fixed as @Rudrava stated that couldn't reproduce it. Request to reopen if this still happens.
