### ISSUE TITLE
Distinct urls for users.

### ISSUE THREAD

**Issue by willdoescode** [benawad/dogehouse#1079]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I go to share mine or someone else's profile and the link is just dogehouse.tv/user or dogehouse.tv/me

**Describe the solution you'd like**
I think it would be nice to have a url like `dogehouse.tv/@username` so that you can look at other peoples profiles as well as share your own that way.

**Describe alternatives you've considered**
I have also considered just having uuids for the url in place of usernames but I feel like that would be hard to use.

**Comment by tejasag** [comment]
I think it would be better too this way

**Comment by KaiDevrim** [comment]
WillDoesCode has a lot of great ideas.

**Comment by willdoescode** [comment]
thank you kai

**Comment by nadirabbas** [comment]
@benawad I can work on this. should be pretty simple
