### ISSUE TITLE
Avatar error after Twitter avatar update

### ISSUE THREAD

**Issue by ptaberg** [benawad/dogehouse#1085]
**Describe the bug**
Avatar shows alt if the avatar was removed from the network you logged with.

**To Reproduce**
1. Login with Twitter
2. Go to Twitter and change your avatar there
3. Go back to DogeHouse

**Expected behavior**
After updating the avatar in Twitter, the avatar in DogeHouse should be updated.

**Screenshots**
![Screen Shot 2021-03-16 at 12 16 36 PM](https://user-images.githubusercontent.com/34740585/111284748-764a8400-8651-11eb-8b57-5f88fb6d58b1.png)

**What device are you on?**
Browser Chrome

**Additional context**

**Comment by drvladb** [comment]
Updating the twitter profile picture will break current stored images, from the doc:

> If a 403 or 404 error is returned when trying to access a profile image, refresh the user object using GET users/show to retrieve the most recent profile_image_url or profile_image_url_https. The URL may have changed, which happens for instance when the user updates their profile image.

Maybe a profile picture refresh button?

Doc:
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners#outdated-profile-images

**Comment by ptaberg** [comment]
@drvladb I think we can check Image exist, and if not then display some default image. Updating avatar from Social Media services requires a backend change. Also, users which see your profile couldn't have the possibility to refresh your photo, and they will see an error.

**Comment by nadirabbas** [comment]
@ptaberg we already check that, but for some reason that seems broken too.

**Comment by nadirabbas** [comment]
for now you can just copy the avatar URL and put it in avatar input

**Comment by 1kvsn** [comment]
@nadirabbas my PR for another Avatar related bug fixes this issue as well since the component is the same. Please check: https://github.com/benawad/dogehouse/pull/1623

If src image doesn't exist, it will cause error and then it'll use the prop **usernameForErrorImg**

**Comment by TheOtterlord** [comment]
Closing as Kofta is deprecated. If the issue persists in Kibbeh, please reopen
