### ISSUE TITLE
Audio Not working. 

### ISSUE THREAD

**Issue by Yasir900aslam** [benawad/dogehouse#109]
This bug happens on an Android Google chrome. Even after the interaction with the browser, I can hear people talking in the room. 
Steps to reproduce:
1-  Open dogehouse in google chrome Andriod, Click the room you want to enter.  
2- Accept the user interaction dialog; Once you are speaker, Audio is muted(Can't hear anyone), Even though the browser has an access to mic.

**Comment by nadirabbas** [comment]
It works for me tho, may be this is fixed @benawad
