### ISSUE TITLE
Overlay like in Discord

### ISSUE THREAD

**Issue by VayerMaking** [benawad/dogehouse#1093]
**Is your feature request related to a problem? Please describe.**
I just thought it would be a nice feature, especially for mobile users.

**Describe the solution you'd like**
Addition of a Discord like overlay when using another app at the same time.
![image](https://user-images.githubusercontent.com/36741716/111300795-23c19580-865a-11eb-801a-66214f12bae6.png)
![image](https://user-images.githubusercontent.com/36741716/111300905-4358be00-865a-11eb-81bc-35ae41bd001c.png)

**Describe alternatives you've considered**
Also the app working in the background while using another app on mobile could be just ok.

**Comment by nadirabbas** [comment]
damn, this is gonna be a big feature

**Comment by VayerMaking** [comment]
I know, but I also think it would be very useful and attract more clients

**Comment by TheOtterlord** [comment]
Not used it, but it seems that [gelectron](https://github.com/hiitiger/gelectron) could be an option? As I assume this would be part of baklava

**Comment by BronzW** [comment]
Yeah,  I don't think there is a web api that interacts with desktop applications right now.

**Comment by finnycode** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-overview 

that might work idk

**Comment by VayerMaking** [comment]
I found an open source discord overlay, especially for linux. So it could be used for reference.
[link](https://github.com/trigg/Discover)

**Comment by amitojsingh366** [comment]
I'm already working on it actually...

**Comment by amitojsingh366** [comment]
@TheOtterlord yea it has to be in bakavla, i think i already mentioned to you that i'm working on it. Also got the approval from ben. but it'll take time

**Comment by amitojsingh366** [comment]
oh, i forgot to mention it here but I've had gone ahead and added the overly sometime ago *(#1404)*. it's really primitive as of rn and will get to improving it soon.
