### ISSUE TITLE
option to handover room admin role

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1097]
currently its random, sometimes unwanted people become owners

**Comment by jamesql** [comment]
I'd be interested in working on this when I get home in a few hours if no one does it by then.

// had people complain about this to me a few hours ago

**Comment by nadirabbas** [comment]
@benawad

**Comment by jamesql** [comment]
should the previous creator be a mod after they have transferred ownership?

**Comment by nadirabbas** [comment]
yeah, that makes sense @jamesql

**Comment by jamesql** [comment]
i should have it done by the end of the day

**Comment by benawad** [comment]
sounds good, go for it!

**Comment by goldyydev** [comment]
Going to close this as it appears that it got added already.
