### ISSUE TITLE
Mic list

### ISSUE THREAD

**Issue by CreamyCheese384** [benawad/dogehouse#11]
Microphone list is 3 options but all the options are empty

**Comment by starbuck93** [comment]
![image](https://user-images.githubusercontent.com/5626027/107788516-7ee02f80-6d1e-11eb-8caf-ea8914ab94fd.png)

Like this? Take a screenshot?

**Comment by CreamyCheese384** [comment]
No, no, like this:![](https://user-images.githubusercontent.com/69057421/107801078-ebc7e980-6d5f-11eb-8de6-6557dd138f36.jpg)
