### ISSUE TITLE
add more custom emotes

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#1109]
Stick image in `kofta/public/emotes` and update the list in `kofta/src/app/modules/room-chat/EmoteData.ts`

**Comment by benawad** [comment]
Let's keep this under 100 or something

**Comment by drvladb** [comment]
Do GIF emojis work?

**Comment by benawad** [comment]
@drvladb one way to find out 😄

**Comment by drvladb** [comment]
![](https://user-images.githubusercontent.com/33793511/111358822-2a074000-8661-11eb-9f33-4016e4807ad5.gif)

**Comment by JDOG787** [comment]
nice!

**Comment by vi241** [comment]
Ben, we have 193 emojis, should we add more?

**Comment by HarrisonMayotte** [comment]
Per recent announcement in #info on discord, no more emojis for now.
