### ISSUE TITLE
Speaker Session is persisted even after user has left the room.

### ISSUE THREAD

**Issue by Yasir900aslam** [benawad/dogehouse#111]
Steps to reproduce: 
1- Once you are a speaker in a room and left the room. 
2- Rejoin the Room, You would be still be acting as a Speaker. 

Mitigation: 
Upon leaving the room, User should be prompted if they really want to leave the room and Speaker session should be cleaned upon approval.

**Comment by benawad** [comment]
this is the behavior that I want
