### ISSUE TITLE
Custom emotes are at the bottom of the emoji picker,  I want them at the top

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#1110]

**Comment by nadirabbas** [comment]
i tried setting the `include` prop on `emoji-mart`, but the thing is, I think they have a bug in the package where it doesn't pickup the `custom` element in the `include` array. it accepts all other categories, and honors the order.

**Comment by benawad** [comment]
we might need to fork/pr then

**Comment by nadirabbas** [comment]
yeah, I'll see what I can do

**Comment by ajmnz** [comment]
We got custom emote picker @ kibbeh now
