### ISSUE TITLE
Doge House, Electron Build error on Linux

### ISSUE THREAD

**Issue by JamalLyons** [benawad/dogehouse#1112]
I'm getting errors when building Doge house for election on Linux. This has been tested on windows and mac and works. 
Steps I took:
- cloned the repo
- cd baklava
- npm i 
- npm i -D 
- npm run build:linux

Next, it built the files fine and I was able to get the deb file. I ran my package manager and I believe it installed okay. Lastly I run `dogehouse` in my terminal to start the app and got this error:

```
user@pc ~> dogehouse
load_input_helper [1918]: Using XFree86 keyboard layout.
load_input_helper [1920]: XKB support is required to accurately determine keyboard characters!
/opt/DogeHouse/dogehouse: symbol lookup error: /opt/DogeHouse/resources/app.asar.unpacked/node_modules/iohook/builds/electron-v85-linux-x64/build/Release/uiohook.so: undefined symbol: xkb_x11_get_core_keyboard_device_id
user@pc ~ [127]> 
```
The Linux distro I'm running is Pop os. Thanks for reading.

**Comment by xendaya** [comment]
Binary Format issue? Cuz I had the same

**Comment by yummyweb** [comment]
I will work on this issue.

**Comment by yummyweb** [comment]
@maksklaus What is your discord, so I can connect with you about the issue.

**Comment by xendaya** [comment]
@yummyweb  i don't use discord

**Comment by yummyweb** [comment]
ok no problem.

**Comment by yummyweb** [comment]
As far as I can tell the error is due to iohook. A similar issue was raised in iohook. This is the issue: https://github.com/wilix-team/iohook/issues/268. For linux, I believe this should fix it: `sudo apt-get install -y libxkbcommon-x11-0`. Please confirm and tell.

**Comment by xendaya** [comment]
> As far as I can tell the error is due to iohook. A similar issue was raised in iohook. This is the issue: [wilix-team/iohook#268](https://github.com/wilix-team/iohook/issues/268). For linux, I believe this should fix it: `sudo apt-get install -y libxkbcommon-x11-0`. Please confirm and tell.

thank you for the solution, it worked perfectly after this

**Comment by yummyweb** [comment]
@maksklaus please put your discord username and tag here so i can DM you about this fix and how it worked.

**Comment by TheOtterlord** [comment]
> @yummyweb i don't use discord

posted by maksklaus

**Comment by JamalLyons** [comment]
> > As far as I can tell the error is due to iohook. A similar issue was raised in iohook. This is the issue: [wilix-team/iohook#268](https://github.com/wilix-team/iohook/issues/268). For linux, I believe this should fix it: `sudo apt-get install -y libxkbcommon-x11-0`. Please confirm and tell.
> 
> thank you for the solution, it worked perfectly after this

Oh it worked for you? That did nothing for me.

**Comment by overlisted** [comment]
i don't feel like installing something myself to run an appimage, are you gonna fix this somehow?

**Comment by yummyweb** [comment]
I don't think we can fix it. At least not right now. @overlisted AppImage is a viable option so we advise to do that.

**Comment by yummyweb** [comment]
@maksklaus please put your system information here. We need it.

**Comment by xendaya** [comment]
{
  "name": "elec",
  "version": "1.0.0",
  "description": "Appname",
  "author": "author <author@mail.com>",
  "main": "main.js",
  "scripts": {
     "postinstall": "install-app-deps",
    "start": "npm install && electron ./app",
    "pack": "build --dir",
    "dist": "build"
  },
    "build": {
    "appId": "yourappid",
    "category": "your.app.category.type",
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    },
    "win": {
      "target": "squirrel",
      "icon": "build/icon.ico"
    }
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^6.0.1",
    "electron-builder": "^21.2.0",
    "electron-rebuild": "^1.8.6"
  },
  "dependencies": {
    "chart.js": "^2.8.0",
    "ejs": "~1.0.0",
    "electron-print": "^1.0.2",
    "electron-store": "^4.0.0",
    "electron-window-manager": "^1.0.6",
    "express": "^4.17.1",
    "express-session": "^1.16.2",
    "mysql": "github:mysqljs/mysql",
    "python-shell": "^1.0.8"
  }
}

//this is my script

changed into this, if anyone understands

"pack": "electron-builder --dir",
  "dist": "electron-builder"

**Comment by yummyweb** [comment]
No yours system info like your os info, not this.

**Comment by xendaya** [comment]
> No yours system info like your os info, not this.

i don't really have the best spec


Type | Full High Definition (FHD) | Full High Definition (FHD) | Ultra High Definition (UHD)
-- | -- | -- | --
Panel technology | Wide Viewing Angle (WVA) | Wide Viewing Angle (WVA) | Wide Viewing Angle (WVA)
Luminance (typical) | 400 nits | 400 nits | 400 nits
Dimensions (active area): |   |   |  
  | Height | 165.24 mm (6.51 in.) | 165.24 mm (6.51 in.) | 165.24 mm (6.51 in.)
  | Width | 293.76 mm (11.57 in.) | 293.76 mm (11.57 in.) | 293.76 mm (11.57 in.)
  | Diagonal | 337.82 mm (13.30 in.) | 337.82 mm (13.30 in.) | 337.82 mm (13.30 in.)
Native resolution | 1920 x 1080 | 1920 x 1080 | 3840 x 2160
Megapixels | 2.07 | 2.07 | 8.29
Pixels per inch (PPI) | 166 | 166 | 331
Contrast ratio (min) | 1000:1 | 1000:1 | 1000:1
Response time (max) | 30 ms | 30 ms | 30 ms
Refresh rate | 60 Hz | 60 Hz | 60 Hz
Horizontal view angle | 89 | 89 | 89
Vertical view angle | 89 | 89 | 89
Pixel pitch | 0.15 mm | 0.15 mm | 0.08 mm
Power consumption (maximum) | 2.9 W | 2.9 W | 5.41 W
Anti-glare vs Anti-reflective | Anti-reflective | Anti-glare | Anti-reflective
Touch options | Yes | No | Yes

**Comment by yummyweb** [comment]
Do not make this hard for me. Send me your linux distro and linux version just tell me which distru u using. That's it.

**Comment by TheOtterlord** [comment]
Essentially, what operating system do you use? what subset of linux? (e.g. rasperry pi os, ubuntu, popos, etc)

**Comment by JamalLyons** [comment]
> > No yours system info like your os info, not this.
> 
> i don't really have the best spec
> 
> Type	Full High Definition (FHD)	Full High Definition (FHD)	Ultra High Definition (UHD)
> Panel technology	Wide Viewing Angle (WVA)	Wide Viewing Angle (WVA)	Wide Viewing Angle (WVA)
> Luminance (typical)	400 nits	400 nits	400 nits
> Dimensions (active area):	 	 	 
>  	Height	165.24 mm (6.51 in.)	165.24 mm (6.51 in.)
....

omg dude sent his monitor stats lmao

**Comment by amitojsingh366** [comment]
This issue has been solved. Please build from latest source or get the [latest release](https://github.com/benawad/dogehouse/releases/latest)
