### ISSUE TITLE
Multiple emojis in a Chat Message cause emojies to be text

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#1115]
**Describe the bug**
Multiple custom emojis (currently only the BTTV ones) cause emojis to be shown as text.

**To Reproduce**
1. Create Room
2. Open Chat
3. Open Emoji Picker
4. Scroll down to BetterTTV section
5. Click on MonkaS emote 2 times (![](https://dogehouse.tv/emotes/monkas.png))
6. Send message
7. See wrong formatting

**Expected behavior**
The multiple emojis should be shown by their images insted of text

**Screenshots**
![image](https://user-images.githubusercontent.com/33793511/111350068-1b685b00-8658-11eb-8735-10bc76ca0b5f.png)

**What device are you on?**
Chrome 89, Win 10

**Comment by navidmafi** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/46371349/111351198-2a6efd80-8698-11eb-80ba-9283b491bdd8.png)
Firefox 86 - Linux Mint 20

**Comment by drvladb** [comment]
Should be platform agnostic.

**Comment by tejxv** [comment]
adding a space between the emojis somehow solves the problem
