### ISSUE TITLE
Sound managing

### ISSUE THREAD

**Issue by RodrigoLee2006** [benawad/dogehouse#1123]
I do not know wheter someone else has already suggested it, or if it has already been implemented, but it would be nice to be able to manage the sound of the people that are talking, just like in discord, for example, when you are in a voice chat and right click the users in the voice chat and you can manage them, mute them, make their voice lower or higher, etc.
In my opinion, a solution to this would be either by creating an option when you click the user to adjust the volume or to make a panel on one of the sides with sliders of all users that can be used to control their sounds.

Hope you guys read it! Thanks!
(Sorry by my bad english and bad drawing skills
![suggsetion_doge](https://user-images.githubusercontent.com/64716063/111362213-49a46580-866d-11eb-8a7a-d713955a0526.jpg)
)

**Comment by amitojsingh366** [comment]
This is already exists afaik

**Comment by Gitter499** [comment]
Nope. Each user can only adjust their own volume. A moderator can kick or ban someone but they can’t mute them.

**Comment by amitojsingh366** [comment]
@Gitter499 no you can reduce/increase anyone's volume
and muting functionality can be achieved by just removing them from speaker
![image](https://user-images.githubusercontent.com/35400192/111364601-80e13980-86a2-11eb-9574-26a20c197c13.png)

**Comment by Gitter499** [comment]
Oh ok. I don’t remember this being there so must be a new feature. OP probably wanted muting but not kicking from speaker, which could be achieved by sliding the volume to 0. I guess a dedicated mute button would be nice.

Thanks for the info!

**Comment by alon-abadi** [comment]
To me this actually makes sense in a way. Some users have bad mics, static noises or incredibly loud mics, but I still think every user should have the final say as for their own config. Maybe admin can manipulate user volume for the entire room (in case of a very loud user or a very quiet one) but users still should have the ability to override with their own preferences (exists today).
