### ISSUE TITLE
Add a button to enable/disable sound (mute/unmute headphones/speakers)

### ISSUE THREAD

**Issue by alon-abadi** [benawad/dogehouse#1130]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but would love a button to enable/disable global sound from site temporarily (including room admin) without needing to access computer settings. Current sound options are limited per user, and sometimes require either muting the tab (which is not possible when the site operates as a chrome app).

**Describe the solution you'd like**
Add a button in the bottom interface.

**Additional context**
![image](https://user-images.githubusercontent.com/3868775/111377061-e801ec80-86a8-11eb-9d37-b8e2638cabb2.png)

edit: clarify speakers = headphones/sound devices, not people.

**Comment by drvladb** [comment]
Duplicate #41 and #706
