### ISSUE TITLE
"description" placeholder when scheduling a room is static text and not linked to translation

### ISSUE THREAD

**Issue by degrootruben** [benawad/dogehouse#1131]
When the room schedule dialog is open there is a field for a description of the room. The placeholder for this component is static and is it not possible to give a translation for this value. It can be found in ScheduleRoomModal.tsx line 134. I think this line should be `placeholder={t("modules.scheduledRooms.modal.roomDescription")}` or something like that.

This is my first time writing an issue so please give me some feedback if you have some!

**Comment by ermalsh** [comment]
Issue looks good! Can be considered an Enhancement or a Bug. 

For new contributors, this is an easy one: 
This can be implemented, we just have to include the new translation in `ScheduleRoomModal.tsx:134` and run `npm run i18`. This will create the translation keys, along with adding the new Translation to each `translation.json`.

**Comment by degrootruben** [comment]
Thanks! So I could go and do this fix now?

**Comment by ermalsh** [comment]
yes

**Comment by degrootruben** [comment]
@ermalsh Running `npm run i18` doesnt add my translation key. What could be the problem?

**Comment by ermalsh** [comment]
> @ermalsh Running `npm run i18` doesnt add my translation key. What could be the problem?

Are you running `npm run i18` in `kofta/` directory?

**Comment by degrootruben** [comment]
Yes

**Comment by ermalsh** [comment]
@degrootruben add it to the EN `translation.json` and then run `npm run i18`. I'm working on fixing the issue with the script.

**Comment by degrootruben** [comment]
Will do. Thanks.
