### ISSUE TITLE
Room counter isn't working

### ISSUE THREAD

**Issue by miguelcarreiro** [benawad/dogehouse#1135]
**Describe the bug**
When I'm not in a room, the room counter shows a wrong number of people inside.

**To Reproduce**
1. Enter Dogehouse and login;
2. Watch room counter;
3. Enter into a room, and check that the number of people inside isn't the same as the counter shown before.

**Expected behavior**
The counter should have the correct number of people inside a room.

**Screenshots**
I recorded a video (without audio), that shows the behaviour of the counter:

https://user-images.githubusercontent.com/17125543/111390994-9e66d100-86ab-11eb-8bd1-cd20dab8c96d.mp4

**What device are you on?**
Chrome 89.0.4389.90 (64-bit) in Linux Mint 19.3.

**Additional context**
When I'm in a room, the counter works fine.

**Comment by jamesql** [comment]
could be this:

1) Servers we're restarting or down for one reason or another
2) People left the room and the following events could have occurred

// I could be wrong about this but its a start

```
       # kousa/lib/beef/mutations/rooms.ex
       # line 135

        # the room is decremented based on this new_people_list
        # so if this is the case this would never be called and the room would not be decremented
        new_people_list = Enum.filter(room.peoplePreviewList, fn x -> x.id != user_id end)

          decrement_room_people_count(
            room.id,
            new_people_list # decremented based on this list
          )
```

**Comment by daloes** [comment]
If you enter the room and then go back with home button, counter shows correct value, When you leave room with "Leave room" it's borked again

**Comment by amitojsingh366** [comment]
I think this has been fixed
