### ISSUE TITLE
Toggle "speaker" to "listener" moves user back to "request speaker"

### ISSUE THREAD

**Issue by MrMalloc** [benawad/dogehouse#114]
When you klick on "Go Back To Listener" you are moved back to "Request to speek" instead of "Listener"

**Comment by Percyvalmg** [comment]
I think it's more like, when you leave a room and then enter again you come back as a person requesting to speak even though you just want to be  a listener.

**Comment by MrMalloc** [comment]
Yes that happens as well.

**Comment by Salman2301** [comment]
related #102
