### ISSUE TITLE
Follower count stuck

### ISSUE THREAD

**Issue by Rudrava** [benawad/dogehouse#1145]
I was just randomly roaming about when I saw that my follower count was stuck posting ss below.

## this shows i have 4 followers
![image](https://user-images.githubusercontent.com/58327905/111410618-18747580-86ff-11eb-9d6f-3f45bd78cfe0.png)

## this shows i have only 2
![image](https://user-images.githubusercontent.com/58327905/111410735-4bb70480-86ff-11eb-9d38-f8d738ae0ebf.png)

**Comment by nadirabbas** [comment]
did you try reloading?

**Comment by Rudrava** [comment]
> did you try reloading?

**Forgot  to mention that**
yea i tried reloading but it did not update 
updated only when I opened it in a new tab

**Comment by yummyweb** [comment]
this happened with me

**Comment by nadirabbas** [comment]
try hard reloading

**Comment by overlisted** [comment]
(hard reloading is shirt ctrl r)

**Comment by TheOtterlord** [comment]
Kofta is now deprecated. If this issue persists on the new site, please reopen
