### ISSUE TITLE
Can't hear anything in mobile device.

### ISSUE THREAD

**Issue by ronakkaria01** [benawad/dogehouse#1150]
I was trying the app on my android device and it does not work. I dont know if my settings are wrong or whatever. But it's not working.

Thanks

**Comment by nadirabbas** [comment]
it works on Chrome, Android for me

**Comment by drvladb** [comment]
@ronakkaria01 Please attach reproduction instructions and system details.

**Comment by TheOtterlord** [comment]
@ronakkaria01 does the [new design](https://next.dogehouse.tv) work?

**Comment by nadirabbas** [comment]
for me it does

**Comment by ajmnz** [comment]
@ronakkaria01 Will close this as we haven't heard back from you since you posted the issue. If this is still a problem, please request to reopen the issue.
