### ISSUE TITLE
Update profile without a profile picture

### ISSUE THREAD

**Issue by MusashiAsada** [benawad/dogehouse#1151]
**Describe the bug**
When trying to update my profile's displaying name it gives me an error. It says that I have an invalid "invalid image"/profile picture. I currently have the default twitter profile picture which leads me to think that is the problem.

**To Reproduce**
1. Go to profile
2. Click on edit profile
3. Change name while having default profile picture
4. See error, "invalid image"

**Expected behavior**
Being able to update my profile's display name even though I have the default profile picture.

**What device are you on?**
Mac book pro, Mac OS Big Sur 11.2

**Comment by ptaberg** [comment]
@MusashiAsada , good point, I have issue which can be solved with it #1085

**Comment by wes337** [comment]
What's the image URL? Could be failing the regex pattern

**Comment by MusashiAsada** [comment]
Here's the URL: https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png

**Comment by nadirabbas** [comment]
yeah the regex is for a different type of profile picture URL: https://pbs.twimg.com/profile_images/1295038552661725184/LzFeB7Dj_400x400.jpg

your has `default_profile_images` in it, I'll fix that.

**Comment by MusashiAsada** [comment]
Thank you! I don't completely understand what the issue is but I'm trying to learn. I just wanted to contribute with something to make this as good as possible!

**Comment by nadirabbas** [comment]
fixed by #1155
