### ISSUE TITLE
When Leaving a Room with the chat window open, the chat window stays open

### ISSUE THREAD

**Issue by dk-raw** [benawad/dogehouse#1157]
**When I click the button to leave a room with the room's chat window open, the chat window remains open even if I join other rooms.**

**Comment by drvladb** [comment]
@dk-raw Can't reproduce, can you please attach a video or reproduction instructions. Also, it would be nice to know system details.

**Comment by daloes** [comment]
also can't reproduce on w10 chrome 87. Chat only stays open if I leave room via home, as expected, but not when via "Leave room"

**Comment by dk-raw** [comment]
**My bad, I thought that clicking the doge in the left corner was leaving the room**
