### ISSUE TITLE
Scheduled room link not working

### ISSUE THREAD

**Issue by MrPoll0** [benawad/dogehouse#1169]
**Describe the bug**
When I enter any scheduled room link, it fails to fetch.

**To Reproduce**
1. Go to any scheduled room link

**Expected behavior**
Show up the information of that scheduled room.

**Screenshots**
https://gyazo.com/87803681efaa291f8db947588b9647d5

**What device are you on?**
Browser Chrome on Windows 10

**Comment by MrPoll0** [comment]
oh i just thought it may be the actual room which is going to get created, am i right?

**Comment by benawad** [comment]
should be fixed now
