### ISSUE TITLE
The mute option on settings is turned on by default

### ISSUE THREAD

**Issue by akinloluwami** [benawad/dogehouse#1182]
I was not able to hear conversations when I joined rooms, so I checked my settings (for the first time), under the sound settings and I saw the mute option is turned on by default.

**Comment by dk-raw** [comment]
**That sounds like a issue with your browser. Try giving the app voice permits**

**Comment by nadirabbas** [comment]
that setting actually means the sound you "hear" when you mute/unmute. a kind od a notification sound.
