### ISSUE TITLE
use chrome live captions

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1188]
Chrome rolled out a new feature called live captions, which automatically transcribes audio/video on the web. we can use this for Dogehouse (uncle sam lol)

![image](https://user-images.githubusercontent.com/38838675/111619160-0978ea80-8807-11eb-842c-0acb4f0396e3.png)

**Comment by overlisted** [comment]
what about users of the normal browsers

**Comment by nadirabbas** [comment]
nothing about them

**Comment by Paultje52** [comment]
You could check the compatibility of the feature, and if the browser supports it, display a button

**Comment by goldyydev** [comment]
I don't think there's an API to activate that, it's just a setting in accessibility

**Comment by nadirabbas** [comment]
@goldyydev oh okay, I'm gonna try it on Dogehouse then

**Comment by nadirabbas** [comment]
@goldyydev  it only shows up on YouTube, so there must be an API?

**Comment by goldyydev** [comment]
i think we need to use a `<video>` element for it to work. it works just fine on twitch and they can't be bothered to patch it in a few hours.

**Comment by TheOtterlord** [comment]
could you pipe the audio through a hidden `<video>` element?

**Comment by nadirabbas** [comment]
yes

**Comment by nadirabbas** [comment]
`<video><source src="mp3 or something"></video>`

**Comment by goldyydev** [comment]
This seems to be working in production now, perhaps Google has changed something? 🤔

Enable it from Settings > Accessibility > Live Captions
