### ISSUE TITLE
Home and profile button too small/missing when room name is long

### ISSUE THREAD

**Issue by daloes** [benawad/dogehouse#1198]
**Describe the bug**

**To Reproduce**
1. Use mobile for small horizontal space
2. Create new room with looong room name
3. Observe tiny/missing home and profile buttons or text overflow if even longer

Idk if this is taken care of in new design

**Expected behavior**
I would expect room name to be cut at some point with ellipsis

For instance:
Long ass room name that does not fit the screen
Would become:
Long ass room nam...

**Screenshots**
![Screenshot_20210318-180651_Chrome](https://user-images.githubusercontent.com/11330406/111667605-2d432d00-8815-11eb-90a6-12f4c0b76217.jpg)
![Screenshot_20210318-180715_Chrome](https://user-images.githubusercontent.com/11330406/111667617-303e1d80-8815-11eb-8ede-42658552dad4.jpg)

**What device are you on?**

Samsung s10e, android 11, chrome

**Comment by wes337** [comment]
I was also able to reproduce this ![](http://g.recordit.co/wSxYqF3yRp.gif), I'll make a PR for this
