### ISSUE TITLE
GDPR: Add account wipe

### ISSUE THREAD

**Issue by nerrixDE** [benawad/dogehouse#12]
So you can comply with GDPR and all data about me you saved is gone

**Comment by fkoeppling** [comment]
OC, very important! Also provide easy way to download user data and fleshed out privacy statement. I, as a user from the EU must know what data you collect about me ;D

**Comment by nerrixDE** [comment]
> OC, very important! Also provide easy way to download user data and fleshed out privacy statement. I, as a user from the EU must know what data you collect about me ;D
pg-dump as a service

**Comment by avarayr** [comment]
hotfix: make the whole app unavailable in the EU.

**Comment by nerrixDE** [comment]
> hotfix: make the whole app unavailable in the EU.

no lmao. data export isnt mandatory for companies with less than a few mio users.
