### ISSUE TITLE
Add platform for translation

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1203]
As many can see a lot of pull request traffic are translations. I think separating them from the repo to another custom made platform would get the focus away from the translations to feature requests, improvements and development.

A platform where you can submit possible changes or add language translations would be awesome as it would make it easier to people without programming experience to submit improvements for languages and as said above drive away all that extra traffic from this repo.

**Comment by Cyber3x** [comment]
But the translation requests will soon stop when all translations are done.

**Comment by HarrisonMayotte** [comment]
I agree that a solution like that would make sense if this was going to be a longer issue, but since translations are getting closer to done as time goes on, there will only be minor patches and things of that nature, so with that said, I'll close the issue here.

**Comment by BronzW** [comment]
Can we reopen this as ajmnz created translate.dogehouse.tv?
