### ISSUE TITLE
Too many event listeners being added to each chat message

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#1212]
<img width="639" alt="Screenshot 2021-03-18 at 20 54 49" src="https://user-images.githubusercontent.com/57961822/111694612-63db7080-8832-11eb-8e50-848bae73c5c0.png">

Probably caused by https://github.com/benawad/dogehouse/pull/484 and by adding `<ReactTooltip />` without an `id` for each component (as said in their [docs](https://github.com/wwayne/react-tooltip#note))

**Comment by wes337** [comment]
It looks like `react-tooltip` is a dependency in the package.json, but it is not used anywhere. The commits from #484 about the tooltip aren't there anymore

**Comment by ajmnz** [comment]
https://github.com/benawad/dogehouse/commit/c2d33ac0f784ddf698e67000e3ac8edc269f3078 removed it
