### ISSUE TITLE
Dogehouse Emojis are too large

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#1213]
**Describe the bug**
When sending the NeutralHouse, SupriseHouse, WinkHouse, CoolHouse, SadHouse, or DogeHouse emojis, they take up the entire chat (and are larger then all standard emojis).

**To Reproduce**
1. Join Room
2. Send any of the above mentioned emojis

**Expected behavior**
The emojis should be the same size as all others.

**Screenshots**
![image](https://user-images.githubusercontent.com/33793511/111698356-1d274f80-880d-11eb-8c9c-81c66989073e.png)

**What device are you on?**
Chrome, Win10

**Comment by goldyydev** [comment]
We got to put a fix height for these emojis (of 100%)
