### ISSUE TITLE
Error when running npm install in `kibbeh`

### ISSUE THREAD

**Issue by Mayowa-Ojo** [benawad/dogehouse#1214]
**Describe the bug**
Tried to install dependencies in `kibbeh` but got a Not Found error.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dogehouse%2fkebab - Not found
npm ERR! 404 
npm ERR! 404  '@dogehouse/kebab@^0.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'kibbeh'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**To Reproduce**
1. Go to 'kibbeh'
2. Run  'npm install'

**Expected behavior**
Should install dependencies without errors.

**What device are you on?**
OS: Linux
Node version: v14.16.0
npm verson: v6.14.11

**Additional context**

**Comment by ThatOneHidde** [comment]
😅

**Comment by nadirabbas** [comment]
It's called `@dogehouse/client` now, maybe update the `package.json`

**Comment by Mayowa-Ojo** [comment]
Yh, thanks. I think we should include a README that explains how to setup the next.js frontend  in `kibbeh`. I also had to switch to yarn because I learned the project now uses yarn.

**Comment by martines3000** [comment]
Looks like I accidentally made the same commit twice... Still learning how the "npm run commit" command works. You can ignore the first commit. :sweat_smile:

**Comment by goldyydev** [comment]
#1233
