### ISSUE TITLE
change room admin failing on prod.

### ISSUE THREAD

**Issue by jamesql** [benawad/dogehouse#1217]
**Describe the bug**
Make room admin failing on prod.

**To Reproduce**
1. Create room
2. Try to transfer ownership

**Expected behavior**
Transfer ownership

If someone wants to assign it to me ill be working on it tonight or tomorrow morning I'll figure it out.

Probably has something failing in the validation for the Kousa.Room.change_room_creator function

**Comment by nadirabbas** [comment]
i'll fix it

**Comment by nadirabbas** [comment]
it works, may be @benawad didn't deploy elixir API? 🤔

**Comment by jamesql** [comment]
hmmm, maybe, do error messages not appear on front-end on prod?
it was working fine for me too

**Comment by nadirabbas** [comment]
it just works, but it has a logical error, the former creator gets made a listener

**Comment by benawad** [comment]
I didn't realize there was a backend change, my bad, let me review next time before merging backend changes

**Comment by nadirabbas** [comment]
@benawad gotcha, the changes were made to fix #1097

**Comment by jamesql** [comment]
All good haha

**Comment by benawad** [comment]
its pushed now
