### ISSUE TITLE
Dogehouse and Profile Menu are push off screen on mobile devices when a room name is too long.

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#1223]
**Describe the bug**
When a room has a long name, it causes other buttons like the home button and profile picture to be moved off screen on smaller mobile devices (IPhone 6s or similar)

**To Reproduce**
1. Get phone with small screen
2. Open room with large name
or 
1. Create room
2. Shrink web browser to smallest size possible

**Expected behavior**
The text should be abbreviated so that the buttons are not offscreen 

**Screenshots**
![image](https://user-images.githubusercontent.com/33793511/111721491-5c1dcb00-8836-11eb-883b-b3e37f8382bd.png)

**What device are you on?**
(Screenshot) Chrome, Win10

**Comment by daloes** [comment]
This was adressed in pr #1206 but apparently it's not working

**Comment by daloes** [comment]
Confirmed issue persists
![Screenshot_20210319-083634_Chrome](https://user-images.githubusercontent.com/11330406/111746414-4fc55c80-888e-11eb-8a33-34130f66e55f.jpg)

**Comment by MadanBhandari** [comment]
let me do this, and also user avatar is not vertically centered, will send pr for both the issues. someone assign this to me.
