### ISSUE TITLE
Mac app crashed on GitHub sign in

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#1229]
Error report:
https://pastebin.com/z9X3fNra

**Comment by TheOtterlord** [comment]
Operating System: macOS BigSur 11.2.3

**Comment by ajmnz** [comment]
Maybe worth noting that I never got to authorize DogeHouse, and left the modal open while trying to log in.

**Comment by TheOtterlord** [comment]
I'm not a mac user, so forgive my lack of knowledge here, but by authorize, do you mean authorizing the app?

**Comment by ajmnz** [comment]
> I'm not a mac user, so forgive my lack of knowledge here, but by authorize, do you mean authorizing the app?

It asks for Accessibility perms when you first open the app (guessing for mic access and that stuff). It'd probably be better to have a blocking screen that goes away once you allow the app.

**Comment by TheOtterlord** [comment]
Interesting. Yeah, it asks for mic access, and as they need to be granted, adding some form of waiting screen could be useful.

**Comment by amitojsingh366** [comment]
> > I'm not a mac user, so forgive my lack of knowledge here, but by authorize, do you mean authorizing the app?
> 
> It asks for Accessibility perms when you first open the app (guessing for mic access and that stuff). It'd probably be better to have a blocking screen that goes away once you allow the app.

Oh so was it like you forgot to approve the perms? And then when you tried using the app it crashed?

**Comment by ajmnz** [comment]
> Oh so was it like you forgot to approve the perms? And then when you tried using the app it crashed?

Exactly. Crashed on gh auth

**Comment by amitojsingh366** [comment]
> 
> 
> > Oh so was it like you forgot to approve the perms? And then when you tried using the app it crashed?
> 
> Exactly. Crashed on gh auth

Ok ill look into it.

**Comment by yummyweb** [comment]
@ajmnz Did you give accessibility permission?

**Comment by amitojsingh366** [comment]
@yummyweb no they didn't so yea we will have to make a modal like they mentioned to wait for the user to allow. I can do that
