### ISSUE TITLE
some phrases in DogeHouse are not included in the translation JSON files

### ISSUE THREAD

**Issue by dk-raw** [benawad/dogehouse#1234]
**Phrases like `Are you sure you want to leave the room?` and `Following` / `Follow` are not present in the JSON file to translate.**

**Comment by daloes** [comment]
additionally:
- [ ] in sound settings options are not translatable
- [ ] in voice settings last 3 options (toggle chat, invite, request), also options in mic dropdown can't be translated (default, speakerphone, headset earpiece)
- [ ] "room no longer exists"
- [ ] "leave room 'x' and join 'y'?"
- [ ] also emoji categories are not translated only "Most used" category is in Slovak in my case but idk if that possible to target

**Comment by daloes** [comment]
Issue also mentioned in #774

**Comment by daloes** [comment]
Also deleted message is missing translation
[message retracted]

**Comment by jamesql** [comment]
im gonna wait untill all the translations are merged and then ill add these in

**Comment by goldyydev** [comment]
Merged #774:
 ![image](https://user-images.githubusercontent.com/35764628/110999591-a95ef000-8391-11eb-85a0-209cbf49141c.png)

**Comment by samarmohan** [comment]
@jamesql, are you going to do this or should I?

**Comment by dk-raw** [comment]
**It is partially fixed now, just translated some more phrases added to the JSON. But still some others are not present (at least in the `el-GR` file **

**Comment by jamesql** [comment]
@samarmohan you are more than welcome to do it, I was working on another feature. Would you like me to assign you?

**Comment by dk-raw** [comment]
@jamesql **I can do that also**

**Comment by jamesql** [comment]
Ok, ill just assign you since you authored it, @samarmohan you're more than welcome to help him if you want
