### ISSUE TITLE
Autodelete inactive rooms

### ISSUE THREAD

**Issue by Abogical** [benawad/dogehouse#1237]
# Problem
Currently there can be inactive rooms with inactive speakers and listeners which ends up just staying in the list of rooms doing nothing for days. Example: https://dogehouse.tv/room/cc4bd0a3-304f-4414-aefb-e60e01fec9e2

# Possible solution
Activity could be measured by the last time someone has spoke. Delete the room if no one has spoken for _X_ hours. _X_ is arbitrary and is set by the server config.

**Comment by dk-raw** [comment]
**The community would not appreciate that.**

**Comment by overlisted** [comment]
Your "possible solution" can easily be bypassed if the speakers just occasionally sent some sound using the api

**Comment by Abogical** [comment]
> Your "possible solution" can be easily bypassed if the speakers just occasionally sent some sound using the API

It's not perfect. However, this is aimed at users who wouldn't bother with the API and have completely forgotten the room somehow.

**Comment by dk-raw** [comment]
> > Your "possible solution" can be easily bypassed if the speakers just occasionally sent some sound using the API
> 
> It's not perfect. However, this is aimed at users who wouldn't bother with the API and have completely forgotten the room somehow.

**There is not way of distinguishing "forgotten" rooms and rooms that are open for specific reasons like `Prog / Dev discussion`**

**Comment by jamesql** [comment]
I think its a big part of the community aspect especially with the room timer at the top. imo i think people like it

**Comment by Abogical** [comment]
Seems this idea is pretty unpopular :disappointed: I'll close the issue.
