### ISSUE TITLE
Changing rooms - hardcoded popup text

### ISSUE THREAD

**Issue by Neaxic** [benawad/dogehouse#1238]
**Describe the bug**
When in an active room, changing to another room, a popup appers with hardcoded english text in it. Its a problem because then we cant translate it in the locales. 

**Screenshots**

![billede](https://user-images.githubusercontent.com/36155981/111786338-fa08a880-88bd-11eb-85f5-894d232dea40.png)

**Comment by daloes** [comment]
Dup of #1234
