### ISSUE TITLE
Be able to see chat history of a room if you were in that room already

### ISSUE THREAD

**Issue by Aducj1910** [benawad/dogehouse#1245]
Whenever I leave a room, and rejoin it the chat is basically blank, is it possible to have it so that the chat doesn't go blank if you leave a room for say only 5 minutes.

**Comment by jamesql** [comment]
this happens due to the fact chat is not stored anywhere, this possibly could be added in the future but right now they are not.

**Comment by goldyydev** [comment]
Ben said he likes this behaviour and prefers it. 

If we ever store chatroom messages, this will be implemented, but the status quo is that we're not going to be storing them anytime soon.
