### ISSUE TITLE
React Native in Yarn Workspaces.

### ISSUE THREAD

**Issue by GyanendroKh** [benawad/dogehouse#1267]
I've been using a package for using react native inside a yarn workspaces.
So far there are no issues but iOS is not supported. And I don't have any experience working with iOS as I don't have any Apple product. If anyone can add iOS support it would be great to use the package here.

Package: [react-native-yarn-workspaces-v2](https://www.npmjs.com/package/react-native-yarn-workspaces-v2)

**Comment by goldyydev** [comment]
Can you please be a little bit more clear about what you're trying to achieve?
