### ISSUE TITLE
guidelines to build the project

### ISSUE THREAD

**Issue by vaibhav135** [benawad/dogehouse#127]
Hii,
I am new to opensource can you please help me as to how I can build the project and if possible please add the instruction in the readme.MD.
current os: Ubuntu 20.04
Thank you

**Comment by nadirabbas** [comment]
# Kousa

To build kousa (Elixir backend) work, you need the following things installed:

Requirements:
### 1. PostgreSQL
        Start the server and create a DB
### 2. RabbitMQ (and RabbitMQ management plugin)
            you can possibly use apt for this. And windows people can use choco install rabbitmq, and then enable the plugin by 
       using the bat file in the C:/Program Files/sbin folder `./rabbitmq-plugins enable rabbitmq-management`. Once enabled, 
       management plugin is available at: `http://localhost:15672/`

### 3. A GitHub OAuth App (Create app here: https://github.com/settings/apps)
           Get the client id and client secret from here.
### 4. A Sentry.io account
        Get the DSN URL from here.

## Run container:
1. Now you need to build the docker image for kouse using `docker build ./kousa`.
2. Once done, you can do `docker images` to list all the images, and copy the `Image ID` and we just built.
3. The API needs a bunch of environment variables to be set, I just used a file to save all of them, the file looks like this:
    ```DATABASE_URL=postgres://postgres:277526@192.168.10.16/dogehouse
       BEN_GITHUB_ID=7872329
       RABBITMQ_URL=amqp://nadir:277526@192.168.10.16:5672
       ACCESS_TOKEN_SECRET=nadir
       REFRESH_TOKEN_SECRET=nadir
       GITHUB_CLIENT_ID=get your own :p
       GITHUB_CLIENT_SECRET=get your own :p
       SENTRY_DNS=get your own :p```

      you can get the rabbitmq URL using the management plugin, just create a new user/password, and use it.
4. Run the container by: `docker run --env-file {ENV_FILE_PATH} -p 4001:4001 {IMAGE_ID}`

# Kofta:
This one is pretty simple, just create an .env file in kofta folder (see .env.example). Set the base URL to localhost:4001 and start the dev server

# Shawarma
this is also dockerized, so spin up a container, map the port 3000, and use it on the Elixir side maybe? I haven't checked this out yet.

**Comment by nadirabbas** [comment]
answered #126

**Comment by drvladb** [comment]
Hey,
This is partly being solved by PR #101. Once that is done, a simple `docker-compose up` will do

**Comment by AndreiJirohHaliliDev2006** [comment]
> Hey,
> This is partly being solved by PR #101. Once that is done, a simple `docker-compose up` will do

@drvladb Actually the PR/issue number you mentioned is an issue, not an merge request.

**Comment by drvladb** [comment]
Thanks @AndreiJirohHaliliDev2006, Fixed!

**Comment by vaibhav135** [comment]
Thanks guys
