### ISSUE TITLE
Cannot open the electron application on Ubuntu 20.04

### ISSUE THREAD

**Issue by MaheshNat** [benawad/dogehouse#1273]
When attempting to open the electron application on Ubuntu 20.04, I get the following error message:
load_input_helper [1918]: Using XFree86 keyboard layout.
load_input_helper [1920]: XKB support is required to accurately determine keyboard characters!
/opt/DogeHouse/dogehouse: symbol lookup error: /opt/DogeHouse/resources/app.asar.unpacked/node_modules/iohook/builds/electron-v85-linux-x64/build/Release/uiohook.so: undefined symbol: xkb_x11_get_core_keyboard_device_id

**To Reproduce**
My keyboard is a corsair k63, running ubuntu 20.04, after typing `dogehouse` in the terminal after installing the .deb file from the releases tab, the error above gets thrown. I have not experienced this error with other electron applications like discord or postman.

**Expected behavior**
The application launches

**Screenshots**
![Screenshot from 2021-03-19 11-52-58](https://user-images.githubusercontent.com/44304651/111815670-f4a16300-88a9-11eb-9a16-e0de62cf300f.png)

**What device are you on?**
![Screenshot from 2021-03-19 11-55-31](https://user-images.githubusercontent.com/44304651/111815772-0d117d80-88aa-11eb-8674-dda859b90c0d.png)

**Comment by MaheshNat** [comment]
This is probably an issue with the iohook package, but here's another issue that should help: https://github.com/wilix-team/iohook/issues/268

**Comment by drvladb** [comment]
Hmmm, it seems like this is fixed (https://github.com/wilix-team/iohook/pull/279) on Feb 5th. @MaheshNat Try building your own binary after running `sudo apt-get install -y libxkbcommon-x11-0`.

**Comment by yummyweb** [comment]
This issue is being looked by the Baklava team. This is a clone of #1112. This issue will also be listed in the README soon. Please close this issue.
