### ISSUE TITLE
Don't let people promote you to a Speaker unless you are asking for it

### ISSUE THREAD

**Issue by corysimmons** [benawad/dogehouse#128]
I keep joining channels and people immediately promote me to speaker. There are dozens of victims constantly screaming and I'm afraid they are going to alert the authorities if this keeps up. >:[

**Comment by nadirabbas** [comment]
> I keep joining channels and people immediately promote me to speaker. There are dozens of victims constantly screaming and I'm afraid they are going to alert the authorities if this keeps up. >:[

+1

**Comment by vaibhav135** [comment]
> I keep joining channels and people immediately promote me to speaker. There are dozens of victims constantly screaming and I'm afraid they are going to alert the authorities if this keeps up. >:[

+1

**Comment by Abhishek12345679** [comment]
> > I keep joining channels and people immediately promote me to speaker. There are dozens of victims constantly screaming and I'm afraid they are going to alert the authorities if this keeps up. >:[
> 
> +1

thumbs up the comment to show support, don't +1.

**Comment by corysimmons** [comment]
>thumbs up the comment to show support, don't +1.

+1

**Comment by MrMalloc** [comment]
This could be related with #114 
Once you were speaker in a room you will always join as "asking to speek".

**Comment by corysimmons** [comment]
I think it's unrelated. I definitely didn't ask to speak in some of the rooms. Room mods just manually promote me to speaker I guess. I think the fix is just disabling them from promoting you to speaker unless you're actively asking for it.
