### ISSUE TITLE
Add appimage to electron releases

### ISSUE THREAD

**Issue by Linux123123** [benawad/dogehouse#1283]
**Is your feature request related to a problem? Please describe.**
So I am on arch and I would like to use the desktop app, but I need to use something like `debtap` or manually put the files in the correct places to install the application.

**Describe the solution you'd like**
Add target `AppImage` in the `build.linux.target` array of `baklava/package.json`.
https://github.com/benawad/dogehouse/blob/cea512f7ff979b3ebfaf20544658167cef879d7c/baklava/package.json#L69

**Describe alternatives you've considered**
Installing manually / using `debtap`

**Comment by rishitxyz** [comment]
Check this [PR](https://github.com/benawad/dogehouse/pull/1378#issue-597313163).

**Comment by Linux123123** [comment]
> Check this [PR](https://github.com/benawad/dogehouse/pull/1378#issue-597313163).

Great! Will close this when it merges.

**Comment by Linux123123** [comment]
Now #1476 closes this issue
