### ISSUE TITLE
Logging in with electron desktop app on OSX opens github/sessions/two-factor and stops.

### ISSUE THREAD

**Issue by willdoescode** [benawad/dogehouse#1285]
**Describe the bug**
When logging in with github on the electron desktop app for OSX the app opens up https://github.com/sessions/two-factor and then does not log in.

**To Reproduce**
1. Go to dogehouse app on OSX
2. Click on login
3. Enter info
4. Enter 2fa code
5. The page opens and page is not found

**Expected behavior**
I expect 2fa to work and log me in.

**Screenshots**
![Screen Shot 2021-03-19 at 11 36 44](https://user-images.githubusercontent.com/53620720/111827663-64621e80-88a7-11eb-81f4-7bcb611e535d.png)

**What device are you on?**
OSX Electron app

**Comment by willdoescode** [comment]
Auth code is already expired don't try to steal

**Comment by HonbraDev** [comment]
lmao

**Comment by Devnol** [comment]
Oh hey Will! Also yeah, same issue here, I would expect it to open the 2fa session on the Electron app itself but it just opens it with the default browser (Firefox) which doesn't have the session info required to actually login so it give a 404.

**Comment by Devnol** [comment]
Confirmed same exact issue in Windows.

**Comment by mmattbtw** [comment]
I can also reproduce this on Windows using the latest build too.

**Comment by TheOtterlord** [comment]
@amitojsingh366 could this be something to do with the allowed domains in the link handler?

**Comment by amitojsingh366** [comment]
@TheOtterlord yes it has to be it. I had an similar issue but i whitelisted it.
@willdoescode could you go to the page again then open dev tools *(cmd+shift+i)* and type in `window.location.href` and post the output here please.

**Comment by Devnol** [comment]
The result of `window.location.href` is "https://github.com/sessions/two-factor" (oh and btw in macOS the devtools shortcut is cmd+opt+i)

**Comment by amitojsingh366** [comment]
> 
> 
> The result of `window.location.href` is "https://github.com/sessions/two-factor" (oh and btw in macOS the devtools shortcut is cmd+opt+i)

Thanks a lot will whitelist it and also thx for the info i keep forgetting the shortcut on mac XD

**Comment by amitojsingh366** [comment]
Fixed in #1404

**Comment by willdoescode** [comment]
Thanks!
