### ISSUE TITLE
Electron app icon is too large on macOS

### ISSUE THREAD

**Issue by HonbraDev** [benawad/dogehouse#1286]
**Describe the bug**
The icon is too big.

**To Reproduce**
1. Download DogeHouse
2. Run on macOS
3. See

**Expected behavior**
Icon is same as others

**Screenshots**
![Snímek obrazovky 2021-03-19 v 19 33 45](https://user-images.githubusercontent.com/54026315/111827803-a2346680-88ea-11eb-900b-f7aeda4134bb.png)

**What device are you on?**
MacBook Pro 2014

**Additional context**
none

**Comment by vi241** [comment]
I wanted to say that lol

**Comment by Deep-Codes** [comment]
I fixed it

<img width="292" alt="Screenshot 2021-03-20 at 12 25 48 AM" src="https://user-images.githubusercontent.com/61158210/111829575-dde32680-8912-11eb-87a7-cacaf39892e6.png">

I can work on a PR

**Comment by vi241** [comment]
> I can work on a PR

it will be helpful if you will do

**Comment by Deep-Codes** [comment]
I think icon size of same size as `VsCode` would be perfect 

Since `Discord` and `Msteam` has pretty small compared to others.

<img width="263" alt="Screenshot 2021-03-20 at 1 03 02 AM" src="https://user-images.githubusercontent.com/61158210/111833343-0de0f880-8918-11eb-88a4-c4302b0a04a1.png">

Opening a PR soon

**Comment by danBamikiya** [comment]
nah the former one was better, makes it stand out. If you notice dogehouse icon looks smaller next to vscode and postman because of their geometries.

**Comment by vi241** [comment]
great

**Comment by vi241** [comment]
@danBamikiya its very annoying and disturbing

**Comment by danBamikiya** [comment]
@ofsho ok.
