### ISSUE TITLE
Adding sinhala translations

### ISSUE THREAD

**Issue by MasterBrian99** [benawad/dogehouse#1305]
i'm adding [Sinhala]( https://en.wikipedia.org/wiki/Sinhala_language) language to dogehouse. i have previous experiences with translations (https://github.com/zenika-open-source/promote-open-source-project)[https://github.com/zenika-open-source/promote-open-source-project] .

**Comment by jamesql** [comment]
sounds good, just make a pull request adding the translation file to /kofta/public/locales/<language_code>/translation.json and edit the /kofta/src/app/components/LanguageSelector.tsx. Let me know if you need any help. haizers#3946 or comment here!

**Comment by MasterBrian99** [comment]
thank you sir.i managed to add translations. #1321
