### ISSUE TITLE
Custom mute sound

### ISSUE THREAD

**Issue by ViliamVadocz** [benawad/dogehouse#1306]
**Is your feature request related to a problem? Please describe.**
I *hate* the current mute sound.

**Describe the solution you'd like**
I would like to be able to point whatever plays the sound to a local file so I can play that mute sound instead.

**Describe alternatives you've considered**
You could have multiple different types of mute sounds to choose from, or just pick one that is less grating.

**Additional context**
I am planning on doing this myself, although I don't really know what I am doing. Help is appreciated.

**Comment by jamesql** [comment]
hmmmm, i feel like this prob would be baklava and pilaf only and would only be local because anything else would require storing the files on a server no?

custom sounds and other custom elements would fit in on baklava so I would try to implement it there

**Comment by ViliamVadocz** [comment]
Yes, it would be local only.

I think the modifications I need to do are as follows:
- Add a new interactable in settings to set the custom sound path
- Make the mute method try the custom file first
- Save the custom path to local cache
- Maybe show an alert if there is an error playing the sound file (maybe if it no longer exists)

I don't have a good grasp of the dogehouse infrastructure. If someone can point me to where I should make these changes I would react with a 🚀 as thanks.

**Comment by f1shy-dev** [comment]
I was taking a look, maybe something with the File api to save the file unless there is some react method for this

I could work on the gui for this tomorrow, in my option the whole settings page needs a redo of some sort.

**Comment by benawad** [comment]
we should just use a better default

**Comment by HarrisonMayotte** [comment]
Closed and added to roadmap #386.
