### ISSUE TITLE
make it so to show the profile you just have to hover over the person's name

### ISSUE THREAD

**Issue by gabrielcastelan** [benawad/dogehouse#1314]
**Potential fix for the "impersonating other people" problem without getting rid of display names altogether**

Make it so to show a user's profile, the user just needs to hover over the person's name or profile picture, instead of having to actually click. It could be triggered after 1 ~ 1,5 seconds hovering over their name/pfp to avoid unwanted behaviour by the user.

Maybe instead of showing the full profile box, show a smaller box with just the user's username and display name, similar to [discord]
(https://cdn.discordapp.com/attachments/820036076114411561/822594866243436605/unknown.png)

**Comment by HarrisonMayotte** [comment]
I don't think this would make much of a difference when it comes to the impersonation issue, but I do think that it would be a good idea for after 2 or some number of seconds (maybe customizable in settings?) a small profile thing pops up.

I've added this to #386 and will close this issue.
