### ISSUE TITLE
Atomic Components Implementation v3 (Mobile)

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#1324]
<h1>Atomic Components v3 (Mobile)</h1>

### New components

To be implemented under `kibbeh/src/ui/mobile`.

- [x] MobileHeader - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2250
    - Requires modified UserAvatar > SingleUser ✅ 
- [x] FeaturedRoomCardAvatars - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2338
    - Requires none  ✅
- [x] FeaturedRoomCardHosts - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2327
    - Requires FeaturedRoomCardAvatars ❌
- [x] MobileNav - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2440
    - Requires none ✅
- [x] AccountOverlay - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2492
    - Requires none ✅
- [x] RoomCardParticipants - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2404
    - Requires modified UserAvatar > MultipleUsers ❌

###  Existing Components - Responsiveness

- [x] SearchBar - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2269
    - Requires SearchBar ✅
- [x] SearchResult > RoomSearchResult - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2354
    - Requires  SearchResult > RoomSearchResult ✅
- [x] SearchResult > UserSearchResult - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2388
    - Requires SearchResult > UserSearchResult ✅
- [x] SettingsIcon - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2449
    - Note the bottom border
    - Requires SettingsIcon ✅
- [x] NotificationElement - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2501
    - Requires modified NotificationElement and modified BoxedIcon ✅
- [x] MessageElement - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2563
    - Note the bottom border
    - Requires MessageElement ✅

### Existing Components - Modifications
- [x] Tag - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2350
    - Needs to include these new types. Note the drop shadow.
    - Requires Tag ✅
- [x] UserAvatar > MultipleUsers - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2411
    - Bigger spacing between small UserAvatar(s)
    - Requires UserAvatar > MultipleUsers ✅
- [x] BoxedIcon - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2613
    - Needs to include the circle type
    - Requires BoxedIcon ✅
- [x] NotificationElement - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2501
    - Needs to include the new rounded BoxedIcon
    - Requires modified BoxedIcon ✅
- [x] UserAvatar > SingleUser - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2665
    - Needs to include custom width/height props or new size (for the MobileHeader - 30px)
    - Requires UserAvatar > SingleUser ✅

-------

**Don't add any margin around the components.**

Put your component in `kibbeh/src/ui` and create a story in `kibbeh/src/stories`

Use tailwind for styling (see the tailwind config for theme info).

You have to use TypeScript.

Work on the `staging` branch.

Please comment below if you start to work on a component, but only claim a component if you plan to work on it right away so it doesn't block other people.

> All the icons are already available under `src/icons`. Some of them will need to be `20px` wide/tall (check on Figma), so you can pass `width={20} height={20}` as props to the icon component for it to scale to the desired size.

Mockup & grid: https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4273%3A1

If you have any questions ask Ben or @ ajb on [Discord](https://discord.gg/82HzQCJCDg).

**Comment by goldyydev** [comment]
Will do `UserAvatar > SingleUser`

**Comment by bansalarnav** [comment]
I will work on `MobileNav`

**Comment by banky** [comment]
Grabbing `SettingsIcon`

**Comment by yummyweb** [comment]
I would work on `Tag`

**Comment by tejasag** [comment]
`MessageElement` is on me

**Comment by banky** [comment]
Grabbing `NotificationElement`

**Comment by DS-Infinity** [comment]
doing `BoxedIcon`

**Comment by BronzW** [comment]
I will see if I can do ``FeaturedRoomCardAvatar`` and ``FeaturedRoomCardHosts`` when I'm finished with the other one

**Comment by bansalarnav** [comment]
#1358 Completed MobileNav

**Comment by wes337** [comment]
I am doing `UserAvatar > MultipleUsers` right now

**Comment by ajmnz** [comment]
> Grabbing `NotificationElement`

~~You'll have to wait for `BoxedIcon`~~, and also do both the modification and responsiveness.

**Comment by sahilmob** [comment]
I'm doing AccountOverlay

**Comment by wes337** [comment]
@ajmnz I'm looking at `SearchResult > RoomSearchResult` and `SearchResult > UserSearchResult`, but they both seem to have a fully responsive implementation. Is there something missing there that I'm not seeing?

**Comment by ajmnz** [comment]
All the icons are already available under `src/icons`. Some of them will need to be `20px` wide/tall (check on Figma), so you can pass `width={20} height={20}` as props to the icon component for it to scale to the desired size.

**Comment by ajmnz** [comment]
> @ajmnz I'm looking at `SearchResult > RoomSearchResult` and `SearchResult > UserSearchResult`, but they both seem to have a fully responsive implementation. Is there something missing there that I'm not seeing?

Seems like they do, I'll mark them as complete then.

**Comment by goldyydev** [comment]
Will do `RoomCardParticipants` once `MultipleUsers` is done

**Comment by banky** [comment]
Looks like NotificationElement is actually complete and already responsive. Pls update the document @ajmnz

**Comment by pratikmane1299** [comment]
@ajmnz Do <code>FeaturedRoomCardAvatars</code> doesn't require modified <code>SingleUser</code> and <code>MultipleUsers</code> components ?

**Comment by PrinceRajRoy** [comment]
I'm taking MobileHeader

**Comment by wes337** [comment]
> 
> 
> I'm taking MobileHeader

@PrinceRajRoy I am curious as to how. I was looking at it and it seemed like 2 or 3 different components. I'm not sure what the order of the screens shown in the mock up are.

**Comment by PrinceRajRoy** [comment]
@wes337 I'm assuming, the component can be provided with a mode prop for showing one of the 3 for the time being or implement them separately like Search.

**Comment by ajmnz** [comment]
> @ajmnz Do `FeaturedRoomCardAvatars` doesn't require modified `SingleUser` and `MultipleUsers` components ?

They are a separate component

**Comment by Mayowa-Ojo** [comment]
Is there any component not assigned to anyone yet? I'd like to chip in

**Comment by ajmnz** [comment]
> Is there any component not assigned to anyone yet? I'd like to chip in

#1390

**Comment by BronzW** [comment]
#1397 Added FeaturedRoomCardHosts

**Comment by BronzW** [comment]
FeaturedRoomCardAvatars is done, check it.

**Comment by BronzW** [comment]
Have anybody done the ``NotificationElement`` modifications yet? If not I'm calling dibs on that.

**Comment by sahilmob** [comment]
@ajmnz is there any abandoned/unassigned components?

**Comment by ajmnz** [comment]
> @ajmnz is there any abandoned/unassigned components?

Not that I know of

**Comment by laforetcan** [comment]
@ajmnz I can take the NotificationElement modification. I need to add round background to icons and manage the responsivness (for exemple height if the text of the notification is too big)?

**Comment by lorstenoplo** [comment]
I will fix responsiveness on landing page 
I am not sure if it's temporary page or something like can somebody confirm?
If its going to stay i'll start working on it.

**Comment by ajmnz** [comment]
> @ajmnz I can take the NotificationElement modification. I need to add round background to icons and manage the responsivness (for exemple height if the text of the notification is too big)?

@ me (ajb) at #design in our discord

**Comment by goldyydev** [comment]
I have re-opened `MobileHeader` as it has been abandoned. Please comment if you'd like to take it.

**Comment by PrinceRajRoy** [comment]
@goldyydev I don't understand I pushed the changes as you requested like 10 days ago

**Comment by goldyydev** [comment]
ah. merged

**Comment by goldyydev** [comment]
We did it reddit

**Comment by BronzW** [comment]
Just took us 22 days
