### ISSUE TITLE
Keep screen on while beeing a speaker

### ISSUE THREAD

**Issue by Playit3110** [benawad/dogehouse#133]
It would be great to let the screen on as long as you want to talk. If you are just a listener it doesnt matter, but as a speaker you need to change some setting or mute yourself and then the screen turns off.

**Comment by drvladb** [comment]
Possible implementation (using wakelock): https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

**Comment by goldyydev** [comment]
was this abandoned?

**Comment by TheOtterlord** [comment]
It seems this has been dealt with [here](https://github.com/benawad/dogehouse/pull/1501#issuecomment-820821051)
