### ISSUE TITLE
Save sound effects and keybinds when logged in on a different device

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#1333]
**Is your feature request related to a problem? Please describe.**
So when you log in on the same account but on a different device it doesn't save the sound effects and keybinds.

**Describe the solution you'd like**
I want dogehouse to save keybinds and sound effects when logged in on the same account but on a different device.

**Comment by HonbraDev** [comment]
So, if I understand correctly, you want cloud sync for sound effect presets and keybinds. If that's what you mean, I think language sync would be helpful too.

**Comment by HarrisonMayotte** [comment]
Added to the "Future Features" section on #386, closing this issue.
