### ISSUE TITLE
After reload pirate is shown as english

### ISSUE THREAD

**Issue by vi241** [benawad/dogehouse#1341]
**Describe the bug**
After I reloaded english is pirate until you change the language to anything else and back to english.

**To Reproduce**
1. Change the language to pirate
2. Reload

**Expected behavior**
English is pirate.

**Screenshots**
<img width="627" alt="Screen Shot 2021-03-20 at 8 02 29" src="https://user-images.githubusercontent.com/60016719/111860788-a005f280-8952-11eb-800e-f55a20da2c36.png">

**What device are you on?**
MacBook Pro 16"

**Comment by Sam-Neale** [comment]
Am able to reproduce this, whilst it switches the selector to English, it remains as pirate.

**Comment by vi241** [comment]
Yes

**Comment by vi241** [comment]
"enlish"

**Comment by f1shy-dev** [comment]
I’m redoing the footer/settings, I’ll try fix this in the process too.

**Comment by vi241** [comment]
ok

**Comment by vi241** [comment]
thank you
