### ISSUE TITLE
Chat Bots and muting people from the chat

### ISSUE THREAD

**Issue by anirudh242** [benawad/dogehouse#1347]
Maybe at a later stage, we could add bots to the chat like Twitch and people could make their own bots? Muting people from the chat would also be good as some people might want some people to speak in the chat but dont want to ban them.

**Comment by BronzW** [comment]
https://github.com/dogegarden/dogehouse-js ?

**Comment by HarrisonMayotte** [comment]
As BronzW posted, we do already have the clientside implementations available for people to create bots with.
