### ISSUE TITLE
text did not fit to box.

### ISSUE THREAD

**Issue by dovenokan** [benawad/dogehouse#136]
![afwafawf](https://user-images.githubusercontent.com/42724589/107858000-edb6a900-6e42-11eb-8d26-6f1946e91ef5.png)

**Comment by Playit3110** [comment]
yeah we need to limit it

**Comment by MrMalloc** [comment]
Limiting probably won't be enough because of different screen sizes. I think it would be better to tackle the issue via css with text-overflow: ellipsis;

**Comment by Playit3110** [comment]
Ok It will be solved soon. :)
