### ISSUE TITLE
On going back, we don't leave the room

### ISSUE THREAD

**Issue by rk3141** [benawad/dogehouse#1367]
**Describe the bug**
When I am in a room and press the browser back button I dont leave the room, but it goes to the homepage, and then after reloading it leaves the room.

**To Reproduce**
1. Join a room
2. Press the back button.
3. You're on the homepage and havent left the room

**Expected behavior**
I expected to leave the room.

**Screen Recording of the bug**
![dogebug](https://user-images.githubusercontent.com/65018379/111869599-63fc7d00-89a6-11eb-98d0-0ede07f3499e.gif)

**Device**
Ubuntu 20.04 Intel Core i5 x86-64 Brave 1.21.77

**Comment by ajmnz** [comment]
That's intended behavior, you have the controls on the bottom to leave the room.
