### ISSUE TITLE
Add an API call to get a user's profile from ID and handle

### ISSUE THREAD

**Issue by HonbraDev** [benawad/dogehouse#1371]
**Is your feature request related to a problem? Please describe.**
I'm making a bot, DodgyCoin, and I would like to have multiple bots or have people pay offline users. Right now I can't do that, because I can't get the user's ID from the handle provided In chat.

**Describe the solution you'd like**
New WebSocket calls:
- `get_user_from_id` `{ id: string }` - returns a user's profile including handle and id
- `get_user_from_handle` `{ handle: string }` - returns a user's profile including handle and id

**Describe alternatives you've considered**
So far I have just listed the users in a room and got their IDs that way, but users can't pay offline users and I can't easily have bots in multiple rooms trading with each other.

**Comment by HarrisonMayotte** [comment]
Added to the "Future Features" section on #386, closing this issue.
