### ISSUE TITLE
End-to-End encryption

### ISSUE THREAD

**Issue by btarg** [benawad/dogehouse#1377]
**Is your feature request related to a problem? Please describe.**
Most modern chat apps, for example the popular WhatsApp, use end-to-end encryption for security and privacy reasons.
DogeHouse doesn't currently implement any encryption for voice or text chat.

**Describe the solution you'd like**
There is an issue page here on the topic of end-to-end encryption: https://github.com/versatica/mediasoup/issues/383
The solution would be to use AES-256 or similar encryption standards at both ends, for voice chat and for text chat.

**Comment by goldyydev** [comment]
Duplicate of #31
