### ISSUE TITLE
Use tauri rather then electron

### ISSUE THREAD

**Issue by Milo123459** [benawad/dogehouse#1381]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Use [Tauri](https://tauri.studio) rather then Electron.
**Describe alternatives you've considered**
n/a
**Additional context**
Tauri is a lot more efficient and doesn't run on Chromium.

**Comment by vi241** [comment]
[here](https://github.com/tauri-apps/tauri#comparison-between-tauri-and-electron) is a comparison between tauri and electron.

**Comment by TheOtterlord** [comment]
While this looks interesting, the app is already integrated with the electron APIs, and it will take some work to move over when most of the team for baklava don't know tauri. This isn't a big concern tbf, but worth noting.

Also, it seems like tauri is still in alpha, and should therefore not be used in production. It's worth keeping an eye on, but for now I think it's best to stick with electron, as it is stable.

**Comment by vi241** [comment]
Yes but @Milo123459 you are welcome to make your own client with tauri if you want to.

**Comment by Milo123459** [comment]
Yea I might.

**Comment by TheOtterlord** [comment]
I'll close this for now. If you do create you own client, feel free to add it [here](https://github.com/benawad/dogehouse/issues/988) (looking forward to it :smile:)

**Comment by vi241** [comment]
@TheOtterlord cool, you are a collaborator now

**Comment by TheOtterlord** [comment]
> @TheOtterlord cool, you are a collaborator now

Yeah, helping out with issue triage along with goldyydev

**Comment by vi241** [comment]
wait, did goldyy get it too?

**Comment by TheOtterlord** [comment]
yeah, see the `dogehouse` channel in the discord, it's not too far up

**Comment by vi241** [comment]
you should have requested the collaborator role but eh

**Comment by vi241** [comment]
you got it anyways
