### ISSUE TITLE
flag emojis not working in firefox

### ISSUE THREAD

**Issue by elad-weiss** [benawad/dogehouse#1387]
the flag emojis in the language selection menu don't work and instead only the country abbreviation shows up

**Comment by tejxv** [comment]
that's how it works if you're on Windows

**Comment by vi241** [comment]
can you send an image?

**Comment by tejxv** [comment]
sure

![Screenshot (360)](https://user-images.githubusercontent.com/54097365/111883835-b8721d80-89e3-11eb-9333-b5a6366e94c4.png)

**Comment by vi241** [comment]
weird

**Comment by tejxv** [comment]
ikr, some folks are working on it tho #1330

**Comment by vi241** [comment]
ok

**Comment by TheOtterlord** [comment]
This can probably be closed as a duplicate then. Then discussion is all in one place

**Comment by vi241** [comment]
@TheOtterlord not exactly a duplicate

**Comment by vi241** [comment]
this is talking about firefox flags not twemoji

**Comment by vi241** [comment]
but I agree with the discussions in 1 place

**Comment by elinarbur** [comment]
> this is talking about firefox flags not twemoji

The twemoji discussion directly addresses the issue. This should just be closed.

**Comment by HarrisonMayotte** [comment]
Yeah the other issue that's open, although not directly firefox, would resolve this and it makes sense to declutter and move the discussion here to that one.
