### ISSUE TITLE
Why this behaviors /problem with responsive design

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#139]
![Screenshot_2021-02-14-00-21-29-200_com android chrome](https://user-images.githubusercontent.com/72514547/107858586-fca95580-6e5a-11eb-96c2-0f1306887512.jpg)
I don't have requested desktop site
Can someone turn off zoom
Use this snippet to stop zoom
```html
 <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />
   
```
And please someone work on responsive design

**Comment by MrMalloc** [comment]
same as #135

**Comment by tanay-pingalkar** [comment]
@MrMalloc ok then please turn off zoom using that above code

**Comment by AB1231231231231231** [comment]
The Bug will be solved soon. :)

**Comment by Playit3110** [comment]
Ok It will be solved soon. :)
