### ISSUE TITLE
Atomic Components Implementation v4 (Tablet)

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#1390]
<h1>Atomic Components v4 (Tablet)</h1>

### Existing Components - Modifications

- [ ] [wip] UserAvatar > SingleUser - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4913%3A478
    - New size `md` (50px).
    - Requires UserAvatar > SingleUser ✅

------

**Don't add any margin around the components.**

Put your component in `kibbeh/src/ui` and create a story in `kibbeh/src/stories`

Use tailwind for styling (see the tailwind config for theme info).

You have to use TypeScript.

Work on the `staging` branch.

Please comment below if you start to work on a component, but only claim a component if you plan to work on it right away so it doesn't block other people.

> All the icons are already available under `src/icons`. Some of them will need to be `20px` wide/tall (check on Figma), so you can pass `width={20} height={20}` as props to the icon component for it to scale to the desired size.

Mockup & grid: https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4911%3A0

If you have any questions ask Ben or @ ajb on [Discord](https://discord.gg/82HzQCJCDg).

**Comment by Mayowa-Ojo** [comment]
I'm going to work on the `UserAvatar` component.

**Comment by BronzW** [comment]
Close this now since it has been done?
