### ISSUE TITLE
Make dogehouse invite only

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1393]
It can't be a clone of Clubhouse unless it is invite-only!

Contributors could get in without an invite, which would encourage contributions!

**Comment by vi241** [comment]
Dogehouse wants to be better than clubhouse

**Comment by vi241** [comment]
Not a clone

**Comment by vi241** [comment]
and invite only is really annoying

**Comment by TheOtterlord** [comment]
Agreed, DogeHouse has been open to all from day 1

**Comment by samarmohan** [comment]
Lol, wanted to see opinions!

**Comment by vi241** [comment]
I dont see the point in this, thank you for your suggestion
