### ISSUE TITLE
Emojis/gifs: Some of the emoji/gifs have the same name, just different capitalization. This is annoying when on Windows

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1394]
**Describe the bug**
Some of the emoji/gifs have the same name, just different capitalization. [omegalul](https://github.com/benawad/dogehouse/blob/staging/kofta/public/emotes/omegalul.png) and [omegaLul](https://github.com/benawad/dogehouse/blob/staging/kofta/public/emotes/omegaLul.png) <br>
This is annoying on Windows

**To Reproduce**
1. Clone the repo on a Windows machine
2. You will get some case-sensitive errors
3. Some changes are listed because Windows can only use one of the files, not both. 

**Expected behavior**
Clones normally

Screenshots**
![image](https://user-images.githubusercontent.com/71091489/111884636-ed08b980-8990-11eb-8938-b7486d2fb8d0.png)

**What device are you on?**
Windows 10

**Fix**
Remove the extra duplicate emojis

**Comment by vi241** [comment]
I will check it

**Comment by ofsho** [comment]
<img width="222" alt="Screen Shot 2021-03-20 at 22 32 20" src="https://user-images.githubusercontent.com/60016719/111884730-2579b900-89cc-11eb-8225-f5115d6666a6.png">
no?

**Comment by vi241** [comment]
I see windows system ... brb

**Comment by samarmohan** [comment]
I am creating a pr, you don't have to worry. (I also really want to contribute)

**Comment by vi241** [comment]
@samarmohan I cant find it

**Comment by vi241** [comment]
Cloned and checked but it didn't work

**Comment by samarmohan** [comment]
Added pr, #1396

**Comment by vi241** [comment]
ok
