### ISSUE TITLE
Add padding to user thumbnail in upper menu - Desktop

### ISSUE THREAD

**Issue by arnaugomez** [benawad/dogehouse#1401]
**Describe the bug**
I suggest adding some padding to the profile picture in the upper menu bar. This will make it more aesthetically pleasing.

I know the task is trivially easy, but I'm a frontend developer with no experience in open source, so this issue would be perfect for me to get started.

**To Reproduce**
1. Log in on desktop
2. Look at the menu bar

**Expected behavior**
Profile picture to have more padding

**Screenshots**
![Captura de Pantalla 2021-03-20 a les 22 33 54](https://user-images.githubusercontent.com/66358043/111886770-9de27900-89d0-11eb-8297-1f75d5a4a587.png)

**What device are you on?**
Desktop, Google Chrome

**Additional context**

**Comment by goldyydev** [comment]
I can not reproduce this bug, can you try disabling all of your extensions?

![image](https://user-images.githubusercontent.com/55450464/111888128-6b417c00-89e2-11eb-84e7-a4ea47fe9374.png)

**Comment by arnaugomez** [comment]
![Captura de pantalla 2021-03-21 a las 11 29 43](https://user-images.githubusercontent.com/66358043/111901486-d4ec7500-8a38-11eb-892e-75dc361b7d5b.png)
I am logged in today and cannot replicate the bug. Yesterday, when I proposed the bug, I had very bad internet connection. Maybe there was also an extension messing up with my CSS. Perhaps it's better to close the issue.
Apologies!
