### ISSUE TITLE
Add single room route

### ISSUE THREAD

**Issue by SirTenzin** [benawad/dogehouse#1403]
**Is your feature request related to a problem? Please describe.** Nope
I am fustrated when i go to code my api wrapper wrapper, i can only track the top public rooms and scheduled rooms. 
**Describe the solution you'd like**
If there was a rooms/room route that would be amazing
**Describe alternatives you've considered**

**Additional context**
heres my wrapper wrapper if you were interested: https://github.com/SirTenzin/dogesword

**Comment by goldyydev** [comment]
Currently getTopPublicRooms will return all rooms. 

AFAIK the getTopPublicRooms function is marked as deprecated with no current alternative (obviously one is being worked on that will probably allow you to get what you want).

</br>
<sup><i>If I answered your question, please make sure to close this issue as we're already flooded with them</i></sup>

**Comment by SirTenzin** [comment]
Oh right thanks ily :)
