### ISSUE TITLE
Kofta: Typescript throwing a lot of errors. TS config needs updating.

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1408]
**Describe the bug**
the `tsconfig.json` may need to be updated. TS is throwing errors left and right. This mostly has to do with `noImplicitAny`. 

**To Reproduce**
1. Clone the repo
2. Go to the `kofta` folder
3. Go into any folder.

**Expected behavior**
No errors should be thrown

**What device are you on?**
Doesn't matter, but Windows 10 with WSL2.

**Other**
I am going through and fixing the TS errors, expect pr soon

**Comment by goldyydev** [comment]
I can not reproduce this. I feel like something is not right with your config

**Comment by samarmohan** [comment]
Wait actually? I'm using VSCode, it's throwing X var implicitly has any type.

**Comment by samarmohan** [comment]
I am just adding `noImplicitAny: false`

**Comment by samarmohan** [comment]
@HarrisonMayotte, did my pr fix the bug?

**Comment by HarrisonMayotte** [comment]
I can set up a local test to see if it does tomorrow when I get a chance but it looks like it does from a brief look.

**Comment by samarmohan** [comment]
Thanks!

**Comment by amitojsingh366** [comment]
@samarmohan i don't experience this issue of yours. Maybe it's because of the setup of your fork or that fact that you are explicitly stating `noImplicitAny: false`
