### ISSUE TITLE
Autocomplete Emotes

### ISSUE THREAD

**Issue by mmattbtw** [benawad/dogehouse#1412]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just being used to something like Chatterino or Twitch Chat, and it is a nice QOL to have on DogeHouse.

**Describe the solution you'd like**
When you type `:` then start typing the emote name after, you would see a small list of emotes (like 3 emotes) with a image of the emote, and the emote name. Then you could click `Enter` and it autocompletes the emote.

**Additional context**

How Twitch does emote completion:
![Twitch emote completion](https://user-images.githubusercontent.com/30363562/111892797-99b45c80-89cc-11eb-9950-65ed81edeb34.png)

**Comment by okdargy** [comment]
Maybe it could look something like this:
![image (25)](https://user-images.githubusercontent.com/76412158/111892900-62927b00-89cd-11eb-91de-f8f429ffb13e.png)

**Comment by isaxk** [comment]
You could also type :) or ;) or :( as shortcuts for 😀😉&😥

**Comment by f1shy-dev** [comment]
I mean I'm adding twemoji (cross platform emojis) so I could add this too while im at it?

**Comment by isaxk** [comment]
_**@vishy-dev**_ said:
>I mean I'm adding twemoji (cross platform emojis) so I could add this too while im at it?

Yeah, do that

**Comment by f1shy-dev** [comment]
Will this be for custom emotes only or all emotes?

**Comment by mmattbtw** [comment]
> Will this be for custom emotes only or all emotes?

I would prefer it to be all, with custom emoted prioritized

**Comment by f1shy-dev** [comment]
It will be for all, emoji-mart has names for the emotes so i could tap into that for this feature

**Comment by BronzW** [comment]
This has been implemented at next.dogehouse.tv
![image](https://user-images.githubusercontent.com/50546858/113869117-a6002e00-97b0-11eb-8378-4a59f878ac82.png)
