### ISSUE TITLE
Speaker chat badges

### ISSUE THREAD

**Issue by mmattbtw** [benawad/dogehouse#1413]
Show a `📣` next to your username in chat, to show that you are a speaker, if you are.

You could also add other things like `👑` for room owner, `🔨` for moderator, and such.

![Speaker Chat Badge](https://user-images.githubusercontent.com/30363562/111893512-3678f900-89d1-11eb-9470-7a80c5c8f52e.png)

**Comment by amitojsingh366** [comment]
Seems like a nice idea!

**Comment by Mayowa-Ojo** [comment]
This is going to be implemented in `kibbeh` right? If yes, there are no components for chat ui yet afaik.

**Comment by jamesql** [comment]
it can be implemented into both kofta and kibbeh once kibbeh has chat ui

**Comment by f1shy-dev** [comment]
We use a sunglasses doge for the room owner right, couldn't we just add this and one for speakers into chat?

**Comment by jamesql** [comment]
@vishy-dev yes I think thats good

**Comment by shubhamrangaa** [comment]
I would like to implement this enhancement.

**Comment by devtanna** [comment]
Interesting, would this badge be a representation of the current user status in the room (when chat list is rendered), i.e.; user is currently a speaker. Or should it be the status of the user when the message was sent?

I'm leaning towards the former implementation.

@shubhamrangaa I noticed you mentioned you wanted to work on this. if you haven't yet I wouldn't mind picking this up :)

**Comment by aaryamvn** [comment]
Hm interesting, if its open i wouldn't mind picking this up.

**Comment by devtanna** [comment]
@fullstackslayer Go for it! I haven't had so much time unfortunately

**Comment by amitojsingh366** [comment]
@fullstackslayer before you start writing code for it please confirm with ajb on [discord](https://discord.gg/UGMJSHEKZ9) first, as this is smtg that's not in the figma.

**Comment by aaryamvn** [comment]
> @fullstackslayer before you start writing code for it please confirm with ajb on [discord](https://discord.gg/UGMJSHEKZ9) first, as this is smtg that's not in the figma.

Cool
