### ISSUE TITLE
Finding an alternative to iohook

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#1415]
**Is your feature request related to a problem? Please describe.**
Yes the problem is #1112 and i feel the only solution to fix this is by finding an alternative to [iohook](https://github.com/wilix-team/iohook) *(global keyup/down event listener)*. I think this has to be done as it causes our electron wrapper to not be able to run on Linux systems! And keeping Linux aside for once, it looks like [iohook](https://github.com/wilix-team/iohook) isn't being maintained anymore!

**Describe the solution you'd like**
A nice alternative to [iohook](https://github.com/wilix-team/iohook) can be found or someone codes one themselves

**Describe alternatives you've considered**
None found tbh...

**Additional context**
Not any additional context ig but i was the one who used [iohook](https://github.com/wilix-team/iohook) in the first place *(lol)* Tho it was cuz i wasn't able to find anything else...

**EDIT:**

Many people are flooding the comments with different libraries that either don't work or are not viable. So below are a few things we are looking for in a ideal library:
- Needs to be a **global** key event listener *(eg: `keyup`/`keydown` events)*
- Needs to be C/C++ based. As those libraries wouldn't require side loading other tools such as JVMs, Python, etc. *(if you find/make any library based on something else but it won't require side loading software it's still viable)*
- Needs to be a maintained library.

Please keep these points in mind before suggesting a library or making a pull request featuring one.

###### Here's why i made this edit btw #1497 

**EDIT 2:**
This issue has been resolved all thanks to @StratusFearMe21 's library [globkey](https://github.com/StratusFearMe21/globkey)
being implemented in #1538 & #1536

**Comment by amitojsingh366** [comment]
Also another big issue is on macOS bigSur clicking any of the dedicated media buttons *(mute, vol up/down, etc.)* on the keyboard crashes the app immediately. This only occurs when iohook is running as i tested it

**Comment by TheOtterlord** [comment]
outdated, but could be forked if we need to change/updated anything? https://www.npmjs.com/package/keypress (edit: not tried it yet, just browsing for ideas)

**Comment by amitojsingh366** [comment]
> 
> 
> outdated, but could be forked if we need to change/updated anything? https://www.npmjs.com/package/keypress (edit: not tried it yet, just browsing for ideas)

Yea ive looked into this before. It dosen't support global events. We need global events

**Comment by btarg** [comment]
This may be worth looking into as an alternative: https://github.com/jaywcjlove/hotkeys/

**Comment by TheOtterlord** [comment]
It seems it uses the browser's document object, so it won't be global :(

**Comment by sahilmob** [comment]
It seams that electron itself supports global event listers or `globalShortcut` as they call it [here](https://www.electronjs.org/docs/api/global-shortcut).

What are the required shortcuts so I try to implement them using the  `globalShortcut` api?

**Comment by amitojsingh366** [comment]
@sahilmob we already used that. It works but what we need is a global `keyup`/`keydown` listener for the Push To Talk key bind specially as it requires for us to know how long the user has pressed. That's where iohook comes in but it's not working on linux

**Comment by babeuh** [comment]
Would this work? https://www.npmjs.com/package/input-event

I'm not on my computer right now so I can't test it.

**Comment by amitojsingh366** [comment]
> Would this work? https://www.npmjs.com/package/input-event
> 
> I'm not on my computer right now so I can't test it.

Please test it and then reply back. From what I've read in the readme this isn't a viable option as they don't mention anywhere that this is a global solution

**Comment by StratusFearMe21** [comment]
> > Would this work? https://www.npmjs.com/package/input-event
> > I'm not on my computer right now so I can't test it.
> 
> Please test it and then reply back. From what I've read in the readme this isn't a viable option as they don't mention anywhere that this is a global solution

I can confirm that this library works globally. But it requires an extra step at install time. The user must be in `input` group in order to gain access to `/dev/input/event0` which is how the library gets global keyevents. This should be trivial to circumvent given that most install systems in Linux allow you to complete this step easily at install time. However this would cripple the AppImage since it can't "install" for say

**Comment by StratusFearMe21** [comment]
I'm not very good at nodejs or javascript in general, but I do know rust. So I used it to make a node module that I'm pretty sure meets all the criteria that was specified. 

[electron_globkey.zip](https://github.com/benawad/dogehouse/files/6191423/electron_globkey.zip)

You use the library by defining a `.on` function, this creates a callback that can be used to do push to talk, here's an example

```javascript
let hook = require('electron_globkey');

hook.on(function(action, key){
    if (action == "keydown" && key == 29) {
        console.log("Ctrl pressed down")
    } else if (action == "keyup" && key == 29) {
        console.log("Ctrl released")
    }
});
```

This example simply watches the Ctrl key and prints whether it was pressed down or released

The `.on` function returns 2 values, a string, and an integer. the string can either be **keyup** or **keydown** and the integer corresponds to the key pressed (I've included a script inside of the **keyfinder** directory for finding which keys corresponds with which numbers). And that's it. I hope you find this library helpful. The module itself is contained in the **dist** folder

**Comment by amitojsingh366** [comment]
> I'm not very good at nodejs or javascript in general, but I do know rust. So I used it to make a node module that I'm pretty sure meets all the criteria that was specified.
> 
> [electron_globkey.zip](https://github.com/benawad/dogehouse/files/6191423/electron_globkey.zip)
> 
> You use the library by defining a `.on` function, this creates a callback that can be used to do push to talk, here's an example
> 
> ```js
> let hook = require('electron_globkey');
> 
> hook.on(function(action, key){
>     if (action == "keydown" && key == 29) {
>         console.log("Ctrl pressed down")
>     } else if (action == "keyup" && key == 29) {
>         console.log("Ctrl released")
>     }
> });
> ```
> 
> This example simply watches the Ctrl key and prints whether it was pressed down or released
> 
> The `.on` function returns 2 values, a string, and an integer. the string can either be **keyup** or **keydown** and the integer corresponds to the key pressed (I've included a script inside of the **keyfinder** directory for finding which keys corresponds with which numbers). And that's it. I hope you find this library helpful. The module itself is contained in the **dist** folder

If this is your project could you please link a github repo. As we wouldn't wanna use anything that isn't open source for this

**Comment by StratusFearMe21** [comment]
Yep, here it is https://github.com/StratusFearMe21/globkey. Sorry for not including this earlier

**Comment by StratusFearMe21** [comment]
I've also created an npm package for this under `globkey` https://www.npmjs.com/package/globkey

**Comment by amitojsingh366** [comment]
Ok we'll look into this

**Comment by StratusFearMe21** [comment]
This code seems to work for me
```javascript
// Code in src/utils/keybinds.ts

export let CURRENT_PTT_KEY = [29, 11];

let hook = require('globkey');
let push_to_talk = false
let last_push_talk = false

hook.on(function (action, key) {
        if (last_push_talk && (key === CURRENT_PTT_KEY[1] || key === CURRENT_PTT_KEY[0]) && action === "keydown") {
            push_to_talk = true
            bWindows.main.webContents.send("@voice/ptt_status_change", false);
        } else if (push_to_talk && action === "keyup") {
            push_to_talk = false
            bWindows.main.webContents.send("@voice/ptt_status_change", true);
        } else if ((key === CURRENT_PTT_KEY[0] && action === "keydown") || (key === CURRENT_PTT_KEY[1] && action === "keydown")) {
            last_push_talk = true
        } else {
            last_push_talk = false
            push_to_talk = false
        }
    });
```
With this code, pressing Ctrl+0 triggers push-to-talk reliably, I'm not entirely sure how keybinds work in the app yet, but I added a function in the library called `capturecombo()` which returns an array of 2 integers when a user presses two keys at the same time when called

```javascript
let hook = require('globkey');

let keybind = hook.capturecombo();

console.log(keybind);

// Sample output: [ 11, 29 ] for Ctrl+0
```

**Comment by amitojsingh366** [comment]
@StratusFearMe21 could i have your discord? i have a few questions...

**Comment by StratusFearMe21** [comment]
CaptainCankle31#6175

**Comment by wes337** [comment]
Why is an external library wanted for this? Electron has [globalShortcuts](https://www.electronjs.org/docs/api/global-shortcut) and the [keydown event](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event) is added to the entire document object.

**Comment by amitojsingh366** [comment]
@wes337 please read my original comment more thoroughly. We need `keyup/keydown` events globally. i.e even when app is in background. Also the event that binds to the entire document object only works when app is in foreground. Hence we need a global key event listener library.

**Comment by amitojsingh366** [comment]
Issue has been resolved! See original comment for more info
