### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by Laurenz1606** [benawad/dogehouse#1427]
Hey DogeHouse Community,
I've loaded the Page, my system language is german and the dropdown showed English. I think, that the Dropdown is defaulted to English, maybe set the dropdown to whatever the users system language is on page load. It's a minor detail i know, but at first i was a bit confused. :)

**Comment by BronzW** [comment]
Is there a media query for this?

**Comment by HarrisonMayotte** [comment]
Not a media query (from what I can find) but it appears that there's a web api for it. https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language

**Comment by goldyydev** [comment]
@vishy-dev while you're working on the language switcher, you might wanna implement this?

**Comment by f1shy-dev** [comment]
I'll try to see if I can fix this. May be an issue in `i18next` or just the way we detect it.

**Comment by rishitxyz** [comment]
```javascript
 <select
      value={i18n.language}
      onChange={(e) => {
        i18n.changeLanguage(e.target.value);
      }}
    >
```
Maybe we can add the value of `navigator.language` here?
If we run 
```javascript
 console.log(navigator.language);
```
for english, it gives out `en-GB` (for me).
So looking at the language component we can slice first two letters from `en-GB` and use it as the value of `<select>` tag maybe.

**Comment by bansalarnav** [comment]
> ```js
>  <select
>       value={i18n.language}
>       onChange={(e) => {
>         i18n.changeLanguage(e.target.value);
>       }}
>     >
> ```
> 
> Maybe we can add the value of `navigator.language` here?
> If we run
> 
> ```js
>  console.log(navigator.language);
> ```
> 
> for english, it gives out `en-GB` (for me).
> So looking at the language component we can slice first two letters from `en-GB` and use it as the value of `<select>` tag maybe.

Slicing and using the first 2 letters will not be a solution as some languages have keys with more than 2 letters.

**Comment by BronzW** [comment]
We could just hard code it in, to exclude some characters like GB

**Comment by vijairamg** [comment]
Is this still active ? If yes , I would like to fix it.

**Comment by BronzW** [comment]
Sure create a pull request

**Comment by ajmnz** [comment]
I believe this has already been addressed, at least on my end it defaults it to Spanish.
