### ISSUE TITLE
Add download link to website

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#1432]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when...
Users accessing the site may not know there is a desktop app

**Describe the solution you'd like**
A download link somewhere on the site

**Describe alternatives you've considered**

**Additional context**
We would possibly need a way of identifying whether to not show the link if the user is already using the desktop app

**Comment by bansalarnav** [comment]
The download link will probably be there on the landing page, depending on what OS the user is on. But as of right now the apps are not complete so no point in hosting them somewhere and adding the link. Dummy buttons can be added for now

**Comment by isaxk** [comment]
> The download link will probably be there on the landing page, depending on what OS the user is on. But as of right now the apps are not complete so no point in hosting them somewhere and adding the link. Dummy buttons can be added for now

There could be download links to the exe/dmg files on the releases pannel on GitHub
We wouldn't need to host them somewhere else

**Comment by bansalarnav** [comment]
That could work for now but definitely not for production as the majority of users won't have ever used GitHub

**Comment by isaxk** [comment]
> That could work for now but definitely not for production as the majority of users won't have ever used GitHub

No I meant a link _to the file_
e.g _https://github.com/benawad/dogehouse/releases/download/v1.0.16/DogeHouse-Setup-1.0.16.exe_

**Comment by goldyydev** [comment]
@ajmnz how will this fit in design wise?

**Comment by ajmnz** [comment]
> @ajmnz how will this fit in design wise?

I think that can come when the landing page hits. Then give the user both options, web or app.

**Comment by isaxk** [comment]
> I think that can come when the landing page hits. Then give the user both options, web or app.

That would be good but if the user is already in the app, we would have to not show it

**Comment by f1shy-dev** [comment]
We could have it show up when the user first visits the page, and also have a button for it somewhere.

**Comment by samarmohan** [comment]
I'll do it

**Comment by isaxk** [comment]
> I'll do it

K thanks

**Comment by samarmohan** [comment]
I'm thinking about putting this in the footer, but if someone has better design ideas, I'm open

**Comment by isaboo** [comment]
> I'm thinking about putting this in the footer, but if someone has better design ideas, I'm open

On the sign in page it could be in the top right hand corner

**Comment by isaxk** [comment]
> I'm thinking about putting this in the footer, but if someone has better design ideas, I'm open

I think a big blue button at the right of the footer would be the best option

You should also check what OS there on:

So on Windows it would link to the exe
On MacOS it would link to to dmg
And on Mobile, it could link to the PWA

**Comment by samarmohan** [comment]
Ok, it's in progress but due to #1462, it won't be released for a while.

**Comment by isaxk** [comment]
> Ok, it's in progress but due to #1462, it won't be released for a while.

Add it to the kibbeh folder then

**Comment by HarrisonMayotte** [comment]
It's no feature PRs across the project. Not just a single section (Kibbeh, kofka, etc.).

**Comment by samarmohan** [comment]
I think he meant to add it later when kibbeh is ready.

**Comment by isaxk** [comment]
In the new design, the menu that appears when tapping your profile picture would be a good place to put the button

**Comment by samarmohan** [comment]
Yes, how would I go about adding translation text for "Download Desktop App"? There are a _lot_ of languages.

**Comment by isaxk** [comment]
The languages don't translate the menus yet so...

**Comment by samarmohan** [comment]
How do I add a download icon SVG, I have no experience with SVGs at all.

**Comment by TheOtterlord** [comment]
you can add an svg by embedding it (as html).

**Comment by isaxk** [comment]
> you can add an svg by embedding it (as html).

in react, you just import it and set the IMG element's SRC as the variable.

**Comment by samarmohan** [comment]
#2220
