### ISSUE TITLE
Dogehouse app logo is HUGE on mac compared to the other ones

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1435]
![image](https://user-images.githubusercontent.com/81065901/111910466-7c909400-8a87-11eb-8c7b-de2c86b71979.png)

**Comment by goldyydev** [comment]
Somebody attempted to fix this, but it messed the Windows icon up

**Comment by f1shy-dev** [comment]
What electron packaging system are we using? There should be support for different sizes across platforms, right?

Also here's a [template for MacOS Big Sur icons.](https://macosicons.com/resources/macos-big-sur-app-icon)

**Comment by Deep-Codes** [comment]
@KittyX29 They haven't released the fixed version


I had fixed this for Mac and if you clone and build it works fine.

See #1286 #1301 

<img width="1122" alt="Screenshot 2021-03-21 at 11 10 22 PM" src="https://user-images.githubusercontent.com/61158210/111915084-9e474680-8a9a-11eb-88e0-918230389112.png">

idk how it looks on windows.

**Comment by ghost** [comment]
Issue fixed [for mac] in  #1286 #1301

**Comment by ghost** [comment]
Lemme know for windows and i will close it

**Comment by ghost** [comment]
@Deep-Codes Which terminal do u use lol ? Looks gOOD :)

**Comment by Deep-Codes** [comment]
> @Deep-Codes Which terminal do u use lol ? Looks gOOD :)

[Hyper Terminal by Vercel](https://hyper.is/) & [Oh My Zsh](https://ohmyz.sh/) 🚀

**Comment by TheOtterlord** [comment]
Looks fine for me on windows:
![image](https://user-images.githubusercontent.com/64310361/111961534-16d4f400-8ae9-11eb-8bd0-23f583401ad5.png)
