### ISSUE TITLE
Regular auth, not just OAuth

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1436]
**Is your feature request related to a problem? Please describe.**
Add normal authentication using normal usernames and passwords

**Describe the solution you'd like**
normal Elixir/Phoenix auth solutions

**Comment by f1shy-dev** [comment]
We could, but then we would have to implement things such as profile picture filtering and things ourselves right? Oauth just is easier. I guess when we release `kibbeh` we could add Google and other commonly used providers too.

**Comment by HarrisonMayotte** [comment]
Short term oauth is probably easier but it would make sense later down the line to be able to make accounts locally.

**Comment by TheOtterlord** [comment]
Closing as duplicate of #842
