### ISSUE TITLE
Electron App: Add ability to record calls 

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1437]
**Is your feature request related to a problem? Please describe.**
Recording would be a nice feature and would make more people use the desktop app.
Dogehouse might as well have everything, we have chats, dogebots, etc.

**Describe alternatives you've considered**
3rd party recording services

**Comment by BronzW** [comment]
Hosts and bots?

**Comment by goldyydev** [comment]
How is this different from #578

**Comment by samarmohan** [comment]
Sorry
