### ISSUE TITLE
Dogehouse crash log for anyone who wants to see 

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1439]
Process:               DogeHouse [4955]
Path:                  /Applications/DogeHouse.app/Contents/MacOS/DogeHouse
Identifier:            com.electron.dogehouse
Version:               1.0.16 (1.0.16)
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           DogeHouse [4955]
User ID:               501

Date/Time:             2021-03-21 21:00:30.325 +0530
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        5D3A0FEF-2924-929D-0BEF-D66AE60B6155

Sleep/Wake UUID:       7F45CC5A-F835-43A1-B1AF-7FA77834F124

Time Awake Since Boot: 32000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [4955]

**Comment by goldyydev** [comment]
Please put this in #1229
