### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#145]
![Screenshot_20210213-153015_Brave](https://user-images.githubusercontent.com/65829743/107862184-b5967280-6e10-11eb-9874-9537b39f9b86.jpg)
![Screenshot_20210213-153033_Brave](https://user-images.githubusercontent.com/65829743/107862188-b9c29000-6e10-11eb-8475-a2c8f031c805.jpg)

**Comment by MrMalloc** [comment]
This is related to #136 and should be resolved with #140

**Comment by nadirabbas** [comment]
i think this is fixed
