### ISSUE TITLE
Whisper doesn't work when @mentioning people

### ISSUE THREAD

**Issue by prokopschield** [benawad/dogehouse#1450]
**Describe the bug**
When you @mention someone in a whisper, the message is not handled as a whisper.

**To Reproduce**
1. Type ` #@user1 @user2 ` in chat

**Expected behavior**
Whisper should work even if someone is mentioned in it

**What device are you on?**
UMAX VisionBook 14Wa

**Comment by TheOtterlord** [comment]
working for me. what browser are you in?

**Comment by amitojsingh366** [comment]
works for me as well...

**Comment by vi241** [comment]
It works for me

**Comment by vi241** [comment]
didn't mean to close

**Comment by amitojsingh366** [comment]
I will be closing this as there has not been any response from the author.

**Comment by prokopschield** [comment]
It appears to work normally now.
