### ISSUE TITLE
Login with a github account with dual-factor authentication in the desktop application impossible

### ISSUE THREAD

**Issue by Nenyoko** [benawad/dogehouse#1451]
Description: when trying to log in with a Github account with two-factor authentication on the desktop app, you end up on an invalid/inexistent Github page. So you can't connect and use the application.

1. Launch the desktop app
2. Click on "Login with Github"
3. Enter your credentials and click on "Sign in"
4. Enter your 6-digit code and click on "Verify"
5. See the error

![WsTFA](https://user-images.githubusercontent.com/59934079/111916702-81037f80-8a7c-11eb-8a38-94f1937c4450.png)
![InAppTFA](https://user-images.githubusercontent.com/59934079/111916703-819c1600-8a7c-11eb-91bf-3766577b61f2.png)

**Comment by amitojsingh366** [comment]
Fixed this in #1404
