### ISSUE TITLE
<3 should make the heart emoji in chat

### ISSUE THREAD

**Issue by Jackbaude** [benawad/dogehouse#1456]
**Problem**
When I type `<3` in chat I expect to see a heart emoji but there is none.

**Solution**
`<3` should auto complete a heart

**Describe alternatives you've considered**
`:heart:` could make the heart but I think many people are used to `<3`

**Comment by goldyydev** [comment]
As per Ben's instructions, new emojis are not to be allowed (for now).

**Comment by HarrisonMayotte** [comment]
I don't think this would really be a new emoji. It'd just convert the text emoticon to a proper emoji.

**Comment by Jackbaude** [comment]
What is the reasoning behind not adding new emojis? I don't think this is like adding a new emoji. The heart emoji already exists and people can use it, this is simply asking for a text shortcut. 

As I look more into it, it looks like you can't write colon emojis, such as `:smile:` or `:handshake:`. This is something that I also believe should be available because it is a very common shortcut.
