### ISSUE TITLE
When copying an emoji in the chat it doesn't include the colons on either side.

### ISSUE THREAD

**Issue by HarrisonMayotte** [benawad/dogehouse#1458]
**Describe the bug**
When copying an emoji in the chat it doesn't include the colons on either side.

**To Reproduce**
1. Copy an emoji posted in the chat.
2. Attempt to past the emoji.
3. Observe that the colons that should be on either side are not present.

**Expected behavior**
It should have the colons around the emoji.

**Screenshots**
https://gyazo.com/4d18232c9aae536ae65631e274bd2de7

**What device are you on?**
Windows, Desktop, Chrome

**Comment by goldyydev** [comment]
#1459
