### ISSUE TITLE
adding arabic crepy language

### ISSUE THREAD

**Issue by sharafabacery** [benawad/dogehouse#1468]
**Is your feature request related to a problem? Please describe.**
something, there are language Egypt develop from arabic change the char. you want this letter س and get a word with no meaning but must begin with the letter we discard 

**Describe the solution you'd like**
ساسب حواجب سفهم يتنيل ساجة حالات = حاسب يفهم حاجه

**Comment by goldyydev** [comment]
Can you please explain this to somebody who can't understand a single word in Arabic?

(in my defense, i tried learning arabic for 2 years but can't remember anything)

**Comment by sharafabacery** [comment]
this was some develop to Arabic in Egypt the gangs talk to each other like that they exchange the letter we want to change with (س=s) and generate a new word  but must begin with the letter we take it   (sappy hob ==happy) ,I make this issue for fun

**Comment by amitojsingh366** [comment]
Your description makes 0 sense. Is this sarcastic? If not please explain more carefully

**Comment by sharafabacery** [comment]
@amitojsingh366  I make this issue for fun

**Comment by amitojsingh366** [comment]
ok. i will close it for fun then.
