### ISSUE TITLE
When shawarma/voice server goes down and back up, audio is no longer heard

### ISSUE THREAD

**Issue by Choongkyu** [benawad/dogehouse#1472]
**Describe the bug**

**To Reproduce**
1. Run all services following CONTRIBUTING.md
2. Join room with two browsers and sign in using two github/twitter accounts to confirm audio can be heard
3. Quit shawarma/voice server and restart
4. See error (no audio)
5. Try to reload browser to be prompted that user interaction is needed for audio but see that no such prompt shows up

**Expected behavior**
Audio to be heard

**What device are you on?**
macbook pro

**Comment by ghost** [comment]
Unable to reproduce, works fine for me ! :)

**Comment by bansalarnav** [comment]
You will have to reload the browser window in order to hear voices again. As when the voice server turns off the WebRTC connection is broken. Reloading after the server is back up creates the connection again

**Comment by Choongkyu** [comment]
@ArnavBansal11 thanks. would you happen to know how the frontend communicates with the voice server?  It looks like there might be a direct connection via websocket, but then it also looks like it communicates indirectly through the backend to the message broker. Are there ports that need attention/forwarding?
