### ISSUE TITLE
Holding the 'Open chat' button repeats the action

### ISSUE THREAD

**Issue by MMK21Hub** [benawad/dogehouse#1479]
**The bug**
Pressing and holding the enter key while the "Chat" button is focused flashes the screen quickly between chat being open and closed. This is especially a problem for users who suffer from seizures. Note that pressing space while the button is focused on has the correct behaviour.

This bug is worse at narrow viewports, i.e. when the chat occupies the whole screen.

**Steps to Reproduce**
1. Enter a room
2. Tab to the "Chat" button
3. Hold down enter
  → :x: The chat flashes on and off rapidly

**Expected behaviour**
The chat will enable/disable once each time I hit enter

**Attatchments**
https://user-images.githubusercontent.com/50421330/111961358-e0977480-8ae8-11eb-8036-213ec713c62c.mp4

**What device are you on?**
Windows 10. Affects the Electron App (v1.0.16), staging.dogehouse.tv, and dogehouse.tv.

**Comment by wes337** [comment]
It was decided that this is an invalid bug

**Comment by MMK21Hub** [comment]
Closing as WAI (source: <https://github.com/benawad/dogehouse/pull/1492#issuecomment-804483637>)
