### ISSUE TITLE
No rooms visible

### ISSUE THREAD

**Issue by boorah** [benawad/dogehouse#1485]
**Describe the bug**
Not able to view any rooms

**Screenshots**

![Screenshot from 2021-03-22 16-53-15](https://user-images.githubusercontent.com/39365143/111982721-50c8e900-8b2f-11eb-9a58-5dfc21b04c43.png)

**What device are you on?**
Ubuntu and Android

**Additional context**
I was in a room last week when suddenly I was kicked out of the room and everything disappeared

**Comment by ghost** [comment]
can u refresh page ?

**Comment by boorah** [comment]
I refreshed the page, tried login again but nothing worked

**Comment by amitojsingh366** [comment]
@boorah make browser go to background *(open another app or smtg)* and then back to foreground. Tell me if it still occurs

**Comment by boorah** [comment]
Still same

**Comment by amitojsingh366** [comment]
@boorah any console logs? anything that looks like an error

**Comment by boorah** [comment]
nope

![Screenshot from 2021-03-22 18-27-59](https://user-images.githubusercontent.com/39365143/111993245-61cc2700-8b3c-11eb-8754-fcaf08be250c.png)

**Comment by bertmeeuws** [comment]
Try incognito?

**Comment by boorah** [comment]
doesn't work

**Comment by boorah** [comment]
If I know the room id and directly paste the url with it, I am able to join the room

**Comment by bertmeeuws** [comment]
Have you tried a different browser? Deleting the browser's cache?

**Comment by boorah** [comment]
yes, I tried brave and chrome too

**Comment by benawad** [comment]
this could happen if you are banned from all current rooms, but I find that unlikely

**Comment by benawad** [comment]
try creating a room does it let you do that?

**Comment by boorah** [comment]
> try creating a room does it let you do that?

Yes

![IMG_20210322_192745.jpg](https://user-images.githubusercontent.com/39365143/112001252-ce4b2400-8b44-11eb-80a5-0c45349bdaba.jpg)

**Comment by herEmanuel** [comment]
Maybe something is interfering with the websocket traffic? In that case the problem may be on your computer

[](https://stackoverflow.com/questions/21191620/websocket-not-sending-data)

**Comment by herEmanuel** [comment]
Maybe something is interfering with the websocket traffic? In that case the problem may be on your computer

https://stackoverflow.com/questions/21191620/websocket-not-sending-data

**Comment by benawad** [comment]
@boorah can you try https://next.dogehouse.tv

**Comment by boorah** [comment]
> @boorah can you try https://next.dogehouse.tv

No, it doesn't work on that too

![Screenshot from 2021-04-01 06-35-07](https://user-images.githubusercontent.com/39365143/113229376-7e8efa00-92b4-11eb-83b1-76565daefc33.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/81065901/113245551-d2a9d680-92d4-11eb-8f52-cef0c6d72f13.png)
It works for me tho

**Comment by ghost** [comment]
Could you try signing out and signing in again @boorah

**Comment by boorah** [comment]
> Could you try signing out and signing in again @boorah

I already tried that

**Comment by kndwin** [comment]
Could you advise if the issue is still happening? If so, it'll be helpful to capture a .har file and see if there's any issues with connectivity.
https://www.medianova.com/en-blog/2019/07/15/a-step-by-step-guide-to-generating-a-har-file

**Comment by benawad** [comment]
@boorah I found a nasty bug that I think was preventing you from seeing rooms, can you see if you see them now

**Comment by boorah** [comment]
> @boorah I found a nasty bug that I think was preventing you from seeing rooms, can you see if you see them now

Yes, now the rooms are visible :D. What was the issue?

**Comment by benawad** [comment]
If someone blocks you it didn't show rooms
