### ISSUE TITLE
Norwegian translation looks weird for some reason that's probably code related

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1491]
**Describe the bug**
If you check out DogeHouse with Norwegian Bokmål localization, some sentences are overly capitalized, like how I typed when I was 8. This probably isn't stupid in English, but in Norwegian, it just looks weird.

**To Reproduce**
1. Go to your browser (Vivaldi, Firefox, Brave etc)
2. Make a new tab
3. Go to this link: dogehouse.tv
4. Change locale to Norwegian Bokmål in the dropdown menu
5. See error

**Expected behavior**
Something like "Logg Inn Med GitHub" should be "Logg inn med GitHub".

**Screenshots**
![image](https://user-images.githubusercontent.com/57069715/112022756-e0bc6200-8b32-11eb-96d1-45898fa13400.png)
![image](https://user-images.githubusercontent.com/57069715/112022797-e87c0680-8b32-11eb-95bd-d11d1eaaea67.png)
![image](https://user-images.githubusercontent.com/57069715/112022814-eb76f700-8b32-11eb-8c47-7a76339ef4e7.png)

there are many more.

Windows 10 Education 20H2, Vivaldi 3.7

**Additional context**

**Comment by bansalarnav** [comment]
This seems to be the case with every language. The first letter of each word is capitalized even though it is not so in the respective `translation.json` files.

**Comment by f1shy-dev** [comment]
The custom button has a tailwind property `capitalise` so it makes the first letters capital. We could either add a thing into the language files whether to do this or just remove it and manually capitalise each language file

**Comment by ghost** [comment]
The second option looks good.

**Comment by BronzW** [comment]
That should probably not be done in css, but already done in the translation.json files so the grammar matches and works for each language.

**Comment by f1shy-dev** [comment]
Yeah!

**Comment by BronzW** [comment]
Yeah we should not use ``capitalise`` in the new design

**Comment by ajmnz** [comment]
Closing this for now, request to reopen if needed.
