### ISSUE TITLE
Username not changing/not displaying if username was taken

### ISSUE THREAD

**Issue by nedasv** [benawad/dogehouse#1494]
**Describe the bug**
Changing username bug, whenever I change my username and refresh the page it sets it back to the old auto-generated one. It also does not display if a username was taken.

**To Reproduce**
1. Go to **Edit Profile**
2. Change 'username' to anything
3. Refresh and shows old username

**Screenshots**
![errordogehouse](https://user-images.githubusercontent.com/68791747/112026670-570a9580-8b2e-11eb-85c3-cf0311310334.gif)

**What device are you on?**
Firefox 86.0.1 (64-bit) - Windows 10

**Comment by bansalarnav** [comment]
It shows me a toast if the username is already taken and also updates my username

**Comment by WManuel69** [comment]
I can reproduce this issue :(

**Comment by TheOtterlord** [comment]
Kofta is deprecated. If this is happening to you on Kibbeh, please open a new issue
