### ISSUE TITLE
missing icon component in kibbeh

### ISSUE THREAD

**Issue by Mayowa-Ojo** [benawad/dogehouse#1496]
**Describe the bug**
The `GenericNotification` component tries to import `LgSolidRocket` icon component from `icons` but it doesn't exist. 

**To Reproduce**
1. Go to 'kibbeh/src/ui/NotificationElement/GenericNotification.tsx'
2. Check import statements
3. See error

**Expected behavior**
There should be a `LgSolidRocket` component or the import should just be `SolidRocket`

**Screenshots**

**What device are you on?**

**Additional context**

**Comment by amitojsingh366** [comment]
I'm not really sure this is a bug as kibbeh is still incomplete...

**Comment by Mayowa-Ojo** [comment]
Yh, just wanted to point it out.

**Comment by WManuel69** [comment]
I'd not think it's meant to be like it is right now, so it's good that you made this issue

**Comment by bansalarnav** [comment]
> 
> 
> **Describe the bug**
> The `GenericNotification` component tries to import `LgSolidRocket` icon component from `icons` but it doesn't exist.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to 'kibbeh/src/ui/NotificationElement/GenericNotification.tsx'
> 
>     2. Check import statements
> 
>     3. See error
> 
> 
> **Expected behavior**
> There should be a `LgSolidRocket` component or the import should just be `SolidRocket`
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **What device are you on?**
> 
> **Additional context**
> Add any other context about the problem here.

I think this is an issue in many components. Because many components were made before the `Sm` and `Lg` prefix was removed and they are still importing icons with those prefixes
