### ISSUE TITLE
Request to Speak button is gone!

### ISSUE THREAD

**Issue by okdargy** [benawad/dogehouse#1506]
**Describe the bug**
Can't see the request button

**To Reproduce**
1. Go to any room
2. See error

**Expected behavior**
The request speaker button should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/76412158/112074083-6f38df80-8b43-11eb-91e5-c7a1ffd92ff2.png)

**What device are you on?**
Chromebook

**Comment by Abogical** [comment]
@benawad The bug seems to be quite recent. Check your recent commits.

**Comment by okdargy** [comment]
I think it is a UI error since I used my bot to request to speak and it worked.

**Comment by Abogical** [comment]
> I think it is a UI error since I used my bot to request to speak and it worked.

![dogebug](https://user-images.githubusercontent.com/10688496/112074492-15560b00-8b7f-11eb-8daf-ba2dba4f1f26.png)

**Comment by okdargy** [comment]
Seems to be back?
![image](https://user-images.githubusercontent.com/76412158/112074948-7365fc80-8b45-11eb-82c6-d6097fa50fe2.png)

**Comment by dragonismcode** [comment]
I have 0 iq.. just realized it was because we only had 1 listener which was myself.
