### ISSUE TITLE
Transcript for language translation in rooms

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#1513]
**Is your feature request related to a problem? Please describe.**
Users who don't speak the language of the speakers in the room won't be able to understand the conversation

**Describe the solution you'd like**
A transcript which automatically translates the text to the users selected language

**Additional context**
This feature is just a suggestion for the final realease of the new design

**Comment by amitojsingh366** [comment]
This is cool. But would require a lot of work and also there's this #1462
