### ISSUE TITLE
search select for languages

### ISSUE THREAD

**Issue by OfekShochat** [benawad/dogehouse#1515]
**Is your feature request related to a problem? Please describe.**
when you select a language, when you will have tons of them, it will be hard to find your preferred one. so search selection would work.
**Describe the solution you'd like**
search selection (https://select2.org/searching)
**Describe alternatives you've considered**
didn't think of it

**Additional context**
something something
also, am I the only one that when I join the discord it says there are no text channels or something?

**Comment by amitojsingh366** [comment]
Seems cool but #1462

**Comment by f1shy-dev** [comment]
I was working on new language picker but #1462 so I scrapped it.

**Comment by HarrisonMayotte** [comment]
The feature can be worked on but it just wouldn't be pushed until following the new design's implementation.

**Comment by OfekShochat** [comment]
also very easy implementation
this is just a recommendation for a TODO. so this can be implemented anytime obviously 
if this will be implemented in new design, sure idk

**Comment by f1shy-dev** [comment]
I was redesigning the picker for twemoji too, so it was going to be custom.

**Comment by ajmnz** [comment]
We won't add a search bar inside the LanguageSelector for now
