### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by SalihBulmaz** [benawad/dogehouse#1519]
It is windows 10 with electron app. 
Neither github nor twitter works for authorization. Leads to github /login/oauth/authorize which is 404 and twitter home page without authorizing.

**Comment by amitojsingh366** [comment]
@SalihBulmaz are you sure you're on the latest version of the app?

**Comment by amitojsingh366** [comment]
@HarrisonMayotte i don't think this bug still occurs. I had fixed it fairly recently, almost right before this issue was created.

**Comment by HarrisonMayotte** [comment]
Gotcha. I'll close this then.

**Comment by SalihBulmaz** [comment]
Sorry for not replying. it was an earlier release. It's working properly now.
