### ISSUE TITLE
slowmode on chat

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#153]
The owner of the room should be able to disable and enable slowmode. like discord.

**Comment by HonbraDev** [comment]
It would be nice to also allow mods to bypass the chat limit. I have a bot that responds to commands and if there are 2 people trying to interact at the same time, one of them can't see their messages.

**Comment by TheOtterlord** [comment]
Also, maybe allowing the slowmode timeout to be changed could be a good idea, larger rooms may want a longer timeout

**Comment by sam17896** [comment]
The twitch do that when the chat is on slow mode, a user can send message after 5 seconds of his previous message. We can also make it so the admin the adjust the time, so the default time will be 5 second and admin can change to 10 or whatever

**Comment by amitojsingh366** [comment]
has been added in #2553
