### ISSUE TITLE
Close emoji menu after pressing send

### ISSUE THREAD

**Issue by arhammusheer** [benawad/dogehouse#1547]
**Is your feature request related to a problem? Please describe.**
The Emoji menu has to be closed manually even after pressing send

**Describe the solution you'd like**
Close the emoji menu automatically after pressing send

**Describe alternatives you've considered**
Manually press the button

**Comment by f1shy-dev** [comment]
Is this `kofta` or `kibbeh`?

**Comment by somerandomdev49** [comment]
It is the React frontend

**Comment by drvladb** [comment]
Please provide more details regarding the browser / platform you are using.

**Comment by TheOtterlord** [comment]
As Kofta is deprecated and Kibbeh correctly handles this, this issue will be closed. If it occures to you in Kibbeh, please reopen
