### ISSUE TITLE
Discord Rich Presence for Baklava

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1549]
I just wanted to get feedback on if this would be a good idea, so I don't code something that won't work or won't be merged. It would say maybe what room you are in and how many participants are in that room (not private rooms though).

**Comment by amitojsingh366** [comment]
@BronzW i don't think we will be implementing this as DogeHouse is supposed to compete with discord too. Instead we are working on a rich presence system for DogeHouse itself

**Comment by BronzW** [comment]
Really? There are thoughts of having discord login which would be even more anti-competitive with discord.

**Comment by benawad** [comment]
0. @amitojsingh366 we are not competing with discord
1. I like rich presence

**Comment by amitojsingh366** [comment]
@benawad ok then ill add this in?

**Comment by BronzW** [comment]
Now implemented
