### ISSUE TITLE
clickable links in chat

### ISSUE THREAD

**Issue by msal4** [benawad/dogehouse#155]
We need clickable links in the chat

**Comment by msal4** [comment]
I'll do this one if no one is already working on it.

**Comment by drvladb** [comment]
Idea: Have a popup when you click on one that asks you if you really want to do that.

**Comment by msal4** [comment]
yeah, but always opens links in a new tab.

**Comment by antonelmvik** [comment]
Yes

**Comment by benawad** [comment]
I haven't setup the system to handle different types of message tokens yet, wait for me to add emotes to do this.

**Comment by msal4** [comment]
Should probably close this one since they're implemented now.
