### ISSUE TITLE
language button displays differently depending on chosen language

### ISSUE THREAD

**Issue by Hotasice123** [benawad/dogehouse#1555]
1) for example english:
![image](https://user-images.githubusercontent.com/50680297/112394870-ad79fe80-8cfd-11eb-8a2f-af863185f509.png)
2) for example german:
![image](https://user-images.githubusercontent.com/50680297/112394955-d26e7180-8cfd-11eb-8e79-aa381198e3a6.png)

Not sure if it's a feature or a bug, but to me the english one doesn't look as aesthetically pleasing as the german one.

**Comment by samarmohan** [comment]
That is because Origin Story in German is so long, it adds a line break to the footer. In `kibbeh`, the new frontend, it will be nicer.

**Comment by ajmnz** [comment]
This relates to kofta, which is now dead
