### ISSUE TITLE
Cannot read chat if the room description is too long.

### ISSUE THREAD

**Issue by darthnithin** [benawad/dogehouse#1556]
**Describe the bug**
When the room description displays longer than the available height on the screen, it prevents a user from reading the chat, as they cannot scroll past the room description. 

**To Reproduce**
1. Create a room
2. Name it anything
3. For room description fill it with a sufficiantly long unicode character that will fill up the page. I used "𒐫".
4.  Open Chat by clicking chat on the bottom bar
5. Click "Show More" on the room discription
6. Now you are unable to view or read chat messages, and you are unable to scroll past the room description. 
**Expected behavior**
You are able to scroll past the room description 

**Screenshots**
![image](https://user-images.githubusercontent.com/10778861/112401758-73dad080-8cc8-11eb-9584-13338f2d94e3.png)

**What device are you on?**
Chromebook

**Comment by drvladb** [comment]
Like #1222, Maybe find a way to clamp description based on character length instead of the number of characters.
