### ISSUE TITLE
Long display names cause names to go past the edge of the page

### ISSUE THREAD

**Issue by darthnithin** [benawad/dogehouse#1557]
**Describe the bug**
Very long display names continue outside the user list in the Room list.

**To Reproduce**
1. Change your display name to a name consisting of long Unicode characters. (i used ﷽)
2. Join a room
3. Click the house in the top left corner to go back to the page listing the rooms.

**Expected behavior**
The long display names should be truncated.
**Screenshots**
![image](https://user-images.githubusercontent.com/10778861/112402664-2e1f0780-8cca-11eb-8004-09707dc8da33.png)

**What device are you on?**
Chromebook
**Additional context**

**Comment by samarmohan** [comment]
I absolutely _hate_ people who make their names super long! 😀 
I think we can just add a name limit either when changing your username or displaying it. <br>

YouTube has the same problem to

**Comment by drvladb** [comment]
It should clamp the user names in the preview menu like it does for room names and names in the room itself.
