### ISSUE TITLE
[ACCESSIBILITY] Use arrow keys to navigate through room members

### ISSUE THREAD

**Issue by MMK21Hub** [benawad/dogehouse#1562]
**Is your feature request related to a problem? Please describe.**
At the moment, the tab key is used to move the focus from one room member to the next, and eventually to any other button. This is fine with a few room members, but in a large room, this is tedious.

**Describe the solution you'd like**
The arrow keys should be used to navigate within the grid of users, while `tab` will take you you fo the grid.

**Describe alternatives you've considered**
Holding down `tab` to move focus quickly. This is not ideal, however.

**Additional context**
I am making this Feature Request for <https://next.dogehouse.tv/>, however, Kofta also suffers from a similar issue.

**Comment by samarmohan** [comment]
> I am making this Feature Request for https://next.dogehouse.tv/, however, Kofta also suffers from a similar issue.

Don't or Kofta, Kibbeh is what we should be focusing on.

**Comment by MMK21Hub** [comment]
Yes, that's what I meant.

**Comment by MMK21Hub** [comment]
Closing due to https://www.youtube.com/watch?v=I8PkQgPiSq8
