### ISSUE TITLE
New line support in chat

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1564]
In discord, you can do ``shift+enter`` to create a new line.

**Comment by samarmohan** [comment]
This is a great idea! It may be hard to implement though.

**Comment by BronzW** [comment]
add a state if you are pressing shift and if you press enter you simply add a new line

**Comment by f1shy-dev** [comment]
I was planning to redo the whole textbox anyway to support WYSIWYG emojis and more, but that was for kofta. When emojis gets added to new-design I could work on this

**Comment by BronzW** [comment]
@vishy-dev If you still want to work on this emojis have been added to kibbeh now

**Comment by TheOtterlord** [comment]
I'm going to close this as it's covered in #1826 along with markdown. If you wish to contribute to the discussion, please do so there
