### ISSUE TITLE
Emojis (with no space) are not properly rendered in the new design

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#1568]
**Describe the bug**
When sending emojis without a space, they are rendered in the old design but not in the new one

**To Reproduce**
1. Open new design
2. Join room
3. Have a bot send two emojis with no space in between

**Expected behavior**
Emojis should render even when there is no space between them

**Screenshots**
![image](https://user-images.githubusercontent.com/33793511/112480230-6dd20780-8d3b-11eb-942a-66f1a349d612.png)
![image](https://user-images.githubusercontent.com/33793511/112480495-b7baed80-8d3b-11eb-9d5d-64c7bf3f2cfa.png)

**What device are you on?**
Macbook; Macos 10.15

**Comment by drvladb** [comment]
This only works with bots for some reason.

**Comment by ajmnz** [comment]
@drvladb I believe this has already been fixed. Can you confirm so we can close it?

**Comment by drvladb** [comment]
Fixed
