### ISSUE TITLE
Electron crashes when opening on M1 MacBook Pro

### ISSUE THREAD

**Issue by arhammusheer** [benawad/dogehouse#1569]
**Describe the bug**
The electron app throws an error when opening.

**To Reproduce**
1. Use an M1 Macbook
2. Download the release from the GitHub repo
3. Install the app and open

**Expected behavior**
The app works and loads up dogehouse website

**Screenshots**
<img width="335" alt="image" src="https://user-images.githubusercontent.com/42689647/112481087-abb34800-8d9c-11eb-8255-4d7a19e5d396.png">

**What device are you on?**
M1 Macbook Pro

**Comment by TheOtterlord** [comment]
Thank you for the report. This issue seems to exist across all macOS devices since the latest release. We believe we have patched this in `staging` and are just awaiting a new release. I'll updating this issue with any progress updates until this is solved.

**Comment by amitojsingh366** [comment]
Yes this issue has been fixed. All we're waiting now is for @benawad to create a new release...

**Comment by amitojsingh366** [comment]
@arhammusheer please try out the latest release https://github.com/benawad/dogehouse/releases/latest

**Comment by amitojsingh366** [comment]
I just tested it. This still occurs. Probably has to do something with signing as my local build installs perfectly...

**Comment by samarmohan** [comment]
Yeah definitely a signing error.

**Comment by amitojsingh366** [comment]
@benawad is working on this

**Comment by amitojsingh366** [comment]
This issue should be fixed now
