### ISSUE TITLE
Build portable apps (for windows) for windows along with installers

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#1570]
**Is your feature request related to a problem? Please describe.**
Not everyone wants to install Dogehouse, building portable apps will allow them to try it first.

**Describe the solution you'd like**
Build portable apps for windows

**Additional context**
https://stackoverflow.com/a/50906309

**Comment by amitojsingh366** [comment]
@drvladb we were building portable before installers but gh actions didn't want to build them at, so now we're sticking to installers

**Comment by drvladb** [comment]
@amitojsingh366 sounds good

**Comment by samarmohan** [comment]
Close this since @amitojsingh366 explained?

**Comment by drvladb** [comment]
Yeah
