### ISSUE TITLE
Running `npm run commit` throws error

### ISSUE THREAD

**Issue by cursorial** [benawad/dogehouse#1571]
**Describe the bug**
Running `npm run commit` results in errors in my development environment

**To Reproduce**
1. Clone the repository
2. Change to root directory
3. Make your changes (I made some to `kofta/src/app/modules/room-chat/RoomDescription.tsx`)
4. Run `npm i`
5. Run `npm run commit`
6. Choose bug fix
7. Fill out relevant details for your commit

```
$ npm run commit

> dogehouse@ commit /home/mc/oss/dogehouse
> cz

cz-cli@4.2.3, cz-conventional-changelog@3.3.0

? Select the type of change that you're committing: fix:      A bug fix
? What is the scope of this change (e.g. component or file name): (press enter to skip) roomdescription
? Write a short, imperative tense description of the change (max 78 chars):
 (47) add max height and scrolling to roomdescription
? Provide a longer description of the change: (press enter to skip)
 
? Are there any breaking changes? No
? Does this change affect any open issues? Yes
? If issues are closed, the commit requires a body. Please enter a longer description of the commit itself:
 -
? Add issue references (e.g. "fix #123", "re #123".):
 fix #1556

> @dogehouse/kibbeh@0.1.0 format /home/mc/oss/dogehouse/kibbeh
> prettier --write src

sh: 1: prettier: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @dogehouse/kibbeh@0.1.0 format: `prettier --write src`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @dogehouse/kibbeh@0.1.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mc/.npm/_logs/2021-03-25T13_48_50_245Z-debug.log
husky - pre-commit hook exited with code 1 (error)
git exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dogehouse@ commit: `cz`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dogehouse@ commit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mc/.npm/_logs/2021-03-25T13_48_50_294Z-debug.log
```

**Expected behavior**
My changes to be committed.

**Screenshots**

**What device are you on?**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Additional context**

Looks like `prettier` is not found, I tried installing with `--save-dev` and re-running but I ended up hitting another error about another missing package, I tried manually installing this package also, but kept hitting missing package errors.

Any ideas why all of the required packages are not being installed when I run `npm i`?

**Comment by amitojsingh366** [comment]
@TheOtterlord looks like what happened to you?

**Comment by samarmohan** [comment]
Delete `node_modules` everywhere, rerun yarn.

**Comment by cursorial** [comment]
> Delete `node_modules` everywhere, rerun yarn.

Same again

**Comment by cursorial** [comment]
:facepalm: `yarn`, not `npm i`

**Comment by TheOtterlord** [comment]
EDIT: Never mind. I reread the logs. Yeah, but it only caused problems on baklava, I just could not find the modules in the package.json of kofta
