### ISSUE TITLE
Where will a footer be in the new design? 

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1575]
In the old design, you could report a bug, join the discord, and change your language via the footer. Where will the footer be in the new design or will there be a new page where you can do this stuff. 

Re #1432

**Comment by ajmnz** [comment]
<img width="249" alt="Screenshot 2021-03-25 at 19 48 01" src="https://user-images.githubusercontent.com/57961822/112527151-0485df00-8da3-11eb-848e-8fb9e120cdaf.png">
