### ISSUE TITLE
ZTsmug broken

### ISSUE THREAD

**Issue by troler36** [benawad/dogehouse#1576]
**Describe the bug**
:ZTsmug: does not show up in the chat

**To Reproduce**
1. Go to a room
2. Click on messages (Emoji's)
3. Click on "ZTsmug"

**Comment by amitojsingh366** [comment]
yep can confirm. it doesn't work

**Comment by TheOtterlord** [comment]
Kofta is now deprecated. As this problem does not exist in Kibbeh, this issue is now resolved. If you find this is happening to you in kibbeh, please reopen

**Comment by amitojsingh366** [comment]
oh lol i fixed this but forgot to close it 😳
