### ISSUE TITLE
Video (Might be a already mentioned suggestion sorry)

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1578]
Video calling should be for private calls maybe public im suggesting only private chats for privacy

**Comment by samarmohan** [comment]
DogeHouse is supposed to be a better version of ClubHouse. Having video doesn't make sense because the goal of this project was to be voice convos, not be a Google Meet or Zoom.

**Comment by ghost** [comment]
Oh ok

**Comment by DogeMan08** [comment]
Can you delete this then
