### ISSUE TITLE
If you go to change room name the poppup title is in english

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1579]
If you go to change room name then it will show the name in english instead of the selected language

I dont know if its just a bug with the language I chose or its a global bug

How to produce the bug:
1. Change language to anything
2. Click on settings and change room name
3. It has the title in english

Its supposed to be in the selected language

**Comment by goldyydev** [comment]
A room's name cannot be magically translated to languages, can you clarify what you mean if it's not the actual room name?

**Comment by samarmohan** [comment]
We can't just translate the room name, that is impossible. The room name will be and stay in whichever language it was created in. @goldyydev, please close.

**Comment by ghost** [comment]
No not the room name, when you click change the room name the poppup title is in english

**Comment by ghost** [comment]
Fixed the title

**Comment by goldyydev** [comment]
I really can't reproduce this.
![image](https://user-images.githubusercontent.com/55450464/112544914-440ef400-8dc0-11eb-8911-be06a05272da.png)

**Comment by ghost** [comment]
Nono lemme send my error i think i said it wrong

**Comment by ghost** [comment]
Set public room name


"Bug Test"

[Nuligi] -- [Bone]

**Comment by ghost** [comment]
thats what i see the title of the popup in english

**Comment by samarmohan** [comment]
Ohh, now you make sense. Let me see if I can reproduce.

**Comment by drvladb** [comment]
@DogeMan08 I am unable to reproduce, please post an example screenshot

![image](https://user-images.githubusercontent.com/33793511/112565678-1a939f80-8da3-11eb-8b2f-7798b017dc8a.png)

**Comment by ghost** [comment]
![Screen Shot 2021-03-25 at 6 51 12 PM](https://user-images.githubusercontent.com/81381841/112637748-dc36c880-8e14-11eb-8688-e15275c80e2e.png)

**Comment by samarmohan** [comment]
That doesn't even appear on mine.

**Comment by cursorial** [comment]
https://github.com/benawad/dogehouse/blob/staging/kofta/src/webrtc/utils/renameRoomAndMakePublic.ts#L6
https://github.com/benawad/dogehouse/blob/staging/kofta/src/webrtc/utils/renameRoomAndMakePrivate.ts#L6

To reproduce:
1. Start a new room
2. Click settings
![Screenshot from 2021-03-26 14-17-32](https://user-images.githubusercontent.com/2265262/112645191-24b6ac00-8e3e-11eb-868c-94ab7f10cd94.png)
3. Click make room public/private
![Screenshot from 2021-03-26 14-17-39](https://user-images.githubusercontent.com/2265262/112645229-2b452380-8e3e-11eb-9007-8d6df6d42fc7.png)
4. See popup
![Screenshot from 2021-03-26 14-17-43](https://user-images.githubusercontent.com/2265262/112645243-313b0480-8e3e-11eb-91f6-65e2ed9b4f7f.png)


To fix:

1. Add new translation keys
2. Pass `t` to helper functions `renameRoomAndMakePublic` and `renameRoomAndMakePrivate`
3. Replace hardcoded English strings with `t('key')`

**Comment by ghost** [comment]
Thanks @cursorial for fixing this I will close this now
