### ISSUE TITLE
Gap doesn't work with flex on Safari

### ISSUE THREAD

**Issue by HonbraDev** [benawad/dogehouse#1588]
Hello.
After a heated discussion with @overlisted, I have realized that `gap` doesn't work with `flex` on Safari.

Safari: 
![Screenshot of Safari](https://user-images.githubusercontent.com/54026315/112607753-cbd51c80-8e19-11eb-90d7-562b82203838.png)

Chromium: 
![Screenshot of Chromium](https://user-images.githubusercontent.com/54026315/112607724-c7a8ff00-8e19-11eb-8dd0-558c893d11e5.png)

Maybe we should put a warning in the contributing docs telling people to use `grid` instead of `flex` for better compatibility.

**Comment by overlisted** [comment]
im pretty sure that the flexbugs postcss plugin can fix that

**Comment by overlisted** [comment]
i will try solving this with flexbugs-fixes after i finish the new login page

**Comment by ajmnz** [comment]
@overlisted Is this fixed now?

**Comment by overlisted** [comment]
It is fixed, but by replacing `gap` completely
