### ISSUE TITLE
Use a font family that supports polish letters

### ISSUE THREAD

**Issue by jakweg** [benawad/dogehouse#1596]
**Describe the bug**
The bug renders some polish letters bolder then the others.

**To Reproduce**
1. Set language to Polish (Polski)
2. Go to https://dogehouse.tv/me
4. See these ugly buttons

**Expected behavior**
I expected polish letters to be rendered with correct size and thickness glyphs.
Like this 
![image](https://user-images.githubusercontent.com/20194971/112654628-ddd1b200-8e4f-11eb-94c8-cb1578a340f8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/20194971/112654286-859ab000-8e4f-11eb-824c-f6c62ec56811.png)

**What device are you on?**
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36 OPR/75.0.3969.93

**Additional context**
It may affect other languages as well

**Comment by goldyydev** [comment]
@JakubekWeg can you please suggest a font family that supports it?

**Comment by jakweg** [comment]
I'm not a designer, so I don't know which font looks the best, however most popular fonts support most languages therefore I would choose a font that is popular and is used by other websites.
For example GitHub uses this CSS to style the website:
```
font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
```
And it works, so why don't we just copy this line?

**Comment by BronzW** [comment]
Using another font family would need to change the whole design system just so that a miniority of people is not ideal. For me it the polish letters look pretty similar to the other ones, it's not like they are completely disturbed.
