### ISSUE TITLE
Leave room button doesn't work on new design

### ISSUE THREAD

**Issue by Berags** [benawad/dogehouse#1597]
**Describe the bug**
When you enter a room the leave button doesn't work on new next.js design

**To Reproduce**
1. Go to 'next.dogehouse.tv'
2. Login with GitHub
2. Click on a random room
3. Click "Leave room" button on bottom right corner

**Expected behavior**
Leave the room you are currently in

**What device are you on?**
HP Laptop, Google Chrome version 89.0.4389.90 (Latest stable release)

**Additional context**
Italian language active.

**Comment by MMK21Hub** [comment]
Can confirm

**Comment by benawad** [comment]
should be fixed now
