### ISSUE TITLE
Alert component background color is not suitable

### ISSUE THREAD

**Issue by tminhduc2811** [benawad/dogehouse#1599]
**Is your feature request related to a problem? Please describe.**
When I click the button to share the room, the alert appears with the default color of react-toastify, which is quite weird and not suitable for the dark theme.
Also, it doesn't support translation.
![image](https://user-images.githubusercontent.com/40265306/112659957-80595780-8e87-11eb-855b-6f6a70e93b35.png)

**Describe the solution you'd like**
Probably should use a dark color and add translation to it.

**Comment by nadirabbas** [comment]
all design-related things will get fixed in the new design. which has different toasts.
