### ISSUE TITLE
I can still hear people talking when I exit the room / go to main list of rooms

### ISSUE THREAD

**Issue by zrakhimov** [benawad/dogehouse#16]
It might be a good idea for UX to actually disable voice/speakers when you get out of the room

**Comment by starbuck93** [comment]
I like this feature, personally. Because you can sill listen or participate while browsing menus and the list of other rooms.

![image](https://user-images.githubusercontent.com/5626027/107789051-1d6c9080-6d1f-11eb-8997-8988abd949bd.png)

Just use this button/icon to disconnect.

**Comment by ExtraE113** [comment]
I also like this feature but it would be nice if the home page told you which room you’re in

**Comment by samarmohan** [comment]
Yeah, it's a feature not a bug :)

**Comment by samarmohan** [comment]
@ExtraE113, it does tell you. The room you are in is light gray.
