### ISSUE TITLE
Kibbeh: Room chat auto scroll is not working

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1604]
I think @benawad commented out the auto-scroll logic, probably because it had some efficiency problem. 

https://user-images.githubusercontent.com/38838675/112665191-9c0b3080-8e7c-11eb-99cb-b7916ab35e2b.mp4

**Comment by f1shy-dev** [comment]
This seems even more broken now, I don't even have a chat scroll.

https://user-images.githubusercontent.com/56125930/112697879-69fbcd80-8e80-11eb-808c-9f3d181d9de3.mov

**Comment by ajmnz** [comment]
I believe this has been fixed, can you confirm? @nadirabbas @vishy-dev

**Comment by nadirabbas** [comment]
yeah
