### ISSUE TITLE
UX issues around chat

### ISSUE THREAD

**Issue by Jirushi-I** [benawad/dogehouse#161]
Right now, chat and voice feels really disconnected.

Problem 1: People didn't realize there was a conversation going on in chat, were confused by the silence and left.
Possible Solution 1: A notification sound you can mute. Also maybe a ping beside the icon of the unread message's sender.

Problem 2: I got distracted and missed a guy saying that he had to go in chat
Possible Solution 2: A notification sound you can mute.

**Comment by TripingPC** [comment]
What if sending a message made a chat bubble icon show in the top-right of your avatar in the grid for a second.

**Comment by nadirabbas** [comment]
done
