### ISSUE TITLE
New website looks weird on Opera

### ISSUE THREAD

**Issue by iWanheda** [benawad/dogehouse#1610]
![](https://b.catgirlsare.sexy/Vqzn5lFw.png)

**Comment by goldyydev** [comment]
Opera is chromium based, that shouldn't happen. try disabling all extensions.

**Comment by iWanheda** [comment]
No extensions with it

**Comment by goldyydev** [comment]
are you trying to access it via [next.dogehouse.tv](https://next.dogehouse.tv) or a local copy?

**Comment by kasparnoor** [comment]
Looks good for me
![unknown (12)](https://user-images.githubusercontent.com/68809743/112691553-2ad07b00-8e86-11eb-96e7-52abac829f1d.png)

**Comment by ermalsh** [comment]
Confirmed this is working well on Opera and other Chromium browsers.
