### ISSUE TITLE
Routing not working correctly to the new dashboard

### ISSUE THREAD

**Issue by kasparnoor** [benawad/dogehouse#1615]
When going to https://next.dogehouse.tv/dashboard > logging in with the button on the top left > it redirects me to the old dashboard, not the new one

**Steps to reproduce:**
1) Go to specifically https://next.dogehouse.tv/dashboard 
2) Log in with the github button

**Expected results:**
Log in to the new dashboard

**Actual results:**
Logs in to the old dashboard

**Comment by amitojsingh366** [comment]
As the new version isn't completed yet i feel this issue is invalid as this may still have to be worked on or may have been fixed already just not deployed...

**Comment by cursorial** [comment]
Is there somewhere we should track issues specific to the new version?

**Comment by kasparnoor** [comment]
> As the new version isn't completed yet i feel this issue is invalid as this may still have to be worked on or may have been fixed already just not deployed...

Are we not supposed to open issues about the new version?

**Comment by amitojsingh366** [comment]
@kasparnoor i'm not really sure. what i wrote above were just my opinions as there's been a flood of issues relating to the new version. i've asked ben about this and what should be done, just waiting for his response. till then ig there isn't a problem

**Comment by f1shy-dev** [comment]
This doesnt seem to be happening anymore, it redirected to new dashboard fine.

**Comment by amitojsingh366** [comment]
@cursorial @kasparnoor you can now create an issue related to the new version under the tag "new-version-bug" there should be a issue template for this aswell.

**Comment by benawad** [comment]
note to self: this caused by not normalizing path and looking at origin `?next` part messes things up

**Comment by goldyydev** [comment]
This has been fixed.
