### ISSUE TITLE
why docker compose up failed

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#162]
![Screenshot 2021-02-14 102546](https://user-images.githubusercontent.com/72514547/107869426-b205f880-6eaf-11eb-8d25-17c887f6ef2c.jpg)
why this failed and what is purpose of python

**Comment by markxoe** [comment]
You have to go the Server location as described here https://github.com/benawad/dogehouse#structure
If you want to start the Voice Server go into the folder shawarma

**Comment by tanay-pingalkar** [comment]
https://github.com/benawad/dogehouse/pull/118
This why this is telling to make run docker compose up in dogehouse dir and said to make docker yml file. 
I think I should  manually setup the project.

**Comment by markxoe** [comment]
Which docker-compose file are you using?
The error clearly says `Cannot locate specified Dockerfile: Dockerfile`, so you are missing a Dockerfile

**Comment by nhalstead** [comment]
You can't use docker-compose up. This project does not have a docker-compose file.
You need to run docker build then docker run IE:

---

Build the Image (from the root of the project)
```
 docker build -t dogehouse-shawarma:local -f ./shawarma/Dockerfile
```

Start the container
###### `dogehouse-shawarma:local` is the tagged image name.
```
 docker run -dp 3000:3000 dogehouse-shawarma:local
```

**Comment by tanay-pingalkar** [comment]
> You can't use docker-compose up. This project does not have a docker-compose file.
> You need to run docker build then docker run IE:
> 
> Build the Image (from the root of the project)
> 
> ```
>  docker build -t dogehouse-shawarma:local -f ./shawarma/Dockerfile
> ```
> 
> Start the container
> 
> ###### `dogehouse-shawarma:local` is the tagged image name.
> ```
>  docker run -dp 3000:3000 dogehouse-shawarma:local
> ```
Yes the project does not have docker compose, but someone in issues has told that, now I am setting it manually

**Comment by tanay-pingalkar** [comment]
> You can't use docker-compose up. This project does not have a docker-compose file.
> You need to run docker build then docker run IE:
> 
> Build the Image (from the root of the project)
> 
> ```
>  docker build -t dogehouse-shawarma:local -f ./shawarma/Dockerfile
> ```
> 
> Start the container
> 
> ###### `dogehouse-shawarma:local` is the tagged image name.
> ```
>  docker run -dp 3000:3000 dogehouse-shawarma:local
> ```

I am setting the environment manually
