### ISSUE TITLE
Empty space bio profile

### ISSUE THREAD

**Issue by menstruated** [benawad/dogehouse#1620]
**Describe the bug**
Can fill bio with empty space

**To Reproduce**
1. Go to 'profile page'
2. Click on 'edit profile'
3. Fill bio with empty space
4. Save and voice settings and sound settings go right to the bottom

**Expected behavior**
Not allow just empty space

**Screenshots**
https://catgirls-are.sexy/​‌​‌​​‌‌​‌​‌​‌​​​‌‌‌​​​‌​‌‌‌​​‌​​‌‌‌​‌‌‌​‌​‌​‌‌​​‌​​‌​​​​‌‌​‌​‌‌

**What device are you on?**
windows

**Comment by imadill** [comment]
Sus link 🤨

**Comment by menstruated** [comment]
> Sus link 🤨

Pays.host..?

**Comment by 1kvsn** [comment]
I've fixed it and raised a PR here: https://github.com/benawad/dogehouse/pull/1624

**Comment by fishsticks89** [comment]
> I've fixed it and raised a PR here: https://github.com/benawad/dogehouse/pull/1624

Should we resolve this then?
