### ISSUE TITLE
New Version Bug: Going back to Login when joining room while in room

### ISSUE THREAD

**Issue by deijjji303** [benawad/dogehouse#1628]
When joining a room while in another room (via mini player in the top right) the user is sent back to "Login with GitHub"

1. Join a room
2. Click on the DogeHouse logo (to go back to the dashboard)
3. Join another room

**Expected behavior**
The user should leave the current room and join the one they clicked on.

**What device are you on?**
Windows 10, Google Chrome Version 89.0.4389.90

**Comment by samarmohan** [comment]
I’m working on fixing this!

**Comment by samarmohan** [comment]
It's gone, I didn't do anything.

**Comment by deijjji303** [comment]
Can confirm I don't have the bug either now. That's maybe because the login page got redone?
