### ISSUE TITLE
MacOS Electron app closes application instead of window

### ISSUE THREAD

**Issue by ben9583** [benawad/dogehouse#1636]
On MacOS, it's expected that when the user closes a window by either clicking the red "x" on the top left of a window or by using Command + W, the window will close, but the application will still be running, as represented by the icon remaining in the dock. However, when closing the app by clicking the "x", the application itself also closes. Furthermore, when closing with Command + W, the application appears to close, but a few seconds later a crash report appears indicating an unexpected termination of the process. This crash report does not appear when using Command + Q.

Keeping the application running after a window is closed is a good idea since it allows background processes, such as a voice call or notifications, to keep running. It also allows the user to jump back in the app quicker and where they left off.

Regarding the crash, I am on a MacBook Pro 16,1 running MacOS Catalina 10.15.7, if this information is necessary.

**Comment by amitojsingh366** [comment]
The first part of you issue is intentional. We will soon add support for the app to run in background *(probably after the next version is released)* but as of right now there is no support.
However i would like to know mode about the crash you mentioned. Can you please attach the crash report below and also tell which build are you using?

**Comment by ben9583** [comment]
I am using the latest release build at the time (1.0.29). I'll paste the first bit of the crash report and upload the entire report as a text file [here](https://github.com/benawad/dogehouse/files/6232730/report.txt):

```
Process:               DogeHouse [17212]
Path:                  /Applications/DogeHouse.app/Contents/MacOS/DogeHouse
Identifier:            com.electron.dogehouse
Version:               1.0.29 (1.0.29)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DogeHouse [17212]
User ID:               501

Date/Time:             2021-03-30 15:54:56.732 -0700
OS Version:            Mac OS X 10.15.7 (19H524)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        20E3346B-08C2-359B-21B7-7DB53E2C1559


Time Awake Since Boot: 110000 seconds

System Integrity Protection: disabled

Crashed Thread:        32  async-std/runtime

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
```

**Comment by amitojsingh366** [comment]
@StratusFearMe21 if I'm not wrong this error looks like the one I've been experiencing due to globkey not yet having graceful exiting?

**Comment by amitojsingh366** [comment]
@ben9583 can you try the latest build [1.0.30](https://github.com/benawad/dogehouse/releases/tag/v1.0.30) and check if this still occurs?

**Comment by ben9583** [comment]
Looks like I'm not getting the crash anymore; thanks!
