### ISSUE TITLE
Black screen when entering room, Firefox

### ISSUE THREAD

**Issue by KeloDraken** [benawad/dogehouse#1640]
**Describe the bug**
When trying to access a doge room the page turns black, only the audio comes through. This happens both in https://dogehouse.tv and https://next.dogehouse.tv

**To Reproduce**
1. Go to 'any room'
2. Audio plays but nothing displayed

**Expected behavior**
There should be a view showing people in the room and a chat box on the side, plus other buttons like raising your hand

**Screenshots**
![Screenshot from 2021-03-27 22-48-36](https://user-images.githubusercontent.com/65687571/112734481-b01f6280-8f4e-11eb-8dee-a32e45224b33.png)
![Screenshot from 2021-03-27 22-50-02](https://user-images.githubusercontent.com/65687571/112734503-ca594080-8f4e-11eb-8f33-af7eeb687415.png)

**What device are you on?**
HP Probook 450 G7. Ubuntu 20.04

**Comment by overlisted** [comment]
I'm on Linux and using Firefox too. Can't reproduce

**Comment by goldyydev** [comment]
I feel like one of your extensions is causing this behaviour. try disabling them and reload the website.
![image](https://user-images.githubusercontent.com/55450464/112736655-68580580-8f65-11eb-87bc-c3d68e844122.png)

**Comment by KeloDraken** [comment]
> I feel like one of your extensions is causing this behaviour. try disabling them and reload the website.
> ![image](https://user-images.githubusercontent.com/55450464/112736655-68580580-8f65-11eb-87bc-c3d68e844122.png)


I disabled all of them, its still happening
![Screenshot from 2021-03-28 00-46-34](https://user-images.githubusercontent.com/65687571/112736946-56736400-8f5f-11eb-96dd-53b3eed15b58.png)
![Screenshot from 2021-03-28 00-46-58](https://user-images.githubusercontent.com/65687571/112736949-583d2780-8f5f-11eb-8878-0472fb62e1b6.png)

**Comment by benawad** [comment]
try opening console and see if there is an error

**Comment by amitojsingh366** [comment]
Can't reproduce. @JustM3Dev i remember you had a similar issue... any ideas?

**Comment by KeloDraken** [comment]
It's working properly now. I don't know why it did that

**Comment by justmedev** [comment]
> Can't reproduce. @JustM3Dev i remember you had a similar issue... any ideas?

Yes I had the same issue. I still don't know why it occurs.
