### ISSUE TITLE
Line alignment while in a room

### ISSUE THREAD

**Issue by RigidStudios** [benawad/dogehouse#1645]
**Problem:**
The separator on the room and on the chat don't align, they're identical sections so they should end identically:
![image](https://user-images.githubusercontent.com/34319439/112752460-3afe6c80-8fe4-11eb-98ef-e0aa79638fff.png)

**Solution:**
Select one size for both and align the lines.

**Comment by ajmnz** [comment]
This relates to kofta, which is now dead
