### ISSUE TITLE
DogeHouse Does Not Install On AUR (Arch User Repository) 

### ISSUE THREAD

**Issue by iDubno** [benawad/dogehouse#1653]
If you try to build DogeHouse in Arch Linux, it will fail to build. 

1. Go to The AUR
2. Build it 
4. You will see an error (see screenshot) 

Screenshots
![NHdMUS1](https://user-images.githubusercontent.com/81489750/112769414-bed24c00-9018-11eb-9b49-7ba4f6ca53a5.png)

**Comment by amitojsingh366** [comment]
DogeHouse is not yet officially supported on AUR. please try to install from the latest builds available [here](https://github.com/benawad/dogehouse/releases/latest)

**Comment by HonbraDev** [comment]
![image](https://user-images.githubusercontent.com/54026315/112821913-903f8a00-9087-11eb-9d12-6ffab33bedee.png)
