### ISSUE TITLE
Room title not displaying properly on iPad chrome

### ISSUE THREAD

**Issue by probicheaux** [benawad/dogehouse#1654]
**Describe the bug**
See title. 

**To Reproduce**
Open a room in old dogehouse on iPad chrome. Seems to only happen on rooms with many speakers. 

**Screenshots**
![4B344AD3-DD53-4579-AA79-D870B1150661](https://user-images.githubusercontent.com/25629529/112771381-5f584a00-8fe0-11eb-9d84-c0b371fcf49d.png)
![5A22745F-BDC7-4502-8F7C-8F749B056A8E](https://user-images.githubusercontent.com/25629529/112771458-e1e10980-8fe0-11eb-87bb-164cb4b98b24.png)

**Comment by GStudiosX2** [comment]
Lol but they working on new design what's the point of them doing this ;-;

**Comment by probicheaux** [comment]
> Lol but they working on new design what's the point of them doing this ;-;

If you mean "why should they fix this bug", I'm not saying they necessarily should, but whoever wrote that component should be made aware that it's not working as intended in this environment so they can avoid this problem in the future!

If you mean "why should anyone look at this issue", see the above.

**Comment by HonbraDev** [comment]
lmao that's Chrome

**Comment by GStudiosX2** [comment]
> > Lol but they working on new design what's the point of them doing this ;-;
> 
> If you mean "why should they fix this bug", I'm not saying they necessarily should, but whoever wrote that component should be made aware that it's not working as intended in this environment so they can avoid this problem in the future!
> 
> If you mean "why should anyone look at this issue", see the above.

im basically saying whats the point in fixing it in the old version if its a bug in the new one too then it can be fixed but theres no point in them doing the old one

**Comment by probicheaux** [comment]
> lmao that's Chrome

Oops

**Comment by fishsticks89** [comment]
> Lol but they working on new design what's the point of them doing this ;-;

Precisely

**Comment by ermalsh** [comment]
New design will take precedence over this issue - I believe DogeHouse is focusing development efforts on frontend items related to new design at the moment rather than focusing on small UI bugs like this. Closing this for now.
