### ISSUE TITLE
Cannot hear voice or sound, showing ICE failed message

### ISSUE THREAD

**Issue by zackworkstorage** [benawad/dogehouse#1661]
**Describe the bug**
Unable to hear the sound after join the room. And i found ICE failed issue when using firefox

**To Reproduce**
1. Install prod branch following "CONTRIBUTING.md"
2. Create new room
3. Join room with 2 different browser
4. See error : WebRTC: ICE failed, add a STUN server and see about:webrtc for more details

**Expected behavior**
Can hear sound

**Screenshots**
![dogehouse-1](https://user-images.githubusercontent.com/80741286/112804801-67c78800-90a7-11eb-9c71-7b8c3499d668.png)
![dogehouse-2](https://user-images.githubusercontent.com/80741286/112805071-b7a64f00-90a7-11eb-873e-1577f1d48335.png)

**What device are you on?**
OS: ubuntu 20
Server: AWS ec2
Browser: firefox & chrome

**Additional context**
I suspect proxy issue and still looking for a solution.

**Comment by fishsticks89** [comment]
We could have the site reload every time it encounters this error as a temporary fix *laughs in jank*

**Comment by ajmnz** [comment]
I believe this relates to local development, which is known to have problems with audio. Will close it now, request to reopen if needed.
