### ISSUE TITLE
Percentage does not show when updating

### ISSUE THREAD

**Issue by imansour12** [benawad/dogehouse#1686]
**Describe the bug**
When opening the DegeHouse exe app (when it needs an update) on windows it does not show a percentage of how far the download has progressed.

**To Reproduce**
1-Download an unupdated windows .exe file of dogehouse
2-Install it
-Run it and it should look for updates and update.

**Expected behavior**
Instead of the text showing percentage that updates as the download progresses, it shows : "[object Object]%"

**Screenshots**
![image](https://user-images.githubusercontent.com/29927611/113047601-cb35e080-91a1-11eb-842e-2ee58ff64c68.png)

**What device are you on?**
I don't see how this helps with this particular issue but I have a ryzen 5 with 16 gigs of ram as well as an Nvidia GTX 1060TI. I have windows ten family.

**Additional context**
No additional context.

**Comment by amitojsingh366** [comment]
I had fixed this in #1675. Please try to use the latest build [1.0.29](https://github.com/benawad/dogehouse/releases/tag/v1.0.29). Or if you want to see the percentage and progress bar in action use build [1.0.28](https://github.com/benawad/dogehouse/releases/tag/v1.0.28) and watch the update occur.
