### ISSUE TITLE
People Not Showing Up After Joining Room

### ISSUE THREAD

**Issue by CreativeQuilt** [benawad/dogehouse#1699]
**Describe the bug**
Too many issues

**To Reproduce**
1. Go to DogeHouse.tv
2. Click on one of the rooms
3. Do you see people there?
4. Inspect JS console does not give errors

**Expected behavior**
It is supposed to show the users

**Screenshots**
https://drive.google.com/file/d/1fQp9KDXYmWjvqibT_-1DJsprzDUUiQ4y/view
**What device are you on?**
Dell Laptop
**Additional context**
Effects a lot of people

**Comment by HarrisonMayotte** [comment]
I'm unable to reproduce on a lenovo laptop, windows server 2012, windows server 2016, and windows 10 desktop.

**Comment by troler36** [comment]
**I am not able to reproduce it**

Device Type / Model:
Desktop or laptop
Operating System:
Linux Ubuntu (64-bit)
True Operating System Core:
Linux x86_64
Browser:
Firefox version 87.0 (64-bit) (Engine: Gecko)
True Browser Core:
Firefox
Browser Build Number / Identifier:
2010-01-01 / 2018-10-01 00:00:00
User Agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
HTTP Version:
2.0
Cookies:
Enabled

**Comment by HarrisonMayotte** [comment]
It appears that this is probably resolved so I'll mark this as closed and it can be reopened if we continue having reports or find anyone else who's able to reproduce it.
