### ISSUE TITLE
Sound notifications

### ISSUE THREAD

**Issue by leonardopaffi** [benawad/dogehouse#170]
These are my ideas:
- When someone is joining the room
- When someone leaves the room
- User requesting to join the speaker group

It is really hard to tell if someone wants to speak or if has joined if you are currently watching another tab/software.

**Comment by TripingPC** [comment]
[Dogehouse_SFX.zip](https://github.com/benawad/dogehouse/files/5981824/Dogehouse_SFX.zip)
Made these sounds as part of a pack for another project, but ended up not using these.

**Comment by ajmnz** [comment]
Sound notifications have already been implemented
