### ISSUE TITLE
changing mics is scuffed

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#1704]

**Comment by f1shy-dev** [comment]
how is it *scuffed*? the gui for it or ? and is this in `kibbeh` or `kofta`

**Comment by fishsticks89** [comment]
> how is it _scuffed_? the gui for it or ? and is this in `kibbeh` or `kofta`

we should only be concerned with fixing kibbeh but the people in discord believe it is a client issue. I have not experienced this on windows chrome... I feel we have insufficient information to act on this and a greater explanation of the issue would be nice
