### ISSUE TITLE
Voice clips 

### ISSUE THREAD

**Issue by GijsRommers** [benawad/dogehouse#1707]
-This is a feature request, and i know there wont be new features till the new design launches -

I just found the fuel the dogehouse rocket needs to propel itself into orbit. Imagine dogehouse with a twitter like timeline where people can post short voice clips on for other people to hear. People can like them and maybe (if we can pull that off) reply with short audio clips back.

**Comment by GijsRommers** [comment]
He has talked about this in two of his dogelogs...

**Comment by isaxk** [comment]
Yes, he has. He talked about a tiktok like feed for audio
