### ISSUE TITLE
Add shortcut keys

### ISSUE THREAD

**Issue by hem1t** [benawad/dogehouse#171]
I think it would be better, if you had shortcut keys!
List of what I think is essential.
* mute/unmute
* chat
* require permission to speak
* Invite

**Comment by hem1t** [comment]
* mute/unmute
* chat
* require permission to speak
* Invite

**Comment by andrewroblesdev** [comment]
I'm down to work on this one

**Comment by andrewroblesdev** [comment]
The pull request associated with this issue has been merged so I think this issue can be closed. However, I don't think I have the permission to do that.
