### ISSUE TITLE
New Version Bug: Room scrolls to bottom when users join/leave

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#1710]
https://user-images.githubusercontent.com/57961822/113359980-29e98e80-9349-11eb-8025-4d8ceb78363d.mov

**Comment by amitojsingh366** [comment]
can reproduce, but for me it just happens randomly. even when there's no new message or anyone leaving/joining

**Comment by goldyydev** [comment]
Both of you are using an older version of DogeHouse, I can identify this because I fixed this exact bug and overhaled the scrollbars. it is live on https://next.dogehouse.tv

**Comment by goldyydev** [comment]
![image](https://user-images.githubusercontent.com/55450464/113365800-f82ff200-935f-11eb-80f0-6c854b72564e.png)

**Comment by goldyydev** [comment]
Apparently this happens only on Firefox

There are a **lot** of compatibility issues with firefox.

**Comment by amitojsingh366** [comment]
> Both of you are using an older version of DogeHouse, I can identify this because I fixed this exact bug and overhaled the scrollbars. it is live on https://next.dogehouse.tv

I was checking on this link itself...

**Comment by amitojsingh366** [comment]
> Apparently this happens only on Firefox
> 
> There are a **lot** of compatibility issues with firefox.

oh ok, yea even im using firefox

**Comment by goldyydev** [comment]
putting the same message in here in case somebody wants to take it.
![image](https://user-images.githubusercontent.com/55450464/113366948-61653480-9363-11eb-8acb-29fd168440a7.png)

**Comment by ajmnz** [comment]
Yeah forgot to mention that part. I’m on Firefox

**Comment by ajmnz** [comment]
Fixed, but now there's a massive margin on the bottom.
