### ISSUE TITLE
Tagalog translation not loading.

### ISSUE THREAD

**Issue by avidianity** [benawad/dogehouse#1713]
I checked in devtools and it seems that `/locales/ph/translation.json` isn't returning the proper json file.

![image](https://user-images.githubusercontent.com/56546989/113366959-57582b80-938d-11eb-96ab-75652b97ea84.png)

**Comment by rzsxdev** [comment]
The Tagalog translation file is not even present in kofta. The person who added the translations added them to kibbeh only as far as I know.

**Comment by TheOtterlord** [comment]
Kofta is now deprecated. If you find the problem appears in Kibbeh, please reopen
