### ISSUE TITLE
New Version Bug: Dogehouse closes the ws connection when i refresh the page

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1714]
If you refresh the page in Kibbeh, it says something along the lines of "You can only have one tab open at a time"

**Comment by goldyydev** [comment]
Ben has acknowledged this bug.
![image](https://user-images.githubusercontent.com/55450464/113424085-3a951580-93d8-11eb-94f7-76709bc2598e.png)

**Comment by goldyydev** [comment]
Ben has fixed this.
