### ISSUE TITLE
Electron App for DodgeHouse

### ISSUE THREAD

**Issue by Stancobridge** [benawad/dogehouse#172]
I will like to follow in the start team for the electron app or this project, @benawad I have sent you message on Twitter about this

**Comment by benawad** [comment]
I'm going to create a guide on how to setup everything locally soon and then you can use that to test the electron app with local api

**Comment by Stancobridge** [comment]
Alright great I will be waiting

**Comment by nadirabbas** [comment]
media-soup doesn't seem to be building on windows, I think it only supports max/Linux for now.

**Comment by benawad** [comment]
readme has instructions to setup things locally and electron shell has been started in baklava folder.

Main things needed:

- Hook into electron keybinds
- Notifications of some sort

**Comment by Stancobridge** [comment]
Notification you mean, is it the Operating System Notification or in App Notification

**Comment by benawad** [comment]
System

**Comment by Stancobridge** [comment]
Suggestion, is not much Better to Use React wrapper for Electron, there is already a React BoilerPlate for it that uses Typescript https://github.com/diego3g/electron-typescript-react

It this good enough, if true then I think the project should use it, thanks

**Comment by benawad** [comment]
Yeah if you want to use that, sure

**Comment by DGKSK8LIFE** [comment]
@Stancobridge what's your discord? Want to work on this together?

**Comment by Stancobridge** [comment]
> @Stancobridge what's your discord? Want to work on this together?

idevosm

**Comment by DGKSK8LIFE** [comment]
I need the ID to add you @Stancobridge

**Comment by TheOtterlord** [comment]
As we now have an Electron app, this issue could probably be closed. But I suppose releasing the binaries might be a good idea first?

**Comment by TheOtterlord** [comment]
Binaries are available in [releases](https://github.com/benawad/dogehouse/releases)
