### ISSUE TITLE
New Version Bug: user nodes have wrong z-index

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1731]
![image](https://user-images.githubusercontent.com/38838675/113479834-b1024800-94aa-11eb-947a-7a28a19c3e31.png)

**Comment by goldyydev** [comment]
is this another firefox only bug?
![image](https://user-images.githubusercontent.com/55450464/113481157-9dea7a80-94a0-11eb-8523-b9ba5ae1279e.png)
also, when zooming in, it seems perfectly fine
![image](https://user-images.githubusercontent.com/55450464/113481169-ac389680-94a0-11eb-9706-3aa7d119b10d.png)

**Comment by nadirabbas** [comment]
then we need more margin to get rid of this illusion.

**Comment by goldyydev** [comment]
there is margin, atleast in chromium
