### ISSUE TITLE
New Version Bug: The user description in user bio has no S P A C E S 

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1734]
![image](https://user-images.githubusercontent.com/81065901/113480207-d7c37d00-94b0-11eb-9e68-60b819a7fed4.png)

**Comment by ghost** [comment]
Its fine in the homepage tho 
![image](https://user-images.githubusercontent.com/81065901/113480315-6637fe80-94b1-11eb-83aa-f35264912cbf.png)

**Comment by ajmnz** [comment]
That profile page is temporary, new one coming this next week.

**Comment by ajmnz** [comment]
Reopening because this can be a potential issue even with the new design

**Comment by benawad** [comment]
what browser?

**Comment by ghost** [comment]
Chrome on M1 Mac Version 89.0.4389.114 (Official Build) (arm64)

**Comment by ajmnz** [comment]
Pretty sure this has been fixed already. @goldyydev @overlisted can you confirm & close?

**Comment by overlisted** [comment]
Just checked in production; spaces do display correctly.

**Comment by amitojsingh366** [comment]
i'm closing this since this seems like it has been fixed
