### ISSUE TITLE
New Version Bug: Things are a littlebit squeezed

### ISSUE THREAD

**Issue by Sound-Cat** [benawad/dogehouse#1736]
The frontend is a littlebit scuffed, I am using Opera GX on a Laptop and on the screenshots you see the problem

Here you can see there is no padding and margin at all:

![Bild_2021-04-03_155123](https://user-images.githubusercontent.com/76255766/113480423-7097cf80-9494-11eb-9443-cdf581ca6439.png)

The icon isn't on the right part:

![Bild_2021-04-03_155321](https://user-images.githubusercontent.com/76255766/113480486-b6ed2e80-9494-11eb-8144-b3906bad5315.png)

And here you see it isn't at the same width:

![image](https://user-images.githubusercontent.com/76255766/113480521-e13eec00-9494-11eb-8493-4ec7e54010ac.png)

**Comment by ghost** [comment]
Its good on chrome tho 

![image](https://user-images.githubusercontent.com/81065901/113480645-093d4800-94b3-11eb-9fe3-a5b627be3ee4.png)

**Comment by amitojsingh366** [comment]
#1766
