### ISSUE TITLE
New Version Bug: Right clicking on room and pressing escape creates several bugs

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1739]
**Describe the bug**
If you right click on a room there is a border added to it and a menu comes up, but if you press escape the border stays there and if you scroll up it goes behind the header.

**To Reproduce**
1. Go to 'next.dogehouse.tv'
2. Right click on random room and press escape
3. See error where the border stays there
4. See error where the border is visible through the header and other parts of the UI

**Expected behavior**
The expected behavior is that when you press escape the border should go away preventing these bugs. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50546858/113480695-f9633b00-9495-11eb-831b-ac03a0960119.png)
![image](https://user-images.githubusercontent.com/50546858/113480714-10099200-9496-11eb-8bc1-6f8f765f7347.png)
![image](https://user-images.githubusercontent.com/50546858/113480725-21529e80-9496-11eb-87b9-29ce8a8b9f13.png)

**What device are you on?**
Google Chrome, Lenovo Laptop

**Comment by ghost** [comment]
This is a problem not with dogehouse, but with how BROWSERS works. Try this on a github issue, it'll be the same
