### ISSUE TITLE
Unicode combining characters are enabled in the chat and room titles

### ISSUE THREAD

**Issue by leonardopaffi** [benawad/dogehouse#174]
![Immagine](https://user-images.githubusercontent.com/8465162/107874839-c0a6dc80-6ebc-11eb-8455-a8277625a0a0.jpg)

**Comment by jamesql** [comment]
I'll give this a look tomorrow.

**Comment by BronzW** [comment]
Hasn't this been fixed? I think @goldyydev created a PR
