### ISSUE TITLE
New Version Bug: No margin at the bottom of room list

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1740]
**Describe the bug**
There is no margin at the bottom of the room list creating an awkard behavior.

**To Reproduce**
1. Go to 'next.dogehouse.tv'
3. Scroll down to the bottom

**Expected behavior**
There should be some sort of margin or padding at the bottom of the list to create a less awkard behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/50546858/113480855-c79ea400-9496-11eb-94a4-ad94ebc17fda.png)

**What device are you on?**
Google Chrome, Lenovo Laptop

**Additional context**
It should probably cut off like with the following list to create a more consistent UI

**Comment by ghost** [comment]
This is the temporary version - Work is still being done :)
