### ISSUE TITLE
New Version Bug: You are able to follow yourself without any effect

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1741]
If you look at somebodies following or followers list you can follow yourself (I'm BronzW) but it has no effect. The follow button should probably not exist if it's you.
![image](https://user-images.githubusercontent.com/50546858/113480984-66c39b80-9497-11eb-996f-a3dbaeff30c2.png)

**Comment by MMK21Hub** [comment]
Can confirm
