### ISSUE TITLE
New Version Bug: the bio scrolls

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1744]
@ajmnz 
![image](https://user-images.githubusercontent.com/38838675/113486602-1f580200-94cd-11eb-9f01-525ed4c06431.png)

**Comment by MMK21Hub** [comment]
Your bug report seems to be very vague, and hard to understand. Please clarify.

**Comment by nadirabbas** [comment]
@ajmnz will understand, I was talking about the scrolling.

**Comment by ajmnz** [comment]
I know nothing about that, definitely shouldn't scroll.
