### ISSUE TITLE
New Version Bug: Search is not functional

### ISSUE THREAD

**Issue by MMK21Hub** [benawad/dogehouse#1747]
**The Bug**
On the dashboard, a search bar is present. However, the user cannot actually use it.

**Steps to Reproduce**
1. https://next.dogehouse.tv/dash
2. Type some things into the search bar
3. Press Enter
    → Nothing happens

**Expected Behaviour**
A 'search' of some description would initialise

**Screenshots**
![image](https://user-images.githubusercontent.com/50421330/113499851-3882a200-9511-11eb-8a2e-7d8ff56ff676.png)

**Environment**
- Windows 10 OS Version 2004
- Chrome 89

**Comment by ajmnz** [comment]
Expected behavior, search hasn't been implemented yet.
