### ISSUE TITLE
The images of the room speakers don't stay in the app.

### ISSUE THREAD

**Issue by imansour12** [benawad/dogehouse#1757]
**Describe the bug**
Images of speakers goes out of the app into the screen. 

**To Reproduce**
Go to the latest build and leave dogehouse in the background and start browsing as you would normally.

**Expected behavior**
The profile pics of the speakers in that specific room should pop in at random places in the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/29927611/113505614-e43ee880-9537-11eb-8572-96b3c2151ad9.png)

**What device are you on?**
Average gaming PC.

**Additional context**
I'm using the exe version of the dogehouse.

**Comment by amitojsingh366** [comment]
you accidentally opened the overlay *(`ctrl+tab`)* without first specifying which window to overlay on.
