### ISSUE TITLE
New Version Bug: no tab title for rooms

### ISSUE THREAD

**Issue by btarg** [benawad/dogehouse#1759]
**Describe the bug**
The tab title is the URL, instead if the room name. I am using the latest Chrome on Windows 10.
![tab title](https://i.imgur.com/jYofxhW.png)

As a sidenote, another bug I encountered was the language menu not working properly (clicking does nothing)

**Comment by goldyydev** [comment]
Currently we're waiting on @benawad to make a REST endpoint to get the room info.

**Comment by BronzW** [comment]
#1778

**Comment by ajmnz** [comment]
Implemented by #1778
