### ISSUE TITLE
5-30s period of no audio right after joining room

### ISSUE THREAD

**Issue by alexywang** [benawad/dogehouse#1764]
**Describe the bug**
5-30 second period of no audio after joining a room. The delay seems pretty random, sometimes I am able to hear audio immediately sometimes not.
**To Reproduce**
1. Click on a room to enter
2. Wait for audio to finally start playing

**Expected behavior**
Audio begins immediately after joining the room

**What device are you on?**
Macbook Pro

**Comment by amitojsingh366** [comment]
i am able to reproduce this. doesn't happen all the time and i think switching clients multiple times causes this

**Comment by benawad** [comment]
I wonder if it is just lag when trying to connect to +20 speakers

**Comment by benawad** [comment]
I have a thing thats synchronous right now, that I should probably switch to async that might solve this

**Comment by nadirabbas** [comment]
@benawad I can confirm this, so what happens is, when you join a room, if somebody is already talking and you join, you won't hear their sentence. once they stop and start talking again, you hear it. That is weird. not sure if I got it right tho
