### ISSUE TITLE
Open Link in New Tab | next.dogehouse.tv

### ISSUE THREAD

**Issue by leviFrosty** [benawad/dogehouse#1765]
**Is your feature request related to a problem? Please describe.**
When in a dogehouse you cannot open a new tab and keep the current page in the same state.

**Describe the solution you'd like**
Opening a new tab doesn't change the previous tab. It should stay the same

**Comment by amitojsingh366** [comment]
this issue seems pointless. dogehouse isn't meant to be opened in multiple tabs, instead just click on whatever dogehouse link you wanna open in a new tab and it should open it in the same tab without making you leave your call...
