### ISSUE TITLE
New Version Bug: Responsive layout not working as expected

### ISSUE THREAD

**Issue by mattmoody05** [benawad/dogehouse#1766]
**Describe the bug**
When viewing the next.dogehouse.tv homepage, ~~both left and right sides are being cut off the page~~ many responsive things such as grids, icons, etc don't function as expected (seems to be that the site is not reacting to change in resolution)

**To Reproduce**
~~1. View on a web browser window that is below 1340px wide~~
~~2. Sign into next.dogehouse.tv, and get to the homepage~~
~~3. See that the right and left sides are being cut off (parts are not visible in the window)~~
This issue seems to be fixed for browsers below 1340px width wise but the issue with Opera and Electron still occur

**Expected behavior**
The affected parts of the website to be responsive and stay in view on the web browser window

**Screenshots**
![Screen Shot 2021-04-04 at 16 16 53](https://user-images.githubusercontent.com/35400192/113541566-2bd27c80-95eb-11eb-83f2-4e43d189656c.png)

**What device are you on?**
2011 Macbook Pro 13", 1280x800 display, macOS 10.13, Firefox & Chome

**Comment by Hendrik7889** [comment]
CSS dosent fit and chat bar is hidden

[
![bug](https://user-images.githubusercontent.com/44064629/113567260-98ab3e00-960e-11eb-8f76-d4a48a29233c.png)
](url)

**Comment by ajmnz** [comment]
Only desktop version is available right now and the grid is hardcoded on purpose (it won't in the future).

**Comment by BooleanCube** [comment]
Website layout is also covered by the vertical tabs feature on Microsoft Edge which is also super annoying, so thats a thing to keep in mind.

**Comment by ajmnz** [comment]
Does that happen on every website or only on edge? Like do websites keep in mind those tabs within their layout?

**Comment by BooleanCube** [comment]
Yea, all the other websites that I use on microsoft edge adjust to the vertical tabbing and change the current layout to fit.

**Comment by BooleanCube** [comment]
But, when I try it in DogeHouse it just covers over even more when I use vertical tabs so thats another bug that I found with the newer version.

**Comment by ajmnz** [comment]
But basically vertical tabs just make the viewport width smaller, so at the end it’s just a matter of responsiveness

**Comment by mattmoody05** [comment]
> CSS dosent fit and chat bar is hidden
> 
> [ ![bug](https://user-images.githubusercontent.com/44064629/113567260-98ab3e00-960e-11eb-8f76-d4a48a29233c.png) ](url)

Hi, this thread is for the next.dogehouse.tv (new version) but it can be seen that this is an issue with both the new and old version. (If you feel the need you could create a seperate issue for the old version). 
Thanks

**Comment by mattmoody05** [comment]
As far as I can tell, the website (both new and old versions) are not 100% responsive yet, but should be at some point in the future (I assume that most poeple are running 1080p or above monitors at this point so it isn't a major issue and there are bigger problems to solve). 
Just a suggestion though, even just taking into consideration desktop users, often people will split their monitors in half, so supporting resolutions that would allow for this would be very useful.

**Comment by mattmoody05** [comment]
As for the edge issue, it seems the same as the issue I have mentioned, in the fact that when viewing the website with a resolution that is below the required width, content starts to be cut off (this being due to the vertical tabs)

**Comment by amitojsingh366** [comment]
here's what this issue is causing on electron/opera GX:
![weird](https://user-images.githubusercontent.com/35400192/113541566-2bd27c80-95eb-11eb-83f2-4e43d189656c.png)

**Comment by mattmoody05** [comment]
As of 06/04/21 this seems to be fixed, I will close the issue as it is no longer relevant.

**Extra info**
This applies on the Firefox browser on a 13" 2011 Macbook Pro, running macOS 10.13 (1280x800 display) 

**Working behaviour shown below**
![Screen Shot 2021-04-06 at 17 08 35](https://user-images.githubusercontent.com/34244370/113742668-c1106680-96fa-11eb-8a48-852233b3383e.png)

**Comment by amitojsingh366** [comment]
its better off not closing this issue as we've closed all similar issues and linked them here. we can just change the description a bit.

**Comment by mattmoody05** [comment]
Sure, sorry for any issues caused by closing it

**Comment by benawad** [comment]
feel free to reopen if something else comes up but I think it should be fixed now

**Comment by BronzW** [comment]
This has not been fixed

**Comment by BronzW** [comment]
Still happens in electron and other web browsers
