### ISSUE TITLE
New Version Bug: Microphone allow while left -> fetch nil room?

### ISSUE THREAD

**Issue by Arthurdw** [benawad/dogehouse#1768]
**Describe the bug**
When you are in a room as a speaker, and you have not allowed the browser to access your microphone. Then this little notification with JSON-like data will show up when you leave and click on the allow button for the microphone.

**To Reproduce**
1. Join a room
2. request for speaker & get granted
3. do not click on the microphone allow/block popup from the browser
4. leave the room
5. click on the allow microphone popup that is still there
6. a notification popup with JSON\-like data appears

**Expected behavior**
That no notification popup appears, or that a proper message appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/38541241/113514027-a60fec00-956c-11eb-8735-f0edbfecb477.png)

**What device are you on?**
Desktop, but I think this should be cross-platform. (Brave browser btw)

**Comment by SalihSaygi** [comment]
Also, after you get this error and then you join a room, you can't hear anything unless you refresh.

**Comment by Arthurdw** [comment]
~ Issue has been resolved for me.
