### ISSUE TITLE
Room no longer exist alert shows JSON response

### ISSUE THREAD

**Issue by akawajid** [benawad/dogehouse#1771]
**Describe the bug**
When a room **no longer exists**, it still appears in feed and when you try to open, it will throw an alert along with real **JSON response**.

**To Reproduce**
1. Go to 'Rooms Feed'
2. Click on any expired room (no longer exists)
3. See error

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/45237545/113514608-b9c54d80-9580-11eb-8a30-311d0ff4c23c.png)

**What device are you on?**
Desktop version : next.dogehouse.tv

**Comment by Arthurdw** [comment]
This seems to cause a similar issue as #1768.

**Comment by nadirabbas** [comment]
this works now
