### ISSUE TITLE
Everything is crammed together

### ISSUE THREAD

**Issue by devstanley** [benawad/dogehouse#1777]
Looking at the website everything looks crammed together and not thought out at all. Such as the Github and Discord logo (picture below) being right next too each other giving no room to each other. 

Don't know if anyone agrees but this is my personal opinion.

**Image**
![image](https://user-images.githubusercontent.com/56117736/113515693-f5a2e780-956d-11eb-8207-eaa22f37d0c9.png)

**Comment by noftaly** [comment]
Another example of this is on the login page (Safari 14): the buttons in the middle as well as the links on the bottom right
![image](https://user-images.githubusercontent.com/34779161/113515877-669acd00-9577-11eb-9f4e-16030c5c2d24.png)

**Comment by purpshell** [comment]
Firefox is the issue on my system
Running Firefox 78.8.0esr (64-bit) on Linux (Linux Mint Debian Edition)
![image](https://user-images.githubusercontent.com/52720753/113516418-dc586600-9582-11eb-9962-42090a0e7700.png)
![image](https://user-images.githubusercontent.com/52720753/113516426-ee3a0900-9582-11eb-9a2f-4b38a428e768.png)
![image](https://user-images.githubusercontent.com/52720753/113516434-f5611700-9582-11eb-94c3-6e2eaa9a07f1.png)

**Comment by purpshell** [comment]
chromium / chrome works

**Comment by devstanley** [comment]
I was using Opera when taking this screenshot. I have also tried Internet Explorer (Doesn't even load), Brave (Works), Firefox (Works) and Windows Explorer (Works).

**Comment by DzhideX** [comment]
I have the same problem as https://github.com/benawad/dogehouse/issues/1777#issuecomment-813067996 on Chrome. Operating System: Linux Ubuntu 20.04

**Comment by srivmutk** [comment]
Same issue on Firefox Mobile version 33.0

![image](https://user-images.githubusercontent.com/52793419/113521248-3e56a280-9566-11eb-8bb4-474e0fe12fa3.png)

**Comment by ajmnz** [comment]
#1766
