### ISSUE TITLE
New bug on mobile 📱 version 

### ISSUE THREAD

**Issue by glappy-py** [benawad/dogehouse#178]
When I request to talk , and the host accepts my request , suddenly the audio is gone and I can't hear what they are speaking

**Comment by benawad** [comment]
Are you able to recreate or is this a first time thing?

**Comment by glappy-py** [comment]
Yes I can recreate it

**Comment by benawad** [comment]
does it happen every time or just sometimes?

**Comment by benawad** [comment]
also are you android or ios and what browser?

**Comment by glappy-py** [comment]
I'm on Android and I use chrome. This happens everytime

**Comment by ajmnz** [comment]
@glappy-py Are you still able to reproduce the issue?

**Comment by glappy-py** [comment]
No , I think it's fixed
