### ISSUE TITLE
New Version Bug: Discord & GitHub links on login page should open in a new tab

### ISSUE THREAD

**Issue by patriksh** [benawad/dogehouse#1780]
**Describe the bug**
Discord & GitHub links on the login page should open in a new tab

**To Reproduce**
Logout.
Click on Discord & Github links in the footer.

**Expected behavior**
Websites open in a new tab.

**Comment by rigba** [comment]
It redirects you after this is a non issue?

**Comment by patriksh** [comment]
I see it's been fixed, closing.
