### ISSUE TITLE
New Version Bug: No space in the bottom of the page

### ISSUE THREAD

**Issue by Ademking** [benawad/dogehouse#1781]
**Describe the bug**
There is no space in the bottom of the page. maybe you add a small footer or something.. I don't know

**Screenshots**
![image](https://user-images.githubusercontent.com/12462188/113517074-de67f800-9575-11eb-82a9-043ca8b40bef.png)

**Comment by hisamafahri** [comment]
#1778

**Comment by ajmnz** [comment]
I believe this has been fixed. Can you confirm @Ademking

**Comment by Ademking** [comment]
@ajmnz Yeah it's fixed!
Keep up the good work
