### ISSUE TITLE
@  autocompletion in chat with Tab

### ISSUE THREAD

**Issue by alcpereira** [benawad/dogehouse#1783]
**Is your feature request related to a problem? Please describe.**
I tried @ someone in chat and expected that Tab would autocomplete the full name.

**Describe the solution you'd like**
Add Tab to the autocompletion option

**Describe alternatives you've considered**
Enter key already works

**Comment by nadirabbas** [comment]
Enter autocompletes when typing usernames.

**Comment by ZackaryH8** [comment]
#1804 Adds this
