### ISSUE TITLE
A UI bug where long names start horizontal scrolling

### ISSUE THREAD

**Issue by atharva-bhange** [benawad/dogehouse#1784]
**Describe the bug**
The screenshot explains it well

**To Reproduce**
You have to find a long name of the user and if that user is your follower, then after viewing your follower u can see the bug

**Expected behavior**
Not have a horizontal scroll and just have it end with ellipse for long names maybe.

**Screenshots**
![image](https://user-images.githubusercontent.com/37930618/113519301-eab97880-95a8-11eb-8284-287436824eb4.png)

**What device are you on?**
Dogehouse next website https://next.dogehouse.tv

**Comment by goldyydev** [comment]
Fixed in 3ec0c32
