### ISSUE TITLE
UI on smaller resolution monitors mean some UI items appear off the screen

### ISSUE THREAD

**Issue by wafwoof** [benawad/dogehouse#1785]
**Describe the bug**
1280x768 monitor will cause dogehouse UI items to appear off screen.

**To Reproduce**
set monitor resolution to 1280x768 (possibly others have not tested extensively).

**Screenshots**
![1280768dogehouse](https://user-images.githubusercontent.com/70172400/113520643-4eac5480-9549-11eb-9ab4-5ae220856e02.PNG)

**What device are you on?**
vivaldi (based on chrome)

**Additional context**
make me part of the front end team

**Comment by ThatOneHidde** [comment]
yes its not responsive yet

**Comment by ajmnz** [comment]
#1766
