### ISSUE TITLE
How to start Mediasoup Server on macos

### ISSUE THREAD

**Issue by gigo1980** [benawad/dogehouse#179]
Hi, can anyone tell me. What will be the requirements for running the Mediasoup Server direct on MacOS (BigSur) and how I can start it? Docker Version is looking ok.

**Comment by JanHolger** [comment]
I didn't try running the voiceserver locally yet but here are the requirements of mediasoup: https://mediasoup.org/documentation/v3/mediasoup/installation/#linux-osx-and-any-nix-system
