### ISSUE TITLE
Add ability to go back to listener from speaker

### ISSUE THREAD

**Issue by faraz-b** [benawad/dogehouse#1794]
**Is your feature request related to a problem? Please describe.**
Currently, you are unable to move back to listener mode after being approved as a speaker. Since the speaker status in that room is persistent, there is no way to leave speaker mode.

**Describe the solution you'd like**
Button for user to just go back to listener mode or just click on the "Listeners" text (kinda like discord moving between rooms)

**Describe alternatives you've considered**
I guess it doesn't really matter if you stay as speaker since you can just mute, but I think this should be an easy implementation and useful in order to keep the speaker list decluttered.

**Additional context**

**Comment by benawad** [comment]
click on your avatar a modal will come up with the option
