### ISSUE TITLE
Vertical scroll bar is on entire page instead of house list

### ISSUE THREAD

**Issue by jajabarr** [benawad/dogehouse#1795]
**Describe the bug**
When scrolling through the house list, the vertical scroll bar is on the right-rail of the entire page, instead of just the section.

**To Reproduce**
1. Go to home
2. Scroll when there are enough channels to scroll

**Expected behavior**
Scroll bar should be inline with the section

**Screenshots**
![image](https://user-images.githubusercontent.com/17663607/113522358-ac926980-9554-11eb-8fc6-7e69d43e6539.png)

**What device are you on?**
Windows 10, Edge Chromium

**Additional context**
N/A

**Comment by goldyydev** [comment]
This is intentional
