### ISSUE TITLE
Hover UI to dogehouse logo from chat room need to be change

### ISSUE THREAD

**Issue by Putnug1122** [benawad/dogehouse#1798]
it would have been better if the hover to the logo had a more modern look
![Screenshot (114)](https://user-images.githubusercontent.com/62296958/113523565-b6f74680-95da-11eb-9dcf-669dac11106e.png)

**Comment by SalihSaygi** [comment]
As far as I know they are not looking for kofta (frontend/UI) prs since next.dogehouse.tv is created and being updated currently.

**Comment by Putnug1122** [comment]
> As far as I know they are not looking for kofta (frontend/UI) prs since next.dogehouse.tv is created and being updated currently.

thank you for the reply
