### ISSUE TITLE
Language can't switch properly 

### ISSUE THREAD

**Issue by Putnug1122** [benawad/dogehouse#1799]
Even though the language has been changed to English, the chatroom still uses the user's default language
![Screenshot (117)](https://user-images.githubusercontent.com/62296958/113523683-d93d9400-95db-11eb-8a46-78908292aae4.png)
![Screenshot (118)](https://user-images.githubusercontent.com/62296958/113523686-db075780-95db-11eb-92e5-146e5a3e5343.png)

**Comment by YO-SC** [comment]
The language selection tab on the settings menu (where you click your profile picture) does not work on the _next_ version of the site. 

[Dogehouse (NEXT)](https://next.dogehouse.tv)

**Comment by Putnug1122** [comment]
> The language selection tab on the settings menu (where you click your profile picture) does not work on the _next_ version of the site.
> 
> [Dogehouse (NEXT)](https://next.dogehouse.tv)

oooh i'm sorry my bad. Thank alot man
