### ISSUE TITLE
New Version Bug: components not placed properly on Opera GX

### ISSUE THREAD

**Issue by epelaaez** [benawad/dogehouse#1803]
**Describe the bug**
When opening https://next.dogehouse.tv/dash with Opera GX browser, some components of the website are not loaded correctly even though zoom is at 100% and all other settings are unchanged.

**To Reproduce**
1. Go to https://next.dogehouse.tv/dash with Opera GX
2. Use browser default settings
3. See components misplaced

**Screenshots**
In the screenshot below there are three errors. First the text on the search bar is going to another line instead of being next to the search icon. Then, the "New room" button is placed below "Your feed" when it should be placed in the same line but spaced to the right. Finally, the follower and following count are placed like a staircase when they should be placed next to each other in the same line.

![image](https://user-images.githubusercontent.com/63567458/113527751-ca94b400-95be-11eb-80ce-7c7335adbea7.png)

When joining a room and going back to home page (as in screenshot below), the icons for the two buttons at the left are not placed in the middle of the button. (Same happens in the screenshot below with the "+" button in "Upcoming rooms".)

![image](https://user-images.githubusercontent.com/63567458/113527854-265f3d00-95bf-11eb-84f6-8dd5d518d659.png)

Finally, when expanding the menu when clicking my profile image, the icons of the buttons are also misplaced as seen in the screeenshot below.

![image](https://user-images.githubusercontent.com/63567458/113527933-68887e80-95bf-11eb-96d0-bbd748bbad87.png)

**What device are you on?**
Windows 10, Opera GX.

**Comment by rigba** [comment]
Can confirm same issues on my operaGX when compared to Chrome. Weird cos theyre both chromium...

Edit: also tested on plain Opera Browser (not the "gaming" fork) and it seems to work perfectly fine. It seems to be a OperaGx specific issue.

![ss1](https://user-images.githubusercontent.com/71916438/113529440-98a54100-9602-11eb-82c6-aed2586b53cd.PNG)
![ss2](https://user-images.githubusercontent.com/71916438/113529444-9a6f0480-9602-11eb-96e5-dbb49d66ed2c.PNG)

**Comment by Zamion101** [comment]
Can confirm same issues on normal Opera (74.0.3911.218) on Windows 10 Pro x64. It looks like some sort of margin error?

@jamesie i don't know if this issues occured beause of the version of Opera but it looks like there is a similar issues on my Opera.

![image](https://user-images.githubusercontent.com/8071263/113530458-637afd80-95c6-11eb-9776-fbec33f9bda4.png)
![image](https://user-images.githubusercontent.com/8071263/113530492-7b528180-95c6-11eb-8b13-f292f387adfe.png)

**Comment by rigba** [comment]
Ugh i figured out how to replicate the issue in a normal browser. 

If you look at the main div on the login page this div `m-auto flex-col p-6 gap-5 bg-primary-800 sm:rounded-8 z-10 sm:w-400 w-full`

Then turn off display flex on this element: 

```
html :not(head *,script,style,.MuiDialog-root,.MuiDialog-root *,.block,.inline-block,.inline,.inline-flex,.table,.table-caption,.table-cell,.table-column,.table-column-group,.table-footer-group,.table-header-group,.table-row-group,.table-row,.flow-root,.grid,.inline-grid,.contents,.hidden) {
    /* display: flex; */
}
```
And indeed if you go over to OperaGX you will notice its not rendering this flex. I looked into it some more and it might be a common issue :
- https://www.reddit.com/r/operabrowser/comments/xcn3t/css_not_working_on_specific_site_4chan/

I think it would be very unlikely that this had something to do with flex box not being supported like in Internet Explorer because I personally develop sites using flex on OperaGX and it works fine. I also have never experienced this bug on other websites. I dont think this is a OperaGX issue but a Dogehouse issue for that reason

**Comment by rigba** [comment]
@Zamion101 yeah its pretty weird. Have you every expirienced any css bugs like this specifically on opera or operagx?( havent personally)

**Comment by epelaaez** [comment]
Adding to @jamesie, I have too developed with Opera GX in the past and have not experienced CSS errors like these while developing or browsing.

**Comment by Zamion101** [comment]
> @Zamion101 yeah its pretty weird. Have you every expirienced any css bugs like this specifically on opera or operagx?( havent personally)

I have little to none experience in front-end unlike @epelaaez but it's the first time i'm experiencing this type of weird CSS (bug?/error) while browsing.

**Comment by amitojsingh366** [comment]
literally same behavior on the electron wrapper.
![image](https://user-images.githubusercontent.com/35400192/113541566-2bd27c80-95eb-11eb-83f2-4e43d189656c.png)

**Comment by amitojsingh366** [comment]
#1766
