### ISSUE TITLE
New Version Bug: Inaccurate/Untranslated Texts

### ISSUE THREAD

**Issue by Zamion101** [benawad/dogehouse#1807]
**Describe the bug**
While using new version of DogeHouse (https://next.dogehouse.tv), some text of the website are not translated and  rendered as `English` rather than `User Language`. This behaviour can be observed in `Profile Page` `https://next.dogehouse.tv/u/`. Also this issues can be related to #1799 .

**To Reproduce**
1. Go to https://next.dogehouse.tv/dash
2. Go to Profile page
3. Observe the issues

**Expected behavior**
Texts should be rendered in `User Language` rather than default behaviour (`English`). 

**Screenshots**
In the Screenshot below there are some translated text in the middle of the screen and un-translated texts on the sides. Also search bar contains un-translated texts.
![image](https://user-images.githubusercontent.com/8071263/113531350-d5544680-95c8-11eb-9955-0feb636b378f.png)

In the Screenshot below there is a console error which describes 404 HTTP Error for `locales/tr-TR/translation.json`
![image](https://user-images.githubusercontent.com/8071263/113531954-798abd00-95ca-11eb-89d7-29cb613a7337.png)

**What device are you on?**
Opera (74.0.3911.218) on Windows 10 Pro x64.

**Comment by nadirabbas** [comment]
I don't think we have i18n in the next version yet.

**Comment by gruselhaus** [comment]
I think a tool (CLI-Script, what so ever) that checks for missing translations would be great!

**Comment by TheOtterlord** [comment]
Kibbeh now has translations. Most strings are translated, but if you are able to contribute translations, please make a pull request.

**Comment by BronzW** [comment]
@TheOtterlord yes, but there are some hardcoded strings that haven't been converted into translation keys. Almost all new components doesn't have them, like the profile page. Instead of having this issue open we should make it a requirement to add translation keys whenever @ajmnz adds new components for people to create.
