### ISSUE TITLE
New Version Bug: The "share link to room" should be white instead of black

### ISSUE THREAD

**Issue by a7medev** [benawad/dogehouse#1811]
**Describe the bug**
The "share link to room" text doesn't have a high contrasted color for the dark background.

**To Reproduce**
1. Join a room
2. Click on the share icon in the right bottom of the room info
4. See the issue

**Expected behavior**
To have a high contrasted color for the dark background, like white or something

**Screenshots**
![Screenshot](https://i.ibb.co/xSYMV5M/Screenshot-from-2021-04-05-08-47-39.png)

**What device are you on?**
Desktop
**Additional context**
Nothing

**Comment by isaxk** [comment]
This just needs a bit of tinkering with the styles, should be quite easy to do

**Comment by BronzW** [comment]
This doesn't happen to me
![image](https://user-images.githubusercontent.com/50546858/113573997-8683cc80-961b-11eb-83c6-87e08b93d508.png)

**Comment by BronzW** [comment]
Is there something I'm missing?

**Comment by ajmnz** [comment]
#1732
