### ISSUE TITLE
New Version Bug: Language button does nothing

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#1812]
**Describe the bug**
The language translation feature button does not do anything.

**To Reproduce**
1. Go to 'next.dogehouse.tv' and login.
2. Click on 'Your profile picture'
3. Click on language
4. Nothing happens

**Expected behavior**
I expected to see a popout with a language list similar to old design

**Screenshots**

**What device are you on?**
Up to date Chrome for Windows 10

**Additional context**

**Comment by daloes** [comment]
can confirm, I can't change language as well, clicking on Language does nothing
Safari 14.0.3

**Comment by isaxk** [comment]
I think the feature hasn't been added yet

**Comment by ajmnz** [comment]
Not a bug, this feature is pending to be added

**Comment by isaxk** [comment]
Ok
