### ISSUE TITLE
Q&A System

### ISSUE THREAD

**Issue by MattGodwin** [benawad/dogehouse#1815]
**Is your feature request related to a problem? Please describe.**
A feature that handles Q&A is necessary as in large rooms such as the contributor meetings people often speak over each other and it can become challenging to understand what everyone is saying.

**Describe the solution you'd like**
A feature where it is easy to add a user as a specific Question Speaker role which can hold 1 user at a time and has a queuing system so that people can join the queue to systematically ask a question to the main speakers rather than the current solution where everyone has to be a speaker to ask a question. There would be easy to use controls for the speakers which let them mute/unmute the question speaker and a button which removes their Question Speaker role and moves the next person in the queue to the Question Speaker role.

**Describe alternatives you've considered**
Other alternatives I have thought about is putting a cap on the number of speakers so that it doesn't get too crowded and confusing.

**Additional context**
An example of the issue can be seen in the contributor meeting.
https://www.youtube.com/watch?v=8TvAC-GEsko&t=1493s

**Comment by isaxk** [comment]
This seems quite complicated and would be tricky to implement, the alternative is a lot more practical

**Comment by TheOtterlord** [comment]
I agree with @isaboo 

The alternative is much more practical than such a complex system.
It would likely be hard to use and implement.

As we did in the contributor meeting, moving people to speaker after they are finished is a much better solution.
There's no need for a large number of speakers, as realistically they are never gonna "take the stage" all at one time.

Maybe a cap could be introduced to the number of speakers, this could perhaps be a setting for the creator/mods, but this is definitely something for the future

**Comment by A-Yamout** [comment]
@TheOtterlord Close in favor of #1900 ?

**Comment by TheOtterlord** [comment]
Yeah, this makes sense
