### ISSUE TITLE
New Version Bug: Zooming out causes room participants to be spaced awkwardly and wrongly

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1823]
**Describe the bug**
When in a room with a few participants and zoom out using `ctrl+-` it causes the avatars and names to be weirdly spaced away from each other vertically.

**To Reproduce**
1. Go to 'next.dogehouse.tv'
2. Click on any room
3. Zoom out using `ctrl+-`

**Expected behavior**
The expected behavior is that the participants are supposed to be at the top of the container instead of spaced so that the listeners are at the half of the container and the speakers at the top.

**Screenshots**
https://user-images.githubusercontent.com/50546858/113573395-5d167100-961a-11eb-8047-083503663533.mp4

**What device are you on?**
Chrome, Windows 10, Lenovo Latop

**Comment by epelaaez** [comment]
On Opera GX, additionaly to the issue described above, the content does not space to the middle of the page, it goes all the way to the left as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/63567458/113606468-59014800-9648-11eb-93db-eb4a6a8c90bd.png)

**Comment by amitojsingh366** [comment]
#1766
