### ISSUE TITLE
Discord Support server

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [benawad/dogehouse#183]
GitHub Discussions is a nice place to discuss about the future of DogeHouse, but what if people want to check if the API servers and the website is up and running? How about if they want to suggest something without adding more noise to the Issue Tracker? Well, Discord.

## Invite Link

> **Server is not official, yet.** Once the server ownership goes to Ben, it'll be official.

<https://discord.gg/ZVdbW32ZeN>

## Todo

- [ ] Add moderation bots to keep things from chaos
- [ ] Rules and channel organization
- [ ] Roles

**Comment by benawad** [comment]
good idea, I'll just create a separate one rather than transfer

**Comment by AndreiJirohHaliliDev2006** [comment]
Hmmmm... Okay.
