### ISSUE TITLE
New Version Bug: room design messed up

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1836]
Something is wrong for sure.

![image](https://user-images.githubusercontent.com/38838675/113613519-c9b95c00-966a-11eb-8eb6-f061e9764002.png)

**Comment by hisamafahri** [comment]
Exactly, something is wrong here

![error1](https://user-images.githubusercontent.com/65691613/113645552-4a02b000-96b1-11eb-9356-01acf96d1f53.png)

**Comment by benawad** [comment]
@hisamafahri can you refresh and see if its fixed for you?

**Comment by hisamafahri** [comment]
@benawad Great! That's solve the problem.

But isn't a little bit weird that the dropdown is on the leftside of the avatar?

![error2](https://user-images.githubusercontent.com/65691613/113645945-052b4900-96b2-11eb-80fe-2f5fa330a895.png)

**Comment by nadirabbas** [comment]
i think it is, a bit unorthodox.
