### ISSUE TITLE
Add a REAL privacy policy and terms of service!

### ISSUE THREAD

**Issue by CreativeQuilt** [benawad/dogehouse#1837]
**Is your feature request related to a problem? Please describe.**
The privacy policy is a rickroll and is required by COPPA law

**Describe the solution you'd like**
A privacy policy and terms of service page

**Comment by fishsticks89** [comment]
The rickroll is a great privacy policy 🤔

**Comment by TheOtterlord** [comment]
Duplicate of #1595
