### ISSUE TITLE
New Version Bug: Setting menu is under the search bar. z-index issue (I Think)

### ISSUE THREAD

**Issue by mrcoet** [benawad/dogehouse#1839]
**Describe the bug**
In screen with >= 1265px width The setting menu is under the search bar. I think it's a z-index issue 

**To Reproduce**
1. Go to 'Main page'
2. Click on 'Your smallest avatar (next to the search bar)'
4. See the issue

**Expected behavior**
The setting menu should appear. but it under the search bar.
**Screenshots**
![image](https://user-images.githubusercontent.com/23162041/113619663-902c2500-9659-11eb-8b78-46e85cea459d.png)

**What device are you on?**
brave browser - latest update.
windows 10 - latest update.

**A solution**
If you remove (z-10) from the class:
![image](https://user-images.githubusercontent.com/23162041/113622555-72f95580-965d-11eb-8578-7aa7ab64aa45.png)
It will solve the issue:
![image](https://user-images.githubusercontent.com/23162041/113622646-93291480-965d-11eb-996f-246a774a1ebf.png)

**Comment by SalihSaygi** [comment]
It was fine like a hour ago. They are probably testing out stuff.
