### ISSUE TITLE
Window hidden behind search bar and name not being displayed correctly

### ISSUE THREAD

**Issue by salmmanfred** [benawad/dogehouse#1840]
**Describe the bug**
A window not being opened properly 

**To Reproduce**
Click on the user icon

**Expected behavior**
The window is not hidden behind the search bar 

**Screenshots**
![bild](https://user-images.githubusercontent.com/32799244/113624392-dedcbd80-965f-11eb-846f-d55c3f799e19.png)

**What device are you on?**
windows PC

**Additional bug**
A smaller bug is: My name is not being desplayed properly like it does not say Salmmanfred it shows some other id

**Comment by ajmnz** [comment]
Closing in favor of #1839
