### ISSUE TITLE
Remove the focus on buttons and other components when clicking.

### ISSUE THREAD

**Issue by rv178** [benawad/dogehouse#1844]
This is a problem considering that the user experience is diminished and the website in whole looks worse when this occurs.

![RemoveThis](https://user-images.githubusercontent.com/69449141/113659563-ecc22b00-96bf-11eb-96ef-29839f06d24c.png)

**Solution**
The easiest way to solve this is to style the button component with `outline: none;`.
```css
button:focus {
   outline: none;
}
```

I had tried this myself and it seems to work, I did not create a pull request because I thought this was a very small snippet of code.

![Test](https://user-images.githubusercontent.com/69449141/113659543-e16eff80-96bf-11eb-9c17-440522e2a941.png)

**Comment by lorstenoplo** [comment]
I have already told but still, how will the user know about the interaction like how will we know if the button is clicked. There are ripples for material design what's there here?

**Comment by rv178** [comment]
> I have already told but still, how will the user know about the interaction like how will we know if the button is clicked. There are ripples for material design what's there here?

The user would know about it when the button is clicked, but I just suggested a really easy to implement and small feature in order to remove the border around the button which can easily be done just by styling the button with the attribute `outline: none;`

**Comment by amitojsingh366** [comment]
i think we need this for now to follow the aria guidelines

**Comment by amitojsingh366** [comment]
have a look at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by lorstenoplo** [comment]
Yeah instead of removing the outline on focus it should altered to something else like changing the colour, changing the size, box shadows, ripples etc.
They will help to retain ux ( following the ARIA guidelines ) and improve the ui like a hell lot.
