### ISSUE TITLE
small issue with text getting chopped at the end of the div for long captions

### ISSUE THREAD

**Issue by Baggiest** [benawad/dogehouse#1850]
my long caption was imported from Twitter and it's chopped at the end of the div, thought I might help :)

my dash view:
![image](https://user-images.githubusercontent.com/76979204/113722628-d8088600-9705-11eb-95bd-89c0618b03b1.png)

device:
full-screen desktop

**Comment by ajmnz** [comment]
@goldyydev I believe you worked on word breaks and stuff.

**Comment by amitojsingh366** [comment]
@MrBaggieBug from next time please use the format we created for the next version to report bugs. that way we can filter them specifically.

**Comment by Baggiest** [comment]
oh sorry this was my first interaction with the project i wasn't aware

will look at the forum really carefully next time :)
