### ISSUE TITLE
Make search bar on new design just say "search" instead of long text on mobile new design

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#1851]
**Is your feature request related to a problem? Please describe.**
It looks ugly when the text in the search bar is cut of mid-word

**Describe the solution you'd like**
It just to say 'Search' or 'Search Dogehouse'

**Describe alternatives you've considered**
Maybe to do an ellipse (...) at the end

**Additional context**
![Screenshot_20210406-150608_Chrome.jpg](https://user-images.githubusercontent.com/76838845/113724376-2f98f880-96ea-11eb-9a0c-f1a3d281e440.jpg)

**Comment by daloes** [comment]
Long text could be visible on tooltip 🤔

**Comment by vi241** [comment]
I think changing it to search on mobile is better

**Comment by vi241** [comment]
or just do it to all of them like you recommended
