### ISSUE TITLE
Dogehouse app doesn't remove tray icon after the app closes

### ISSUE THREAD

**Issue by babeuh** [benawad/dogehouse#1852]
**Describe the bug**
In the Dogehouse electron application the system tray icon is not removed after the app closes, which causes an error if you try to close it again with the tray or if you try to left click on the tray icon

**To Reproduce**
1. Open Dogehouse app
2. Open the system tray
3. Right Click on Dogehouse icon
4. Click on "Quit Dogehouse"
6. Go to step 3 until step 4
7. See error

**Expected behavior**
The Dogehouse tray icon should be removed when the application closes

**Screenshots**
![image](https://user-images.githubusercontent.com/60193302/113730778-5271df80-96df-11eb-9335-e87de1095a8c.png)

**What device are you on?**
Desktop, Windows 10

**Additional context**

**Comment by amitojsingh366** [comment]
hmmmm

**Comment by babeuh** [comment]
This is how I fixed this in my electron apps but there might be a better way. (just a suggestion)
```js
mainWindow.on('close', () => {
  tray.destroy();
});
```

**Comment by amitojsingh366** [comment]
`tray.destroy()` isn't what we're looking for as the issue lies with the app not even closing properly. i have a fix in mind and will release an update soon.
