### ISSUE TITLE
New Version Bug: Responsive UI not working on mobile

### ISSUE THREAD

**Issue by asxlvm** [benawad/dogehouse#1856]
**Describe the bug**
UI looks scuffed on some mobile versions and doesn't work on some mobile versions

**To Reproduce**
1. Go to 'next.dogehouse.tv' in Mobile Opera and you will see that the UI is scuffed, if you go on next.dogehouse.tv on F12 Browser you will see the UI normally but it doesn't work

**Expected behavior**
UI is scuffed on some mobile browsers and doesn't work on some mobile browsers.

**Screenshots**
F12 Browser: (Good UI but buttons don't work)
![Screenshot_2021-04-06-21-51-08-658_com asfmapps f12](https://user-images.githubusercontent.com/81298611/113771251-6d664300-9723-11eb-9052-f8ef71fb9039.jpg)
Opera Browser: (Bad UI but buttons work)
![Screenshot_2021-04-06-21-51-05-061_com opera browser](https://user-images.githubusercontent.com/81298611/113771422-a1d9ff00-9723-11eb-868d-feb1d83cbd0c.jpg)

**What device are you on?**
Xiaomi Pocophone F1 (Android 10)

**Additional context**

**Comment by amitojsingh366** [comment]
only the desktop version is complete *(complete as in ready for testing, it still isn't responsive)*. the mobile version is still being worked on

**Comment by amitojsingh366** [comment]
ill leave this open for now

**Comment by amitojsingh366** [comment]
actually nvm. please refer #1766 for any responsive UI related issues
