### ISSUE TITLE
Emotes with menu don't work after lower casing json.

### ISSUE THREAD

**Issue by theCow61** [benawad/dogehouse#1863]
**Describe the bug**
#1842 brakes emotes. Emote menu auto populates input field thing with old emote name which doesn't match with the update json.

Can be fixed by automatically lower casing the emote names when the menu auto populates the input field or reverting the #1842 push.

**Comment by nadirabbas** [comment]
you need to convert to lowercase in `createChatMessage` too.

**Comment by amitojsingh366** [comment]
i've fixed this. will push soon

**Comment by theCow61** [comment]
Wierd the v.toLowerCase() isn't working right now but when I did it on my fix PR with yarn staging it worked.

**Comment by theCow61** [comment]
Never mind its working now.

**Comment by amitojsingh366** [comment]
@theCow61 it will only work after ben deploys it, and it seems like ben has deployed it now
