### ISSUE TITLE
New Version Bug: Cannot return to room screen after chatting in mobile

### ISSUE THREAD

**Issue by lorstenoplo** [benawad/dogehouse#1864]
**Description of the bug :**
After entering a room if we go to the chat screen and chat till the time scrollbar is visible then we cannot see then return options

**Steps to reproduce the behavior :**
1. Go to any room on next.dogehouse.tv
2. Click on chat
3. Keep chatting
4. See the options disappear

**Expected behavior :**
The options pannel should still be accessible

**Screenshots :**
You can see that there is no options pannel :

![Screenshot_20210407-124152](https://user-images.githubusercontent.com/69671750/113827553-10a96d80-97a1-11eb-9289-a3c1b0c02d12.png)

Although it visible initially :

![Screenshot_20210407-124428~2](https://user-images.githubusercontent.com/69671750/113827636-274fc480-97a1-11eb-8cfb-788b5b965e0d.png)

**Device info :**
I'm on a phone

**Additional info :**
I could have directly created a pr but I felt it was a simple css bug and can be fixed with ease.

**Comment by benawad** [comment]
fixed
