### ISSUE TITLE
The username's input field background changes to white when invalid

### ISSUE THREAD

**Issue by xBrainZy** [benawad/dogehouse#1867]
**Is your feature request related to a problem? Please describe.**
When creating a username the length of characters must be between 4 - 14 and they must only be alphanumeric/ underscore right? 
When the username is invalid, the background of the input field changes to white, and the color of the text changes to light grey. That's just too bright and I can't see the text properly. The new users might not be comfortable with it. 

**Describe the solution you'd like**
It's better to keep the dark background and let the color of the text be either red or any bright color of your choice. 

**Additional context**
![image](https://user-images.githubusercontent.com/31233518/113861700-2a9e7c80-97b0-11eb-885e-cc95aa53e411.png)

**Comment by ajmnz** [comment]
Can reproduce

**Comment by BronzW** [comment]
I think this is a problem with WebKit and can be solved with the `-webkit-autofill` pseudo selector. https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by benawad** [comment]
fixed
