### ISSUE TITLE
New Version Bug: Mobile UI has bad placement

### ISSUE THREAD

**Issue by asxlvm** [benawad/dogehouse#1868]
**Describe the bug**
Things that are supposed to be in-line are split between lines, things that should be on the right are on the left conflicting with other UI

**To Reproduce**
1. Go to 'next.dogehouse.tv' on mobile (I use the Opera browser)
2. Join a room
3.  Inspect the scuffed UI

**Expected behavior**
Clear good looking UI with good placement, obv.

**Screenshots**
Screenshots are needed here;
![Screenshot_2021-04-07-14-24-35-623_com opera browser](https://user-images.githubusercontent.com/81298611/113866300-713ea780-97ad-11eb-9c84-8c137cdfe129.jpg)
![Screenshot_2021-04-07-14-24-44-330_com opera browser](https://user-images.githubusercontent.com/81298611/113866309-73a10180-97ad-11eb-9976-50de5a80814f.jpg)

**What device are you on?**
Xiaomi Pocophone F1 (Android 10)

**Additional context**
I am not sure if this error is on any other browser but I use mobile Opera.

**Comment by BronzW** [comment]
The same thing happens when switching to the new version in the electron app

**Comment by amitojsingh366** [comment]
#1766
