### ISSUE TITLE
Consider adding breadcrumb navigation to the Design System

### ISSUE THREAD

**Issue by christopher-talke** [benawad/dogehouse#1871]
**Describe the solution you'd like**
Pretty straight forward, an addition of a `breadcrumb` component. 

> Breadcrumbs show users their current location relative to the information architecture and enable them to quickly move up to a parent level or previous step.

**Describe alternatives you've considered**
Some notable examples can be found here:

- Ant Design: [https://ant.design/components/breadcrumb](https://ant.design/components/breadcrumb)
- Lightning Design System: [https://www.lightningdesignsystem.com/components/breadcrumbs](https://www.lightningdesignsystem.com/components/breadcrumbs)
- Atlassian Design System: [https://atlassian.design/components/breadcrumbs](https://atlassian.design/components/breadcrumbs)
- Carbon Design System (IBM): [https://www.carbondesignsystem.com/components/breadcrumb](https://www.carbondesignsystem.com/components/breadcrumb/usage/)

**Additional context**
I took it upon myself to throw one [together ](https://github.com/christopher-talke/dogehouse/commit/9d630a9d8e7e2fb1e0a6dafa1eab56d304a74bfc) but it ended up getting closed (...which is fair enough, didn't read the [design guidelines](https://github.com/benawad/dogehouse/blob/staging/DESIGN_GUIDELINES.md) ).

@ajmnz - I still believe its worth throwing onto the roadmap, below is a brief `screen cap` of what I had in mind. 

![breadcrumbs_for_life](https://user-images.githubusercontent.com/25414518/113868867-79213a80-97f3-11eb-9d5b-dd277a76c502.gif)

**Comment by goldyydev** [comment]
@ajmnz That's your line of duty.

**Comment by ajmnz** [comment]
Yep, I noted it down. I'm not discarding your request by closing this issue, but I might approach this differently and I think it doesn't make sense to have yet *another* open issue.

Appreciate the explanation and docs, will keep you posted
