### ISSUE TITLE
New Version Bug: (Mobile) Buttons for changing screens don't work after chat-overflow

### ISSUE THREAD

**Issue by asxlvm** [benawad/dogehouse#1875]
**Describe the bug**
If there's a lot of messages in chat, the three buttons for changing screens aren't there

**To Reproduce**
1. Go to 'next.dogehouse.tv'
2. Type for a while...
3. And when there's alot of messages, the buttons disappear
4. Observe ;)

**Expected behavior**
The 2 buttons should always be there
Expected screenshot:
![Screenshot_2021-04-07-21-33-15-915_com brave browser](https://user-images.githubusercontent.com/81298611/113923488-e11e5380-97e8-11eb-88c3-d586a88fc0e8.jpg)

**Screenshots**
Not working screenshot:
![Screenshot_2021-04-07-21-24-29-200_com brave browser](https://user-images.githubusercontent.com/81298611/113923359-c0ee9480-97e8-11eb-93e5-9e9b945f7b33.jpg)

**What device are you on?**
Xiaomi Pocophone F1 (Android 10)

**Additional context**
Mobile Brave browser

**Comment by ajmnz** [comment]
#1864
