### ISSUE TITLE
New Version Bug: Changing viewport size causes following list's scrollbar to go back to default

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#1890]
![image](https://user-images.githubusercontent.com/50546858/114029861-3eaeb080-987a-11eb-89cf-59e18b06fd71.png)

**Comment by lorstenoplo** [comment]
The reverse should happen though, the scroll bars should be restored to default on smaller screens like mobiles

**Comment by BronzW** [comment]
I think as I can't reproduce this problem again today this issue should be closed.
