### ISSUE TITLE
Electron app doesn't want to launch on Linux

### ISSUE THREAD

**Issue by borisgrigorov** [benawad/dogehouse#1893]
**Describe the bug**
An error is thrown when trying to launch the electron app.

**To Reproduce**
1. Open AppImage file in terminal (to see the error)
2. See the error

**Expected behavior**
The app should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/45951844/114051966-de296e80-988d-11eb-8b55-cbe1b8ffb56d.png)

**What device are you on?**
Ubuntu 20.10, Linux

**Comment by amitojsingh366** [comment]
im looking into this

**Comment by amitojsingh366** [comment]
does the app not launch at all or does it get stuck on "Checking for updates..."?

**Comment by borisgrigorov** [comment]
It crashes when checking for updates.
