### ISSUE TITLE
New Version Bug: there's a lot of space wasted

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1894]
This is how kibbeh looks like
![image](https://user-images.githubusercontent.com/38838675/114077723-8a387d00-98c1-11eb-95fd-db935c26e7df.png)

This is how kofta looks like:
![image](https://user-images.githubusercontent.com/38838675/114077793-9c1a2000-98c1-11eb-82a9-3b23ac4770b4.png)

on my laptop, which doesn't have a very big screen (35.6 cm / 14 in)

**Comment by btarg** [comment]
There should definitely be less empty space around the room view, and connecting the room view and chat could help too.

**Comment by BronzW** [comment]
Yeah you can't really get a view of what people are in the room.

**Comment by ajmnz** [comment]
User grid in rooms is temp and responsiveness too. Also note that atm notifications, messages, etc are missing from the header, so we'll get to fill the space eventually.

Your people sidebar isn't showing though

**Comment by isaxk** [comment]
> User grid in rooms is temp and responsiveness too. Also note that atm notifications, messages, etc are missing from the header, so we'll get to fill the space eventually.
> 
> Your people sidebar isn't showing though

That's because their screen is slightly too small

**Comment by nadirabbas** [comment]
Gonne close this as @benawad clarified in _DogeLog[4]_.
