### ISSUE TITLE
Chat drafts carry across rooms

### ISSUE THREAD

**Issue by igbanam** [benawad/dogehouse#1905]
**Describe the bug**
Chat message drafts carry across rooms. — dunno if bug or intended feature 🤔 

I was in a room, in the middle of typing a message in the chat. The room owner closed the room, I got popped back into the homepage. I joined another room… the message I was typing in the previous room is pre-populated in the chat. 

**To Reproduce**
1. Join a room
2. Begin typing in the chat; don't send
3. Have the room creator close/delete the room
4. Join another room
5. You chat has the message from the closed room

**Expected behavior**
You chat should be a clean slate.

**Screenshots**
n/a — privacy

**What device are you on?**
web

**Additional context**
nope

**Comment by TheOtterlord** [comment]
#### Good first issue
You should just need to clear the chatbox's value when someone enters a new room (or you can do it when they leave)

**Comment by BronzW** [comment]
Duplicate #1891

**Comment by BronzW** [comment]
Is there a way to know when you join a new room?
