### ISSUE TITLE
WAYTOODANK doesn't appear in autocomplete when typing :way, but it does appear when you type :dank

### ISSUE THREAD

**Issue by SunbroJedi** [benawad/dogehouse#1914]
**Describe the bug**
When ":WAY", or any amount of letters that it starts with, WAYTOODANK doesn't appear in autocomplete, however, when ":dank" is entered, it does appear.

**To Reproduce**
1. type :way, or any amount of the letters it starts with

**Expected behavior**
The emote known as WAYTOODANK should appear in the autocomplete above the text box.

**Screenshots**
![2021-04-09-11:06:45-screenshot](https://user-images.githubusercontent.com/55336959/114201033-cbfa0f80-9923-11eb-8853-5cd658070e7b.png)

![2021-04-09-11:06:58-screenshot](https://user-images.githubusercontent.com/55336959/114201139-e16f3980-9923-11eb-9353-ff9ed46b79c0.png)

**What device are you on?**
A linux pc.

**Additional context**
I'm using Next.dogehouse on firefox

**Comment by daloes** [comment]
waytoodank needs to be added to keywords for emoji,  can try :feelsdankman it should also show waytoodank emoji

{
    name: "WAYTOODANK",
    short_names: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman"],
    imageUrl: "/emotes/WAYTOODANK.gif",
  },

**Comment by daloes** [comment]
So this shouldn't be a bug, it's behaving as configured. You can create pr adding this keyword or somebody can expand the lookup to include the name/short_names with keywords for matching.
