### ISSUE TITLE
Emoji picker not using the available width

### ISSUE THREAD

**Issue by daloes** [benawad/dogehouse#1915]
**Describe the bug**
Tested on phone, new design
When you open emoji picker there is unused space on right side of emojis as they do not fill the whole space instead are capped at 7 emojis per row. Emoji picker background however spans the whole width

**To Reproduce**
1. Go to chat
2. Click on emoji picker
3. Observe empty space on right
4. Flip phone to landscape
5. Observe even more wasted space

**Expected behavior**
Emojis should fill as much horizontal space as possible and only then continue on next row. This would make it much more pleasant to use in landscape also.

**Screenshots**
![Screenshot_20210409-172239_Chrome](https://user-images.githubusercontent.com/11330406/114204132-1fd31b80-9959-11eb-8472-042d02f9be9d.jpg)
![Screenshot_20210409-171528_Chrome](https://user-images.githubusercontent.com/11330406/114204136-21044880-9959-11eb-8885-0cbc2da557f6.jpg)

**What device are you on?**
S10e, android 11, chrome

**Comment by daloes** [comment]
Damn this was meant as new-version-bug

**Comment by vi241** [comment]
does the browser matter for mobile?

**Comment by goldyydev** [comment]
this is a mobile only bug

**Comment by vi241** [comment]
yes ik

**Comment by daloes** [comment]
I dont think browser matters it seems like general css layout issue on phone view. I can't test the possible cause as I'm not near my laptop atm

**Comment by jobveldhuis** [comment]
I have added a full-width class to the EmojiPicker component, so that it will adhere to the limits of the parent, instead of the natural limits of the component. See #1954
