### ISSUE TITLE
New Version Bug: Chat caused Unexpected Error

### ISSUE THREAD

**Issue by TheOtterlord** [benawad/dogehouse#1918]
**Describe the bug**
If you scroll quickly up the room chat on the [beta](https://next.dogehouse.tv), it causes the page to error out.

**To Reproduce**
1. Go to a room on [next](https://next.dogehouse.tv)
2. Wait for the chat to start scrolling
3. Scroll up
4. See error page

**Expected behavior**
The chat scrolls without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/64310361/114209420-8145bb00-9956-11eb-8119-64b339b45549.png)

**What device are you on?**
Firefox Developer Edition; Windows 10
Also tested on Firefox & Firefox Nightly

**Additional context**
Same error number as #1889

**Comment by TheOtterlord** [comment]
Nevermind. I was being served cache data

**Comment by TheOtterlord** [comment]
Ok, apparently it still exists sometimes. but I can't seem to replicate it with 100% success.

**Comment by TheOtterlord** [comment]
Reopening as it still exists. Happens at about 25% - 33% scrollbar height

**Comment by amitojsingh366** [comment]
i can reproduce this:

https://user-images.githubusercontent.com/35400192/114700957-def94f00-9d2a-11eb-8e0b-35318f6de65d.mp4

**Comment by amitojsingh366** [comment]
probably has to do smtg with #1876

**Comment by sahilmob** [comment]
Guys are you still able to reproduce this issue. I tried to reproduce it locally without any success

https://user-images.githubusercontent.com/33333226/115162232-0cd3f000-a0ab-11eb-93f5-0c77168f4977.mp4

**Comment by amitojsingh366** [comment]
still occurs, currently fixing it
