### ISSUE TITLE
Chat Freeze on scroll or key press

### ISSUE THREAD

**Issue by LiamTownsley** [benawad/dogehouse#1919]
**Is your feature request related to a problem? Please describe.**
When trying to read previously sent messages in chat when it's moving fast, it's impossible to read the messages before t hey are scrolled away.

**Describe the solution you'd like**
Similar to Twitch, you press a key the chat stops automatically moving and freezes in place so you can read what you're trying to read.

**Describe alternatives you've considered**
No idea, in all honesty.

**Additional context**
![3oMrS01](https://user-images.githubusercontent.com/25304583/114210933-f5349300-9957-11eb-926e-38b2edcec981.gif)

**Comment by goldyydev** [comment]
cannot reproduce, what browser (and extensions) are you using?

**Comment by nadirabbas** [comment]
if you scroll up, the chat actually stops.

**Comment by ch70357** [comment]
This is happening on Chrome. when using the scrollbar to scroll up, the chat continues to load and lower it.

**Comment by LiamTownsley** [comment]
> cannot reproduce, what browser (and extensions) are you using?

**Browser**: Chrome 89.0.4389.114
**Extentions** (that has access to the site): 
* Dashlane
* HTTPS Everywher
* uBlock Origin

Not tested on other browsers but I presume this is chrome-specific by what you're saying.

**Comment by sahilmob** [comment]
Apparently, the scrollbar will adapt and maintain the same scrolling position until it reaches 100 message which is set in `useRoomChatStore.ts`, after that limit the messages array will be sliced to 100 message, therefore each message position will be shifted for each incoming message.

With 100 message limit:
https://user-images.githubusercontent.com/33333226/114287661-3c627700-9a71-11eb-80ac-4afb3c379768.mp4

Without limit:
https://user-images.githubusercontent.com/33333226/114287669-48e6cf80-9a71-11eb-96e9-3c926897c987.mp4

**Comment by ch70357** [comment]
Makes sense. I noticed this in 2 rooms, bee hive swarm (something to that effect), and the FizzBuzz room. Both acted like messages were being injected to perform load testing, or possibly the API was compromised and being used to insert numerous messages. 

I'm on Chrome version 89.0.4389.114 (64 bit), with no extensions.
