### ISSUE TITLE
Pinned messages for chat

### ISSUE THREAD

**Issue by MaheshNat** [benawad/dogehouse#192]
have the ability for mods to pin certain messages, so that they will be stored. Any new members that join the room will be able to view the pinned chat messages. I don't know how viable this would be since you are likely not storing any chat information permanently as of now, but just a suggestion. It could be used to pin important links or a message describing what the room is talking about.

**Comment by mohammedgad** [comment]
@benawad I think I can work on the BE part.

**Comment by nadirabbas** [comment]
@benawad We can have a field in the room. Something like `room_rules` or something. This can also be used as a pinned message for new users to give them context about the current discussion. This can be editable. We can put this along with the room name edit modal.

This way only a few lines of code could close this issue.

**Comment by benawad** [comment]
yeah I want to add a room description where stuff like that can go

**Comment by nadirabbas** [comment]
@benawad creating an issue and will add a field to the DB.

**Comment by nadirabbas** [comment]
done
