### ISSUE TITLE
New dogehouse messed up on phone

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#1920]
![Screenshot_20210409-220441_Chrome](https://user-images.githubusercontent.com/72514547/114212892-f5e11f80-997f-11eb-8305-d76b01ca37a2.jpg)
This is how it looks on my phone. Some css problems maybe

**Comment by daloes** [comment]
Your screen might be too small. What device are you using? On my phone, s10e, layout is fine at 1080x2280

Also this is new-version-bug

**Comment by learningnoobi** [comment]
it seems fine though

**Comment by ajmnz** [comment]
Follow the template for new version bugs (include device, browser, etc.)
