### ISSUE TITLE
Last language not displaying in kibbeh.

### ISSUE THREAD

**Issue by GiggioG** [benawad/dogehouse#1923]
So I was the contributor for the Toki Pona Language, and I recently saw that it was deployed. So I went to next.dogehouse.tv and opened the language menu, scrolled to the bottom, but didn't see it there. I `Inspect Element`ed the language menu, and I saw Toki Pona at the bottom as another `<button>`, but it just didn't render. When I hovered over the `<button>` and it highlighted below the language list:
![image](https://user-images.githubusercontent.com/47040505/114218048-9c71f400-9971-11eb-8f70-8d48627e815c.png)
If someone knows why, then please try to fix it, because I don't know anything about react.

**Comment by goldyydev** [comment]
Gonna PR again after #1922 is merged not to cause further issues with linting.
