### ISSUE TITLE
Add bot detection

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1924]
@benawad what do you think?

Bots join directly using the API, so they don't have UI, hence no mouse movements, and human-like interaction with the page. So we can infer on the front end if someone is not a bot.

If a bot joins from something like Puppeteer, it's gonna have a UI, but we still can use libraries that can distinguish between human and bots

After we know it's a bot, maybe we can add some kind of badge next to its name, so people who join know that it's a bot. I think it's pretty helpful.

**Comment by TheOtterlord** [comment]
Most bots (and I mean almost all) are created using the unofficial library `dogehouse.js` or using `kebab`, neither of which use the web browser so detecting if they are in puppeteer will not work.

Detecting it on the backend will probably be implemented when the bot api is added, but that will not be coming for a while. I believe ben also mentioned in a DogeLog (and a contributor meeting) that this would be coming in the **far future**, but I can't remember which one. Gonna close this as we have multiple issues (e.g. #1207) related to this and we have 230+ issues total.

Also, to any bot developers reading this, including `bot` in the username of your bot accounts will help with a some of the confusion.

**Comment by nadirabbas** [comment]
I said if they are using API directly, then we can detect who is not a bot (humans). and the accounts that are left, are bots :/

**Comment by TheOtterlord** [comment]
Actually that's a pretty cool idea.

**Comment by nadirabbas** [comment]
thanks, lol, that's why i opened this issue,

**Comment by TheOtterlord** [comment]
yeah, sry. I obviously didn't understand properly. I'll reopen this :)

**Comment by overlisted** [comment]
seems too rough though, we can just do what discord did (extending #1207) and ban all "self-bots" (non-bot accounts which aren't used by humans)

**Comment by nadirabbas** [comment]
@overlisted but that isnt related to what i said at all.

**Comment by isaxk** [comment]
> seems too rough though, we can just do what discord did (extending #1207) and ban all "self-bots" (non-bot accounts which aren't used by humans)

I don't think it's rough, when the official API is realeased it wouldn't take much work, to send to the front end that 'this user is a bot' and then react to display something like a robot emoji next to the bot's name.
