### ISSUE TITLE
Increase/Decrease everyone's volume in the room at once

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#1926]
A single slider to increment/decrement everyone's volume in DogeHouse. 
You can change speakers' volume to 200% in DogeHouse, even if your speakers are at max, so this pretty helpful if you have low volume speakers.

**Comment by goldyydev** [comment]
@nadirabbas  https://next.dogehouse.tv/voice-settings ?

**Comment by nadirabbas** [comment]
oh that's a thing?
