### ISSUE TITLE
Adding a popup telling user that they have not allowed microphone access

### ISSUE THREAD

**Issue by poweitsao** [benawad/dogehouse#1927]
**Is your feature request related to a problem? Please describe.**
When I first joined to speak in a room, I didn't know that chrome was blocking my mic and spent like 10 min trying to fix my mic.  There was nothing on the UI that tells me my mic is blocked.

**Describe the solution you'd like**
I know chrome usually has a pop-up but I think it would be beneficial to have an alert of some sort next to the mic button that tells the user "doghouse does not have permission to use your mic" along with a tutorial/gif of how to fix it. This would allow even those who are not tech-savvy to figure out how to give mic permissions.

**Describe alternatives you've considered**
The alternative would be for the user to discover on their own that their mic is blocked. You see a tiny icon on chrome but with this implementation, it would be clear to the user that the issue is with permissions and not mic hardware. 

**Additional context**
I think putting the text of "mic permissions not granted" here in the room would be great.
![image](https://user-images.githubusercontent.com/29420368/114220897-8eed4780-993a-11eb-8c2c-1374e42be635.png)

**Comment by goldyydev** [comment]
@ajmnz

**Comment by ajmnz** [comment]
@goldyydev a non-autoclosing error toast should do it for now
