### ISSUE TITLE
CODE OF CONDUCT for new contributors

### ISSUE THREAD

**Issue by FotieMConstant** [benawad/dogehouse#193]
Hi, I think a Code of conduct for new contributors will be great @benawad, to help keep things clean amongst contributors. I can work on that at put it up on a pull request.

**Comment by FotieMConstant** [comment]
Created a pr for this issue here #195

**Comment by drvladb** [comment]
Done by #195

**Comment by FotieMConstant** [comment]
The pr has been approved and merged, closing this issue!
