### ISSUE TITLE
New Version Bug: Profile picture popup is missing a margin

### ISSUE THREAD

**Issue by arrudagates** [benawad/dogehouse#1932]
**Describe the bug**
Profile pop up is mising a margin on top

**To Reproduce**
1. Go to any dogehouse page
2. Click on your pfp in the top right corner
4. Notice how there is no margin between the popup and the top of the page

**Expected behavior**
The top of the popup should line up with the profile picture

**Screenshots**
![](https://cdn.discordapp.com/attachments/620330473876357123/830150173224992798/1617993369.png)

**What device are you on?**
Web (Linux, Firefox)

**Comment by arrudagates** [comment]
Should be fixed with
`padding-top: 30px;`

and to complement
`padding-right: 5px;`

**Comment by swikars1** [comment]
why padding not margin

**Comment by arrudagates** [comment]
Because that's how the rest of the header is styled

**Comment by BronzW** [comment]
But that isn't part of the header. Using margin works fine aswell and makes more sense
