### ISSUE TITLE
npm install is giving errors

### ISSUE THREAD

**Issue by armedev** [benawad/dogehouse#1950]
**Describe the bug**
npm Install not working or maybe I am lacking some tips.

**To Reproduce**
1. Go to 'kofta/'
2. run npm i.

**Expected behavior**
It should Install all packages.

**Screenshots**
![Screenshot from 2021-04-10 22-47-18](https://user-images.githubusercontent.com/51921579/114278746-d107ad80-9a4e-11eb-9ab0-bf1cf9a25caa.png)

**What device are you on?**
Kali Linux

**Comment by BronzW** [comment]
Cannot reproduce. Have you tried in powershell or cmd?

**Comment by AakashSharma7269** [comment]
![image](https://user-images.githubusercontent.com/60808802/114338923-b417cb00-9b71-11eb-8547-95bb020cf0e1.png)

**Comment by paolapog** [comment]
Try to remove the `node_modules` folder and run again `npm i` **OR** try to `npm install --save extract-zip` manually.
I 've already tried to reproduce the issue but I cannot

**Comment by cursorial** [comment]
`yarn`

**Comment by TheOtterlord** [comment]
Kofta is now archived.
