### ISSUE TITLE
New Version Bug: blank page when joining any room on iphone Safari browser

### ISSUE THREAD

**Issue by yzx396** [benawad/dogehouse#1952]
**Describe the bug**
On my iphone 12 pro safari browser, I can see list of rooms after github signin to next.dogehouse.tv, but when I join any room, it will lead me to a blank page without any voice.

**To Reproduce**
1. Go to next.dogehouse.tv in safari browser on iphone
2. Click on Github login
3. Click on the first room
4. See a blank page and no voice

**Expected behavior**
See a room with people and hear voice from speakers

**What device are you on?**
iPhone 12 Pro

**Additional context**
no

**Comment by jobveldhuis** [comment]
I can actually reproduce this bug and have some more info to add. It will play the sound of the room for a couple of seconds until it has loaded the blank page, then all sound will cut out and it will no longer work.

**Comment by BronzW** [comment]
Can reproduce on iPhone 7

**Comment by kndwin** [comment]
Does it work with other browsers on the iPhone or is it just exclusively Safari?
Can you confirm if the behavior is the same if you open Safari on another device (laptop) but with a mobile width?

**Comment by yzx396** [comment]
The problem is gone
