### ISSUE TITLE
New Version Bug: No custom scrollbar on right panel

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#1955]
There's no custom scrollbar on the right panel

![image](https://user-images.githubusercontent.com/35400192/114283648-76248500-9a53-11eb-8205-d3082d7f6660.png)

**Comment by Ademking** [comment]
Same here:
![image](https://user-images.githubusercontent.com/12462188/114286483-01534a00-9a57-11eb-95a6-acd5a2422321.png)

**Comment by benawad** [comment]
anyone know if there is a way to globally style the scrollbar rather than us doing it for each and everyone

**Comment by amitojsingh366** [comment]
> anyone know if there is a way to globally style the scrollbar rather than us doing it for each and everyone

yes if you put it in `kibbeh/src/styles/global.css`

**Comment by amitojsingh366** [comment]
@benawad see #1962
