### ISSUE TITLE
Room doesn't exist bug.

### ISSUE THREAD

**Issue by Shinyzenith** [benawad/dogehouse#1965]
Sharing the link to a private room, often said "room doesn't exist anymore" on clicking on it altough it's actually a live room.

**Comment by ghost** [comment]
Thats cuz its a private room and the user on the other shd not be able to access it. So according to the user on the other end, "The room doesnt exist anymore"

**Comment by Shinyzenith** [comment]
@Krishna-Ramasimha but if that's indeed the issue then why does it tell me "room is private" when I try to join?
