### ISSUE TITLE
Kousa: ws data sanitization

### ISSUE THREAD

**Issue by dark-elixir-shibe** [benawad/dogehouse#1972]
- [ ] level 0: basic ws input/reply sanitization
- [ ] level 1: advanced ws input/output sanitization (details hidden due to security considerations, leave comment if you want to help)
- [ ] level 2: eliminate usage of naked websocket pushes from the interior of the codebase
- [ ] level 3: document how to add new websocket content
- [ ] level 4: catalog all websocket communications into a formalized contract
- [ ] level 5: work on versioning strategy for moving from BE "0.1" to BE "0.2" and further.

**Comment by dark-elixir-shibe** [comment]
current work on ws input/reply sanitization here:  https://github.com/dark-elixir-shibe/dogehouse/tree/kousa/isaac/ws-validation

**Comment by dark-elixir-shibe** [comment]
general technique:  use Ecto embedded schemas to provide simple declarative interfaces for validation:  https://www.youtube.com/watch?v=k_xDi7zAcNM

**Comment by goldyydev** [comment]
@benawad this one's for you to review

**Comment by dark-elixir-shibe** [comment]
completed
