### ISSUE TITLE
Error while joining the room in mobile

### ISSUE THREAD

**Issue by chsaikumar445** [benawad/dogehouse#1981]
I don't what the error is about but here is the ss
![Screenshot_2021-04-12-22-35-02-775_com android chrome](https://user-images.githubusercontent.com/44166843/114433603-a436d000-9bdf-11eb-9df4-c54e5256f36a.jpg)

**Comment by TheOtterlord** [comment]
Try using the [new design](https://next.dogehouse.tv).

**Comment by okdargy** [comment]
> Try using the [new design](https://next.dogehouse.tv).

Same thing happens on the new design. I think the room is bugged, not DogeHouse. 

The room that is bugged is named "DoobHouse!" if you want to try reproduce this.
![image](https://user-images.githubusercontent.com/76412158/114626616-9766ba80-9c79-11eb-8ca8-4a276b953ba1.png)
![image](https://user-images.githubusercontent.com/76412158/114627009-25db3c00-9c7a-11eb-9af0-fef6fd03a1c3.png)

**Comment by TheOtterlord** [comment]
This room was bugged and no longer exists. It should no longer appear in the list of rooms. I'll close this issue, but feel free to reopen if it happens again

**Comment by okdargy** [comment]
Happened again #2070 

![image](https://user-images.githubusercontent.com/76412158/115087979-e3616b80-9ed4-11eb-8295-104982ceb0e7.png)
