### ISSUE TITLE
add margin-bottom to modal for edit profile and other things

### ISSUE THREAD

**Issue by munetta** [benawad/dogehouse#1999]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BronzW** [comment]
Filling in the fields in the description of this issue will help resolving it. I don't see any meaning in margin-bottom to the edit profile modal as it looks fine to me 
![image](https://user-images.githubusercontent.com/50546858/114725757-0f49e900-9d3d-11eb-898e-79a0f65a662d.png)

**Comment by munetta** [comment]
Ok

**Comment by ajmnz** [comment]
This is temp and will be moved to settings eventually
