### ISSUE TITLE
Amount of people duplicate everytime you open the Invite tab

### ISSUE THREAD

**Issue by okdargy** [benawad/dogehouse#2007]
**Describe the bug**
Amount of people duplicate everytime you open the Invite tab

**To Reproduce**
1. Go to any room
2. Make sure a follower is online
3. Click Invite
4. Go back and click Invite again

**Expected behavior**
Supposed to show only the same amount of followers.

**Screenshots**
![image](https://user-images.githubusercontent.com/76412158/114626338-3343f680-9c79-11eb-9f4c-73da6bfb15fe.png)

**What device are you on?**
Chromebook

**Additional context**
None

**Comment by kndwin** [comment]
Can you advise if this behavior is reproducible with [next.dogehouse.tv](https://next.dogehouse.tv)?

**Comment by okdargy** [comment]
> Can you advise if this behavior is reproducible with [next.dogehouse.tv](https://next.dogehouse.tv)?

No, it is not reproducible on [next.dogehouse.tv](https://next.dogehouse.tv)

**Comment by kndwin** [comment]
Given that there's a general move towards the next Next.js platform (#1969) I'm guessing this bug might not be picked up.

**Comment by BronzW** [comment]
Resolving bugs in the old version is meaningless.
