### ISSUE TITLE
New Version Bug: Scrolling inside room frame also scrolls the dogehouse logo

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#2011]
**Describe the bug**
When I joined a room, I scrolled inside of the frame which lists the listeners and speakers. After a certain point it also scrolls the dogehouse logo.

**To Reproduce**
1. Go to 'a room'
3. Scroll down in 'the frame of people'
4. See dogehouse logo scroll.

**Expected behavior**
The logo to be fixed

**Screenshots**

**What device are you on?**
Recent version of Google Chrome for Windows.

**Additional context**

**Comment by amitojsingh366** [comment]
this seems to be fixed now, ben was experimenting with global flex then ended up causing this. im closing this, if it still occurs comment below
