### ISSUE TITLE
New Version Bug: Chat area becomes fullscreen if firefox sidebar is on.

### ISSUE THREAD

**Issue by Tr4nt420** [benawad/dogehouse#2014]
**Describe the bug**
The chat area will become fullscreen if I turn on my firefox sidebar, and everything will be back to normal if it's off

**To Reproduce**
1. Go to 'Any DogeHouse room'
2. Click on 'Chat icon -> Go to Firefox

 Menu bar -> View -> Sidebar -> Bookmark or History or Synced tab'

**Expected behavior**
The chat room will become fullscreen

**Screenshots**

https://user-images.githubusercontent.com/48475991/114686620-2be62100-9d3d-11eb-88a9-1ff2bbf6a900.mp4

**What device are you on?**
Latitude D620
1280x800

**Comment by BronzW** [comment]
Thanks for the issue, but this is the expected behavior as the website is responsive and using things like bookmarks in Firefox will cause the view port to become smaller and change itself to fit it in a user-friendly way.

**Comment by Tr4nt420** [comment]
> Thanks for the issue, but this is the expected behavior as the website is responsive and using things like bookmarks in Firefox will cause the view port to become smaller and change itself to fit it in a user-friendly way.

So, what you're saying is the website thought that im using a mobile device?

**Comment by BronzW** [comment]
Yes, and being on a smaller screen like a laptop from 1998 will also cause this to happen. Putting the chat to the side like any big screen would would not be possible without making other parts of the UI and the chat itself very, very small so that's why it takes up the whole screen and is minimizable and maximizable when on a small screen.

**Comment by goldyydev** [comment]
Hey, what version of Firefox is this this?

**Comment by Tr4nt420** [comment]
> Hey, what version of Firefox is this this?

Version 87.0 (64 bit)
Mozilla Firefox for Ubuntu
canonical - 1.0

**Comment by goldyydev** [comment]
this is something for @ajmnz to decide as it is a part of the grid sizes.

**Comment by ajmnz** [comment]
> this is something for @ajmnz to decide as it is a part of the grid sizes.

It says video is corrupt, but it's expected behavior for what @BronzW said
