### ISSUE TITLE
Ability to remove followers

### ISSUE THREAD

**Issue by ovandenbosch** [benawad/dogehouse#2015]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to remove followers if you would like.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by okdargy** [comment]
How would this enhancement be helpful? I can't really think of a situation where you'll need to remove your followers.

**Comment by ovandenbosch** [comment]
Idk, if you want to make your account more private. An alternative would maybe be able to make private accounts with request to follow
