### ISSUE TITLE
Settings dropdown not flexible for translations

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#2018]
![image](https://user-images.githubusercontent.com/50546858/114757890-abcfb380-9d5c-11eb-9e21-3a57e884bf49.png)

**Comment by amitojsingh366** [comment]
i see...
<img width="838" alt="Screen Shot 2021-04-15 at 12 24 47 PM" src="https://user-images.githubusercontent.com/35400192/114846673-95216f00-9de5-11eb-8ebe-31e531e89734.png">
