### ISSUE TITLE
will need ssr eventually, probably worth converting to next.js

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#202]

**Comment by NadirAbbasAlegnor** [comment]
@benawad is this open to work or are you working on this?

**Comment by benawad** [comment]
I'm not working on this right now (and won't for a while), you can give it a try if you want but I think it will be tricky

**Comment by NadirAbbasAlegnor** [comment]
I will give it a try.

**Comment by overlisted** [comment]
Why? Apps that are mostly hidden behind auth usually don't need SSR

**Comment by benawad** [comment]
DogeHouse doesn't need it now, but in the future more things will be public

**Comment by overlisted** [comment]
Oh, an "anonymous" mode can indeed be added.

**Comment by yummyweb** [comment]
I believe this should be closed now that this is in motion. What do you say, @benawad?
