### ISSUE TITLE
Storybook has compiling issues 

### ISSUE THREAD

**Issue by Mvrs** [benawad/dogehouse#2024]
**Describe the bug**
Compiling when running storybook. TypeError: `this.getOptions is not a function`

**To Reproduce**
1. yarn `storybook`
2. See error

**Expected behavior**
Compiled Successfully (link to localhost storybook server)
webpack built preview e594b8865722d9c8f801 in 25422ms

**Screenshots**
![error-patch-1](https://user-images.githubusercontent.com/5723692/114800472-a5d2d600-9d4e-11eb-8ffa-e60dee505302.png)

**What device are you on?**
HP-Spectre-x360 2017
Memory: **15.5gb**
Processor: **Intel® Core™ i7-7500U CPU @ 2.70GHz × 4**
Graphics: **Mesa Intel® HD Graphics 620 (KBL GT2)**
OS Name: **Ubuntu 20.04.2 LTS**
GNOME Version: **3.36.8**

**Comment by Mvrs** [comment]
note: I'm running storybook **v6.2.7** 😅

**Comment by ajhalili2006** [comment]
Hi @Mvrs! I can't see the error message clearly. Can you please either reproduce the issue while recording with Asciinema or dump the error logs from your terminal into GitHub Gists?

**Comment by Mvrs** [comment]
@AndreiJirohHaliliDev2006 sure thing!

**Comment by BronzW** [comment]
Running `git pull origin staging` & `yarn` & `yarn staging` will now fix this issue by https://github.com/benawad/dogehouse/commit/3f36c8c07b408679e846496c10089dbd44f01df1
