### ISSUE TITLE
Dogehouse logo not showing properly

### ISSUE THREAD

**Issue by DimoDimchev** [benawad/dogehouse#2025]
The Dogehouse logo in the new beta doesn't show up properly.

I jumped on the beta first thing this morning on my MacBook Air 2020 (Intel Chip), and I saw that the logo appeared dark, when it should be white.

Check the top left of the screenshot to see the logo.

<img width="1171" alt="Screenshot 2021-04-15 at 7 56 21 AM" src="https://user-images.githubusercontent.com/38102582/114816174-4ca38a80-9dc0-11eb-97ad-388c3805dcb8.png">

**Comment by Szegoo** [comment]
I will try to fix it :D
