### ISSUE TITLE
New Version Bug: Electron app's title bar makes it scroll weirdly

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2027]
**Describe the bug**
The custom title bar makes the electron app scroll. I'm the one who added this so i know exactly what causes this. Adding the `margin-top` property on the UI does. *(see video below)*

**To Reproduce**
1. Go to 'next.dogehouse.tv' on the app
2. Scroll and see

**Expected behavior**
Shouldn't cause scrolling/should only scroll the room cards

**Screenshots**

https://user-images.githubusercontent.com/35400192/114820020-056cc800-9dc7-11eb-8c32-a5cafbeeb352.mp4

**What device are you on?**
Win 10, baklava: 1.0.55

**Additional context**
Need some css pro to solve this, the margin top property im talking about and showing in the video is found at `kibbeh/src/styles/electron-header.css`

**Comment by isaxk** [comment]
I experienced this even on the website #2011

**Comment by amitojsingh366** [comment]
> I experienced this even on the website #2011

yes, that seems to be fixed now. ben was experimenting with something that caused it. however this bug on the app is all my doing and idk how to fix it

**Comment by victivus** [comment]
This might be a solution :

    html {
      height: fit-content;
    }
    
![image](https://user-images.githubusercontent.com/60193302/115106830-07ad5e80-9f4e-11eb-9d19-06c137a0677d.png)

**Comment by MrDogeBro** [comment]
I think I have a solution for this problem — working on it right now and will PR the fix once I get it in
