### ISSUE TITLE
Change focused style of buttons

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2032]
I really don't enjoy looking at the default button outline when in focus, I'd like to either remove it completely and add some other kind of visual clue that you actually clicked on it or restyle the outline. Right now it looks like this and I think it's pretty ugly: 

![image](https://user-images.githubusercontent.com/73597777/114841176-9bfdb100-9de8-11eb-92d0-e616503fde6a.png)

**Comment by amitojsingh366** [comment]
maybe we could replace those with [tailwind css rings](https://tailwindcss.com/docs/ring-width)

**Comment by goldyydev** [comment]
@ajmnz

**Comment by goldyydev** [comment]
This is a bug (that also applies to Kibbeh)

Someone needs to add outline-none the button component.

**Comment by amitojsingh366** [comment]
> This is a bug (that also applies to Kibbeh)
> 
> Someone needs to add outline-none the button component.

i think we need some sort of outline for aria. correct me if i'm wrong

**Comment by ajmnz** [comment]
@benawad we need to address this. Browser default focus is nasty

**Comment by aaryamvn** [comment]
I have noticed this myself, are we using tailwind? If so we could add the ring classes and customize it. If we are using plain css it isn't a huge deal; we can add outline properties and things

**Comment by ghost** [comment]
I'd really like to do something about this but I can't seem to run the frontend locally, I followed all the guidelines, I'm getting an error that it can't find 'dogehouse/kibbeh/.next/build-manifest.json'. Maybe there's something wrong with my machine, I'm using wsl2 maybe there's a problem with that, I could just try editing the 'Button.tsx' file but I'm not going to know if that even worked without looking at it

**Comment by ghost** [comment]
Also this appears every time I run `yarn staging` inside kibbeh, it only appears once when I run it but not on refresh: 
![image](https://user-images.githubusercontent.com/73597777/115044875-fed57200-9ee6-11eb-93e8-b65fb9f01e74.png)
Some kinda webpack error

**Comment by benawad** [comment]
https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/

**Comment by ajmnz** [comment]
> https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/

> Style the element itself. You can remove the outline as long as you style the focused element differently (using a combination of color, background-color, border or text-decoration: underline for example).

^ Exactly what we're wanting to do

**Comment by amitojsingh366** [comment]
> maybe we could replace those with [tailwind css rings](https://tailwindcss.com/docs/ring-width)
 
@ajmnz @benawad  ^
