### ISSUE TITLE
Npm i crashes in dogehouse repo, fine everywhere else :(

### ISSUE THREAD

**Issue by KittyBorgX** [benawad/dogehouse#2058]
pm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path 
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/krishnaramasimha/Documents/projects/dogehouse/dogehouse/kofta/node_modules/@babel/core/node_modules/semver/bin/semver'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krishnaramasimha/.npm/_logs/2021-04-16T11_32_28_848Z-debug.log

**Comment by crispyaus** [comment]
Try `npm cache clean`

**Comment by goldyydev** [comment]
we do not use npm, we use yarn.

also, kofta is deprecated therefore questions about it will not be answered.
