### ISSUE TITLE
UX:View Profile on separate page

### ISSUE THREAD

**Issue by Alibek10599** [benawad/dogehouse#2061]
**Is your feature request related to a problem? Please describe.**
For example I can not view profile of users which I have not subscribed

**Describe the solution you'd like**
It is more UX feature imho) 

**Describe alternatives you've considered**
Would be convenient to observe those user profiles who were not subscribed to view on full screen page like the profile page of users

**Additional context**
Kind regards. Sorry if I misconsidered something and fear=

**Comment by goldyydev** [comment]
@ajmnz

**Comment by ajmnz** [comment]
User page is being developed (#2022), then you'll be able to see anyone's profile regardless if you are following them or not
