### ISSUE TITLE
Old Version Button Does Not Work

### ISSUE THREAD

**Issue by chasecrampton** [benawad/dogehouse#2062]
**Describe the bug**
If you try to click the "Use Old Version" button nothing happens.

**To Reproduce**
1. Go To DogeHouse
2. Click on your profile
3. Click "Use Old Design"

**Expected behavior**
Old version should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/56277964/115032341-0d3b7380-9e7e-11eb-8ffc-3a6223d56860.png)

**What device are you on?**
Windows 10 Pro

**Comment by samarmohan** [comment]
Old version is gone.
