### ISSUE TITLE
Theme colour is now incorrect

### ISSUE THREAD

**Issue by MMK21Hub** [benawad/dogehouse#2068]
**Describe the bug**
When Dogehouse is installed as a PWA, the theme colour is still the colour from Kofta.

**To Reproduce**
1. Firefox Mobile
2. "Add to Home Screen'
3. Open DogeHouse as a PWA
4. Incorrect colour on the top of your screen

**Expected behavior**
The new accent/theme colour (Doge Blood iirc) would be there

**Screenshots**

**What device are you on?**

Android 10

**Additional context**
I had installed Dogehouse back when Kofta was the default site.

**Comment by TheOtterlord** [comment]
> Additional context
> I had installed Dogehouse back when Kofta was the default site.

Have you reinstalled the PWA since kibbeh was made the main site?

**Comment by goldyydev** [comment]
Shouldn't matter, we're not setting the theme colour up.

**Comment by MMK21Hub** [comment]
> Have you reinstalled the PWA since kibbeh was made the main site?

No, but as far as I can tell Kibbeh doesn't have a `manifest.json` yet?

**Comment by ghost** [comment]
It does not.

**Comment by MMK21Hub** [comment]
Closing due to https://www.youtube.com/watch?v=I8PkQgPiSq8
