### ISSUE TITLE
Invalid room still registers user

### ISSUE THREAD

**Issue by aaryamvn** [benawad/dogehouse#2070]
When I click a room that doesnt exist anymore, it still displays my name in the room participants:

![image](https://user-images.githubusercontent.com/67153585/115053981-567ed800-9efd-11eb-9c15-d7477d83e089.png)

as you can see in the image, I clicked the bot room thingy and initially, it only had "Dhruvs Bot", but despite being an invalid room it still presented my name.

**Comment by dhruv-programmes** [comment]
was prob with twitter outh api

**Comment by dhruv-programmes** [comment]
You may close it now as its fixed

**Comment by aaryamvn** [comment]
ah ok cool
