### ISSUE TITLE
modify language feature

### ISSUE THREAD

**Issue by julesntare** [benawad/dogehouse#2072]
**Describe the bug**
Language translate option needs to respond to all contents

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Language menu'
2. Click on 'let's say francais'
3. check if the title 'Your Feed', 'Upcoming rooms', search placeholder labelled 'Search for rooms, users or categories' do change for any language translated
4. See an error

**Expected behaviour**
I expected those contents to change accordingly

**Screenshots**
![Capture](https://user-images.githubusercontent.com/40698224/115061660-c08d8200-9ee9-11eb-90e6-415d17bcd786.PNG)

**Comment by TheOtterlord** [comment]
This is due to some strings in the [translation file](https://github.com/benawad/dogehouse/blob/staging/kibbeh/public/locales/fr/translation.json) not yet being translated. If you would like to add/improve any translations, please edit the file and create a pull request
