### ISSUE TITLE
Add Chat feature when people can't able to access their microphone and if they don't want to talk.

### ISSUE THREAD

**Issue by priyanshuSharma-WebDev** [benawad/dogehouse#21]
Well I know this is discord thing but it really helpful.

**Comment by rampa2510** [comment]
This is a clubhouse clone not a discord one no need for a chat box

**Comment by priyanshuSharma-WebDev** [comment]
Yeah I know, Well it's funny but I can't able access my microphone that's why I really missed chat feature.

**Comment by samarmohan** [comment]
This is smart. I was about to create an issue about this but this is already there!
