### ISSUE TITLE
When in a room on mobile the dashboard is partially blocked by the current room you are in

### ISSUE THREAD

**Issue by Arezea** [benawad/dogehouse#2103]
**Describe the bug**
When in a room on mobile the dashboard is partially blocked by the current room you are in
**To Reproduce**
1. Go to Dashboard
2. Make sure you are in a room
3. Go to chrome dev tools and make the width and height 483 x 300
4. See overlapping
![Screen Shot 2021-04-17 at 19 05 45](https://user-images.githubusercontent.com/82657415/115122649-f184ba00-9fb0-11eb-99fd-772470a5b300.png)

**Expected behavior**

**Comment by dk-raw** [comment]
I don't think 483x300 is a common resolution. 
![image](https://user-images.githubusercontent.com/68110106/115122825-affd0a80-9fc2-11eb-8ce4-31e762a6c666.png)
It still works in vertical mode
![image](https://user-images.githubusercontent.com/68110106/115122844-cefb9c80-9fc2-11eb-84dd-3beea397cac3.png)

**Comment by Arezea** [comment]
It doesjt work on alot pf resolutions if you keep going down

**Comment by dk-raw** [comment]
I mean 483x300 is not common resolution at all. Phones are like 400x800 usually.

**Comment by BronzW** [comment]
People usually don't have squares for their phones. Rectangular viewports doesn't cause this issue, as shown by @dk-raw

**Comment by okdargy** [comment]
> People usually don't have squares for their phones. Rectangular viewports doesn't cause this issue, as shown by @dk-raw

_unless you have a blackberry passport_

**Comment by BronzW** [comment]
If you have a blackberry passport then respect to you man
