### ISSUE TITLE
Unexpected behavior when refreshing page after changing username

### ISSUE THREAD

**Issue by maximgeller** [benawad/dogehouse#2104]
**Describe the bug**
When I change my username and refresh the page, it can no longer find my profile since the username is different and the url is based off of it. It would be helpful to make changing the username cause a page reload (or similar) with the correct username. 
**To Reproduce**
1. Click on edit profile on your page
2. change your username and click save
3. refresh the page

**Expected behavior**
I would like my new profile page with the right username to appear

**What device are you on?**
Brave browser, Windows 10

**Comment by dk-raw** [comment]
When changing the username, there is no need to refresh the page. Just continue using Doge House.
