### ISSUE TITLE
Search Bar Doesn't Seem To Work

### ISSUE THREAD

**Issue by Arezea** [benawad/dogehouse#2106]
**Describe the bug**
The new search bar doesn't seem to work since it only returns on results
**To Reproduce**
1. Go to dogehouse
2. Click on the search bar 
3. Search benbot which is a user who exists

**Expected behavior**
Dropdown of user, rooms, categories
**Screenshot**
![Screen Shot 2021-04-17 at 22 52 35](https://user-images.githubusercontent.com/82657415/115127615-b34ac300-9fcf-11eb-848d-bf171c260b58.png)

**Screenshot 2**

![Screen Shot 2021-04-17 at 22 54 01 1](https://user-images.githubusercontent.com/82657415/115127628-d6757280-9fcf-11eb-8a7c-3c2d2ee1978b.png)

**Device**

Mac 

**Browser**

Chrome

**Account Name**

@Areze

**Comment by BronzW** [comment]
You need to prefix it with @

**Comment by BronzW** [comment]
![image](https://user-images.githubusercontent.com/50546858/115127791-ac28b280-9fd9-11eb-854c-b56aee9e0d56.png)
