### ISSUE TITLE
Search icon not positioned properly on mobile

### ISSUE THREAD

**Issue by DimoDimchev** [benawad/dogehouse#2129]
**Description**
The magnifying glass icon on the search bar is not positioned properly on the mobile version of the site.

**To recreate**
Open dogehouse.tv on Safari via iPhone and log into your account via GitHub

**Screenshot**
![image](https://user-images.githubusercontent.com/38102582/115162330-908ddc80-a0ab-11eb-900b-831ea6c8a66f.jpeg)

**Comment by benawad** [comment]
fixed
