### ISSUE TITLE
Can't open Mac app

### ISSUE THREAD

**Issue by DimoDimchev** [benawad/dogehouse#2134]
**Description**
Upon opening the MacOS app I get a pop up saying I have no permission to open the app, even after giving myself read and write access within the app.

**How to replicate**
Download the latest release and run it on MacOS 11.2.3

**Screenshot**
<img width="541" alt="Screenshot 2021-04-19 at 7 37 48 AM" src="https://user-images.githubusercontent.com/38102582/115182524-c601ec80-a0e2-11eb-8804-c5f5de92f273.png">

**Comment by amitojsingh366** [comment]
Seems like an issue with your local setup. MacOS thinks that you don't have access to DogeHouse, so try asking whoever has admin rights over your computer?

**Comment by DimoDimchev** [comment]
I am the only account associated with this computer. No admin other than me

**Comment by amitojsingh366** [comment]
@DimoDimchev can you give more details about your machine?

**Comment by ajmnz** [comment]
Try pasting this in your terminal: `sudo chmod -R 755 path/to/DogeHouse.app`. Change the path to your path to the DogeHouse.app.

**Comment by DimoDimchev** [comment]
@amitojsingh366 MacBook Air 2020 (Intel i5 chip)

**Comment by DimoDimchev** [comment]
@ajmnz I did that and after that when I tried opening the app I got a pop-up saying the app is damaged and can't be opened. 
<img width="258" alt="Screenshot 2021-04-19 at 9 42 57 AM" src="https://user-images.githubusercontent.com/38102582/115192542-a0c9aa00-a0f3-11eb-8cda-601dadf3adfd.png">

**Comment by amitojsingh366** [comment]
@DimoDimchev can you try a re-install

**Comment by DimoDimchev** [comment]
@amitojsingh366 I resolved the problem. I tried downloading the .dmg directly from the releases and that seemed to work. Thanks and sorry for taking up your time!

**Comment by amitojsingh366** [comment]
@DimoDimchev wait so where did you get the previous release that didn't work from?

**Comment by DimoDimchev** [comment]
@amitojsingh366 There is a .zip file in the releases too. I hadn't noticed the .dmg previously and downloaded the zipped one straight away.

**Comment by amitojsingh366** [comment]
@DimoDimchev oh the zip, those are just included for autoupdates, please don't mind those. the only files you should worry about are: `.exe`, `.dmg`, `.AppImage` and `.deb`
