### ISSUE TITLE
Language sorting and labels

### ISSUE THREAD

**Issue by wes337** [benawad/dogehouse#2136]
**Describe the bug**
The languages are sorted by their language code. The labels are translated. This makes it difficult to navigate through the list and find your language. The label shouldn't have the emoji flag inside of it _(this could be another object key)_.

Open the list of languages in the language selector and try to find any language other than English.

**Screenshots**
![image](https://user-images.githubusercontent.com/9464690/115190030-1764a880-a0f0-11eb-8243-5b1bc63c7bac.png)

**Comment by ajmnz** [comment]
How would you tackle this? Ordering them by their label on alphabetical order?

**Comment by wes337** [comment]
Use translated values for the labels, then sort the array in the component it's used in. Right now each language inside the `LanguageSelector` component is only in it's own language, and it's unsorted.

I can open a PR for this
