### ISSUE TITLE
Kibbeh: Scheduled rooms are listed awkwardly

### ISSUE THREAD

**Issue by neinkopp** [benawad/dogehouse#2139]
**Describe the bug**
The elements of the scheduled-rooms-list are pretty far apart.
Fig. 1: Why is there a bottom margin of 24 on the separate room items?
Fig. 2: After "Load More", the bottom margins of the previous rooms are reducing to 4 units.

**To Reproduce**
1. Go to https://dogehouse.tv/scheduled-rooms
2. You should see the very big bottom margins right away
3. Scroll down and click on "Load more" to see the second bug

**Expected behavior**
The bottom margin of each item should be reduced to 4 units

**Screenshots**
Fig. 1
![image](https://user-images.githubusercontent.com/66413542/115213941-54d23180-a102-11eb-8124-fee91ec855e8.png)
Fig. 2
![image](https://user-images.githubusercontent.com/66413542/115214466-d4600080-a102-11eb-9a78-fa624713c93d.png)

**What device are you on?**

- Brave 1.23.71 
- Chromium: 90.0.4430.72 (Official Build) (64-bit)
- Revision b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
- OS: Windows 10 OS Version 2004 (Build 19041.84)
- JavaScript: V8 9.0.257.17
- User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

**Comment by MeztliRA** [comment]
tried to reproduced, it work perfectly fine for me.

**Comment by neinkopp** [comment]
Strange... tried it in a private tab, same issue. Which browser do you use?

**Comment by MeztliRA** [comment]
> Strange... tried it in a private tab, same issue. Which browser do you use?

vivaldi, it use chromium too

**Comment by MeztliRA** [comment]
@neinkopp managed to reproduced it
![Screenshot from 2021-04-19 17-28-38](https://user-images.githubusercontent.com/78863518/115222259-bf03ca00-a134-11eb-846b-416689be38bd.png)

**Comment by neinkopp** [comment]
> @neinkopp managed to reproduced it
> ![Screenshot from 2021-04-19 17-28-38](https://user-images.githubusercontent.com/78863518/115222259-bf03ca00-a134-11eb-846b-416689be38bd.png)

That's good to hear.
