### ISSUE TITLE
Unexpected error when visiting a scheduled room link on mobile

### ISSUE THREAD

**Issue by dmfigol** [benawad/dogehouse#2144]
**Describe the bug**
when I click on a link to the scheduled room from my mobile, I get unexpected error.
Tested on iPhone 8 with Safari and Chrome

**To Reproduce**
1. Go to a scheduled room from mobile, e.g. https://dogehouse.tv/scheduled-room/928ddd13-96fc-46d2-9729-8cb4f0837c3f
2. See error

**Expected behavior**
No error

**Screenshots**
https://cdn.discordapp.com/attachments/810571477770174506/833646608783900672/image0.png

**What device are you on?**
iPhone 8

**Additional context**
The link seems to be working from different desktop browsers just fine

**Comment by dk-raw** [comment]
This happens when opening devtools as well.

**Comment by BronzW** [comment]
Well not because of devtools, more of the viewport size I think.

**Comment by BronzW** [comment]
I think this might happen because you are not logged in when clicking on a link instead of going through this website. I suspect that the error shows up because it tries to fetch something that isn't there because you haven't logged in.

**Comment by kukosek** [comment]
![image](https://user-images.githubusercontent.com/16265013/115287492-a0abc780-a150-11eb-9475-a660697d1703.png)
Hey this just randomly popped up. So I opened devtools and some errors are there. But I still heard voice.

**Comment by kukosek** [comment]
Its happened again, when I was scrolling chat
