### ISSUE TITLE
New Version Bug: Show/Hide Button for no purpose

### ISSUE THREAD

**Issue by OrhanOzkercin** [benawad/dogehouse#2147]
**Describe the bug**
I'm pretty new to this app but there is a button that does nothing at least in some scenarios.

**Screenshots**
![bug](https://user-images.githubusercontent.com/25130814/115252906-911e8580-a134-11eb-8f15-08085ce8775a.gif)

**What device are you on?**
Windows, Chrome

**Comment by dk-raw** [comment]
I believe that someone is currently working on this.

**Comment by benawad** [comment]
this is deploying as we speak
