### ISSUE TITLE
Add a PWA support

### ISSUE THREAD

**Issue by etteryand0** [benawad/dogehouse#2150]
**Is your feature request related to a problem? Please describe.**
It could be simplier (1 click to doge) and prettier (no link bar at the top) to use dogehouse as a PWA on mobile/desktop. 

**Describe the solution you'd like**
I want to be able to add PWA to my mobile/desktop from browser just like on twitter

**Describe alternatives you've considered**
Or you could create React Native WebView app and then build it to use dogehouse from mobile

**Comment by ghost** [comment]
I'm gonna try to work on this
