### ISSUE TITLE
Search box clears when switching tabs

### ISSUE THREAD

**Issue by jackdelahunt** [benawad/dogehouse#2162]
**Describe the bug**
When adding text to the search box and switching tabs in the browoser clears the text in the search box

**To Reproduce**
1. Go to main page (works on any page)
2. Click on search box and enter text
3. Open new tab and switch to it
4. Go back to doge house tab
5. See no text in search box

**Expected behavior**
When switching back to the doge house page the text remains in the search box

**What device are you on?**
Fedora Linux,
Chrome

**Comment by ghost** [comment]
Can reproduce, Vivaldi 3.7 on Windows 10
![image](https://user-images.githubusercontent.com/57069715/115275378-02b10080-a142-11eb-875d-ab141e295eec.png)

**Comment by shivaluma** [comment]
I think this occurs because of the Downshift library.
As mentioned in this issue: [Downshift#574](https://github.com/downshift-js/downshift/issues/574)
