### ISSUE TITLE
Add a 'Kill Connection' button in room page

### ISSUE THREAD

**Issue by babakfp** [benawad/dogehouse#2166]
**Is your feature request related to a problem?**
Add a kill button for the room. Let's say I have 2 tabs open on Chrome. I want to stop the room connection and go and watch the video on Youtube.

**Describe the solution you'd like**
Add a 'Kill Connection' button on the right side of the 'Leave' button.
![Screenshot 2021-04-19 113517](https://user-images.githubusercontent.com/44144724/115286064-80095080-a103-11eb-8fae-585ec9dee555.png)

**Describe alternatives you've considered**
I can close the tab.

**Additional context**
It isn't a big deal for me, but it's just good to have it.

**Comment by babakfp** [comment]
A mute button too?

**Comment by amitojsingh366** [comment]
i dont see the point of this?

**Comment by babakfp** [comment]
You play a video on Youtube and you can pause and mute it. You play music and you can pause it whenever you want. You are watching the TV and you have a mute button. I think a mute button is necessary. I named it 'Kill Connection' because the user may be mute it for a long time and it cost mony. So it's good to have 2 buttons. One for muting and one for killing the connection. if it was muted for a long time, then the connection can get disconnected automatically.

**Comment by amitojsingh366** [comment]
@babakfp oh you mean something like discord's deafen? if yes im already working on it, pr soon.

**Comment by babakfp** [comment]
@amitojsingh366 
Don't know a lot about Discord.

**Comment by amitojsingh366** [comment]
basically, if you toggle deafen no one can hear you and you cant hear them aswell

**Comment by babakfp** [comment]
I don't know about that. I just explained what is needed so...
