### ISSUE TITLE
Unnecessary responsive breakpoint because half of the page is empty

### ISSUE THREAD

**Issue by babakfp** [benawad/dogehouse#2167]
**Describe the bug**
I have a 15.6inc laptop and in 110% zoom, I lose the sidebar (in the room page). Somehow I did change the page zoom (from 100% to 110%) without knowing it, so I was wondering how the heck the sidebar disappeared!!.
![Screenshot 2021-04-19 115441](https://user-images.githubusercontent.com/44144724/115289082-0ffcc980-a107-11eb-8c36-8016f8297325.png)

**To Reproduce**
Go to a room and zoom x much and you will see that sidebar disappears.

**Expected behavior**
Applying a smaller breakpoint because after disappears, there is plenty of empty space in the right and left of the page. For example: if the current breakpoint is 1000, make it 800.

**What device are you on?**
- ASSUS Laptop 15.6inc
- Chrome Version 89.0.4389.128 (Official Build) (64-bit)

**Comment by amitojsingh366** [comment]
this is intended responsive layout behavior, just make your browser full screen/increase size and you will see it

**Comment by babakfp** [comment]
Well, it isn't a good UX. I was searching for a button (to bring it back) and... nothing. in 110% zoom, the sidebar disappears and it isn't even necessary. We do responsive when it's necessary not when half of the page is empty. If no feedback is needed, then just close the issues section and make everyone's life easier.
I'm not complaining because of a small issue, I'm complaining because you rushed and smashed the close button.

**Comment by amitojsingh366** [comment]
@babakfp i am sorry if you felt that your issue was closed unreasonably and i apologize for me not giving more reason for it. however what the issue's title and description say are intentional, i will re-open the issue for you and then you can update the title and description accordingly. im really sorry again.

**Comment by babakfp** [comment]
@amitojsingh366 
Well, I changed the title and the description.
Right now for some reason, I can't log in, to the website. After clicking on the GitHub login button, it redirects me to the `https://dogehouse.tv/dash` address, and after that nothing happens.
