### ISSUE TITLE
Add a close icon to the chat component (in full screen mode)

### ISSUE THREAD

**Issue by babakfp** [benawad/dogehouse#2168]
**Describe the bug**
In the first look, I didn't understand that the header of the component is a button to close the chat.
![Screenshot 2021-04-19 115008](https://user-images.githubusercontent.com/44144724/115289592-9addc400-a107-11eb-8506-c8bf78c12fe5.png)

**To Reproduce**
Remove the chat component from the right sidebar (I don't know how I did it). Now click on the button:
![Screenshot 2021-04-19 115441](https://user-images.githubusercontent.com/44144724/115290086-15a6df00-a108-11eb-8c97-f6a1c4fcfa53.png)

**Comment by amitojsingh366** [comment]
i agree with this. its hard to grasp at first, especially on mobile

**Comment by dk-raw** [comment]
You press on "Chat" to close it

**Comment by amitojsingh366** [comment]
> You press on "Chat" to close it

yes ik but someone who doesn't will just be stuck there

**Comment by nadirabbas** [comment]
this has been fixed
