### ISSUE TITLE
[Settings | Desktop] Components Implementation

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#2174]
# Components Implementation

### Settings | Desktop

New components available for anyone that wants to contribute to the new design (`kibbeh`). Make sure to read the guidelines at the bottom of the issue.

---

### New components

- [x] SettingsWrapper - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9018%3A9349
    - Requires none ✅
    - Container for each page in settings (`padding: 20px` or `.p-4`)
- [x] BaseSettingsItem - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A69
    - Requires none ✅
    - Container/Wrapper for some settings items, size can (and must) vary
- [x] ChangeAvatarCard - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9018%3A9352
    - Requires BaseSettingsItem, UserAvatar, Button ✅
- [x] ChangeBannerCard - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9018%3A9354
    - Requires Button ✅
- [x] NativeCheckbox - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A0
    - Requires none ✅
    - The on/off functionality is important
- [x] NativeRadio - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9018%3A9356
    - Requires none ✅
    - Handle children (text) as you think is best
- [x] ErrorButtonItem - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A5
    - Requires  BaseSettingsItem, Button ✅
- [x] VolumeIndicator - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A58
    - Requires none ✅
    - It should react to some value (convert it to percentage maybe)
- [x] UserWideButton - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A3
    - Requires UserAvatar, Button ✅
- [x] SettingsItemButton - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A87
    - Requires  BaseSettingsItem, Button ✅
- [x] KeybindCard - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9055%3A18
    - Requires BaseSettingsItem ✅
    - Should match current behavior with regard to listening for user input after the keyboard icon is pressed
    - The red border appears when the listening mode is on

---

Guidelines:
- Don't add margin around the components.
- The bordered rectangle around each component in Figma is just for delimitation purposes.
- Put your component in `kibbeh/src/ui` and create a story in `kibbeh/src/stories`.
- Use tailwind for styling (see the tailwind config for theme info).
- You have to use TypeScript.
- Work on the `staging` branch.
- Please comment below if you start to work on a component, but only claim a component if you plan to work on it right away, so it doesn't block other people.
- Don't start working on a component if its dependencies aren't done.

Mockup & grid (get some context about each component): https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=9018%3A1060

> Most icons should be available under `kibbeh/src/icons`, but if the one you need isn't, ask on Discord or place a temp one with a comment pointing it out

If you have any questions ask Ben or @ ajb on [Discord](https://discord.gg/82HzQCJCDg).

**Comment by samarmohan** [comment]
I'll do BaseSettingsItem

**Comment by Mvrs** [comment]
I'll work on NativeCheckbox and Native Radio.

**Comment by Mayowa-Ojo** [comment]
I'll do `ErrorButtonItem` and `KeybindCard` once their dependencies are done.

**Comment by Angshu31** [comment]
I'll do `SettingsItemButton` once its deps are finished. And `ChangeAvatarCard`

**Comment by BronzW** [comment]
I would like to do `NativeRadio`

**Comment by Mvrs** [comment]
> I would like to do `NativeRadio`

I called it my guy 😅

**Comment by BronzW** [comment]
Well you took two components

**Comment by BronzW** [comment]
But sure it's yours

**Comment by goldyydev** [comment]
I'll take `VolumeIndicator`

**Comment by BronzW** [comment]
I'll take the `SettingsItemButton`

**Comment by sahilmob** [comment]
I'll do `ChangeBannerCard `

**Comment by AkshayJaitly** [comment]
I would like to work on UserWideButton

**Comment by goldyydev** [comment]
Most of these components should've been done already, they shouldn't take that long.

has anyone abandoned a component?

**Comment by Mayowa-Ojo** [comment]
Prerequisite components are delaying work on other components. I've been waiting for `BaseSettingsItem`

**Comment by wes337** [comment]
No takers for SettingsWrapper? Looks quite straightforward, I can do it.

**Comment by wes337** [comment]
I'm also going to take "BaseSettingsItem". It's just a container component and was claimed 3 days ago. It should not take that long imo

**Comment by Mvrs** [comment]
I'm still working on `NativeRadio` and `NativeCheckbox`. They'll be done soon 😎

**Comment by Mvrs** [comment]
@ajmnz for `NativeRadio` you want the cards to be `var(--text-primary-900)` or `var(--text-primary-800)`? It's just inconsistent with the figma preview. Every component is **800** but in figma its **900**

**Comment by AkshayJaitly** [comment]
**#2261 - UserWideButton added**

**Comment by ajmnz** [comment]
> Prerequisite components are delaying work on other components. I've been waiting for `BaseSettingsItem`

You can start now

**Comment by Mayowa-Ojo** [comment]
#2267 - `ErrorButtonItem` added

**Comment by samarmohan** [comment]
@Ongshu777, have you done ChangeAvatarCard?
And sorry for not doing BaseSettingsItem, I was busy.

**Comment by Mayowa-Ojo** [comment]
#2282 - `KeybindCard` component added

**Comment by ajmnz** [comment]
@Mvrs @Ongshu777 What's your progress? Free them up if you aren't able to work on them right away

**Comment by Mvrs** [comment]
> @Mvrs @Ongshu777 What's your progress? Free them up if you aren't able to work on them right away

Will be done by 7pm PST. I should be done well before that.

**Comment by Angshu31** [comment]
> @Mvrs @Ongshu777 What's your progress? Free them up if you aren't able to work on them right away

Yea, I'm don't have time, I'll let someone else do it.

**Comment by Mayowa-Ojo** [comment]
> > @Mvrs @Ongshu777 What's your progress? Free them up if you aren't able to work on them right away
> 
> Yea, I'm don't have time, I'll let someone else do it.

I'll do `ChangeAvatarCard` if no one has picked it up

> If anyone has picked it up please indicate cause I'm starting now

**Comment by Mayowa-Ojo** [comment]
#2298 - added `ChangeAvatarCard`

**Comment by Mvrs** [comment]
@ajmnz give me tmr 6am PST. I had a huge 5 hr bug and I'm rolling now. My bad. Last extension 🙏🏿🥲

**Comment by Mvrs** [comment]
@Mayowa-Ojo you wanna take `NativeCheckbox`? I'm too tired now 😅.

**Comment by Mvrs** [comment]
Almost done with `Checkbox` just a quick UI then it's a wrap 🥲🚀
