### ISSUE TITLE
Can hear ppl when not in a room.

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2177]
https://imgur.com/a/CS4a3KC
see vid above *(turn on audio)*

**Comment by amitojsingh366** [comment]
i found out what does it.
join a room
turn on vpn
force refresh *(ctrl/cmd+shift+r)*

https://imgur.com/a/V2JBmc0
see vid above, it shows how to do it *(again, turn audio on)*

**Comment by benawad** [comment]
are you able to do that in other rooms too?

**Comment by amitojsingh366** [comment]
> 
> 
> are you able to do that in other rooms too?

yes i just checked, i can

**Comment by amitojsingh366** [comment]
this also happened when i switched clients
