### ISSUE TITLE
The right sidebar (active room + upcoming rooms) doesn't appear on medium and small size screen.

### ISSUE THREAD

**Issue by kareemaboueid** [benawad/dogehouse#2178]
when shrinking to sm or md sizes, the sidebar goes away.

**Comment by amitojsingh366** [comment]
this is intentional as there isn't enough room to display those on sm/md screens, if you have a better way to show it feel free to suggest

**Comment by jobveldhuis** [comment]
There is more specification about this design choice in [this video](https://www.youtube.com/watch?v=Dk1gxZ_K3E0), if you were wondering. But this is a feature, intentional by design.

**Comment by charafmrah** [comment]
That's how it was designed to be, it's not a bug.
