### ISSUE TITLE
Can't install repo in windows

### ISSUE THREAD

**Issue by Hasintha-Jayasinghe** [benawad/dogehouse#218]
After cloning the repo and attempting to install the dependencies it get's stuck on 'mediasoup'

**Comment by nadirabbas** [comment]
You need to use Windows Subsystem for Linux (WSL) or a Virtual machine to run it, `mediasoup-client` can't be built on windows.

**Comment by Hasintha-Jayasinghe** [comment]
I was trying with wsl.
I tried with yarn and npm.

**Comment by JanHolger** [comment]
mediasoup-client is totally fine, as it's js/ts only. mediasoup itself requires c++ build tools. You can find the instructions in the mediasoup docs.
https://mediasoup.org/documentation/v3/mediasoup/installation/#windows

I haven't tested it myself but as they have this section in the docs i guess it should work.
