### ISSUE TITLE
View emoji name when hovering over it

### ISSUE THREAD

**Issue by Bevan0** [benawad/dogehouse#2181]
**Is your feature request related to a problem? Please describe.**
Occasionally I want to check what emoji something is in chat, but can't.

**Describe the solution you'd like**
Just have it when you hover over the emoji, it should show the name of it.

**Describe alternatives you've considered**
Looking through the emoji menu

**Additional context**

**Comment by Aksh-Bansal-dev** [comment]
I would like to fix this
