### ISSUE TITLE
a best-friend feature

### ISSUE THREAD

**Issue by juliankroes** [benawad/dogehouse#2189]
a best-friend feature like Instagram would be nice, the person marked as best-friend would have a border around their icon and be at the top of your friends list.

![Screenshot 2021-04-20 10 27 38 AM](https://user-images.githubusercontent.com/75953276/115363923-2cf6d280-a1c3-11eb-88bd-11de215e3efb.png)

**Comment by asxlvm** [comment]
That is a good idea! :D
