### ISSUE TITLE
Changing/disabling focus outlines for UI elements

### ISSUE THREAD

**Issue by neinkopp** [benawad/dogehouse#2193]
**Is your feature request related to a problem? Please describe.**
When I click and hold on a button, link or another element, the default browser focus outline shows up. For example in chromium (haven't tried it in different browsers) this is pretty annoying, because of multiple reasons:

1. The outlines are really eye-catching (this is indeed what they are supposed to do, but do not fit the design) because they consist of a black and white border.
2. It does not fit into the design of DogeHouse.
3. It partially covers some (designed) focus outlines of buttons (see screenshot 1).
4. In lists or menus, the outline is only visible at the top and bottom, which doesn't really make sense from an accessibility point of view (see screenshot 2). In general the outlines are ugly in some places.

**Describe the solution you'd like**
I would like to see these standard focus outlines disappear and instead find a better solution that fits better into the design of DogeHouse and is not so buggy. For the room participants, a more compatible solution could be found, because without the outline you see less which profile you are clicking on (screenshot 3).
In general, a uniform solution would be highly desirable.

**Describe alternatives you've considered**
You could also outline all links/elements uniformly. In the "friends" section there are no focus outlines on the links.

**Additional context**
I have heard from different people (on DogeHouse) who also do not like the default outlines.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/66413542/115383504-376e9780-a1d6-11eb-92ed-4dee22d3807c.png)
2. ![image](https://user-images.githubusercontent.com/66413542/115384227-15294980-a1d7-11eb-98a9-32f2b2436a9f.png)
3. ![image](https://user-images.githubusercontent.com/66413542/115384713-a3053480-a1d7-11eb-957a-ad2c45f5b375.png)

_info: I used "inspect" to inspect the separate elements, then right clicked on the html link/button/etc. and "force state -> :focus" in the dev tools, and then added "outline: none" to the elements to disable the default focus outline_

**Comment by dk-raw** [comment]
Duplicate.
