### ISSUE TITLE
Debug Audio CSS Bug

### ISSUE THREAD

**Issue by s3ansh33p** [benawad/dogehouse#2197]
**Describe the bug**

**To Reproduce**
1. Go to a room (with a lot of users to make it easier to test)
2. Enable Debug Audio
3. Scroll up and down
4. Observe CSS issue of clipping debug UI

**Expected behavior**
Debug UI to hide elements on scroll as seen with existing users.

**Screenshots**
https://cdn.discordapp.com/attachments/793015082141351996/834045878591160370/2021-04-20_20-38-56.mp4

**What device are you on?**
Chrome, Windows 10

**Additional context**
N/A

**Comment by amitojsingh366** [comment]
z-index issue, ill fix it...

**Comment by TheOtterlord** [comment]
![image](https://user-images.githubusercontent.com/64310361/116790004-00d42f00-aaaa-11eb-8cc3-5e12ae3f178e.png)
