### ISSUE TITLE
Youtube Sign In

### ISSUE THREAD

**Issue by IntegraterGithub** [benawad/dogehouse#2198]
I was thinking of making a "sign up with youtube" as dogehouse is centered towards creators and obviously a lot of creators are on youtube however before I start working on it, do you want a sign up with youtube?

**Comment by PuckDan** [comment]
Its basically sign up with google.

**Comment by dk-raw** [comment]
I don't think YouTube has it's own dedicated OAuth API

**Comment by dk-raw** [comment]
> Its basically sign up with google.

exactly
