### ISSUE TITLE
Home page doesn’t render on Firefox mobile

### ISSUE THREAD

**Issue by ExtraE113** [benawad/dogehouse#22]
![AD24FBE6-4C46-4A42-BA66-5AC9BDBCD9E8](https://user-images.githubusercontent.com/33768950/107789716-cd81cf80-6d06-11eb-809d-681f65f80100.png)
This is what a new user sees when loading on firefox mobile. Requesting the desktop site fixes this. 

iPhone 8
iOS 14.3
Firefox Mobile Daylight 31.0

**Comment by ExtraE113** [comment]
Some further testing reveals that no pages render without requesting the desktop sitr

**Comment by jinrehacek** [comment]
Maybe it's iOS only problem? Because it works fine on Firefox Android 9, MIUI 12, Xiaomi Redmi Note 8T.

**Comment by benawad** [comment]
try it without the slash at the end and see if that is the problem

**Comment by benawad** [comment]
could you see what is in your console

**Comment by ExtraE113** [comment]
The console isn't available on firefox mobile for iOS.

**Comment by chribjel** [comment]
I opened the console in Edge for android, and got this error:
![image](https://user-images.githubusercontent.com/56649743/108201629-6312ca00-7120-11eb-81ee-176caa87e50a.png)

It works if i request the desktop website, although that is a bad experience on mobile.

**Comment by ExtraE113** [comment]
This appears to be fixed? Can someone else confirm? If so I’ll close it.

**Comment by chribjel** [comment]
> This appears to be fixed? Can someone else confirm? If so I’ll close it.

Yes this is fixed for me at least! :) (Edge for Android)
