### ISSUE TITLE
Switching between old audio and new audio

### ISSUE THREAD

**Issue by asxlvm** [benawad/dogehouse#2205]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, I want the old sound effects back because personally, these ones sound like from a lullaby rather than from an app.

**Describe the solution you'd like**
There would be a new option in Audio Settings to switch between the new and old audio, the new being defaulted.

**Describe alternatives you've considered**
Switching to the old audio entirely but some people like the new audio.

**Additional context**
None.

**Comment by dk-raw** [comment]
Ben decided to let the community decide.
