### ISSUE TITLE
Account for laptops with lower resolution

### ISSUE THREAD

**Issue by Mayowa-Ojo** [benawad/dogehouse#2207]
**Is your feature request related to a problem? Please describe.**
The current responsive screen options don't account for laptops with smaller resolution (e.g w: 1336).

**Describe the solution you'd like**
`1336` should be the minimum width as it can still take 3 cols and it doesn't make much sense to see tablet view on a laptop simply because it has lower resolution.

**Describe alternatives you've considered**

**Additional context**
This behaviour was observed on a 15" PC with `1336 x 768` resolution.

**Comment by samarmohan** [comment]
You should pr this, if you don’t want to, I’ll do it tomorrow

**Comment by Mayowa-Ojo** [comment]
Alright. I'll make a PR
