### ISSUE TITLE
chat freaks out

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2224]
https://user-images.githubusercontent.com/35400192/115548025-a79d1c00-a2af-11eb-85d9-b6573663dfd0.mp4

**Comment by asxlvm** [comment]
Also happened to me.
Android 10
Brave Browser (1.22.71)

**Comment by asxlvm** [comment]
@amitojsingh366 I also got it recorded now

https://user-images.githubusercontent.com/81298611/115554578-e67ea200-a2ae-11eb-9a42-7fc387116640.mp4

**Comment by asxlvm** [comment]
I maybe know why bugs like this happen, when you're not typing, the scrollbar for chat doesn't appear but when you type it does, so it shrinks the message, vis.;
![IMG_20210421_144206](https://user-images.githubusercontent.com/81298611/115555561-f21e9880-a2af-11eb-9915-854c49d4b2f4.jpg)
![IMG_20210421_144217](https://user-images.githubusercontent.com/81298611/115555575-f3e85c00-a2af-11eb-9644-694e0d8c8d7a.jpg)

**Comment by asxlvm** [comment]
https://user-images.githubusercontent.com/81298611/115555169-7fadb880-a2af-11eb-9949-5e107606f6f1.mp4

Another version of the bug

**Comment by amitojsingh366** [comment]
can't reproduce anymore, probably fixed by a38c3f94577fe36942d79a08a002422febf106af
