### ISSUE TITLE
Chat scuffed probably just mobile

### ISSUE THREAD

**Issue by asxlvm** [benawad/dogehouse#2226]
**Describe the bug**
Reopening chat doesn't scroll at the bottom of the convo

**To Reproduce**
1. Go to 'dogehouse.tv'
2. Join a room
3. Chat for a while, open, reopen chat

**Expected behavior**
Chat should automatically scroll

**Screenshots**

https://user-images.githubusercontent.com/81298611/115554104-67896980-a2ae-11eb-9ce2-0b2c890c544a.mp4

**What device are you on?**
I remember my browser version just because I'm reposting this for like the third time without a response.
Android 10 Xiaomi Pocophone F1
Brave Mobile (1.22.71)

**Additional context**
There was a lot of messages in chat

**Comment by PraveshKunwar** [comment]
Agreed, I think other people have been experiencing recent issues with the chat.

**Comment by amitojsingh366** [comment]
should be fixed in a38c3f94577fe36942d79a08a002422febf106af please confirm
