### ISSUE TITLE
Audio Randomly Disconnects

### ISSUE THREAD

**Issue by MrDogeBro** [benawad/dogehouse#2229]
## Description

When I am sitting in a room, I get randomly disconnected from audio from time to time. I don't know why this happens but when I turn on the audio debugger, it says `recv transport state: disconnected`. This is also not a one off. This has happened to me multiple times. The best solution I have to fix the issue is leave and re-join the room.

If you would like any more details or anything like that, let me know. Thanks!

## Reproduce
I don't know how to reproduce. Just sit in a room for a bit and then you might get disconnected from audio randomly.

## Expected Behavior
The audio should stay connected when inside a room.

## Device
Mac OSX 10.11.6

**Comment by A-Yamout** [comment]
@MrDogeBro Could this be your internet connection/stability and not doghouse?

**Comment by MrDogeBro** [comment]
My internet may have blipped but that would not be the problem because when its disconnected, I have checked and my internet is working. And, even if my internet did blip, it should automatically reconnect as soon as it can, just like in discord. Also, I have been using the internet while it disconnects and what I was doing did not get interrupted so I am pretty sure that it is not an internet issue.

**Comment by benawad** [comment]
Next time this happens can you create a new issue with a screenshot or copy/paste dump of your console

**Comment by MrDogeBro** [comment]
@benawad I will try to remember to do that if it happens again.
