### ISSUE TITLE
Not working on Edge browser for Android

### ISSUE THREAD

**Issue by PaulJoshi** [benawad/dogehouse#223]
The website is completely blank in Microsoft Edge for Android

**Comment by ExtraE113** [comment]
Does it render if you request the desktop site? Could be related to #22

**Comment by PaulJoshi** [comment]
Yes it renders when I request desktop site.

Vivo Z1 Pro
Android 10
Edge Mobile 46.01.24

**Comment by benawad** [comment]
Can you connect it to your computer and check the console?

**Comment by ExtraE113** [comment]
@benawad see #22

**Comment by PaulJoshi** [comment]
> Can you connect it to your computer and check the console?

This is what I see in the console in Edge for Android
![image](https://user-images.githubusercontent.com/49583322/108286258-c3e8e380-71ae-11eb-83bb-4694e86f8ba5.png)

**Comment by nadirabbas** [comment]
This is `mediasoup-client` related.

**Comment by benawad** [comment]
fixed in most recent version
