### ISSUE TITLE
Other authentication systems?

### ISSUE THREAD

**Issue by PraveshKunwar** [benawad/dogehouse#2231]
Will there be any other authentication systems that dogehouse will implement besides github and twitter? maybe like google, custom oauth?

**Comment by TheOtterlord** [comment]
Discord was implemented, but was removed due to a severe security bug.
I believe we plan to reimplement it along with google.
I don't believe email authentication is planned for a while.
Closing in favour of #340

**Comment by PraveshKunwar** [comment]
Ok thanks appreciate it for replying back!
