### ISSUE TITLE
Need a head DogeTester

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#2238]
would be good to start creating e2e tests with cypress

**Comment by judicaelandria** [comment]
yeah, we really should

**Comment by amitojsingh366** [comment]
i think i can be head dogetester, also i've been finding many bugs recently. but i haven't heard of/know of what cypress is

**Comment by judicaelandria** [comment]
@amitojsingh366 found many too while we have been in dogehouse yesterday with your bot(which is great)

**Comment by judicaelandria** [comment]
and oh man, cypress is great, just tried it today, I think I can be a tester too

**Comment by ghost** [comment]
i'm down i guess

**Comment by benawad** [comment]
@Odyssey346 ok go ahead and setup Cypress and start writing some tests

**Comment by ghost** [comment]
oh god

**Comment by ghost** [comment]
assign someone else, thought this was for testing the app, not writing tests

**Comment by ghost** [comment]
sry

**Comment by judicaelandria** [comment]
@benawad I can work on this but only on weekends, but if someone would takr this I can help him/her too

**Comment by benawad** [comment]
I'm setting it up, @judicaelandria you are welcome to add to it when you have time
