### ISSUE TITLE
Add Puppeteer e2e tests

### ISSUE THREAD

**Issue by bchampp** [benawad/dogehouse#2239]
There should be automated e2e tests to cover core user functionality. I propose using the puppeteer framework and automating front end tests with github actions.

**Comment by jobveldhuis** [comment]
Hey there, #2238 describes the need for a head tester using Cypress, which is an E2E testing suite. I think we will be using that, but @benawad will be the one who can confirm that.

**Comment by christian-bromann** [comment]
I would recommend to use [WebdriverIO](https://webdriver.io/) (fyi: I am the maintainer 😉 ) for this as it provides the ability to [control multiple browser](https://github.com/webdriverio/webdriverio/blob/main/examples/wdio/multiremote/mocha.test.js) within a single test abstracted into a single API and testrunner framework.

**Comment by nadirabbas** [comment]
I believe we have Cypress now
