### ISSUE TITLE
Buttons overflowing in small screens

### ISSUE THREAD

**Issue by devjayprakash** [benawad/dogehouse#2244]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the chat ui in smaller phones such as moto g4

**Expected behavior**
The ui should adapt to the small screen.  

**Screenshots**
Screen short of the overflowing ui
![Screenshot_20210422_140540](https://user-images.githubusercontent.com/25636260/115683945-90743200-a374-11eb-99cf-a2cf09a1b391.png)

**What device are you on?**
moto g4

**Additional context**
The bottom buttons on the chat page overflows when there is a smaller screen.

**Comment by dk-raw** [comment]
What is the exact resolution?

**Comment by devjayprakash** [comment]
Its 360 X 640

**Comment by A-Yamout** [comment]
had been fixed in #2404 @DevelopAppWithMe, can you close this issue
