### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by Bqleine** [benawad/dogehouse#2248]
Is your feature request related to a problem? Please describe.
Some parts of the website are not translated (code-wise)

Describe the solution you'd like
Add the parts of the website to translation.json so they can be translated

Additional context
Here are the missing translations I could find :
![image](https://user-images.githubusercontent.com/51089082/115698168-9e21bb80-a364-11eb-8eef-36f15ae3f947.png)
*"With" on the room header*

![image](https://user-images.githubusercontent.com/51089082/115698254-b5f93f80-a364-11eb-8fcc-c2323553af0f.png)
*am/pm*
This should use a 24 hour base for some countries

![image](https://user-images.githubusercontent.com/51089082/115698482-f3f66380-a364-11eb-83a9-dd789bb12a98.png)
*Sounds in sound settings (part 2 electric boogaloo)*

![image](https://user-images.githubusercontent.com/51089082/115698662-26a05c00-a365-11eb-8586-9bcf78a8ce09.png)
*App names in the reminder dropdown of scheduled rooms*

![image](https://user-images.githubusercontent.com/51089082/115698759-45065780-a365-11eb-8eac-272397ff794b.png)
*date in the schedule room popup*

![image](https://user-images.githubusercontent.com/51089082/115698898-69faca80-a365-11eb-87c5-e0b2ecef2710.png)
*Copy button in the share room link page (/room/id/invite)*

**Comment by Bqleine** [comment]
Note : If you make a pull request but it only fixes some of them. Please specify it in the comments so the missing ones get translated too

**Comment by dk-raw** [comment]
I think there is a yarn command you can run to add the missing keys
