### ISSUE TITLE
"enter" button for the chat?

### ISSUE THREAD

**Issue by adraneia** [benawad/dogehouse#2250]
**Is your feature request related to a problem? Please describe.**
ok so i was laying back to my chair, checking up on what i can do on this site, and i thought "Well i could send some emojis" 
so i choose the emojis that i wanted to send and then i realise: i actually have to stop chilling, "get up" and then press the enter(??)

**Describe the solution you'd like**
you could add a button like "chat" or "Send" or an arrow etc, for those that just dont wanna press the enter on their keyboards

**Describe alternatives you've considered**
this is how it looks like rn btw
![send enter](https://user-images.githubusercontent.com/77756019/115711150-dd0f3b80-a37b-11eb-8b80-166549fc2d64.jpg)

**Comment by Ayushsunny** [comment]
Hey @adraneia I wanna work on this issue

**Comment by goldyydev** [comment]
@Ayushsunny here ya go.

**Comment by Ayushsunny** [comment]
> @Ayushsunny here ya go.

Hey @goldyydev could you help me with the codebase please so that I can look for it more easily as I am new to open source

**Comment by samarmohan** [comment]
> Hey @goldyydev could you help me with the codebase please so that I can look for it more easily as I am new to open source

Do you still need help?

**Comment by Ayushsunny** [comment]
> > Hey @goldyydev could you help me with the codebase please so that I can look for it more easily as I am new to open source
> 
> Do you still need help?

yes @samarmohan could help me please that what exactly I need to do here

**Comment by wes337** [comment]
@Ayushsunny 

![fe](https://user-images.githubusercontent.com/9464690/115901112-736d5b00-a469-11eb-84d3-ef987eb73893.PNG)

I believe for this issue, you should add a clickable button here. 
Something like the Material UI "Send" icon (https://material-ui.com/components/material-icons/#material-icons).

So you'll need to:
1. Make an icon component in Kibbeh `src/icons/OutlineSend.tsx`
2. Add it into the `RoomChatInput` component as an icon button which acts as a submit button for the form.

**Comment by Ayushsunny** [comment]
Hello @ajmnz , @goldyydev I have made the changes.
May I make a PR now for this ?
