### ISSUE TITLE
Cannot hear speaker audio

### ISSUE THREAD

**Issue by mgpwilson** [benawad/dogehouse#2256]
**Describe the bug**
I cannot hear audio in rooms. The recv transport state is initially connecting for a while and then becomes disconnected. On refresh of the page, I am asked to click an okay button and then the same process happens.

**To Reproduce**
Specifically on my machine:
1. Join a room
2. Don't hear audio

**Expected behavior**
Hear audio.

**Screenshots**
![image](https://user-images.githubusercontent.com/9961083/115769767-ce3c7f00-a3a3-11eb-9641-49ebee28e55f.png)

**What device are you on?**
Windows 10 / Google Chrome Version 90.0.4430.85

**Comment by ajmnz** [comment]
Make sure to take a screenshot of the console in devtools next time it happens

**Comment by nadirabbas** [comment]
Closing it as we don't have much information
