### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by Aldiwildan77** [benawad/dogehouse#2257]
**Describe the bug**
when I choose dogehouse room it's getting an error message like "An unexpected error has occurred." But the sound of the speaker hears after we press the back button in the browser. every time I join a room it's getting this error.

**To Reproduce**
1. Go to the web
2. Click on one channel
3. Wait to connect
4. Error message occurred like "An unexpected error has occurred."
5. Press the back button in your browser
6. Then we should connect but an error occurred again with another message like "web socket was killed by the server.."

**Expected behavior**
user should be joined to the channel room 

**Screenshots**
**First Join**
![image](https://user-images.githubusercontent.com/29916319/115772782-b97ade00-a3d9-11eb-9807-10bb15900714.png)

**After Press Back Button**
![image](https://user-images.githubusercontent.com/29916319/115773089-17a7c100-a3da-11eb-9dd4-cf1847e53643.png)

**Chrome Console**
![image](https://user-images.githubusercontent.com/29916319/115773400-766d3a80-a3da-11eb-9dfd-61693f5a9efc.png)

**What device are you on?**
Linux Ubuntu 20.04

**Comment by 0xPiyush** [comment]
This also occurs on Brave browser on windows 10 .

**Comment by sap471** [comment]
had same issues on chrome 90.0.4430.72 on ubuntu 20.04

**Comment by code5717** [comment]
i got this on Chrome windows 10 too

**Comment by DimoDimchev** [comment]
I have the same issue currently on iPhone XR

**Comment by Saidfatah** [comment]
I encountered this just now from opera browser

**Comment by benawad** [comment]
should be fixed on latest dpeloy
