### ISSUE TITLE
Users without a display name appear blank

### ISSUE THREAD

**Issue by TripingPC** [benawad/dogehouse#226]
If someone with a GitHub account without a display name joins the room, their name in the grid appears blank instead of using their username.

name in listeners list: 
![image](https://user-images.githubusercontent.com/8508676/107951870-fdc7a900-6f66-11eb-8bad-5fb4fa7b7df0.png)

name in profile window:
![image](https://user-images.githubusercontent.com/8508676/107951903-09b36b00-6f67-11eb-80c2-c36d3696b40e.png)

**Comment by prateekshourya29** [comment]
Hello, I'm new to open source. Can i work on this?

**Comment by saranonearth** [comment]
@benawad can I work on this? 🍭

**Comment by ianjwhite99** [comment]
@benawad I was going to address this but the issue looks to have been potentially resolved. I attempted to recreate this by removing my GitHub display name and then signing up for an account but I was greeted by the username "Novice Doge". I joined a few different chat rooms and my display name was appearing as "Novice" every time. The only PR that I see however is #568 but that was to address the validation for the form input.

I can't seem to duplicate the issue. Unless I am missing something @TripingPC

**Comment by yummyweb** [comment]
This is a tricky one because the user may use what is known as a null terminator character. This is also seen in one of the Kahoot or Facebook hacks where some user has an empty username or display name. This should be done in the server-side.

**Comment by AsToNlele** [comment]
Commit 68eac26801bf3542d483304c710a9c51d019db10 fixes this.
