### ISSUE TITLE
Deafen button not visible if you're a listener

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2271]
**Describe the bug**
you can't see the deafen button when you're a listener, but you can still press the deafen keybind.

**To Reproduce**
1. Go in a room
2. Be a listener
3. Don't see the deafen button
4. Press deafen keybind

**Expected behavior**
Deafen button is visible
**Screenshots**

**What device are you on?**
Firefox 87 on openSUSE

**Additional context**
I may try to fix this myself later

**Comment by BronzW** [comment]
I can reproduce this

**Comment by ghost** [comment]
Can also reproduce on Windows 10, Firefox 88

**Comment by saihnii4** [comment]
I can also reproduce this on Manjaro Linux, Firefox 87

**Comment by amitojsingh366** [comment]
this is intentional. will work on it after deafen fully starts working

**Comment by ghost** [comment]
can you explain why that's intentional? for me, it's just weird
