### ISSUE TITLE
Deafen button causes unexpected errors

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#2273]
![image](https://user-images.githubusercontent.com/50546858/115872756-74d75d00-a442-11eb-89dd-c5c9f2011d41.png)
When clicking on and off the deafen button.

There is also no transition between hover states and colors of the button.

**Comment by saihnii4** [comment]
I've also encountered this error, here's what a staff member said
![Screenshot from 2021-04-23 21-02-57](https://user-images.githubusercontent.com/81787757/115875054-69eaef80-a477-11eb-9bb1-1d00b40ba330.png)

**Comment by amitojsingh366** [comment]
dupe #2270
