### ISSUE TITLE
Review Follow/Following Presentation

### ISSUE THREAD

**Issue by s3ansh33p** [benawad/dogehouse#2281]
**Describe the bug**
Followers and Following counts round at 9.95k to 10k, though 10k should only be displayed when 10k is actually achieved.

**To Reproduce**
View https://dogehouse.tv/u/benawad or any with x thousand users in followers or following. View true count here: https://api.dogegarden.net/v1/user/benawad or by watching the websocket.

**Expected behavior**
Don't round up. 9,999 should not be marked as 10k.

**Screenshots**
N/A

**What device are you on?**
Chrome, Windows 10

**Additional context**
If the current logic simply divides by 1000 and rounds to 1 d.p. use the Math.floor() or equivalent function to get the min value.

**Comment by wes337** [comment]
I can do this, will also write some unit tests for the `kFormatter` lib.
