### ISSUE TITLE
Private Room Share Url UI Blank

### ISSUE THREAD

**Issue by 4nkitd** [benawad/dogehouse#2287]
**Describe the bug**
when a user click on the users btn to share the url of the room he sees a blank page.

**To Reproduce**
1. Create a private room
2. Click on Share URL Button on bottom
3. See error

**Expected behavior**
should how a input box and others buttons with url

**Screenshots**

**What device are you on?**
should be like
![image](https://user-images.githubusercontent.com/52023083/115938053-0ed8ed00-a4b7-11eb-983b-f2cf7a5cc49c.png)

with issue
![image](https://user-images.githubusercontent.com/52023083/115938106-35972380-a4b7-11eb-8584-3510b795aa34.png)

**Comment by wes337** [comment]
So I did a bit of digging here, and it seems like we do not want to show a copy/paste URL here. We want to first fetch the invite list, which is your followers/following (I think), and send them invites.

Problem is, the `getInviteList` is returning `data.users` as an empty array.

So we might need confirmation on how exactly private rooms and inviting users is supposed to work.
