### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by shakky24** [benawad/dogehouse#2289]
Scrolling through the list of online people isn't smooth.

**Comment by dk-raw** [comment]
Works fine for me. What platform are you on?

**Comment by A-Yamout** [comment]
Maybe we should implement [this](https://github.com/LeDDGroup/scroll-utility)?

**Comment by dk-raw** [comment]
I cannot reproduce the bug on my system. That's why I asked him about his. The scrollbar works fine on 4 different browsers for me.

**Comment by A-Yamout** [comment]
@shakky24 Could you please tell us what browser and OS your using.
