### ISSUE TITLE
Border and Outline !

### ISSUE THREAD

**Issue by CodeRustyPro** [benawad/dogehouse#2290]
![Screenshot (183)](https://user-images.githubusercontent.com/65584840/115948968-0a302b00-a4ef-11eb-92d7-bdedb2b8aac7.png)
When you click on anything on dogehouse there is a bad rectangular border 

Just add border :0; and outline:0; in css , or else just add :focus and then border :0; and outline:0; in css @benawad

**Comment by dk-raw** [comment]
Duplicate
