### ISSUE TITLE
unable to view profile modal/page (trying to ban offensive profile)

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2294]
this is the profile: [https://dogehouse.tv/u/cumni***aa](https://dogehouse.tv/u/cumnigggaa)
<img width="1205" alt="Screen Shot 2021-04-24 at 7 05 08 PM" src="https://user-images.githubusercontent.com/35400192/115965067-0a044f80-a530-11eb-9165-e14ffae0fd4d.png">

<img width="455" alt="Screen Shot 2021-04-24 at 7 04 20 PM" src="https://user-images.githubusercontent.com/35400192/115965049-f658e900-a52f-11eb-8de1-fc0199bf0414.png">

**Comment by amitojsingh366** [comment]
this happens to everyone who does not have a bio @benawad

**Comment by s3ansh33p** [comment]
Video Clip 1: https://cdn.discordapp.com/attachments/793015082141351996/835546258902089798/2021-04-25_00-02-02.mp4
