### ISSUE TITLE
[Feature request] Collaboration/white board

### ISSUE THREAD

**Issue by Zimquadery** [benawad/dogehouse#230]
This feature may come handy for brainstorming. Specifically, game idea brainstorming. Now, most of the game devs uses discord for voice and jamboard for idea development. Sending jamboard link is gross 🤮. It may also be useful to UI/UX designers.

**Comment by lupu60** [comment]
@benawad  maybe excalidraw can be integrated.

**Comment by benawad** [comment]
out of scope for this project
