### ISSUE TITLE
The calendar list is stuck to your screen when you scroll down on scheduled rooms page

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#2301]
**Describe the bug**
The calendar list is stuck to your screen when you scroll down.

**To Reproduce**
1.  scheduled rooms
2. Click on 'the calendar icon'
3. scroll down

**Expected behavior**
I expected the calendar list to stay where it was.

https://user-images.githubusercontent.com/65829743/115980971-329f4000-a556-11eb-9702-756f7b6a347f.mp4

**What device are you on?**
PC Windows Brave browser

**Comment by isaxk** [comment]
> **Expected behavior**
> I expected the calendar list to stay where it was.*

*or it could just disappear
