### ISSUE TITLE
pfp ded

### ISSUE THREAD

**Issue by KittyBorgX** [benawad/dogehouse#2308]
Console : 
Failed to load resource: the server responded with a status of 404 ()
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 Object
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 nulling transports
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 creating a device
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 create recv transport
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 transport options Object
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 connect-transport recv success
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 recv transport 9d45df58-c2d1-4d73-92e0-3549a194ad02 connectionstatechange connecting
b38c4eb412e9e89fc8b835f0369fa17e22c84d20.8d3e80a87ef766f43617.js:1 recv transport 9d45df58-c2d1-4d73-92e0-3549a194ad02 connectionstatechange connected
30759238:1 Failed to load resource: net::ERR_TIMED_OUT
34707863:1 Failed to load resource: net::ERR_TIMED_OUT
53620720:1 Failed to load resource: net::ERR_TIMED_OUT
31000120:1 Failed to load resource: net::ERR_TIMED_OUT
58500221:1 Failed to load resource: net::ERR_TIMED_OUT
7872329:1 Failed to load resource: net::ERR_TIMED_OUT

Pic : 
![image](https://user-images.githubusercontent.com/82328083/115997763-fde8c280-a601-11eb-8e14-a5aa3d6597d7.png)

**Comment by goldyydev** [comment]
Your firewall could be blocking these images, as you can see some temporary images have already loaded

**Comment by benawad** [comment]
the urls are from gh or twitter, unrelated to dogehouse
