### ISSUE TITLE
No access to terms of use etc-

### ISSUE THREAD

**Issue by resteqs** [benawad/dogehouse#2309]
**Is your feature request related to a problem? Please describe.**
It is a problem when you can't see the rules of the platform

**Describe the solution you'd like**
Ad a link to Terms of service

**Describe alternatives you've considered**
Ad a button to terms of service

**Additional context**
do it :D

**Comment by goldyydev** [comment]
![image](https://user-images.githubusercontent.com/55450464/116555452-152af700-a905-11eb-96d9-95b79300ed5e.png)
