### ISSUE TITLE
Twitter Auth

### ISSUE THREAD

**Issue by andraspalasti** [benawad/dogehouse#2310]
I was already signed in with github but i signed out and tried to sign in with twitter because in twitter i have a profile picture. Then i authorized the app to use my twitter information then got redirected but probably with a problem.
The url that i was redirected to was this:

https://dogehouse.tv/?error=something%20went%20wrong,%20try%20again%20and%20if%20the%20error%20persists,%20tell%20ben%20to%20check%20the%20server%20logs

I noticed that i dont have an email address in my twitter account maybe that was the problem but i dont know.

Here's a video of the incident:
https://user-images.githubusercontent.com/72408521/115999229-4ea0f100-a5eb-11eb-8e2a-c5330bff8a3a.mp4

**Browser**
Brave V1.23.73

**Comment by HenryLeC** [comment]
To the best of my knowledge the OAuth system needs your email, so if you could attempt to link an email to your twitter account and then log in again that would be great. Once you do that if you could update the issue that would be amazing.

**Comment by andraspalasti** [comment]
I linked my email to my twitter account its the same email that i use with github, but it still doesn't work.

**Comment by TudorVersoiu** [comment]
Same issue here even after linking an email.

**Comment by nikhilpokharel44** [comment]
ben was talking about changing the refresh tokens for all registered account, I guess he forgot ours :)

**Comment by andraspalasti** [comment]
I don't know what did the contributors change but it is working now, I just tried it out.
Can i close this issue?
