### ISSUE TITLE
Doesn't auto reconnect... here's what i got in the log

### ISSUE THREAD

**Issue by FotieMConstant** [benawad/dogehouse#2318]
When I get disconnected because of internet issues or wifi breaks. doesn't auto reconnect
![image](https://user-images.githubusercontent.com/42372656/116004600-68e2cb00-a5fb-11eb-8ebf-3e3f9638019f.png)

**Comment by FotieMConstant** [comment]
@benawad here you go!

**Comment by A-Yamout** [comment]
isn't that normal for security? @FotieMConstant

**Comment by FotieMConstant** [comment]
not quite sure, @benawad asked me to create an issue for this with a screenshot!

**Comment by A-Yamout** [comment]
when you say doesn't auto reconnect does it say you have to login again? @FotieMConstant
