### ISSUE TITLE
Redirect to intended room after logging in

### ISSUE THREAD

**Issue by sohank1** [benawad/dogehouse#2319]
**Describe the bug**
If you are not logged in and you click a link to the room it takes you to the login page after you login you are redirected to the dashboard page instead of the room page

**To Reproduce**
1. Click a link to room while not logged in
2. Login with GitHub or twitter
3. It redirects you to /dash instead of the link you originally clicked

**Expected behavior**
I was expecting to be redirected to the original link I clicked

**What device are you on?** Chrome Android 8 same thing also happens in win 10 latest chrome.

**Comment by ajmnz** [comment]
Changed your title to make it more clear 👍🏼
