### ISSUE TITLE
Add Hover Text to Add to Calendar Button on Scheduled Rooms

### ISSUE THREAD

**Issue by SammRosenthal** [benawad/dogehouse#2322]
**Is your feature request related to a problem? Please describe.**
Want to know what the add to calendar button does without having to open the drop down.

**Describe the solution you'd like**
Add hover text to the add to calendar button on scheduled rooms saying something like "Add to Calendar".

**Describe alternatives you've considered**
We could possibly use a different icon that has something like a small + on the calendar to make it more clear that it won't do something like take you to a different page.

I would like to do this as a first contribution if you think something like this is a good idea.

**Comment by ajmnz** [comment]
Added #2324
