### ISSUE TITLE
Banner photo is transparent when using a transparent profile image

### ISSUE THREAD

**Issue by mwenku** [benawad/dogehouse#2332]
**Cover Photo is visible through transparent profile image**
when using a profile image that has a transparent background, the banner image is visible through the background
a photo showing the bug has been attached

**To Reproduce**
1. Go to 'dogehouse.tv/u/your_username.'
2. Click on 'replace your profile picture with an image with a transparent background for example: https://avatars.githubusercontent.com/u/64831126?v=4'
3. Look at the profile image's background
4. See the error ?

**Expected behavior**
if the users chooses to use a profile image with a transparent background, the background should be replaced by a color for example white  white.

**Screenshots**
here is a screenshot of the error
![error](https://user-images.githubusercontent.com/64831126/116062327-a580e780-a638-11eb-8210-39072a2c52be.PNG)

**What device are you on?**
- OS: Windows 10
- Browser: opera

**Comment by overlisted** [comment]
that can be somewhat fixed by giving the image a background-color
![image](https://user-images.githubusercontent.com/66535446/116322981-6c25b480-a7bd-11eb-922d-11acd80d6d34.png)
