### ISSUE TITLE
Remove Button Outlines

### ISSUE THREAD

**Issue by sohank1** [benawad/dogehouse#2337]
**Is your feature request related to a problem? Please describe.**
Buttons on most website don't have this outline. I think it would look much better if it was removed.

![image](https://user-images.githubusercontent.com/51346607/116088639-0c6dc300-a670-11eb-8823-aa89c9030b2d.png)
![image](https://user-images.githubusercontent.com/51346607/116088778-2effdc00-a670-11eb-933a-416617d90ca2.png)

**Comment by nadirabbas** [comment]
i believe this has been fixed
