### ISSUE TITLE
A versionated API like Stripe's should be considered

### ISSUE THREAD

**Issue by rmortes** [benawad/dogehouse#2339]
I'm watching the latest video, and Ben said that merging a PR broke the service because the API was updated but the client's weren't. 

Stripe has a versionated API that works differently depending on the version sent with the request. Something like this cloud be added to the project, and support the last 20 or 30 versions of the master branch at the API. This way, the client's updates could be done asyncronously from the API's updates.

**Comment by hamzaseif13** [comment]
I disagree with you it shouldn't do that

**Comment by bennihtm** [comment]
Maybe the API endpoints could change, when the expected answer or request change in a major way (e.g. `api.dogehouse.tv/v1/request-blablabla` and then in the next version `api.dogehouse.tv/v2/request-blablabla`.
