### ISSUE TITLE
serbian translation has mistakes in some places

### ISSUE THREAD

**Issue by markocupic024** [benawad/dogehouse#2341]
title is sufficient

**Comment by drvladb** [comment]
If you are able to, please help us by contributing changed to the translations.

How to open/What is a PR: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by HenryLeC** [comment]
I dont speak serbian but if you add a comment saying where you have found mistakes and what the correct translation is I would be happy to add those fixes to the translation.

**Comment by markocupic024** [comment]
I already made a pull request and fixed it

**Comment by TheOtterlord** [comment]
As this is fixed I'll close the issue
