### ISSUE TITLE
Login issue for twitter account

### ISSUE THREAD

**Issue by nikhilpokharel44** [benawad/dogehouse#2342]
I was trying to login via my twitter account which was authenticated before but suddenly I couldn't login and was redirected to login page again until i use my github account 
now i have completely new account opened 😌

**Comment by NatanCieplinski** [comment]
Probably a duplicate of #2310

You got a new account opened because using another auth provider results in a new account. To understand why watch his [DogeLog](https://youtu.be/bngsrbFI2UY?t=240).
