### ISSUE TITLE
Missing Page Reload / Page Update when updating fields in Profile

### ISSUE THREAD

**Issue by DevParapalli** [benawad/dogehouse#2347]
**Is your feature request related to a problem? Please describe.**
Profile doesn't reload when anything about it updates. Additionally the user profile URL should be cached (even if for a short time, ~86400 seconds) and redirected (if possible) to the new username.

**Describe the solution you'd like**
Page should reload on any edits made to the profile.

**Describe alternatives you've considered**
Page should update URL and Fields for Profile 

**Additional context**
None
Problem is reproduceable with any account.

**Comment by benawad** [comment]
should be fixed now
