### ISSUE TITLE
shift click to tag

### ISSUE THREAD

**Issue by plunched** [benawad/dogehouse#2350]
**Is your feature request related to a problem? Please describe.**
So when I want to tag someone when chatting in the live-chat, I have to remember their name to then type it manually in the chat.

**Describe the solution you'd like**
It would be cool if you could tag someone by 'shift-clicking' their name.

**Describe alternatives you've considered**
You could still get their profile page by just regular clicking their name.

**Comment by nadirabbas** [comment]
Nice

**Comment by plunched** [comment]
oh sorry, I didn't see any open issues so I assumed there where none.
