### ISSUE TITLE
bot auth is broken

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2359]
- bot token requests broken `api.dogehouse.tv/bot/auth`

**Comment by A-Yamout** [comment]
Can you please provide more context and background info @amitojsingh366

**Comment by benawad** [comment]
it's not broken, you are sending the wrong format

what does your request look like?

**Comment by amitojsingh366** [comment]
> 
> 
> it's not broken, you are sending the wrong format
> 
> what does your request look like?

this is what my request looks like:
```typescript
 axios.post("https://api.dogehouse.tv/bot/auth", { apiKey: data.apiKey }).then((resp) => {
     console.log(resp.data);
});
```
i used this code and it worked at least five times and then it started throwing error 500

**Comment by amitojsingh366** [comment]
> 
> 
>     * bot token requests broken `api.dogehouse.tv/bot/auth`

on my local clone i tried reproducing this and it works perfectly, i assume this is just an issue with the current build of the api deployed. @benawad pls look into this
