### ISSUE TITLE
Banners are random every time the page is reloaded (for people that I haven't updated their banner)

### ISSUE THREAD

**Issue by drvladb** [benawad/dogehouse#2360]
**Is your feature request related to a problem? Please describe.**
The banner (for people that I haven't updated their banner) is random every time the page is reloaded.

**Describe the solution you'd like**
If the random banner should be retained, it should be set as a direct url (at registration or something) or should be randomly seeded if the value can't be stored.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by amitojsingh366** [comment]
this is intentional
