### ISSUE TITLE
Translation to Portuguese (Brazil) is not working properly

### ISSUE THREAD

**Issue by adomaitisc** [benawad/dogehouse#2362]
**Describe the bug**
In the language setting, when selecting Portuguese (Brazil), it only translated the "following" nad "followers", and Capitalize some other content such as "Upcoming Rooms", "Explore More Rooms" and more text. 
I do not know if it is only happening to Portugues (Brazil), but I can affirm that Portuguese (Portugal) is working properly.

**To Reproduce**
1. Log in your Account.
2. Click on the user image.
3. Select "language" in the dropdow.
4. Select Portuguese (Brazil).
5. Now you can see the changes it is making on the website.

**Expected behavior**
The Expected behavior id to the whole website to be translated, from the Search bar to the "Upcoming rooms".

**Screenshots**
![image](https://user-images.githubusercontent.com/57054660/116142112-e536e600-a6af-11eb-8d91-4f447dd24f7b.png)

**Caption**
The image shows the discrepancy, showing "Your Feed" in english, and "Criar Sala" in portuguese. The language is set to Portuguese (Brazil).

**What device are you on?**
I experienced this bug at Edge, Windows.

**Comment by joaorodrs** [comment]
Same happened to me, on both Edge and Chrome. But look at the [translation file](https://github.com/benawad/dogehouse/blob/staging/kibbeh/public/locales/pt-BR/translation.json), you can see that there's some  things in english, so it's just fix it.
I don't mind some words being in english, this is pretty normal but most translations like `"Your feed"` that should be at least `"Seu Feed"`, but anyway I think that's the way to go.
