### ISSUE TITLE
Language flag/ISO code does not show

### ISSUE THREAD

**Issue by BronzW** [benawad/dogehouse#2376]
![image](https://user-images.githubusercontent.com/50546858/116197141-a008c780-a734-11eb-94a7-a5153306b1d9.png)

**Comment by amitojsingh366** [comment]
i think this is intentional

**Comment by BronzW** [comment]
Why

**Comment by BronzW** [comment]
@ajmnz Changed it in his latest PR so the flags is their own property in LanguageSelector.tsx but he didn't add support for it in the html.

**Comment by amitojsingh366** [comment]
im not sure about this, ill ask @ajmnz to look into this

**Comment by ajmnz** [comment]
Many times flags don’t respresent all the people that speak a certain language. It can even offend people in some occasions and that’s why I removed them. 

I left them as a separate property because I felt that they could be useful in the future, but the change was intentional.
