### ISSUE TITLE
Using selenium python for automate testing on a local machine 

### ISSUE THREAD

**Issue by sheecegardezi** [benawad/dogehouse#2379]
In your blog Apr 27, 2021. You mentioned issue regarding testing multi-tab applications. I wanted to start a discussion. On weather writing tests using selenium(https://selenium-python.readthedocs.io/) in python bindings might be a good solution. I am fairly decent in it I can write tests in selenium if it is a viable idea.

**Comment by benawad** [comment]
I want to use https://github.com/microsoft/playwright
