### ISSUE TITLE
Audio Stops Working after few seconds of joining room

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [benawad/dogehouse#2385]
**Describe the bug**
I tried joining a room today and after a few seconds, the audio stopped. I tried reloading the page and after a few seconds, the audio stopped. I thought it might have something to do with that room, but when I went to a different room, the same error happened.

**To Reproduce**
1. Go to dogehouse dashboard
2. Click on any room
3. join and wait a few seconds

**Expected behavior**
What I expected it to do is play the audio for that room.

**What device are you on?**
MacBook Pro 13" 2014

**Additional context**
OS: macOS 11.3
Browser: Brave Version 1.23.71 using Chromium: 90.0.4430.72

**Comment by benawad** [comment]
what is the error?

**Comment by Isaiah-Hamilton** [comment]
@benawad The problem has been fixed, though I don't know how it was fixed. The problem was that when I joined a room with my Bluetooth headset connected. The audio would stop working after a few seconds. I would reload the page and the bug would happen again. Though it is working now, and I don't know why. I will let you know if I find anything else.

**Comment by Isaiah-Hamilton** [comment]
Update, Audio only stops when I'm connected to my school's network, which is a problem with the school's network. Sorry for bothering you ben.
