### ISSUE TITLE
Missing features in dashboard depending on window size

### ISSUE THREAD

**Issue by realansgar** [benawad/dogehouse#2386]
**Describe the bug**
Dogehouse has a responsive dashboard, as described in [Ben's Video](https://www.youtube.com/watch?v=Dk1gxZ_K3E0). In it's current form, smaller window sizes get less columns to prevent a cluttered screen. But the features of these now hidden columns never reappear in some other place. In smaller windows, they are simply inaccessible. These include:

- friend list
- upcoming rooms
- and worst of all, the currently joined room 

**To Reproduce**
1. Join a room.
2. Go to 'https://dogehouse.tv/dash'
3. Resize your window to the maximum widescreen size.
4. Slowly resize your window to increasingly smaller widths to notice all changes on @media breakpoints:
5. First, the friend list on the left disappears.
6. Then, the right sidebar with the info about the room you are currently in disappears. Also the Upcoming rooms are gone.
7. Later on, a floating button that takes you to your current room reappears.

**Expected behavior**
On every window size, all features of the dashboard are available in some form. For example, they could be accessible through a hamburger menu. Most importantly, the floating button that shows your current room should show up immediately after the right sidebar disappears, not later on.

**What device are you on?**
Firefox 88

**Comment by BronzW** [comment]
Having all features present is not something possible. On a phone that can't be done.

**Comment by BronzW** [comment]
Things like a friends list is not completely urgent for somebody to have to successfully interact with the app, and you can still view your profile. Things like scheduled rooms should though be available somewhere else.

**Comment by realansgar** [comment]
I'm not saying they should be "present" as in "visible all the time". But they should be accessible through some navigation. For example by introducing a hamburger menu and/or separate pages. In my opinion, all features should be accessible on all platforms (mobile, web, desktop) in some way.

**Comment by ajmnz** [comment]
Tablet/Mobile layout is temporary. Check Figma to know how it'll look when everything's in place

**Comment by realansgar** [comment]
@ajmnz Thanks, I didn't know about this. Currently I'm not seeing a "Current room" floating button in the tablet design mockup but that should be easy to add.
