### ISSUE TITLE
Title overflows div 

### ISSUE THREAD

**Issue by ExtraE113** [benawad/dogehouse#24]
![133A1830-AF91-4F14-9F9F-E614DA9B62F2](https://user-images.githubusercontent.com/33768950/107790632-d4f5a880-6d07-11eb-9c70-1c2cbc0f47db.jpeg)

Firefox mobile 31, iPhone 8

**Comment by MadanBhandari** [comment]
this issue still exist ?

**Comment by goldyydev** [comment]
This issue has been fixed
![image](https://user-images.githubusercontent.com/55450464/111882168-bf396a00-89bc-11eb-9395-284d95a1076c.png)
