### ISSUE TITLE
[UX] Clicking the profile card should redirect to the user's profile page

### ISSUE THREAD

**Issue by younesaassila** [benawad/dogehouse#2429]
**Is your feature request related to a problem? Please describe.**
As of now, clicking the sidebar's profile card opens up the 'Edit Profile' dialog.
The problem is, most users would expect to be redirected to their profile page when clicking on this element (just like other social media platforms do ; e.g. Twitter).

**Describe the solution you'd like**
Clicking the sidebar's profile card should redirect the user to their profile page instead of opening up the 'Edit Profile' dialog.

**Additional context**
![image](https://user-images.githubusercontent.com/47226184/116573195-e022a280-a90c-11eb-965e-1e136d8b0230.png)

**Comment by ajmnz** [comment]
This is temp while we don't have a proper settings page

**Comment by younesaassila** [comment]
@ajmnz But there is an 'Edit Profile' button on the profile page itself! The current design seems redundant, not standard and doesn't make sense regardless of whether or not a Settings page is available.

**Comment by ajmnz** [comment]
Many users were complaining that they didn’t see where to edit the profile. We now have this button in the profile page because it was implemented two days ago. 
This behavior will eventually be replaced for a link to the profile page.
