### ISSUE TITLE
a much wow like button

### ISSUE THREAD

**Issue by MrRandomInternetDude** [benawad/dogehouse#2430]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be cool if there was a like button that reflected the words "much wow" as what is stated when something is said "liked"

**Describe alternatives you've considered**
There could be multiple doge like emoji reactions to consider adding. Something that I see making doge house unique could be its embrace of making everything a joke within itself. I only want to share this idea for everyone to build upon. 

**Additional context**
The emoji reaction should be fun. Weather it changes color or does something is up to who creates it.

**Comment by nadirabbas** [comment]
much wow
