### ISSUE TITLE
Electron app deafen (Ctrl-X) keyboard shortcut applies even when the app is minimized and another window is in focus

### ISSUE THREAD

**Issue by redpwilliams** [benawad/dogehouse#2435]
**Describe the bug**
The Electron Desktop Application's keyboard shortcut for deafening a room is triggered even when the app is minimized and another window is active. For example, I could be in VScode trying to cut out some code with DogeHouse minimized but still open, but instead of cutting the code out, it deafens the audio in the room even though DogeHouse is minimize.

**To Reproduce**
1. Open the Electron desktop app
2. Join any room
3. Hit minimize in the top right, and open any other window (and focus on it)
4. Press Ctrl-X.
5. The room will deafen, but the Ctrl-X shortcut should apply only when DogeHouse is in focus

**Expected behavior**
Ctrl-X does whatever it's mapped to do for the current window. For example, if a code editor is open and focused on and the Electron app is minimized while listening in a room, Ctrl-X should cut out highlighted text (or do whatever it's programmed to do) instead of deafening the room.

**What device are you on?**
Windows 10

**Comment by amitojsingh366** [comment]
this is intended behaviour, one of the plus points of the electron app is the global keybind feature. and yes i know control+x wasn't a good keybind decision, this will be changed later today. till then you can customize the keybind to your linking

**Comment by redpwilliams** [comment]
Now that I think about it, the global keybind does sound like a good idea, and it's even better that it's customizable. Thanks for telling me this! I look forward to the changes.
