### ISSUE TITLE
chat banned person should be able to send messages to the room creator

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#2437]
a person who is banned from the chat should be able to send whispers to the room creator if he/she was banned cuz of a misunderstanding. Happened to me twice.

**Comment by ajmnz** [comment]
Unless we have some kind of block system, that would allow banned users to spam room creators. Which isn’t good

**Comment by nadirabbas** [comment]
@ajmnz just kick em out

**Comment by nadirabbas** [comment]
but i got banned due to a misunderstanding, I had no way to tell them 😢

**Comment by benawad** [comment]
I think the solution is to make it more visually obvious who has been banned from chat

**Comment by nadirabbas** [comment]
but how do I chat with the creator to tell him to unban me?

**Comment by amitojsingh366** [comment]
@benawad he isnt saying they didnt know he was banned, he's saying that due to a misunderstanding they intentionally banned him

**Comment by nadirabbas** [comment]
yeah they didnt understand what's going on in the chat and thought i was being rude or something

**Comment by amitojsingh366** [comment]
i think keep like a 5 msg limit that you can send the mods/admins after being banned so they can appeal

**Comment by amitojsingh366** [comment]
> yeah they didnt understand what's going on in the chat and thought i was being rude or something

are you sure about that 🤔

**Comment by nadirabbas** [comment]
@amitojsingh366 remember earlier today?

**Comment by benawad** [comment]
chat ban is a chat ban, ask to speak if it needs to be cleared up
