### ISSUE TITLE
Hide login screen if already logged in

### ISSUE THREAD

**Issue by vikashd** [benawad/dogehouse#2440]
**Is your feature request related to a problem? Please describe.**
Minor issue.

**Describe the solution you'd like**
Currently when you visit the site depending on connection speed the login screen appears if you're logged in already.

**Describe alternatives you've considered**
Perhaps hide the login (show a loader, e.g spinning doge) while it's checking if you're logged in.

**Comment by dk-raw** [comment]
It is authenticating you before accessing DogeHouse
