### ISSUE TITLE
Improper etiquette on dogehouse?

### ISSUE THREAD

**Issue by RonaldColyar** [benawad/dogehouse#2441]
There is a wild person who framed me for harassing other users on dogehouse two days after I got into an argumentative debate with him I got framed for harassing people on the platform by him. Let me get this straight: the creator of the bots(holopanio) got into an argument with me and two days later he is saying I made a bot to harras him? He complains about everyone and I think was a bad banning decision. Take a look at the video attached below(it is short). He even posted this crazy stuff to youtube promoting improper etiquette,  is it safe to say he should be banned?  Does having a preference of women and liking nature videos deserve a ban from the site? 

https://user-images.githubusercontent.com/35206353/116632288-d4db7100-a924-11eb-89a4-a4594faa2435.mp4

Here is the full video that he posted on youtube: https://www.youtube.com/watch?v=el2qCl2OR0w

**Comment by A-Yamout** [comment]
This is very awful behavior but a GitHub issue would not be the place for this, you can tell the staff or ben about this on the discord server. @RonaldColyar

**Comment by dusnm** [comment]
There should honestly be a Code of Conduct to help resolve these issues in the future, but I agree Github issues isn't the place for these kinds of discussions.

**Comment by 0xEquinox** [comment]
Dude, you made people feel unsafe on the platform, you constantly objectify women, call people fat, admitted to creating bots that spam whispered people tell them obscene things, and your ban evading because that's your second account cause your first one was banned.

**Comment by RonaldColyar** [comment]
One of holopaino's friends on a witch hunt...

**Comment by TheOtterlord** [comment]
Please remember to follow our [code of conduct](https://github.com/benawad/dogehouse/blob/staging/CODE_OF_CONDUCT.md) when partaking in these discussions. GitHub issues are not the place for this sort of discussion. If you wish to continue this, please do so elsewhere.
