### ISSUE TITLE
Missing formated title in profile pages

### ISSUE THREAD

**Issue by Einliterflasche** [benawad/dogehouse#2442]
HTML title when in profile pages displays "https://dogehouse.tv/u/username".

1. Go to any profile page dogehouse.tv/u/username
2. look at title of the tab
3. See error

**Expected behavior**
Title that looks somewhat like "u/username | DogeHouse" like on the dashboard page.

**What device are you on?**
Windows 10 Home 19042.928
Brave Browser Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit

**Comment by thuaung30** [comment]
Can I do this fix?

**Comment by ghost** [comment]
yes, you can
