### ISSUE TITLE
Pilaf crashes after installing on android emulator.

### ISSUE THREAD

**Issue by Hasintha-Jayasinghe** [benawad/dogehouse#2443]
After installing the app it crashes without any errors. The emulator is running android 10 ( I tried with 11 but that had other build errors). Can someone point out what's wrong?

**Comment by Hasintha-Jayasinghe** [comment]
I tried on a physical device too.

**Comment by transli** [comment]
Seems there's an issue with react-native-webrtc.

# This one fixes a weird WebRTC runtime problem on some devices.
# https://github.com/jitsi/jitsi-meet/issues/7911#issuecomment-714323255

Add this line to android/gradle.properties:
android.enableDexingArtifactTransform.desugaring=false

**Comment by Hasintha-Jayasinghe** [comment]
yep that fixed it!
