### ISSUE TITLE
doughdoge emoji overlaps because it's huge

### ISSUE THREAD

**Issue by Gers2017** [benawad/dogehouse#2465]
**Describe the bug**
The doughdoge emoji doesn't scale well on mobile and overlaps the chat.

**To Reproduce**
1. Go to https://dogehouse.tv/ and create a room
2. Spam the doughdoge  emoji on the chat
3. Change the viewport size to a small size.
4. Enjoy

**Expected behavior**
I was expecting a normal and responsive list of messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/49139988/116752765-45d16600-a9c3-11eb-8abf-02d5b9142088.png)
![image](https://user-images.githubusercontent.com/49139988/116752771-48cc5680-a9c3-11eb-9f5a-8c453c3429aa.png)

**What device are you on?**
Laptop. Brave browser

**Additional context**
None

**Comment by jobveldhuis** [comment]
I have implemented a fix by scaling the DoughDoge emoji to the correct size. See PR #2488.
