### ISSUE TITLE
Noise Cancellation

### ISSUE THREAD

**Issue by he1d1** [benawad/dogehouse#2470]
**Is your feature request related to a problem? Please describe.**
Its really annoying to hear a room of 24 people all mashing their cherry MX brows when someone mentions an obscure framework and everyone wants to pretend to know what it is.

**Describe the solution you'd like**
It would be great to implement noise cancellation to DogeHouse so I dont have to rely on other people to use push to talk or a client side application like Nvida Broadcast.

**Describe alternatives you've considered**
Push to talk or a client side application like Nvida Broadcast

**Comment by nadirabbas** [comment]
@hiluw we got push to talk, people just dont use it

**Comment by he1d1** [comment]
That's my point. Noise suppression would let people who don't like push to talk still type without muting

**Comment by he1d1** [comment]
Since project isn't continuing, I'll close this.
