### ISSUE TITLE
Search bar moves up whenever you go to anyone profile page

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#2471]
**Describe the bug**
search bar moves up when you go to anyone's profile or scheduled room page.

**To Reproduce**
1. Go to 'dash'
2. Click on 'a profile or scheduled room'
3. See error

https://user-images.githubusercontent.com/65829743/116766582-dc684c00-a9f0-11eb-9504-935b0182a33a.mp4

**What device are you on?**
Windows brave browser

**Comment by benawad** [comment]
should be fixed in latest deploy
