### ISSUE TITLE
The title and leave button is cut off when you join a room on mobile

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#2472]
**Describe the bug**
the title and leave button is cut off when you join a room on mobile.

**To Reproduce**
1. Go to 'mobile'
2. Click on 'a room'
3. See error

**Screenshots**
![Screenshot_20210430-202249_Brave](https://user-images.githubusercontent.com/65829743/116766813-11c16980-a9f2-11eb-840f-3b66e3452237.jpg)
**What device are you on?**
Samsung S8+ Brave Browser

**Comment by ajmnz** [comment]
I believe this has been fixed, can you confirm @PuckDan ?

**Comment by PuckDan** [comment]
yes it has been fixed
