### ISSUE TITLE
Can't see room name on phone

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#2473]
![Screenshot_2021-05-01-10-05-38-45](https://user-images.githubusercontent.com/38838675/116771452-fc395780-aa64-11eb-81be-f889005e542b.jpg)

**Comment by Isaiah-Hamilton** [comment]
What screen size is your phone because it seems to be working just fine for me.

**Comment by amitojsingh366** [comment]
> 
> 
> What screen size is your phone because it seems to be working just fine for me.

this was an actual issue, it has been fixed now
