### ISSUE TITLE
Seeing messages in rooms your arnt in

### ISSUE THREAD

**Issue by 0xEquinox** [benawad/dogehouse#2474]
**Describe the bug**
If you are banned from a room and enter another room you are able to see all messages from the room you are banned in.

**To Reproduce**
1. Go to a room and get banned or have someone banned
2. Make a new room
3. Have someone in the room you are banned in send a message

**Expected behavior**
After this, you should see the messages in your new room

**Screenshots**
Don't have any 

**What device are you on?**
Windows pc using the browser app

**Comment by TheOtterlord** [comment]
Just checking. No new messages popped up from the previous room, right?

**Comment by 0xEquinox** [comment]
> 
> 
> Just checking. No new messages popped up from the previous room, right?

You should be able to see all the messages being sent in the old room in the new room.

**Comment by TheOtterlord** [comment]
ah, ok. so this is quite a severe bug then 🤔

**Comment by ajmnz** [comment]
I'm able to reproduce this

**Comment by TheOtterlord** [comment]
We may also want to add some tests for this when it's fixed
