### ISSUE TITLE
Search bar for the languages

### ISSUE THREAD

**Issue by IntegraterGithub** [benawad/dogehouse#2482]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when it takes so long to find a language

**Describe the solution you'd like**
A search bar.

**Comment by laurens-vrh** [comment]
Maybe when you press a key, it takes you to that letter in the list of languages. Kind of like the font selector in word

**Comment by dk-raw** [comment]
The language selector is not a select element and it is not that easy to implement such a thing. Although, that sounds like a good idea.
