### ISSUE TITLE
Sign out button not working

### ISSUE THREAD

**Issue by isaxk** [benawad/dogehouse#2489]
**Describe the bug**
Sign out button doesn't do anything.

**To Reproduce**
1. Go to 'dogehouse'
2. Click on 'your profile'
3. Go to sign out

**Expected behavior**
It to sign out and show login page

**Screenshots**

**What device are you on?**
Chrome for Android

**Additional context**

**Comment by jobveldhuis** [comment]
Can you reproduce this problem on desktop web? If so, do you have any errors in your JavaScript console?

**Comment by junedkhatri31** [comment]
<img width="634" alt="Screenshot 2021-05-02 at 5 58 30 PM" src="https://user-images.githubusercontent.com/20799038/116813158-06944800-ab70-11eb-850d-ba6766dd4c13.png">
I am able to re-produce this in mobile layout.

Steps to reproduce the behavior:

1. Go to https://dogehouse.tv on mobile / switch to mobile from dev tools
2. Click on 'your profile'
3. Go to sign out
4. See error
