### ISSUE TITLE
Change Ip to IP

### ISSUE THREAD

**Issue by crispyaus** [benawad/dogehouse#2495]
Change Ip to IP

![image](https://user-images.githubusercontent.com/34707863/116823295-fbb8d200-abc6-11eb-9242-7bcd0d483612.png)
to
![image](https://user-images.githubusercontent.com/34707863/116823308-0b381b00-abc7-11eb-9538-64e4e3e55b8c.png)

**Comment by ghost** [comment]
can you do it? it's a simple change in strings (if you won't, i can)

**Comment by Alirezamxz** [comment]
I will fix it.
