### ISSUE TITLE
Curse Word Filtering in Chat

### ISSUE THREAD

**Issue by RobertWetzler** [benawad/dogehouse#251]
Someone called me a racial slur in my chat. It's up to Ben, but I feel like there are some words that should not be allowed.

**Comment by mohammedgad** [comment]
That can be an option in the room settings

**Comment by jakiki6** [comment]
https://github.com/web-mech/badwords might be useful to filter them

**Comment by benawad** [comment]
Filtering is useless, they will just spell them differently. I will implement a reporting system and they will be permanently banned.

**Comment by ExtraE113** [comment]
May be worth implementing client-side filtering so it's not obvious that you've been censored? IE:

- I say something and it shows up as "Hey you ...." but _not_ censored on my screen
- On your screen: "Hey you *******"

**Comment by mohammedgad** [comment]
@ExtraE113 I think that will be confusing.

**Comment by nadirabbas** [comment]
@benawad working on this must be fun 😂

**Comment by DGKSK8LIFE** [comment]
> Filtering is useless, they will just spell them differently. I will implement a reporting system and they will be permanently banned.

You need to validate reports and mitigate any potential for fake reporting/spam and botting. Might wanna implement ReCAPTCHAs for this.

**Comment by nadirabbas** [comment]
> Filtering is useless, they will just spell them differently. I will implement a reporting system and they will be permanently banned.

https://github.com/MauriceButler/badwords/blob/master/array.js

**Comment by isaxk** [comment]
> > Filtering is useless, they will just spell them differently. I will implement a reporting system and they will be permanently banned.
> 
> https://github.com/MauriceButler/badwords/blob/master/array.js

I ♥️ MIT license

**Comment by TheOtterlord** [comment]
badwords package combined with a few other things makes for a decent filter

**Comment by A-Yamout** [comment]
@benawad What if we do it discord style and let the users on both sides decide, so it will be client side?

**Comment by ghost** [comment]
Emoji letters and special english characters like 𝕒𝕓𝕔𝕕𝕖𝕗 and  🅰🅱 should be blocked too.

**Comment by DGKSK8LIFE** [comment]
> Emoji letters and special english characters like 𝕒𝕓𝕔𝕕𝕖𝕗 and 🅰🅱 should be blocked too.

This will be more difficult though because you'd have to cross-validate the input with all possible Unicode characters.

**Comment by TheOtterlord** [comment]
> This will be more difficult though because you'd have to cross-validate the input with all possible Unicode characters.

It may be more difficult, but otherwise people can easily get around it. unless we disallow all of these characters 🤔

**Comment by nadirabbas** [comment]
rip
