### ISSUE TITLE
UI is messed up in mobile view, but the buttons are working

### ISSUE THREAD

**Issue by prLorence** [benawad/dogehouse#2513]
**Describe the bug**
When visiting profiles the buttons are overflowed if that's what you call it.

**To Reproduce**
1. I didn't do anything in particular, just visited some profiles and it just happened

**Expected behavior**
Stacked buttons would be nice.

**Screenshots**
![IMG_20210503_124853](https://user-images.githubusercontent.com/78683375/116842411-1747cb00-ac0f-11eb-9dfe-e2576ddb5367.jpg)
![IMG_20210503_124818](https://user-images.githubusercontent.com/78683375/116842417-19118e80-ac0f-11eb-9d46-daa81eb7c032.jpg)

**What device are you on?**
Redmi note 8

**Additional context**
My screen resolution is 1080x2280 and aspect ratio is 16:9

**Comment by amitojsingh366** [comment]
can you try a different browser?

**Comment by amitojsingh366** [comment]
dupe of #2483
