### ISSUE TITLE
Possibly incorrect label

### ISSUE THREAD

**Issue by mattmoody05** [benawad/dogehouse#2516]
**Describe the bug**
Label reading "GitHub/Twitter avatar URL" where I assume discord should be included too. I assume that this was forgotten when adding Discord auth back into DogeHouse.

**To Reproduce**
1. Go to the account page from dogehouse.tv/dash
2. Click "edit profile"
3. The incorrect label should now be on screen

**Expected behavior**
Expected label to read "GitHub/Twitter/Discord avatar URL"

**Screenshots**
![Screenshot 2021-05-03 at 07 38 48](https://user-images.githubusercontent.com/34244370/116847513-9b378e00-abe2-11eb-8da0-78d8c0297e8c.png)

**What device are you on?**
2011 Macbook Pro --> macOS 10.15.7 --> Safari

**Comment by amitojsingh366** [comment]
rn discord avatar urls aren't supported

**Comment by mattmoody05** [comment]
Went onto the website, my discord avatar shows up fine? (Still with the incorrect label)
![Screenshot 2021-05-03 at 07 56 18](https://user-images.githubusercontent.com/34244370/116848716-169a3f00-abe5-11eb-8112-aed6468c3526.png)

**Comment by amitojsingh366** [comment]
> 
> 
> Went onto the website, my discord avatar shows up fine? (Still with the incorrect label)
> ![Screenshot 2021-05-03 at 07 56 18](https://user-images.githubusercontent.com/34244370/116848716-169a3f00-abe5-11eb-8112-aed6468c3526.png)

ok this is a bug, when you register with discord your avatar works but after that you cannot set that discord url as an avatar, #2492 fixes this
