### ISSUE TITLE
English text on profile page in Dutch.

### ISSUE THREAD

**Issue by laurens-vrh** [benawad/dogehouse#2521]
**Describe the bug**
On a user profile page, the "block", "unblock", and "about" text is in English, while the rest is in Dutch.
These fields should say "Blokkeer", "Deblokkeer" and "Over".

**To Reproduce**
1. Change your language to Dutch.
2. Go to someone's profile page (eg. https://dogehouse.tv/u/benawad)
3. See error

**Expected behavior**
The block button should say "Blokkeer", and when clicked "Deblokkeer".
The about text should say "Over"

**Screenshots**
![image](https://user-images.githubusercontent.com/66695935/116860110-57a04c80-ac01-11eb-8828-c76fb6992e9f.png)

**What device are you on?**
Windows 10, Opera Browser

**Additional context**
The EN-NL translations:
- block = blokkeer
- unblock = deblokkeer
- about = over

**Comment by MeztliRA** [comment]
they probably haven't been translated yet, you can translate it and open a pull request

**Comment by dk-raw** [comment]
Yes, go to kibbeh/public/locales and find Dutch. It is pretty easy to translate yourself.

**Comment by laurens-vrh** [comment]
I tried that, but in the language file it all seems to have been translated, it just doesn't show on the site ..?

**Comment by laurens-vrh** [comment]
Console shows the same error as in #1807 . Only other texts aren't translated in my case.
When I change my language to something else, like Spanish, these texts stay in English, so it's not just a problem with the Dutch translation.

**Comment by rzsxdev** [comment]
I think it's just because some values are still hardcoded and not using the translations.

**Comment by dk-raw** [comment]
No, there are just not present in the json files or not translated. Go to `kibbeh/public/locales` and see for your own language.
