### ISSUE TITLE
Avatar URL is always "invalid"

### ISSUE THREAD

**Issue by dk-raw** [benawad/dogehouse#2534]
**Describe the bug**
The avatar url is always invalid even if I don't change it. Also, it wont accept any URL as an image

**To Reproduce**
1. Go to your profile page
2. Click on 'edit'
3. Do not change anything
4. Click Save or whatever it says

**Expected behavior**
Just save the changes and close

**Screenshots**

![Screenshot 2021-05-03 195513](https://user-images.githubusercontent.com/68110106/116906925-92c66e00-ac49-11eb-8ad4-514892676762.jpg)

![Screenshot 2021-05-03 195523](https://user-images.githubusercontent.com/68110106/116906938-978b2200-ac49-11eb-9ad7-a50d68458151.jpg)

![Screenshot 2021-05-03 195533](https://user-images.githubusercontent.com/68110106/116906946-99ed7c00-ac49-11eb-8ee7-f42581d6de01.jpg)

**What device are you on?**

Windows 10 pro for workstations desktop using Opera(chromium)

**Comment by TheOtterlord** [comment]
It's worth noting this bug is scoped to discord and is fixed by #2492

**Comment by dk-raw** [comment]
#2492 does not fix that

**Comment by amitojsingh366** [comment]
> #2492 does not fix that

it does fix it
