### ISSUE TITLE
Layering bug with search results on user page

### ISSUE THREAD

**Issue by thefakequake** [benawad/dogehouse#2535]
**Describe the bug**
The search results feed from the search bar appear beneath some of the content on the user's page.

**To Reproduce**
1. Go to a user's page
2. Search something in the search bar

**Expected behavior**
Search results would be on top of the user's page.

**Screenshots**
![image](https://user-images.githubusercontent.com/67868381/116918523-eafc7080-ac47-11eb-9940-c100608bee90.png)

**What device are you on?**
PC running Windows 10, using Microsoft Edge Chromium.

**Additional context**
None.

**Comment by amitojsingh366** [comment]
this was fixed in #2537
