### ISSUE TITLE
UI bug in /scheduled-rooms when scrolling

### ISSUE THREAD

**Issue by MaheshNat** [benawad/dogehouse#2538]
**Describe the bug**
When scrolling down the /scheduled-rooms page on desktop, the calendar icon, room host, and room host profile pic appear above the "Schedule room" button and search bar.

**To Reproduce**
1. Go to /scheduled-rooms
3. Scroll down

**Expected behavior**
The icons and text are hidden from view when scrolling down

**Screenshots**
![Screenshot from 2021-05-03 14-18-49](https://user-images.githubusercontent.com/44304651/116922118-824acf00-ac1a-11eb-95bf-80f15c68ab12.png)
![Screenshot from 2021-05-03 14-18-38](https://user-images.githubusercontent.com/44304651/116922125-84ad2900-ac1a-11eb-8b9d-f9ab7960230d.png)

**What device are you on?**
Ubuntu 20.04 LTS Chromium

**Comment by amitojsingh366** [comment]
this was fixed in #2537
