### ISSUE TITLE
Participants apper in front of "your feed" bar

### ISSUE THREAD

**Issue by KauanRakoski** [benawad/dogehouse#2539]
**Description of the bug**

Images of room participants appear in front of the "your feed" bar, when they are expected to appear behind it. I am using **Brave** as the browser app.

![image](https://user-images.githubusercontent.com/66558074/116922043-2f2d4800-ac2b-11eb-9cba-c1f7cebe19b9.png)

![image](https://user-images.githubusercontent.com/66558074/116922195-64d23100-ac2b-11eb-9ead-fdd3d2832242.png)

**Comment by amitojsingh366** [comment]
this was fixed in #2537
