### ISSUE TITLE
dogehouse cannot handle discord callback

### ISSUE THREAD

**Issue by aryaniyaps** [benawad/dogehouse#2543]
**Describe the bug**
I tried to login with discord but then the dogehouse api does not handle the callback.
It's an internal server error, I don't know what's wrong, wanted to let you know.

**To Reproduce**
1. Go to the dogehouse landing page
2. Click on login with discord
3. Authorize dogehouse from discord

**Expected behavior**
I want dogehouse to handle the callback and allow me to login with discord

**Screenshots**
![image](https://user-images.githubusercontent.com/69184573/116992096-243dea80-acf3-11eb-8ddc-7c227a6a7b76.png)

**What device are you on?**
Chrome Browser, Windows 10

**Comment by dk-raw** [comment]
works fine for me. Maybe cloudflare was down at that moment,

**Comment by huukhang1512** [comment]
![image](https://user-images.githubusercontent.com/52158153/117001798-266d6c80-ad26-11eb-99f3-9b97d22b3e12.png)

I also have this problem on my machine. It works really well when signing in with GitHub but not with Discord.

**Comment by BronzW** [comment]
I think this issue has already been declared here #2528

**Comment by TheOtterlord** [comment]
Closing as duplicate. #2528 will serve as the active issue
