### ISSUE TITLE
Duplicated whisper to yourself

### ISSUE THREAD

**Issue by Gers2017** [benawad/dogehouse#2550]
**Describe the bug**
Sending a whisper generate a duplicated message on the chat

**To Reproduce**
1. Go to https://dogehouse.tv
2. Click on "new room"
3. Creta a whisper ``` #@USERNAME ``` for yourself
4. Press enter and enjoy

**Expected behavior**
Only one message please

**Screenshots**
![daaaaa](https://user-images.githubusercontent.com/49139988/117042049-bb417d00-acc8-11eb-8f2d-f8f069a7c44d.png)
![daaaaaaaaaa22222](https://user-images.githubusercontent.com/49139988/117042071-c1cff480-acc8-11eb-8af2-29985e1f5961.png)

![bug123](https://user-images.githubusercontent.com/49139988/117041900-8fbe9280-acc8-11eb-8634-e5c6bbdbc3fa.png)
![bug1234](https://user-images.githubusercontent.com/49139988/117041921-93eab000-acc8-11eb-86db-9836682b8003.png)

**What device are you on?**
Laptop
**Additional context**
```No

```

**Comment by amitojsingh366** [comment]
I can reproduce this

**Comment by Gers2017** [comment]
you mean you can't?

**Comment by amitojsingh366** [comment]
> 
> 
> you mean you can't?

no i said i CAN. i agree with you, this is a thing
