### ISSUE TITLE
Navigation UI broken on iPhone 6 with safari browser

### ISSUE THREAD

**Issue by RobyCigar** [benawad/dogehouse#2563]
**Describe the bug**
The navigation link on room is broken.

**To Reproduce**
It appear everytime I join the room

**Expected behavior**
I think the navigation icon should be visible

**Screenshots**
![6BE8B727-FEB4-4F16-94E8-8317C4995FE1](https://user-images.githubusercontent.com/69680330/117135006-933d4100-add0-11eb-9c18-a319a39ec712.png)

**What device are you on?**
I’m using iPhone 6, with safari browser

**Additional context**

**Comment by nadirabbas** [comment]
this has been fixed with the new design
