### ISSUE TITLE
User interface blur on certain scale

### ISSUE THREAD

**Issue by DarrenOfficial** [benawad/dogehouse#2567]
**Describe the bug**
When you go to the website and try to edit your profile and you change your browser scaling it out of focus/blur

**To Reproduce**
1. Go to 'DogeHouse.tv'
2. Click on 'Edit Profile'
3. Change Scaling

**Expected behavior**
The text should stayed the same not blurry

**Screenshots**
[Bug Video](https://youtu.be/IbeBxIsNids)

**What device are you on?**
Laptop running Windows 10 on display size of 1366 x 768
Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by samarmohan** [comment]
That is expected behavior. Someone add https://github.com/benawad/dogehouse/labels/expected-behavior-but-awkward-and-could-get-rework

**Comment by DarrenOfficial** [comment]
RIP DogeHouse.
