### ISSUE TITLE
Unable to hear anything when switching to a new room unless reload

### ISSUE THREAD

**Issue by codicate** [benawad/dogehouse#2571]
**Describe the bug**
When I go back to the main menu with back button, and joining a new room, I can't hear anything unless I reload the page. I can however, hear voice cues, such as when I deafen myself.

Another thing is that sometimes I am able to hear the audio of the last room when I join a new room. This doesn't happen when I join a new room for the first time, as the I discribed earlier, I can't hear anything. But if I switch back to the old room and then back to the new room again, I would hear the audio of the old room while being in the new room. The room info display in the main page shows I am in the new room, while hearing old room audio.

However, if I go back to the main page, and manually leave the room by clicking on the leave button, and then join a new room, I would be able to hear audio of the new room correctly.

**To Reproduce**
1. Go to roomX
2. Go back to main page using navigation buttons/mouse side buttons/Dogehouse logo button
3. Join another roomY, you wouldn't be able to hear anything. Browser tab also no longer displays 'this page is playing audio' icon
4. Go back to main page
5. Go back to roomX, you wouldn't be able to hear anything
6. Go back to roomY, now you hear the audio of roomX

**What device are you on?**
Windows 10, Chrome Version 90.0.4430.93 (Official Build) (64-bit)
same thing happened on firefox developer edition 89.0b8 (64-bit)

**Comment by samarmohan** [comment]
This was fixed in https://github.com/benawad/dogehouse/commit/229d7b5a4d3f51e01d0458752ff69c1747ee765c
