### ISSUE TITLE
a better dogehouse logo

### ISSUE THREAD

**Issue by bruh2k** [benawad/dogehouse#2581]
pls help: https://gofund.me/8f289f03

![moJQ9b1V](https://user-images.githubusercontent.com/83729909/117209584-f601fd00-ae0f-11eb-9efe-e838a380722d.png)

**Comment by roselpadilla** [comment]
+ 1

**Comment by ashwnn** [comment]
https://benawad.gay/ for new favico?

**Comment by HopeTS** [comment]
+1

**Comment by roselpadilla** [comment]
Yes, I agree.

**Comment by pessip** [comment]
+1

**Comment by roselpadilla** [comment]
+1

**Comment by ashwnn** [comment]
![image](https://user-images.githubusercontent.com/69374625/117204168-d1247000-ada4-11eb-93d0-603c9ab3295c.png)
Urgent issue regarding UI design. Current logo is gay

**Comment by HopeTS** [comment]
http://benawad.gay

**Comment by nadirabbas** [comment]
@ax20 nice design

**Comment by ashwnn** [comment]
Thanks it was curated by my frontend team, They thought it would be the best class of action for the company. Would you be intrested in a collabration?

**Comment by bruh2k** [comment]
![moJQ9b1V](https://user-images.githubusercontent.com/83729909/117204626-f7c8c200-ae09-11eb-94ec-32d56c563ea9.jpg)

**Comment by bruh2k** [comment]
hey refresh

**Comment by bruh2k** [comment]
@benawad they forced me

**Comment by ax20** [comment]
![d21](https://user-images.githubusercontent.com/69374625/117205645-c074f980-ada6-11eb-95a1-8033c469be76.jpg)
New twitter  banner?

**Comment by bruh2k** [comment]
https://www.change.org/p/ben-awad-petition-to-change-dogehouse-tv-logo-to-fck-sh?recruiter=1200944809&utm_source=share_petition&utm_medium=copylink&utm_campaign=share_petition

**Comment by ashwnn** [comment]
![ben + angular](https://user-images.githubusercontent.com/69374625/117207192-86a4f280-ada8-11eb-9646-d6a47db6d656.jpg)

**Comment by bruh2k** [comment]
![Uploading moJQ9b1V.jpg…]()

no body can surpass this

**Comment by bruh2k** [comment]
![moJQ9b1V](https://user-images.githubusercontent.com/83729909/117207424-5e031400-ae0d-11eb-94fd-b1ac54461bc9.jpg)
no body can beat this masterpiece

**Comment by KristofKekesi** [comment]
# Why angular is the best framework

https://www.digitaldoughnut.com/articles/2018/december/why-angular-is-the-best-framework

**Comment by bruh2k** [comment]
@KristofKekesi  i angree

**Comment by LeulAria** [comment]
LOL you guys

**Comment by bruh2k** [comment]
@benawad

**Comment by LeulAria** [comment]
you can't even crop

**Comment by ZohebMOPO** [comment]
an array of memes😂

**Comment by goldyydev** [comment]
Going to close this just so I can get 20 dislikes, which are a lot on GitHub

**Comment by ax20** [comment]
tygngf
