### ISSUE TITLE
Can't edit bio in profile page

### ISSUE THREAD

**Issue by NuttakitDW** [benawad/dogehouse#259]

**Comment by tejxv** [comment]
I think they're actually extracted from your github account, so to update your bio you need to change it on github and the changes should reflect automatically.

**Comment by NuttakitDW** [comment]
> I think they're actually extracted from your github account, so to update your bio you need to change it on github and the changes should reflect automatically.

Unfortunately, I try it already but it doesn't change even I had change my bio on github.

**Comment by gsdeveloper** [comment]
Duplicate of #73, #106 and #137. It's being [worked on](https://github.com/benawad/dogehouse/projects/1#card-54870754).

**Comment by nadirabbas** [comment]
The bio is saved in the database, so it should be changeable here without changing it on Github.

**Comment by okket** [comment]
Changing bio only on Dogehouse might lead to some nasty NSFW stuff...

**Comment by fillipvt** [comment]
At least have a way to pull updates from the bio.

I just updated mine but dogehouse still has the old one

**Comment by nadirabbas** [comment]
Ben is working on it.
