### ISSUE TITLE
https://github.com/[username].png is not allowed as profile image

### ISSUE THREAD

**Issue by luwol03** [benawad/dogehouse#2598]
**Describe the bug**
Github profile image regex doesn't allow [username].png

**To Reproduce**
1. Go to 'edit profile'
2. Set profile image to `https://github.com/[your username].png`
3. Click on 'Save'
4. See error 'Invalid image'

**Expected behavior**

Save profile image URL.

**Screenshots**

![image](https://user-images.githubusercontent.com/60048565/117264143-3cc51680-ae53-11eb-986d-92b271478bdf.png)

**What device are you on?**

not device spefific (I use Chrome, the only valid browser :smile:  )

**Additional context**

**Comment by amitojsingh366** [comment]
this is intended as we don't have a image reporting system as of right now, when we get that we probably will also get custom images *(not only custom github images)*

**Comment by luwol03** [comment]
No, we could try to make a regex which allows only `https://github.com/[username].png` and nothing from the gh content pictures. 
Sorry for the late report on github, but I totally forgot about it. [see bens message on discord](https://discord.com/channels/810571477316403233/810571477770174506/836999049261088769)

**Comment by amitojsingh366** [comment]
> 
> 
> No, we could try to make a regex which allows only `https://github.com/[username].png` and nothing else.
> Sorry for the late report on github, but I totally forgot about it. [see bens message on discord](https://discord.com/channels/810571477316403233/810571477770174506/836999049261088769)

from the message you've linked me to it seems like ben wants more sources not only `https://github.com/[username].png` and i feel that shouldn't be so hard. 
@nadirabbas you added a few regexs before right? why don't you go ahead and add this?

**Comment by jobveldhuis** [comment]
Are Github images always png? In that case, this regex should do the trick:
`^(^https?:\/\/github\.com\/)([a-zA-Z0-9_-]*)\.(png)$`

If the images could also be jpeg, this should work:
`^(^https?:\/\/github\.com\/)([a-zA-Z0-9_-]*)\.(png|jpg|jpeg)$`

**Comment by luwol03** [comment]
Since this project is no longer under active development and I'm cleaning up my open issue list, I'll close that for now.

**Comment by nadirabbas** [comment]
> Since this project is no longer under active development and I'm cleaning up my open issue list, I'll close that for now.

"for now"?

**Comment by luwol03** [comment]
> > Since this project is no longer under active development and I'm cleaning up my open issue list, I'll close that for now.
> 
> 
> 
> "for now"?

I don't know, maybe this project will be resumed.
