### ISSUE TITLE
Scheduled room is not displayed after reload?

### ISSUE THREAD

**Issue by neinkopp** [benawad/dogehouse#2601]
**Describe the bug**
When I schedule a new room, it gets displayed right away, and I can interact with it.

**To Reproduce**
1. Go to home page
2. Click on the plus button at "scheduled rooms"
3. Enter room details
4. Room is shown right away, if you reload (Ctrl+R), it goes away.

**Expected behavior**
The room should obviously stay scheduled, or did I something wrong? Is this supposed to work differently?

**Screenshots**
![image](https://user-images.githubusercontent.com/66413542/117281258-c086ff00-ae63-11eb-8f14-b1bb8a9b2c53.png)
After reloading:
![image](https://user-images.githubusercontent.com/66413542/117281290-c67ce000-ae63-11eb-95a2-0a74d98d36e2.png)

**What device are you on?**
Brave: 1.24.82 
Chromium: 90.0.4430.93 (Official Build) (64-bit)
Revision: 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS: Windows 10 OS Version 2004 (Build 19041.84)
JavaScript: V8 9.0.257.23
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Github account

**Additional context**
I tested this on kibbeh (Brave Browser) and baklava (Windows 10). Could be a bug with the (shadow) ban system?!

**Comment by amitojsingh366** [comment]
~~i can reproduce this issue~~ nvm i can't

**Comment by amitojsingh366** [comment]
after reloading your scheduled room goes down the list according to the time it was scheduled at, this is why you don't see it there anymore. if you scroll you should be able to see it

**Comment by neinkopp** [comment]
Is there a limit to how many scheduled rooms are displayed? Because I scheduled a room for the next month and it doesn't show up. I think the rooms which are scheduled to a later date should be lazy-loaded, which they don't do atm.
