### ISSUE TITLE
Can't use `Ctrl + TAB` shortcut key in any application while the desktop application is open

### ISSUE THREAD

**Issue by gargakshit** [benawad/dogehouse#2605]
**Describe the bug**
When the `Ctrl + TAB` shortcut key is pressed, the currently selected windows loses focus (and the dogehouse window doesn't gain focus either). The issue is gone after dogehouse is closed. `Ctrl + Shift + TAB` seems to work just fine

**System Information**

- **OS**: Windows 10
- **Dogehouse Version** - 1.0.63

**To Reproduce**
1. Open dogehouse desktop application
2. Focus any other application while dogehouse is still running
3. Press `Ctrl + TAB`
4. Current window loses focus

**Expected behavior**
If it is a dogehouse shortcut, dogehouse should gain focus (or display a popup with click pass through enabled in case it is push to talk), or `Ctrl + TAB` should work as intended in the other application. Also if this is the decided shortcut for some dogehouse action, consider changing it as `Ctrl + TAB` is used in a lot of applications. For example

- Most browsers - change tabs
- VSCode - change tabs
- Telegram - change chats

**What device are you on?**
Windows 10, DogeHouse desktop

**Comment by amitojsingh366** [comment]
yes this is a dogehouse shortcut, it's a shortcut for the unfinished "overlay" feature that is supposed to overlay a window on another window of yours. you can change the shortcut in profile > overlay settings. i will change the default later today

**Comment by gargakshit** [comment]
> yes this is a dogehouse shortcut, it's a shortcut for the unfinished "overlay" feature that is supposed to overlay a window on another window of yours. you can change the shortcut in profile > overlay settings. i will change the default later today

Cool, thanks
