### ISSUE TITLE
SSR the Users page's OpenGraph tags

### ISSUE THREAD

**Issue by frissyn** [benawad/dogehouse#2609]
I think it's pretty safe to say that Dogehouse falls under the umbrella category of "Social Media", so I think it'd be worthwhile to add OpenGraph metadata and standard HTML metadata to different pages. Posting a link to a room, user, etc. would have its properties changed to reflect the content.

For example, a [user page](https://dogehouse.tv/u/frissyn) could look like:
```html
<head>
...
<meta property="og:site_name" content="Dogehouse">
<meta property="og:title" content="frissyn | Dogehouse"/>
<meta property="og:url" content="https://dogehouse.tv/u/frissyn"/>
<meta property="og:image:url" content="https://avatars.githubusercontent.com/u/62220201"/>
...
</head>
```

And you can imagine how it'd look for rooms and all that jazz. Using the [Open Graph Docs](https://ogp.me/) you could do some pretty cool stuff. I'd love to work on it myself, but looking at the GitHub source is pretty daunting and I don't even know where I'd begin to add this functionality. 👍🏽

**Comment by JDOG787** [comment]
Good idea! I think I'd like to tackle this if that's ok

**Comment by goldyydev** [comment]
We do have them, we can't send them to the server due to the users page being client side rendered.

**Comment by frissyn** [comment]
So you'd just need to make them server-side rendered, which makes sense
