### ISSUE TITLE
Word mistake

### ISSUE THREAD

**Issue by Bilal-Akkil** [benawad/dogehouse#2619]
https://github.com/benawad/dogehouse/blob/da73ee624c3879179b3abe5aa17e82b70cb4bd73/kibbeh/public/locales/ar/translation.json#L235

Instead of the word اصدفاء
It should be اصدقاء

**Comment by dk-raw** [comment]
It is very easy to fix it yourself. Do you want me to assign you? (make sure you run `yarn commit` and follow the conventional commit format)

**Comment by Bilal-Akkil** [comment]
> It is very easy to fix it yourself. Do you want me to assign you? (make sure you run `yarn commit` and follow the conventional commit format)

I actually just found out about DogeHouse, so I was hoping if you would tell me where to find the instructions to update them my self.

**Comment by BronzW** [comment]
CONTRIBUTING.md

**Comment by dk-raw** [comment]
1. Fork the repository
![image](https://user-images.githubusercontent.com/68110106/117442026-e7663380-af3e-11eb-84aa-67fc17aacc30.png)

2. in the forked repository, go to `kibbeh/public/locales/ar/translation.json`

3. click on `edit`

![image](https://user-images.githubusercontent.com/68110106/117442166-141a4b00-af3f-11eb-9dde-d4aded906159.png)
4. make the changes on the translation

5. click commit changes and add `fix(kibbeh): update Arabic Translations ` as the commit message(leave the description empty)
![image](https://user-images.githubusercontent.com/68110106/117442435-6e1b1080-af3f-11eb-990f-9a1a270fef29.png)

6. go to the main folder view and click `pull request` or `fetch upstream`
![image](https://user-images.githubusercontent.com/68110106/117442650-bafee700-af3f-11eb-9abd-e7ced2ca4be8.png)

**Comment by amitojsingh366** [comment]
i believe you have changed this in #2627
