### ISSUE TITLE
Highlight dominant speaker when you connect to a channel, rather than just after the speaker changes

### ISSUE THREAD

**Issue by corysimmons** [benawad/dogehouse#262]
Not sure if this is intentional because I can't figure out how it would've regressed. 🤔

**Comment by nadirabbas** [comment]
What do you mean by dominant speaker cory?

**Comment by corysimmons** [comment]
In channels, when one person is speaking louder than everyone else, they are the "dominant speaker". In calls like Google Meet, Slack calls, etc. They frequently will switch the camera to the dominant speaker.

In Dogehouse, Ben was putting a blue (? I'm colorblind) border about 2px wide around the dominant speaker while they were talking (to indicate who was currently talking), but it doesn't seem to work anymore.

**Comment by corysimmons** [comment]
Scratch that, I just checked again and it is working.

The problem I was experiencing is there would be 1 consistent dominant speaker for a long time when I was joining channels, and no one would have a border around them.

It turns out, the border begins appearing after the first change of dominant speaker, rather than appearing on the dominant speaker whenever you join a room.

You can test this by joining a channel that is playing music or something. There won't be a border around them.

>Not super important now that I see what's going on, but it'd be a nice tweak so you'd know who was talking if you joined a channel while one person was in the middle of a big rant.

**Comment by nadirabbas** [comment]
Yes I noticed that, I'll try to figure out the problem and probably push submit a PR.

**Comment by benawad** [comment]
should be fixed now
