### ISSUE TITLE
Insert translation 

### ISSUE THREAD

**Issue by Bilal-Akkil** [benawad/dogehouse#2620]
https://github.com/benawad/dogehouse/blob/da73ee624c3879179b3abe5aa17e82b70cb4bd73/kibbeh/public/locales/ar/translation.json#L295

The translation should be 
تم تعطيل المحادثة

**Comment by dk-raw** [comment]
It is very easy to fix it yourself. Do you want me to assign you? (make sure you run `yarn commit` and follow the conventional commit format)

**Comment by amitojsingh366** [comment]
i believe you have added this yourself in #2627
