### ISSUE TITLE
Chat with People 

### ISSUE THREAD

**Issue by AlishahMughal123** [benawad/dogehouse#2626]
Umm I`ve a suggestion , why not to create a chat box with the person we want to talk, like if I want to talk with someone privately, so this`ll good if you guys introduce chat thing .

Thanks

**Comment by samarmohan** [comment]
We have a whisper feature, which is like a private message. Do #@USERNAME message

**Comment by AlishahMughal123** [comment]
I don`t think so.

**Comment by goldyydev** [comment]
This is the DM's feature, it is currently being worked on.

#576 and the DogeLogs
