### ISSUE TITLE
Report user 

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2634]
**Is your feature request related to a problem? Please describe.**
No, I want to work on a report user system for dogehouse.

**Describe the solution you'd like**
Maybe In a room you can click on a user and report it and or report them from their account page.

**Describe alternatives you've considered**
We could always just message mods but, that inconvenient.

**Additional context**
We need this system before we can add profile picture uploading.

**Comment by samarmohan** [comment]
We're working on that.
