### ISSUE TITLE
Leaving groups should be alot easier.

### ISSUE THREAD

**Issue by NickersWeb** [benawad/dogehouse#2649]
**Is your feature request related to a problem? Please describe.**
Frustrating when you've been in multiple abandoned groups and the only way to clear your logs is to manually leave each and every group. This can be very time consuming and annoying. Just think of discord and how you can't leave multiple groups at once. 

**Describe the solution you'd like**
Ability to select all groups at once and then the user can select which groups they still want to stay in. Hopefully that should reduce the amount of time it takes. Then throw a pop up to confirm this action.
A clear and concise description of what you want to happen. Potentially a checkbox to ask if you want to notify people of the groups because then users are going to be spammed with this client leaving all those groups. Perhaps don't even notify them.

**Comment by amitojsingh366** [comment]
what groups are you talking about?

**Comment by NickersWeb** [comment]
As long rooms cannot be followed, then this shouldn't be a issue.
