### ISSUE TITLE
Windows App Github signin with webauthn

### ISSUE THREAD

**Issue by VeeBack** [benawad/dogehouse#2658]
**Describe the bug**
When signing in with github with an account that has added a security key, asks for the key, but then pops up a normal browser with the URL `https://github.com/sessions/two-factor/webauthn`

**To Reproduce**
1. Open up the Windows Desktop app and press `Log in with GitHub`
2. Put in your credentials
3. Press `Use security key`
4. Press the butten on your security key
5. A windows will pop up in regular chrome with the URL `https://github.com/sessions/two-factor/webauthn` with a 404 page. The app is still not authenticated. 

**Expected behavior**
The login flow should be completed, and I should have access to DogeHouse

**What device are you on?**
Windows 10

**Comment by amitojsingh366** [comment]
@HVEVB can you try again with the latest version?

**Comment by VeeBack** [comment]
It does indeed work. Thank you :)

**Comment by amitojsingh366** [comment]
np!
