### ISSUE TITLE
Add string "aboutStuffix" to "profileTabs" object (kibbeh/localization)

### ISSUE THREAD

**Issue by tarikcoskun** [benawad/dogehouse#2662]
**Is your feature request related to a problem? Please describe.**
In some languages, the word "about" comes after the name and if this is the case for the language, it looks a little bit stupid. As example, normally you would say "About me" but it would be "Me about" in this case.

**Describe the solution you'd like**
A string named "aboutSuffix" can be added to "profileTabs" object and it would be used instead of the normal "about" string if this is the case for the language.

Example usage in Turkish:
```json
"profileTabs": {
  "about": "",
  "aboutSuffix": "hakkında"
},
```

Example usage in English:
```json
"profileTabs": {
  "about": "About",
  "aboutSuffix": ""
},
```

**Additional context**
![unnamed](https://user-images.githubusercontent.com/44239968/117555271-7e79db00-b066-11eb-9aca-89e9d9e6f35f.png)
*Normally, the word "About" comes after the name in Turkish language*

![unnamed2](https://user-images.githubusercontent.com/44239968/117555334-006a0400-b067-11eb-82fc-e477b3cc474a.png)
*The word "About" comes first in the website*

**Comment by amitojsingh366** [comment]
makes sense, you can go ahead and add this if you want or wait until someone implements it
