### ISSUE TITLE
trouble adding translation component

### ISSUE THREAD

**Issue by MeztliRA** [benawad/dogehouse#2666]
i tried adding adding a translation component, and there doesnt seem to be the `gen:i18:keys` script and `translationKeys.ts` file

**Comment by amitojsingh366** [comment]
please follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#translating

**Comment by MeztliRA** [comment]
> please follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#translating

im trying to follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#supporting-translation-in-new-components

but the `gen:i18:keys` script and `translationKeys.ts` file doesn't exist.

**Comment by amitojsingh366** [comment]
> 
> 
> > please follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#translating
> 
> im trying to follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#supporting-translation-in-new-components
> 
> but the `gen:i18:keys` script and `translationKeys.ts` file doesn't exist.

where are you running the command and also could you please ask this on the [discord server](https://discord.com/invite/wCbKBZF9cV), i could provide you with one on one help there

**Comment by MeztliRA** [comment]
> > > please follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#translating
> > 
> > 
> > im trying to follow https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md#supporting-translation-in-new-components
> > but the `gen:i18:keys` script and `translationKeys.ts` file doesn't exist.
> 
> where are you running the command and also could you please ask this on the [discord server](https://discord.com/invite/wCbKBZF9cV), i could provide you with one on one help there

i pinged you in the server
