### ISSUE TITLE
Error page at the "scheduled" section on responsive view

### ISSUE THREAD

**Issue by orzklv** [benawad/dogehouse#2667]
**Describe the bug**
Renders error screen when you press the scheduled section on responsive view.

**To Reproduce**
1. Set the language to Owo Engwish
2. Go responsive
![Screenshot (32)](https://user-images.githubusercontent.com/54666588/117562241-d3ddd880-b0b6-11eb-812a-0d5b8972a508.png)
3. Click on 'second section button'
![Screenshot (32) - Copy_LI](https://user-images.githubusercontent.com/54666588/117562254-e9530280-b0b6-11eb-877d-cef046164643.jpg)
4. Enjoy the error
![Screenshot (31)](https://user-images.githubusercontent.com/54666588/117562263-fe2f9600-b0b6-11eb-8aef-2a79d7546579.png)

**What device are you on?**
Windows 10 Latest Update
Core-i7 GTX2060 and whole PC is Gigabyte

![Screenshot (33)](https://user-images.githubusercontent.com/54666588/117562304-64b4b400-b0b7-11eb-82ce-cf4aa64e8dd8.png)

**Comment by orzklv** [comment]
Also, I found out that it happens only on OwO Engwish. `I guess, the translation pack is not fully translated.`

**Comment by orzklv** [comment]
**English itself is working well btw**

![Screenshot (34)](https://user-images.githubusercontent.com/54666588/117562540-23250880-b0b9-11eb-8661-b753a05ad4b5.png)

**To Reproduce** note updated!

**Comment by amitojsingh366** [comment]
i can reproduce this on both the app and the browser

**Comment by ajmnz** [comment]
Can reproduce on prod, not locally
