### ISSUE TITLE
AUR installer does not install required npm packages beforehand

### ISSUE THREAD

**Issue by orzklv** [benawad/dogehouse#2674]
**Describe the bug**
While installing dogehouse from aur, it throws an error saying that there are a few packages that should be installed

**To Reproduce**
1. Just try to install dogehouse on a machine with no nodejs installed

**Expected behavior** + **Screenshots**
![Screenshot from 2021-05-09 17-06-14](https://user-images.githubusercontent.com/54666588/117571715-2b953780-b0e9-11eb-8896-732b1d07b192.png)

**What device are you on?**
![Screenshot from 2021-05-09 17-08-58](https://user-images.githubusercontent.com/54666588/117571747-44055200-b0e9-11eb-8d6e-b2b8ad0a07f9.png)

**Comment by saihnii4** [comment]
i'm pretty sure that it actually installs nj-cli (which is a rust crate), but by default, the path where nj-cli is installed (which is usually `~/.cargo/bin`) is not in `$PATH`, causing this error
