### ISSUE TITLE
Stay on tray

### ISSUE THREAD

**Issue by orzklv** [benawad/dogehouse#2680]
**Is your feature request related to a problem? Please describe.**
While talking in the channel, I may close it unexpectedly and it will shut the instance down.

**Describe the solution you'd like**
Make the app stay on tray even if the last window gets closed

**Describe alternatives you've considered**
I dunno how it can be done but... I think it can be done through services. I mean creating an instance service which will save the last session and hold it till the app gets connected.

**Additional context**
Also, I'd like to get the tray feature available on linux desktop environments like Gnome or KDE

**Comment by ajmnz** [comment]
@amitojsingh366

**Comment by amitojsingh366** [comment]
yea this is planned but will not be implemented for a while
