### ISSUE TITLE
desktop app problem with 2fa twitter accounts (in my case linux)

### ISSUE THREAD

**Issue by Baggiest** [benawad/dogehouse#2682]
so im running ubuntu and i download the app, but there is a slight problem

for Twitter accounts with 2factor auth when you enter the code it redirects to an external browser, and the external browser would always throw a 403 at you, and you cant login at all

sorry I don't know how to use labels in bug reports like a normal human being 

![image](https://user-images.githubusercontent.com/76979204/117584243-0fad8800-b121-11eb-9921-3a5414ab52d2.png)

**Comment by amitojsingh366** [comment]
could you try in the latest version and see if the issue still persists?

**Comment by Baggiest** [comment]
sure

wait a sec

**Comment by Baggiest** [comment]
sheesh flawless its perfect

but there is a weird transition and stuff when you enter the password wrong, but you can close and open dogehouse, it goes away
