### ISSUE TITLE
The Follower Only tag interferes with chat.

### ISSUE THREAD

**Issue by chalkedgoose** [benawad/dogehouse#2686]
**Describe the bug**
The follower only tag interferes with the chat 
logs visually.

**To Reproduce**
1. Go to dogehouse room
2. Set it to Follower only mode in the chat
3. Type a couple of inputs in the chat a bit 

**Expected behavior**
I expected the chat not be overlapped by the Follower only tag

**Screenshots**
![pHv5SRB](https://user-images.githubusercontent.com/26678464/117602142-d2d39800-b104-11eb-8685-87906c39535b.png)

**What device are you on?**
2021 Macbook Pro 16 inch 

**Additional context**
Chrome browser and MacOS Big Sur

**Comment by NickersWeb** [comment]
Could not reproduce... seems to currently work ... https://i.imgur.com/a5AtJiG.png
