### ISSUE TITLE
Report users: Moderation 

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2690]
**Is your feature request related to a problem? Please describe.**
No, I noticed that the report users was under needs thinking and I have an idea.

**Describe the solution you'd like**
We could have a moderation page where mods can ban, temp-ban, reset userdata and much more. I think that this will allow doge house to have lots more features that it otherwise may have never had.

**Describe alternatives you've considered**
So far, I have not thought of any other ways to do this.

**Additional context**
Not really.

**Comment by TheOtterlord** [comment]
Sounds like a good idea, but please keep all discussion about this in a single issue. The issue for the reporting system is #449
