### ISSUE TITLE
Gif reaction in chat messages.

### ISSUE THREAD

**Issue by chalkedgoose** [benawad/dogehouse#2694]
**Is your feature request related to a problem? Please describe.**
 An issue for a supporting feature (gif search in chat) was previously mentioned in #2657, but I would like support 
for rendering gifs in the dogehouse room chat as an alternative form of expression to Emojis. 

**Describe the solution you'd like**
I would like a component that could be integrated into the messages of
the dogehouse room and render images in a visually consistent format.

- gif source gating (allowlist) probably Tenor & Giphy links
- visual rendering of the gifs into a visually consistent image component

**Describe alternatives you've considered**
I have not considered alternative solutions besides just outright sharing the link to the external gif.

**Additional context**
We could release and test this feature fairly quickly since we'd just need to render image links and not implement the logic mentioned in #2657 like gif search, integration into the message input box and complications arising from sorting/visually organizing a selection of gifs. And if/when #2657 is released this feature could support it.

Similar feature on discord

<img width="300" alt="Screen Shot 2021-05-10 at 2 42 33 PM" src="https://user-images.githubusercontent.com/26678464/117728231-06aecc00-b19e-11eb-80e8-76721d316089.png">

**Comment by NickersWeb** [comment]
[Pull request](https://github.com/benawad/dogehouse/pull/2695) has already been closed
