### ISSUE TITLE
hire 1 ui designer to design dogehouse

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#271]

**Comment by ajmnz** [comment]
I've been sketching some ideas over the past days just for fun, so I might be able to help.

**Comment by darshgun** [comment]
I like to contribute to the project

**Comment by mohammedgad** [comment]
I know some good candidates.

**Comment by ajmnz** [comment]
Any news on this @benawad? Got some concepts I'd like to show you.

**Comment by benawad** [comment]
I'm going to be hiring 1 experienced ui designer to architect the entire design system for dogehouse (I don't want the design to be inconsistent with multiple people trying to contribute). I will leave it up to them if they would like help.

**Comment by ajmnz** [comment]
Guess I'll leave them here then 😅 

![dh-login](https://user-images.githubusercontent.com/57961822/108506021-7bb5e800-72b8-11eb-9746-fa58de0eb41b.png)
![dh-dashboard](https://user-images.githubusercontent.com/57961822/108506017-7a84bb00-72b8-11eb-913f-fb343ab27388.png)

**Comment by ChannelJuanNews** [comment]
Wow that design look sick

**Comment by DGKSK8LIFE** [comment]
If you want, I can also design for you @benawad

**Comment by ajmnz** [comment]
Did you get a chance to check the concepts, @benawad? If you haven't found anyone already, I might be the one you're looking for 🤞🏼

**Comment by benawad** [comment]
@ajmnz yeah that design is my favorite so far, I'll be picking a designer in a couple days

**Comment by ajmnz** [comment]
@benawad Sounds good! I'll keep an eye for any updates then 👍🏼

**Comment by jhgeluk** [comment]
@benawad Who was the designer? I'm also looking for a designer!

**Comment by amitojsingh366** [comment]
> @benawad Who was the designer? I'm also looking for a designer!

it was @ajmnz
