### ISSUE TITLE
just a typo

### ISSUE THREAD

**Issue by noahdepalma** [benawad/dogehouse#2711]
https://github.com/benawad/dogehouse/blob/63f392248193c7193cd7cb396b1243c84c5fde9f/pilaf/src/pages/CreateRoomPage.tsx#L114

I guessing "fileds" was meant to say "fields"

**Comment by troler36** [comment]
This gives me flashbacks to Linux Kernel crack

**Comment by ghost** [comment]
Make a PR.

**Comment by noahdepalma** [comment]
I will

**Comment by noahdepalma** [comment]
I don't know how to

**Comment by josephshepin** [comment]
fork the repo, clone it to your computer, edit the code, commit it back to your fork repo and then click the "pull requests" tab above and merge your fork into the main repo

**Comment by noahdepalma** [comment]
thx

**Comment by isaxk** [comment]
> fork the repo, clone it to your computer, edit the code, commit it back to your fork repo and then click the "pull requests" tab above and merge your fork into the main repo

Or you could just find the file online, click the edit icon and GitHub will do most of it for you

**Comment by josephshepin** [comment]
that works too. But if you don't know how to do a PR, might be a good time to learn 👍🏻
