### ISSUE TITLE
Feature Suggestion: PWA

### ISSUE THREAD

**Issue by epic-developer** [benawad/dogehouse#2712]
Making Dogehouse into a progressive web app would be very cool! A notification system implemented along with this would also be cool.

**Comment by loftwah** [comment]
https://www.pwabuilder.com/ is an awesome tool that could do this.

**Comment by ghost** [comment]
I implemented this a while back,  but Ben expressed that he doesn't want a service worker. The manifest is here, so on mobile, you can install it like you normally would.

**Comment by Odyssey346** [comment]
![Uploading Screenshot_20210514-004805_One UI Home.jpg…]()

**Comment by ghost** [comment]
![Screenshot_20210514-004805_One UI Home](https://user-images.githubusercontent.com/57069715/118196924-21a76780-b44e-11eb-8beb-927c9b02279b.jpg)

**Comment by amitojsingh366** [comment]
> I implemented this a while back, but Ben expressed that he doesn't want a service worker. The manifest is here, so on mobile, you can install it like you normally would.

i'm gonna close this based on the quoted comment
