### ISSUE TITLE
Cannot switch back to English after you change profile language.

### ISSUE THREAD

**Issue by leocrawf** [benawad/dogehouse#2731]
**Describe the bug**

**To Reproduce**
1. Go to 'any page'
2. Click on 'profile/langauge then select a language'
3. .....
4. English is not listed as a language, so if you are really English speaking and click on another language you cannot change back to English.

**Expected behavior**
Should be able to change from English to another language and then back to English.

**Comment by amitojsingh366** [comment]
i am able to switch back, are you sure you looked through the list properly?

**Comment by Poshy163** [comment]
Yeah so am I, you may of not looked for it hard enough.

**Comment by samarmohan** [comment]
I can switch back too. Can you send a screenshot?

**Comment by samarmohan** [comment]
Once #2744 gets merged try again.
