### ISSUE TITLE
Search: show no results message when there only 2 characters typed

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2733]
## Searchbar Message
Currently it takes at least more than 2 characters in the searchbar to trigger the actual search. If someone doesn't type more than 2 characters, they'l get an blank search result box. It would be nice to get a hint or the "no results" message :)

![Bildschirmfoto 2021-05-13 um 11 45 58](https://user-images.githubusercontent.com/10587159/118109204-2d107980-b3e1-11eb-9103-e6bf77622e16.png)

**Comment by XfaonXE** [comment]
I think thats something with SQL, or maybe its just coded like that
