### ISSUE TITLE
Login Page flashes when navigating to base URL

### ISSUE THREAD

**Issue by NickersWeb** [benawad/dogehouse#2735]
**Describe the bug**
When logged in and navigating to the base url e.g. "https://dogehouse.tv/", the login screen flashes for a split second. 
Potentially not handling authenticated users and seem to navigate away from login screen.

**To Reproduce**
1. navigate to base url when logged in.
2. See login page flash before navigating to dash.

**Expected behavior**
Authenticated uses should automatically be on dash from root. 
React Route for "/" && "/dash" should be the same. 

**Screenshots**
Have video if required.

**What device are you on?**
Windows 10 PC Edge Browser

**Comment by samarmohan** [comment]
Yeah, that is expected. We can't really do anything because the login screen needs to recognize the tokens, can't stop that from happening.

**Comment by NickersWeb** [comment]
Is this a related issue with oauth then?

**Comment by samarmohan** [comment]
It is not an issue. It's probably https://github.com/benawad/dogehouse/labels/expected-behavior-but-awkward-and-could-get-rework
