### ISSUE TITLE
Add electron builds to releases

### ISSUE THREAD

**Issue by arhammusheer** [benawad/dogehouse#274]
The electron wrapper `baklava` exists and has scripts set up to build electron app packages.

Add binaries of the builds to the releases of the repository so that people can use the electron client without building from the source.

**Comment by benawad** [comment]
How does oauth work for electron?

**Comment by arhammusheer** [comment]
For now the electron app is only loading the website from the domain and uses built in caching to decrease loadtimes. The github callback was configured to redirect to dogehouse.tv so I could not run the react app locally.

**Comment by TheOtterlord** [comment]
The binaries are available in [releases](https://github.com/benawad/dogehouse/releases). You can download the latest version [here](https://github.com/benawad/dogehouse/releases/latest).
