### ISSUE TITLE
add a loader when searching for stuff

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#2741]
sometimes it takes a little while to load the results when searching stuff on dogehouse. A loader would be nice.
![image](https://user-images.githubusercontent.com/38838675/118152962-c74ade80-b42e-11eb-8ff9-4352283ef60f.png)

**Comment by akashrajum7** [comment]
I would like to work on this and https://github.com/benawad/dogehouse/issues/2733 and create a PR if it's okay.

**Comment by samarmohan** [comment]
How is your progress in #2733 @akashrajum7?

**Comment by akashrajum7** [comment]
Haven't started working on it, would you like to take it up? @samarmohan
