### ISSUE TITLE
Auth only needs refresh token

### ISSUE THREAD

**Issue by sohank1** [benawad/dogehouse#2745]
If you send a bad access token and a good refresh token. Server will send you a new access token. This is really bad because now a hacker only needs someone's refresh token to make requests as them.

**Comment by samarmohan** [comment]
Close this issue now and privately reach out to Ben. https://github.com/benawad/dogehouse/blob/staging/SECURITY.md

**Comment by samarmohan** [comment]
Don't submit issues if there is a security issue.

**Comment by benawad** [comment]
This is expected behavior, access token is only used for caching purposes

**Comment by sohank1** [comment]
Oh wow, I think it would be more secure if you checked if the access token has valid signature and is not expired at least before letting the user authenticate.
