### ISSUE TITLE
Profile is unsearchable 

### ISSUE THREAD

**Issue by amitojsingh366** [benawad/dogehouse#2755]
**Describe the bug**
i'm unable to search for @goldyydev on dogehouse, his username is [`____`](https://dogehouse.tv/u/____) and when i search for it i don't get any relevant results

**To Reproduce**
1. Go to 'dogehouse'
2. Click on 'searchbar'
3. Search for `____`

**Expected behavior**
I should be able to get his profile in the results 

**Screenshots**
<img width="679" alt="Screen Shot 2021-05-14 at 2 48 07 PM" src="https://user-images.githubusercontent.com/35400192/118266532-691c0b00-b4c3-11eb-8083-20b1a353cd6c.png">
**What device are you on?**
macOS 11.2.3, brave browser
**Additional context**
i wanted to give @goldyydev badges as he's a collaborator and contributor so i searched his username

**Comment by amitojsingh366** [comment]
@benawad

**Comment by willdoescode** [comment]
This is interesting when I use a backslash the profile shows up

<img width="713" alt="Screen Shot 2021-05-14 at 09 02 15" src="https://user-images.githubusercontent.com/53620720/118297497-14609c00-b493-11eb-8272-ebbf400143ce.png">

**Comment by isaxk** [comment]
Maybe it glitches because his profile username contains special characters
