### ISSUE TITLE
Bots can mute speakers.

### ISSUE THREAD

**Issue by willdoescode** [benawad/dogehouse#2774]
**Describe the bug**
The bug is that a bot can use the `room:set_role"` opcode and set a user role as `raised_hand` with a speakers userid and it will mute the user.

**To Reproduce**
1. Send websocket request
```json
{
        "op": "room:set_role",
        "p" : {
          "role" : "raised_hand",
          "userId": "userid here",
        },
        "v" : "0.2.0",
        "ref": "[uuid]"
}
```

**Expected behavior**
Bots, especially non admin bots, should not be able to mute users at will

https://user-images.githubusercontent.com/53620720/118387490-a8398180-b5d3-11eb-8dc9-8d0c6b401bbc.mov

**Screenshots**
![Screen Shot 2021-05-15 at 23 17 25](https://user-images.githubusercontent.com/53620720/118387508-b5ef0700-b5d3-11eb-8258-5a8771efab81.png)
![Screen Shot 2021-05-15 at 23 17 31](https://user-images.githubusercontent.com/53620720/118387512-b9828e00-b5d3-11eb-9bea-9f3e76024cea.png)

**What device are you on?**
My dogehouse library

**Comment by willdoescode** [comment]
I just tested it again and it even turns off the effected users headphone audio.

**Comment by willdoescode** [comment]
More testing reveals that said bot has to be a speaker as well.

**Comment by TheOtterlord** [comment]
just to check, the bot has to be moderator or higher correct?

**Comment by willdoescode** [comment]
The bot does not have to be, and even if it were moderators can not normally mute people just move them to speakers. @TheOtterlord

**Comment by TheOtterlord** [comment]
oh, ok. this is quite serious then. not just a kebab problem, but a backend problem!

**Comment by willdoescode** [comment]
Yeah thats what I was thinking.

**Comment by willdoescode** [comment]
If this got into the wrong hands somebody could do lots of bad stuff to rooms.

**Comment by TheOtterlord** [comment]
hmm, this should be a high priority. hopefully an elixir dev comes online soon

**Comment by TheOtterlord** [comment]
oops. those buttons are too close XD

**Comment by willdoescode** [comment]
@overlisted

**Comment by overlisted** [comment]
what

**Comment by BronzW** [comment]
Can we link them?

**Comment by willdoescode** [comment]
> Can we link them?

who?
