### ISSUE TITLE
DogeHouse emojis are broken

### ISSUE THREAD

**Issue by FotieMConstant** [benawad/dogehouse#2782]
I just noticed this while in a room

**Comment by saihnii4** [comment]
could you explain a bit further?

**Comment by FotieMConstant** [comment]
Yeah, sure...  When I click on an emoji, and after being done adding the emoji, when I send it, it sends the text not the actual emoji(more like the emoji name)

**Comment by FotieMConstant** [comment]
Preview

![Screenshot_2021-05-16-16-05-17-192_com android chrome~2](https://user-images.githubusercontent.com/42372656/118402176-b71a4580-b660-11eb-9cc1-35553593596c.jpg)

**Comment by MeztliRA** [comment]
yeah its broken

**Comment by saihnii4** [comment]
can reproduce, maybe the parser got broken?

**Comment by prokopschield** [comment]
I submitted a fix: https://github.com/benawad/dogehouse/pull/2785

**Comment by n3oney** [comment]
I have a fix for it, I'll PR soon
