### ISSUE TITLE
Dogehouse Emojis breaking bot rooms

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2789]
**Describe the bug**
When using an emoji in a dogehouse bot room, it either gives a speaker (if there are any) admin or just closes the room.

**To Reproduce**
1. Join a room that's hosted by a bot
2. Use windows key and . to open the emojis
3. Use a random emoji

**Expected behavior**
The room should close if there are no speakers or a random speaker will be given admin and the bot will leave

**What device are you on?**
Windows 10

**Additional context**
None.

**Comment by n3oney** [comment]
This doesn't seen to be an issue with Dogehouse but with Moonstone

**Comment by amitojsingh366** [comment]
this is a moonstone issue

**Comment by n3oney** [comment]
This should be fixed:
https://github.com/fuwwy/moonstone/pull/12
