### ISSUE TITLE
Add functionality on homepage to search chat rooms

### ISSUE THREAD

**Issue by darshgun** [benawad/dogehouse#279]

**Comment by nadirabbas** [comment]
Hey darsh, search for what?

**Comment by darshgun** [comment]
> Hey darsh, search for what?

Hey, just updated the title. Search functionality to the homepage to search chat rooms. Saw on some instances there are more than 10 active chat rooms. This will give users a way of filtering/ finding chat rooms by title

**Comment by goldyydev** [comment]
This is being worked on in Kibbeh

**Comment by ajmnz** [comment]
Search has been implemented
