### ISSUE TITLE
Original Roadmap

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#28]
0. Fix bugs

- x-state??
1. Fill in missing things

??? notifications → app needed → react-native-web

??? global keybinds → desktop app needed → electron

2. Option to record rooms [podcast]

3. Discord/Twitch features for monetization

- DogeNitro
- DogeSubs
- DogeAds

**Comment by Rizialdi** [comment]
Hi Ben,

Do you think that it could be an option for listener to have a chat window to add message ? For example, speakers sometimes come to a subject and Im sure there's always someone who want to add some points. This could also serve speaker to invite listener.

**Comment by vhoyer** [comment]
Let me comment on web notifications:

You said you have a perception that 99% of ppl don't use notifications, but, as a main user of webapps, I use the push notifications selective, and if I didn't want the notifications on the web, I wouldn't want than on a native app. :D

So like, either notifications are bad, or I want then, so I don't think that web notifications are inherently bad

**Comment by KhushrajRathod** [comment]
How about a CLI for this? I could try to work on that

**Comment by r3nanp** [comment]
### Hi @benawad!

I will make a template using Electron + Typescript + React, to make maintenance easier.

**Comment by takashi1kun** [comment]
It would be nice to be able to select the output device, i have connected both, speakers and hearphones and it was sounding through the speakers.

**Comment by mikestaub** [comment]
I would prioritize moderation tools. Clubhouse didn't do that and it nearly sunk them.

**Comment by r3nanp** [comment]
That is true. @mikestaub

**Comment by Mipsters** [comment]
Some sort of message when the application updates will be better then kicking everyone off 😆 
will save you github issues

**Comment by Percyvalmg** [comment]
I would suggest making the chat section for listeners only allow for 160 characters or even less.

**Comment by LetsMelon** [comment]
It would probably also be good if listeners could give live feedback to the speaker with emojis. So that the emoji is next to his logo and is visible to everyone in the room.

**Comment by CoderLogy** [comment]
Can I help you in making python backend and also to tell you I am working on a cloud cryptocurrency I anyone wants to help me in that of course you are welcome

**Comment by CoderLogy** [comment]
I have made a chat application I think we you should make like this one something https://login-eb9cb.web.app/

**Comment by MooseTheCoder** [comment]
Have you considered using [coturn](https://github.com/coturn/coturn) for the voice side of things? I built a small discord clone a while back and found it extremely useful having something that done the bulk of the hard work.
