### ISSUE TITLE
Remove the 404 page and use the Redirects feature instead

### ISSUE THREAD

**Issue by chalkedgoose** [benawad/dogehouse#2811]
**Is your feature request related to a problem? Please describe.**
```dogehouse/kibbeh/src/pages/404.tsx``` is redundant since we don't have a 404 page
 it is a simple redirect. We should instead use the [Redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) feature built into the Next by modifying 
```next.config.js``` This should significantly speed up redirects and send a 301 redirect response code to browsers.

```js
module.exports = {
  ...,
  async redirects() {
    return [
      {
        source: '/404',
        destination: '/',
        permanent: true,
      },
    ]
  },
}
```

**Comment by chalkedgoose** [comment]
@overlisted @amitojsingh366

**Comment by overlisted** [comment]
can you do it yourself

**Comment by chalkedgoose** [comment]
> can you do it yourself

@overlisted I could do it myself but it will be a while due to my day job. 
And I also wanted feedback/validation on this approach to the 404 redirect.

**Comment by overlisted** [comment]
> And I also wanted feedback/validation on this approach to the 404 redirect

I'm not a Next.js professional, but it seems reasonable to me

**Comment by rocktimsaikia** [comment]
@overlisted Can I take this?

**Comment by amitojsingh366** [comment]
> 
> 
> @overlisted Can I take this?

go ahead

**Comment by amitojsingh366** [comment]
@chalkedgoose i tried it and unfortunately it seems like you cannot turn a 404 to a 301. it will have to go through `pages/404.tsx` and then redirected to `/dash`

**Comment by amitojsingh366** [comment]
and looking at it again i don't see why we would want to turn a 404 into a 301

**Comment by chalkedgoose** [comment]
> and looking at it again i don't see why we would want to turn a 404 into a 301

@amitojsingh366 The reason you'd want to do it is that your essentially utilizing the page as a 301 redirect anyways. There's just no status code and a client side redirect.
