### ISSUE TITLE
Missing margin in View bots page

### ISSUE THREAD

**Issue by firecraftgaming** [benawad/dogehouse#2823]
**Describe the bug**
There should be 0.75rem on both top and bottom of a separator on the view your bots page

**To Reproduce**
1. Go to Developer Settings
2. There is no margin on the separator

**Expected behavior**
In someway there is missing margin but there is an `my-3` tag on it

**Screenshots**
![image](https://user-images.githubusercontent.com/42218879/118704883-e0310680-b817-11eb-81af-504e43103932.png)

**What device are you on?**
PC / Chrome

**Additional context**
Already have a fix for it and gonna publish PR soon, my solution edits to remove class name and add margin top and bottom to style prop, if you have any other suggestions please publish

**Comment by amitojsingh366** [comment]
this has been fixed
