### ISSUE TITLE
Emoji UI doesn't work

### ISSUE THREAD

**Issue by jaipack17** [benawad/dogehouse#2830]
When selecting an emoji using the emoji selector in chat. And then sending the emoji. The emoji doesn't work. 

1. I click the emoji button 
![image](https://user-images.githubusercontent.com/74130881/118792204-0f498580-b8b5-11eb-8140-11bb3028f8d5.png)

2. I select an emoji by clicking on one
![image](https://user-images.githubusercontent.com/74130881/118792468-4ddf4000-b8b5-11eb-892c-d30c94126d89.png)

3. I click on an emoji and it shows up in my text box
![image](https://user-images.githubusercontent.com/74130881/118792539-60f21000-b8b5-11eb-8e3e-8c9378785215.png)

4. When I click send. The emoji doesn't show up
![image](https://user-images.githubusercontent.com/74130881/118792666-7ff0a200-b8b5-11eb-9cc7-7ea5aa762e9b.png)

I might find a fix to this soon. So I might make a PR.
Thanks.

**Comment by willdoescode** [comment]
This should be fixed now.
