### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Ry4nW** [benawad/dogehouse#2833]
Even when searching for something that exists. Loads forever at times and "web socket not connected" for others.

**Comment by byeze** [comment]
Hi Ry4nW!

Could you share some screenshots and context about this bug? It would be very helpful so we can debug.
Also, for me search is working. Did you check running this on other browsers and / or devices?

Thank you

**Comment by Ry4nW** [comment]
Didn't work the other day but works fine now with the same browser and device. Thanks for checking.
