### ISSUE TITLE
How to save DogeHouse

### ISSUE THREAD

**Issue by KristofKekesi** [benawad/dogehouse#2835]
### 1. Stay active
It is important to be active on DogeHouse. We are still have three months left.
### 2. Notify Elon
Retweet HoloPanio's [tweet][tweet] and comment `@elonmusk`.

[tweet]: https://twitter.com/jrobe3221/status/1395024289754238980

**Comment by saihnii4** [comment]
I don't think Holo's tweet is exactly "trending" material, nor is it going to seem any different from a crypto scam that's popular these days.
