### ISSUE TITLE
I want to redesign this for the new purpose

### ISSUE THREAD

**Issue by Pythone** [benawad/dogehouse#2841]
I am looking to redesign Dogehouse with the new purpose in mind.
What design goals do you have?
I am doing the concepts in SVG(final concept may be tested with the Dogehouse JS api).
What are the specifications I need for the redesign?

**Comment by amitojsingh366** [comment]
@ajmnz

**Comment by Pythone** [comment]
was I too late?

**Comment by ajmnz** [comment]
> @ajmnz

what am I supposed to say

**Comment by Pythone** [comment]
sorry
