### ISSUE TITLE
Dogehouse Restructuring 

### ISSUE THREAD

**Issue by troler36** [benawad/dogehouse#2844]
**Dogehouse is gone it won't come back! What do you think will make it magically come back?!**
 
Dogehouse to Ben Awad is gone. But it's not really gone. We can through had work revive scrape all of the data that is left while Dogehouse is still up. 
     Or we can choose a trustworthy contributor all of the data. Instead of relying on 1 person to say what is allowed and what is not we can have a voting system. Let's say there's a bug and we get 4 fixes. All of them fix the same problem the same way. All verified people. By verified I mean those who have contributed X amount of commits. So trolls and bots wouldn't flood the system. If more than 1/2 of these people agree to add this feature in a given period of time. Then that bug fix gets implemented. Feel free to critique me hackers

**Comment by TheOtterlord** [comment]
Discussions are ongoing between collaborators and contributors as to what we will do with DogeHouse. Please join the discord to join in the conversations
