### ISSUE TITLE
lol I only see blurred images

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#2846]
https://i.imgur.com/jY4tR8a.png

**Comment by TheOtterlord** [comment]
hmm, cannot reproduce. does this happen all the time? or does it disappear when you refresh?

**Comment by willdoescode** [comment]
that is weird looking.

**Comment by dk-raw** [comment]
It is like you blurred the images yourself. weird.

**Comment by ghost** [comment]
what browser is this?

**Comment by dk-raw** [comment]
lol. just found out ben removed collaborators

**Comment by nadirabbas** [comment]
@dk-raw what you mean?

**Comment by ghost** [comment]
can you please tell us what browser you're on?
