### ISSUE TITLE
Message deletion bug.

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2847]
**Describe the bug**
Message deletion bug.

**To Reproduce**
1. Send a message
2. Inspect and change the message text.
3. Have a mod delete the message.

**Expected behavior**
It should just delete the message.

**What device are you on?**
Brave for linux

**Comment by TheOtterlord** [comment]
cannot reproduce. 

Firefox Developer Edition

Maybe a chromium issue?

**Comment by ghost** [comment]
Sorry. I edited the issue.
