### ISSUE TITLE
TailwindCSS?

### ISSUE THREAD

**Issue by overlisted** [benawad/dogehouse#285]
Do you know about [Tailwind](https://tailwindcss.com)? It's basically `style` attribute but cooler: unlike `style=`, it allows for `@media`, pseudoclasses and other amazing stuff without writing a single CSS file. And by looking at the amount of `style=` in your code, I can assume that you will like Tailwind. this sounds like an ad but I just wanna suggest using it in dogehouse

**Comment by nadirabbas** [comment]
![Uploading image.png…]()

**Comment by nadirabbas** [comment]
it is being used

![image](https://user-images.githubusercontent.com/38838675/108347745-b3625880-7202-11eb-98ae-bd66adbadd8f.png)

**Comment by Abogical** [comment]
He's already using Tailwind:
https://github.com/benawad/dogehouse/blob/staging/kofta/tailwind.config.js
