### ISSUE TITLE
Vote to kick feature-permission to begin?

### ISSUE THREAD

**Issue by RonaldColyar** [benawad/dogehouse#287]
I would like to implement a vote to kick feature. Someone joined one of my rooms the other day and was being disrespectful. The admin was AFK, but the chat/listeners wanted him gone. So I would like permission to begin developing a vote to kick feature.

[U.I. inspiration](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FGlobalOffensive%2Fcomments%2Feg0jzd%2Fvote_ui_redesign%2F&psig=AOvVaw2yafNi-0ajto6ldZDm7l_t&ust=1613736127558000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIiZitex8-4CFQAAAAAdAAAAABAa)

**Comment by benawad** [comment]
I don't want vote to kick, better for admin to create a mod before going afk or switch rooms
