### ISSUE TITLE
Yo, listen up here's a story

### ISSUE THREAD

**Issue by rezhit** [benawad/dogehouse#2877]
About a little guy
That lives in a blue world
And all day and all night
And everything he sees is just blue
Like him inside and outside
Blue his house
With a blue little window
And a blue corvette
And everything is blue for him
And himself and everybody around
Cause he ain't got nobody to listen to
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
I have a blue house
With a blue window
Blue is the colour of all that I wear
Blue are the streets
And all the trees are too
I have a girlfriend and she is so blue
Blue are the people here
That walk around
Blue like my corvette its in and outside
Blue are the words I say
And what I think
Blue are the feelings
That live inside me
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
I have a blue house
With a blue window
Blue is the colour of all that I wear
Blue are the streets
And all the trees are too
I have a girlfriend and she is so blue
Blue are the people here
That walk around
Blue like my corvette, its in and outside
Blue are the words I say
And what I think
Blue are the feelings
That live inside me
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
I'm blue
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di
Da ba dee da ba di

**Comment by shahiryarlaam** [comment]
emotional
