### ISSUE TITLE
DogeHouse is no longer loading on iOS Safari

### ISSUE THREAD

**Issue by younesaassila** [benawad/dogehouse#298]
When accessing [DogeHouse.tv](https://dogehouse.tv) from Safari on iOS, a blank dark-gray page is shown.

This issue started appearing today.

Here's a screenshot: ![Screenshot](https://i.imgur.com/JxCdDqW.png)

**OS:** iOS 14.4

**Comment by nadirabbas** [comment]
@benawad I think it is in the regex for mention matching. iOS has been known for not supporting some regex patterns. Sadly I don't have Apple products so I couldn't test.

**Comment by overlisted** [comment]
It might be because something on the way to final react-dom `render()` call is broken

**Comment by ajmnz** [comment]
It definitely has to do with some regex error. 

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

Working on it.

**Comment by ajmnz** [comment]
Got it. Error is coming from the package `normalize-url`. `kofta/node_modules/normalize_url/index.js` @ line 125.

Commit cb2f0d1b276819189ccb4e7fc30864ebc3a379f2 introduced the bug.

Will downgrade it to normalize-url@4 and test asap if that solves the issue.

**Comment by benawad** [comment]
commented out normalize-url for now

**Comment by ajmnz** [comment]
> commented out normalize-url for now

Made a PR
