### ISSUE TITLE
Error - Voice couldn't get through

### ISSUE THREAD

**Issue by lokeshcs** [benawad/dogehouse#3]
Receiving a console error saying `send-track send failed Cannot read property 'recvTransport' of undefined` and also this toast

<img width="1767" alt="Screenshot 2021-02-12 at 9 05 19 PM" src="https://user-images.githubusercontent.com/49974617/107788174-1d4baf80-6d76-11eb-8df6-f0c5c1078d63.png">

**Comment by yigitlevent** [comment]
I'll copy my issue here:

`error connecting to voice server | Cannot read property 'recvTransport' of undefined`

Mind you, this room had 80+ listeners/speakers when this error started to occur, but I am still able to listen to other rooms with lower number of listeners/speakers.

**Comment by benawad** [comment]
note to self: this is probably caused by a race condition when a listener tries to subscribe when a room/speaker leaves
