### ISSUE TITLE
Ease Of Use Fixes For UI

### ISSUE THREAD

**Issue by AustinVieth** [benawad/dogehouse#30]
The UI icons are somewhat confusing, 

Labels for the Icons would be appreciated!

This problem becomes more of an issue because you can only ask to speak once in a room. In my case I entered the room, clicked the icons to see what they did, had no feedback, and then by clicking again I figured out I requested to speak.

I love the project though, I think a little more affordance would go a long way.

**Comment by TheJaysH** [comment]
100% Even just something like an HTML title attribute would help a lot
