### ISSUE TITLE
I will be pitching DogeHouse on DogeHouse to investors at 3pm PST on 2/26 

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#301]

**Comment by nadirabbas** [comment]
pin this probably

**Comment by RonaldColyar** [comment]
Taking off , hopefully it remains open source.

**Comment by Yakumwamba** [comment]
Watching this space 👀

**Comment by FotieMConstant** [comment]
> Taking off , hopefully it remains open source.

Hopefully bro. all the best @benawad

**Comment by benawad** [comment]
postponing this into the future, closer to when I want funding

**Comment by DGKSK8LIFE** [comment]
> postponing this into the future, closer to when I want funding

So you are not having the meeting?

**Comment by FotieMConstant** [comment]
So, no meeting?
