### ISSUE TITLE
Leaving call while requesting to speak

### ISSUE THREAD

**Issue by ProNanigans** [benawad/dogehouse#303]
If you request to speak and leave a call while that request is pending, then when you join another room, it still shows that you are requesting to speak.

**Comment by nadirabbas** [comment]
nice catch!

**Comment by benawad** [comment]
same room or different room?

**Comment by ProNanigans** [comment]
> same room or different room?

For me, it happened when trying both a different room and the same room

**Comment by benawad** [comment]
when you did it in the different room had you been to that room before?

**Comment by ProNanigans** [comment]
I don’t fully remember, but I don’t think it mattered if I’d been in that
room before.

**Comment by benawad** [comment]
should be fixed now
