### ISSUE TITLE
Notification Sound when you get a message 

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [benawad/dogehouse#306]
## WHY?
I was alone in a room and had the doghouse link open in the background with my mic muted, people came into my room and wrote in the chat but I was not aware, it would be great if you get a voice sound every time some user sends a message (also have the ability to turn off this feature )

![image](https://user-images.githubusercontent.com/54576074/108469380-1f4dcb00-72ae-11eb-987a-dafec70d440d.png)

**Comment by mohammedgad** [comment]
We need that! @nadirabbas what do you think?

**Comment by nadirabbas** [comment]
Yeah I think, it should be toggleable tho

**Comment by rh3xp** [comment]
It should notify especially when someone mentions you, like a fuzzy search of all the usernames in the current chat window.

**Comment by nadirabbas** [comment]
PR on the way

**Comment by nadirabbas** [comment]
#308
