### ISSUE TITLE
Make electron port/version of the app for desktop usage, thanks 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [benawad/dogehouse#311]

**Comment by DGKSK8LIFE** [comment]
If you want, @benawad, I can assign this issue to myself and make a PR to include electron. Ty

**Comment by benawad** [comment]
you are welcome to work with @Stancobridge

idk where they are in the process

**Comment by benawad** [comment]
cc #172

**Comment by DGKSK8LIFE** [comment]
Thanks, @benawad. @Stancobridge what's your discord? Want to work on this together?

**Comment by nadirabbas** [comment]
I built the electron app locally, it seemed to work correctly.

**Comment by DGKSK8LIFE** [comment]
If it is working correctly without any hitches, maybe make a PR? @nadirabbas

**Comment by nadirabbas** [comment]
@DGKSK8LIFE It is already merged.

**Comment by DGKSK8LIFE** [comment]
what #? @nadirabbas

**Comment by nadirabbas** [comment]
The electron app is already in the codebase.

**Comment by DGKSK8LIFE** [comment]
Ah ok. So there is an electron port already? Where can I download it? @nadirabbas

**Comment by nadirabbas** [comment]
https://github.com/benawad/dogehouse/tree/staging/baklava

**Comment by DGKSK8LIFE** [comment]
Ty @nadirabbas. When it is merged into prod I will close the issue

**Comment by nadirabbas** [comment]
It is merged into prod

**Comment by nadirabbas** [comment]
https://github.com/benawad/dogehouse/tree/prod/baklava

**Comment by DGKSK8LIFE** [comment]
Could there be UI integration so I could download an `exe` of the electron app from `dogehouse.tv`? Guess that's a separate feature request

**Comment by nadirabbas** [comment]
I don't think @benawad has tried building the electron app yet. If he doesn't want any changes, you can build the exe

**Comment by DGKSK8LIFE** [comment]
Yeah, @benawad if you're ok with it, I can setup compilation of the electron app and make a PR for it.

**Comment by DGKSK8LIFE** [comment]
Maybe a github action that auto-compiles and checks integrity of the electron app. Then the Dogehouse app can hyperlink to github releases of the executables? Ty

**Comment by benawad** [comment]
yeah I'll be setting this up after I finish some other stuff

**Comment by benawad** [comment]
Before I add electron to releases, I want a way for it to auto-update itself on new releases so we don't get a bunch of stale electron clients

**Comment by nadirabbas** [comment]
@benawad  can we like auto-refresh or something? cuz the newly built files have unique hash names anyway, so it will fetch new resources.

**Comment by benawad** [comment]
I want something like that, I haven't looked into electron so idk how easy that is to do

**Comment by nadirabbas** [comment]
@benawad  I will look into it. We have to set some value on the backend to tell it that new changes were deployed.

**Comment by TheOtterlord** [comment]
If you're talking about the client, you could use 'electron-builder' and [this](https://www.electron.build/auto-update)?

**Comment by TheOtterlord** [comment]
The port is complete and the binaries are available in [releases](https://github.com/benawad/dogehouse/releases). You can download the latest version [here](https://github.com/benawad/dogehouse/releases/latest).

**Comment by DGKSK8LIFE** [comment]
Thanks @TheOtterlord

**Comment by DGKSK8LIFE** [comment]
the github oauth (two factor auth) sign in isn't working for me on the latest electron version on windows 10 @TheOtterlord @benawad
