### ISSUE TITLE
Add [What's new] section

### ISSUE THREAD

**Issue by mohammedgad** [benawad/dogehouse#313]
We need to add a section on the website to let people know What's newly added, and maybe teach them how it works.
*I can work on the BE endpoint if that's approved*

**Comment by benawad** [comment]
I think we can do it entirely on the frontend

**Comment by mohammedgad** [comment]
yea I think that would be nice, but will we display all the previous newly added?

**Comment by benawad** [comment]
no, just the latest

**Comment by DGKSK8LIFE** [comment]
@benawad Agree that it could be done entirely on the frontend. What you could do, is use markdown documentation for the changelog, then scrape the markdown in the repo (or use github api; not sure), and display it.

**Comment by benawad** [comment]
what's left on this is to setup semantic release to automate changelog creation

**Comment by ajmnz** [comment]
Closing in favor of #337
