### ISSUE TITLE
no room title on iOS

### ISSUE THREAD

**Issue by tejxv** [benawad/dogehouse#315]
it pops up for a second upon entering the room and then it just disappears.

![image](https://user-images.githubusercontent.com/54097365/108549559-4db1c180-7313-11eb-8c95-65f1e42e29d8.png)

**Comment by benawad** [comment]
@tejxv if you refresh is it still like that? I can't recreate

**Comment by tejxv** [comment]
@benawad  yeah i did refresh a couple of times but same behaviour, i even tried chrome but no luck.
FYI: it's an iPhone 8 running iOS 14.4

**Comment by tejxv** [comment]
bug in action: 
https://photos.app.goo.gl/tKwAQDPtsxA5wBhJA

**Comment by benawad** [comment]
when you get some time and are back on your computer, would you be able to plug your phone in, inspect with safari devtools and see what the cause is?

**Comment by tejxv** [comment]
yeah sure, i'll definitely try that and will let you know when i find something useful

**Comment by ajmnz** [comment]
@tejxv Are you using an adblocker of some sort for iOS? I haven't been able to reproduce the issue.

**Comment by tejxv** [comment]
@ajmnz that's just odd, i think something's messed up on my side and no i'm not using any sort of adblocker

**Comment by tejxv** [comment]
this seems to be fixed now because of #318
