### ISSUE TITLE
Everyone has random characters as usernames

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#319]
I don't know if this is intended, but if not, I thought to open an issue.

![image](https://user-images.githubusercontent.com/38838675/108579380-6d171180-7348-11eb-8185-c84d8f875f86.png)

**Comment by tejxv** [comment]
yes it's totally intended, ben added the ability to change username, bio and display name.
![image](https://user-images.githubusercontent.com/54097365/108582203-7bccdc80-72e6-11eb-938c-6dfc52582f0f.jpeg)
