### ISSUE TITLE
Rename directories to something contextual instead of food

### ISSUE THREAD

**Issue by DGKSK8LIFE** [benawad/dogehouse#320]
Please rename these directories 
![image](https://user-images.githubusercontent.com/45473363/108582607-0b2fbb00-72fa-11eb-8bb0-610722277112.png)

**Comment by DGKSK8LIFE** [comment]
also `feta` needs to be renamed, @benawad

**Comment by benawad** [comment]
I like it

**Comment by DGKSK8LIFE** [comment]
Ah I see the documentation in the README. ok
