### ISSUE TITLE
DogeHouse is zoomed in because of a long title (image)

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#324]
![woahdoge](https://user-images.githubusercontent.com/65829743/108584763-7c2a9f00-7309-11eb-91f2-ff69091ac4df.PNG)

caused by a long title

**Comment by PuckDan** [comment]
it was caused by a long title

**Comment by nadirabbas** [comment]
The title seems to be very short. Doesn't it?

**Comment by benawad** [comment]
what browser are you in? I can check it the ellipsis is not working their

**Comment by PuckDan** [comment]
brave browser. i also tested it on chrome and it did the same thing.
