### ISSUE TITLE
Clicking the username doesn't open twitter/github

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#325]
I think @benawad removed it to solve #289 
I can create a column in the `users` table called: `oauth_profile_url`, which we can store the profile URL in while authenticating with Github/Twitter/Google etc.

If this is wanted, this can be assigned to me.

**Comment by benawad** [comment]
instead I want to just make it so the bio linkifies so you can link to whatever you want

**Comment by nadirabbas** [comment]
Oh thats good! will close this

**Comment by nadirabbas** [comment]
I can work on it, if it's not already being worked on. I'll maybe push tomorrow

**Comment by benawad** [comment]
go for it

**Comment by nadirabbas** [comment]
@benawad for validating the URL length, I am setting the max length to 255.
