### ISSUE TITLE
room name cannot be edited

### ISSUE THREAD

**Issue by theekrystallee** [benawad/dogehouse#329]

**Comment by nadirabbas** [comment]
It can be edited if you click on the name:
![image](https://user-images.githubusercontent.com/38838675/108591252-94420300-7389-11eb-9474-c5e638314b7b.png)

**Comment by tejxv** [comment]
@nadirabbas it partially works, when on rename room modal, it only works upon hitting enter key but clicking on OK button doesn't do anything, which used to work if i remember correctly
