### ISSUE TITLE
how can i verify my elixir server is running

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#332]

**Comment by nadirabbas** [comment]
Go to localhost:4001/auth/github/web, if it redirects you, meaning it works

**Comment by tanay-pingalkar** [comment]
> Go to localhost:4001/auth/github/web, if it redirects you, meaning it works

but how can i get git client secret...

**Comment by nadirabbas** [comment]
Go to: https://github.com/settings/apps
Create an app, this will give you the credentials.

**Comment by tanay-pingalkar** [comment]
> Go to: https://github.com/settings/apps
> Create an app, this will give you the credentials.

yup what to put in callback url

**Comment by nadirabbas** [comment]
http://localhost:4001/auth/github/callback

**Comment by tanay-pingalkar** [comment]
> http://localhost:4001/auth/github/callback

thanks that works
