### ISSUE TITLE
not able to create test user

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#333]
i had logged in using github but now i want to test chat feature, I only have 1 github accout. So i tried to create test user but when i click ok, nothing happened, why. Should i add twitter auth secret that i can use twitter to create another account.

**Comment by mohammedgad** [comment]
Hi @tanay-pingalkar Is there a specific error displayed on the BE logs?

**Comment by tanay-pingalkar** [comment]
> Hi @tanay-pingalkar Is there a specific error displayed on the BE logs?

No that's why I am confused

**Comment by benawad** [comment]
sometimes you need to press it a couple of times

**Comment by ajmnz** [comment]
I think your problem comes when calling the api, check for errors in devtools as you might have set the wrong url for it. Happened to me when writing the local development steps.

**Comment by mohammedgad** [comment]
@tanay-pingalkar did you export `REACT_APP_API_BASE_URL=http://localhost:4001` ?

**Comment by tanay-pingalkar** [comment]
> @tanay-pingalkar did you export `REACT_APP_API_BASE_URL=http://localhost:4001` ?

Yup

**Comment by tanay-pingalkar** [comment]
> I think your problem comes when calling the api, check for errors in devtools as you might have set the wrong url for it. Happened to me when writing the local development steps.

I will check

**Comment by nadirabbas** [comment]
If you're using Docker, the test user won't get created, as that is production.

**Comment by tanay-pingalkar** [comment]
> If you're using Docker, the test user won't get created, as that is production.

No i am not using docker

**Comment by tanay-pingalkar** [comment]
i am getting ```11:16:15.792 [error] calling logger:remove_handler(default) failed: :error {:badmatch, {:error, {:not_found, :default}}}``` warning otherwise everything is going good in elixer api

**Comment by tanay-pingalkar** [comment]
dont know how when i restart the whole setup, i got test user working. Thanks for the help.
