### ISSUE TITLE
[Feature] Play a sound when someone joins or leave the room

### ISSUE THREAD

**Issue by mohammedgad** [benawad/dogehouse#334]
This is from discord, when someone enters a room or leaves, a sound notification is played.
I am not sure if that's useful or not for Dogehouse, but let's discuss it.

**Comment by nadirabbas** [comment]
I think instead of a sound, this will trigger a message-like thingy in the chat: "Someone left", "Someone joined",
Because then there will be too much sound. Because people keep joining and leaving continuously.


Because Dogehouse is not like Discord. I hear people like to explore different rooms and keep joining/leaving. Unlike Discord, where people specifically open the app to join a specific room.

**Comment by benawad** [comment]
we can keep the join/leave sound to only speakers

**Comment by nadirabbas** [comment]
@benawad aye aye captain. I will work on this, can suggest a sound? Or can I just use the same one like mention sound?

**Comment by mohammedgad** [comment]
> I think instead of a sound, this will trigger a message-like thingy in the chat: "Someone left", "Someone joined",
> Because then there will be too much sound. Because people keep joining and leaving continuously.
> 
> Because Dogehouse is not like Discord. I hear people like to explore different rooms and keep joining/leaving. Unlike Discord, where people specifically open the app to join a specific room.

That's exactly why I was wondering if that is an idea good for dogehouse or not, It was good for me in discord as a speaker to be notified to check who is joined before continuing the talk.



> @benawad aye aye captain. I will work on this, can suggest a sound? Or can I just use the same one like mention sound?

Maybe a very light sound?


> we can keep the join/leave sound to only speakers

I think adding an option to enable and disable that for users would be useful too.

**Comment by nadirabbas** [comment]
> I think adding an option to enable and disable that for users would be useful too.

Great suggestion @mohammedgad

**Comment by benawad** [comment]
closing for # #170
