### ISSUE TITLE
[Feature] [working] Working on emoji feature

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#335]
I am currently working on emoji feature. I know we can send emoji on mobile but what about pc user. So i am gonna add one. Their is special react lib called react emoji. Should I use that Or should I create one from scratch.

**Comment by benawad** [comment]
use https://github.com/missive/emoji-mart

**Comment by nadirabbas** [comment]
@tanay-pingalkar you can use a token called: "emoji" maybe. Then maybe @mohammedgad can do backend validation.

**Comment by ajmnz** [comment]
Would be nice to have them bound to something like :emoji:

**Comment by tanay-pingalkar** [comment]
> use https://github.com/missive/emoji-mart

dont know why emoji-mart is behaving so different

**Comment by nadirabbas** [comment]
@tanay-pingalkar different how?

**Comment by tanay-pingalkar** [comment]
> @tanay-pingalkar different how?

it is working as they had told in their docs

**Comment by tanay-pingalkar** [comment]
wala it works
i am gonna create pr tomorrow
