### ISSUE TITLE
Chat messages duplicating

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#336]
#### Reproducing steps:

1. Join a room
2. Copy room URL
3. Paste in a new tab
4. Hit enter (ofc)

Chat messages will start duplicating in the new tab, and the old socket will be killed by the server.

**Comment by benawad** [comment]
is this happening in prod for you, I thought I fixed this

**Comment by nadirabbas** [comment]
@benawad yes prod, happened earlier today.

**Comment by benawad** [comment]
I can't replicate with those steps

**Comment by nadirabbas** [comment]
I will post a video

**Comment by nadirabbas** [comment]
@benawad Weird, now even I can't reproduce it. I think it got fixes when you deployed.
