### ISSUE TITLE
Validation: Possible to be nameless using unicode chars

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#338]
<img width="575" alt="Captura de Pantalla 2021-02-20 a les 15 56 01" src="https://user-images.githubusercontent.com/57961822/108599903-23541880-7394-11eb-8c63-72aa221c665d.png">

**Comment by mohammedgad** [comment]
I can work on that @benawad

**Comment by JammSpread** [comment]
I think Unicode characters should still be allowed for display names just white-space characters should be disabled. I feel it should be similar to Discord where you can have "fancy usernames".
