### ISSUE TITLE
[Feature] Add AFK button.

### ISSUE THREAD

**Issue by mohammedgad** [benawad/dogehouse#339]
We need to add an AFK/unAFK button for speakers alongside the mute button to let people know that you went to make a cup of coffee.

Q: *should that be added to the listeners also?*

**Comment by yaslam-dev** [comment]
It would be cool for AFK to add drinking coffee doge to avatar of speakers.

**Comment by ajmnz** [comment]
I'll try to implement that

**Comment by nadirabbas** [comment]
@Yasir900aslam YES!!

**Comment by ajmnz** [comment]
Hahaha

![doge coffee](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fstatic1.zipso.net%2Fwp-content%2Fuploads%2F2014%2F03%2Fdoge-coffee.jpg&f=1&nofb=1)

**Comment by ajmnz** [comment]
I think setting the opacity down and adding a `title` tag would make it more clear. What do you guys think?

<img width="561" alt="Captura de Pantalla 2021-02-20 a les 18 33 23" src="https://user-images.githubusercontent.com/57961822/108603768-1f32f580-73aa-11eb-89d1-15f6e608fa65.png">

**Comment by nadirabbas** [comment]
@ajmnz I agree

**Comment by mohammedgad** [comment]
seems nice, but we will miss the doge coffee 😞

**Comment by nadirabbas** [comment]
Why dont we make a dogecoffee icon thingy in ps. Instead of the user if AFK label,show that

**Comment by mohammedgad** [comment]
@nadirabbas what is ps?
anyway, I agree because dogycoffe will be there 😂

**Comment by nadirabbas** [comment]
It is an abbreviation I invented for Photoshop.

**Comment by ajmnz** [comment]
@nadirabbas Time for design I guess :)

Got any ideas?

**Comment by mohammedgad** [comment]
@nadirabbas @ajmnz totally agree.

**Comment by nadirabbas** [comment]
@ajmnz lets take the Dogehouse logo and do something with it. well no the logo, the icon from the site.

**Comment by mohammedgad** [comment]
@nadirabbas it's here https://github.com/benawad/dogehouse/tree/staging/kofta/src/assets/regular-doge.png 🕺

**Comment by nadirabbas** [comment]
Just put a cup of coffee in front of it, I think that'd be sufficient.

**Comment by ajmnz** [comment]
![dogecoffee2](https://user-images.githubusercontent.com/57961822/108604191-a2554b00-73ac-11eb-9eef-7569e15698e5.png)

<img width="96" alt="Captura de Pantalla 2021-02-20 a les 18 51 47" src="https://user-images.githubusercontent.com/57961822/108604199-b1d49400-73ac-11eb-8e2e-44b1e2368ca8.png">

Not very convincing to me. Can be confused with a mod.

**Comment by nadirabbas** [comment]
I think just make the coffee more prominent somehow? I am NOT A designer so I don't know what I am talking about.

**Comment by ajmnz** [comment]
<img width="107" alt="Captura de Pantalla 2021-02-20 a les 18 54 22" src="https://user-images.githubusercontent.com/57961822/108604252-0ed04a00-73ad-11eb-8b35-352b909e9256.png">

Well look at that. Making progress I guess

**Comment by ajmnz** [comment]
> I think just make the coffee more prominent somehow? I am NOT A designer so I don't know what I am talking about.

I mean we're working with a 50x50px image and putting an element over it even smaller.

**Comment by nadirabbas** [comment]
But the last one you posted made sense.

**Comment by mohammedgad** [comment]
> <img alt="Captura de Pantalla 2021-02-20 a les 18 54 22" width="107" src="https://user-images.githubusercontent.com/57961822/108604252-0ed04a00-73ad-11eb-8b35-352b909e9256.png">
> 
> Well look at that. Making progress I guess

@ajmnz nice, that makes sense as I believe the AFK should be equivalent to the mute and treated the same way as the mute.
maybe the AFK should mute the user too @nadirabbas @ajmnz what do you think about that?

**Comment by ajmnz** [comment]
I think this one makes even more sense, tbh. Just to prevent a doge overload.

<img width="112" alt="Captura de Pantalla 2021-02-20 a les 18 58 21" src="https://user-images.githubusercontent.com/57961822/108604344-9d44cb80-73ad-11eb-9250-05f28e98b4d9.png">

**Comment by nadirabbas** [comment]
but you lose our trademark. we're trying to funky with this. as the whole dogehouse is.

**Comment by ajmnz** [comment]
> but you lose our trademark

In my opinion it shouldn't be abused. It is already present everywhere.

**Comment by mohammedgad** [comment]
I think that will be back to ben in the end, he didn't approve the feature itself yet 😂

**Comment by nadirabbas** [comment]
I think there is a 50% chance this isn't getting approved, ben disapproved my auto AFK timer. But this is cleaner, lets see.

**Comment by ajmnz** [comment]
@nadirabbas in case this gets approved, do you want to go with the backend? I have no idea about elixir 😅

**Comment by mohammedgad** [comment]
let's hope, I believe we really need it for speakers.

**Comment by benawad** [comment]
I don't want to add an afk button at moment. 

1. There are more important features to add first
2. We may do emoji reactions sometime which will trump this
