### ISSUE TITLE
Delete chat messages

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#350]
- Creators can delete messages of Mods/Listeners
- Mods can delete listeners chat messages
- Listeners can only delete their own.

I want to work on this if this is not undesired.  @benawad 
Many many people have requested this.

**Comment by mohammedgad** [comment]
@nadirabbas won't that make the chat logic complex somehow? some people won't like their messages to be deleted by others.

**Comment by nadirabbas** [comment]
@mohammedgad but as moderators/creators, they need to be able to have full control over their rooms.

**Comment by mohammedgad** [comment]
@nadirabbas yup I believe that's totally valid, I don't know what I was thinking. 😄

**Comment by benawad** [comment]
I want this

**Comment by tanay-pingalkar** [comment]
can you also add feature to store messages that even if user reload website the messages will be still there........and what if user can send small buffer of image (actually not needed but possible)...

**Comment by nadirabbas** [comment]
@tanay-pingalkar That's for later I guess.

**Comment by nadirabbas** [comment]
@benawad we can publish all the previously sent messages in an event when the user reconnects. Not sure if this is needed right now.

**Comment by tanay-pingalkar** [comment]
> @benawad we can publish all the previously sent messages in an event when the user reconnects. Not sure if this is needed right now.

i think this is important

**Comment by benawad** [comment]
1. Chat disappearing on reload is intended, it matches twitch
2. I don't want to republish anything atm
