### ISSUE TITLE
Quote/reply to other user message

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#351]
It'd be really useful to be able to quote someone's message and would make it a better UX rather than mentioning every time or copying the user's message. Especially has happened to me when multiple people are having conversations in parallel.

**Comment by nadirabbas** [comment]
what if we add some button on the message, clicking which auto mentions that user? Cuz I don't think there is enough space to show a quoted message, unless you do some design magic and make some space.

**Comment by ajmnz** [comment]
Theoretically it could be done entirely on the frontend. Using some keyword similar to what github uses (>) and then parsing the message, although it may imply allowing multiline messages (ctrl+enter).

**Comment by ajmnz** [comment]
> what if we add some button on the message, clicking which auto mentions that user? Cuz I don't think there is enough space to show a quoted message, unless you do some design magic and make some space.

We could stick a button in the top right edge of the message that appears on hover. Let me sketch something quickly.

**Comment by ajmnz** [comment]
Idk, something like that maybe. @nadirabbas 

<img width="309" alt="Captura de Pantalla 2021-02-21 a les 18 33 41" src="https://user-images.githubusercontent.com/57961822/108633204-53beb400-7473-11eb-82c4-4b785df91a70.png">

<img width="309" alt="Captura de Pantalla 2021-02-21 a les 18 33 41" src="https://user-images.githubusercontent.com/57961822/108633423-71404d80-7474-11eb-8b0f-a35358bb0ece.png">

**Comment by nadirabbas** [comment]
You never fail to impress. Lets see what Ben says,

**Comment by nadirabbas** [comment]
so clicking on the reply actually should scroll to that message right?

**Comment by nadirabbas** [comment]
We also need to be very careful about the UX

**Comment by ajmnz** [comment]
> so clicking on the reply actually should scroll to that message right?

Yes, it should. If we have each message with their unique id, scrolling to them is relatively easy.

```javascript
document.querySelector('messageId').scrollIntoView({
  behavior: 'smooth',
});
```

**Comment by ajmnz** [comment]
> We also need to be very careful about the UX

That too. With mentions, urls, emojis coming soon, quotes... It could get unusable and confusing.

**Comment by mohammedgad** [comment]
yea, I believe that would make the chat crowded.

**Comment by tanay-pingalkar** [comment]
the quote/reply message will only appear if the user will hover/click over the message and also have key binding like discord

**Comment by nadirabbas** [comment]
I guess mentions fix this
