### ISSUE TITLE
Mentions goes wrong

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#367]
![Screenshot_2021-02-22-22-31-51-569_com android chrome](https://user-images.githubusercontent.com/72514547/108742601-dd4ab080-755d-11eb-949b-7a623a90bd8c.jpg)
What's this.... Nadir have a look at this

**Comment by nadirabbas** [comment]
Yeah I noticed it, the background is basically transparent.

**Comment by tanay-pingalkar** [comment]
Ok then i am closing the issue
