### ISSUE TITLE
Add speakers/members image in the room card

### ISSUE THREAD

**Issue by AbhinavRajesh** [benawad/dogehouse#390]
**Is your feature request related to a problem? Please describe.**
It would be really cool if we could see the image of the speakers before we join a room

**Describe the solution you'd like**
As this app uses github/twitter authentication adding picture from github/twitter account should do

**Describe alternatives you've considered**
Option for user to upload profile picture in settings

**Additional context**
![image](https://user-images.githubusercontent.com/54738622/108884552-bd35f280-762c-11eb-805e-5dac63a923c7.png)
Instead of names, add profile picture or keep both profile picture and name of the speaker/members present in the room

**Comment by goldyydev** [comment]
Being worked on in Kibbeh
![image](https://user-images.githubusercontent.com/55450464/111883286-ff9be680-89c2-11eb-9682-0ae7b91c94b2.png)
