### ISSUE TITLE
Auto-refresh room cards in the homepage

### ISSUE THREAD

**Issue by miguelcarreiro** [benawad/dogehouse#392]
**Is your feature request related to a problem? Please describe.**
When in the homepage, I have to update the page several times to have updated info about the rooms, which can be a bit annoying.

**Describe the solution you'd like**
Auto-update room cards in the homepage.

**Describe alternatives you've considered**
A button to update cards without refreshing the entire page.

**Comment by benawad** [comment]
yeah I think we need a better system to keep homepage with fresh info

**Comment by drvladb** [comment]
Done by #991
