### ISSUE TITLE
Emoji Reactions

### ISSUE THREAD

**Issue by nemanjapesic** [benawad/dogehouse#394]
The idea is to have some emoji or thumbs up floating up from behind users avatar when that user presses the reaction key.

In yesterdays discussion we found that It would be great to have this feature as a kind of virtual nod of approval to the current speaker without having to interrupt him or wait for him to finish before giving him a feedback on what he is currently saying.

Something like this animation, but probably shorter and fading away:
https://www.youtube.com/watch?v=Mz04HQl7cTo&ab_channel=NadzSamson

**Comment by benawad** [comment]
I'm about to deploy emojis to chat and I think this might cover some of this use case. Feel free to reopen after trying if you still like a reaction thingy
