### ISSUE TITLE
User can change there name to blank even after validation!

### ISSUE THREAD

**Issue by AbhinavRajesh** [benawad/dogehouse#400]
**Describe the bug**
User can change their name to blank

**To Reproduce**
1. Go to 'https://dogehouse.tv'
2. Click on 'Edit Profile'

When submitting the name without any content it successfully throws out an error
![image](https://user-images.githubusercontent.com/54738622/108950375-2731b480-768c-11eb-8870-abf5f8cf645e.png)

But when submitting the name with 2 or more spaces in the name field, it successfully changes the name without throwing out the error
![image](https://user-images.githubusercontent.com/54738622/108950470-47fa0a00-768c-11eb-8202-e1d2eb10fee6.png)

**Expected behavior**
Blank spaces in the user's name shouldn't be considered a valid character during validation

**What device are you on?**
Chrome: 88.0.4324.182

**Additional context**
Can be fixed by trimming the name field ( Removing the trailing spaces ) while submitting

**Comment by daddasoft** [comment]
yeah definitely  the string Should be trimmed

**Comment by baibhabmondal** [comment]
Hey Ben can I take this one?
