### ISSUE TITLE
send private messages in the room chat

### ISSUE THREAD

**Issue by James-Baloyi** [benawad/dogehouse#402]
Sometimes you want to say something to someone in secret, but you can't because everything in chat is visible to everyone.

I suggest something like @user #whisper {insert message here} - only the users you've tagged should be able to see it.

This is quicker and easier to implement than an entire private chat thing - so if that's in the works this can serve as a placeholder of sorts.

**Comment by nadirabbas** [comment]
love this idea until we get DMs. @benawad ?

**Comment by benawad** [comment]
I'm good with this, but I want a cleaner syntax. Something like `@#user` so I don't have to type `#whisper` every time

**Comment by nadirabbas** [comment]
@benawad basically had to move the only `tokens` handler after the `whisperedFor` handler in `socket_handler.ex`
