### ISSUE TITLE
can take room previews

### ISSUE THREAD

**Issue by tanay-pingalkar** [benawad/dogehouse#403]
i think this will be great to have a preview of room before joining the room.

**Comment by ajmnz** [comment]
@tanay-pingalkar What do you mean by having a preview of the room? Isn't that what we already have?

**Comment by tanay-pingalkar** [comment]
> @tanay-pingalkar What do you mean by having a preview of the room? Isn't that what we already have?

this issue is old, i saw on youtube that ben awad is planning to make a feed in doge house where you can also take a room preview in feed..i
