### ISSUE TITLE
Implementation of detailed design docs

### ISSUE THREAD

**Issue by RonaldColyar** [benawad/dogehouse#404]
Me and Fotie have came up with the idea: to collaborate on a series of design documents for each individual portion of dogehouse(strucuture and flow)to make contributing easier. Is there anyway we could be assigned this task?

**Comment by FotieMConstant** [comment]
@benawad ? ...Indeed we need a detailed technical documentation for the doghouse project.

**Comment by benawad** [comment]
Sounds good, I'm also going to be releases a video soon that'll go into more detail that you can use as well.

**Comment by TatchumNono** [comment]
@benawad Hi, I wish to contribute to the documentation.

**Comment by FotieMConstant** [comment]
@RonaldColyar once we are done with the doc we will have to use Storybook to document the code(frontend), I think it'll really be helpful for documenting the code (Components), check this issue #424

**Comment by anuraagbarde** [comment]
Please do so, even a small diagram describing the data flow of a few set of modules will save a lot of time for both the future contributors and the future self of the writer themselves.
