### ISSUE TITLE
Not opening profile of users that left the room when clicking on their name in the chat

### ISSUE THREAD

**Issue by nemanjapesic** [benawad/dogehouse#406]
**Describe the bug**
The profile of users that left the room is not opening when clicking on their name in the chat

**To Reproduce**
1. Say bye to someone, they are leaving
2. Click on their name to see their profile and follow them
3. It doesn't open
4. Try not to cry

**Expected behavior**
It should display their profile info in a modal

**What device are you on?**
Windows PC, Chrome
Android

**Comment by nadirabbas** [comment]
yeah they are out of memory at that point lol

**Comment by nadirabbas** [comment]
@benawad What if we make a request to the backend from `ProfileModalFetcher`?

**Comment by benawad** [comment]
Yeah and we should denote in the profile that they left the room

**Comment by melnary** [comment]
@nadirabbas addressed this in 828f4622378f58531b16945e4d631b17e644ca62, this issue can be closed now!
