### ISSUE TITLE
Chat input shouldn't have autocomplete

### ISSUE THREAD

**Issue by nafg** [benawad/dogehouse#410]
**Describe the bug**
The chat input pops up autocomplete suggestions from my previously entered messages

**To Reproduce**
1. Go into a room
2. Enter a message in the chat
3. Click on the chat input
4. See previous message pop up as an autocomplete suggestion

**Expected behavior**
No popup

**What device are you on?**
chromebook

**Comment by kaijihan** [comment]
![Screenshot_20210225-083338_Chrome](https://user-images.githubusercontent.com/79467682/109089667-32481b80-7744-11eb-9b7f-411e39c1a05e.jpg)

**Comment by tejxv** [comment]
this can be fixed with [autocomplete="off"](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#disabling_autocompletion)
