### ISSUE TITLE
Reward for Rooms.

### ISSUE THREAD

**Issue by yaslam-dev** [benawad/dogehouse#415]
At Dogehouse, It is normal for public rooms to last for more than 16 to 18 hours, one thing we can do to provide feedback to speaker and listener is to reward them.

Specs :
1- A timer component will be rendered somewhere on the room(Team will decide), to let people know how much time is elapsed since its creation, changing the name of the room shouldn't reset the timer and it will be destroyed once the room is destroyed. 

2- A hidden custom party popper (picture / gif) will be triggered if the room has elapsed more than 24 hours or other time-limit that the team decides.

This will provide a good feedback to users just like game rewards system.
If @benawad  likes the idea, I can get it done.

**Comment by benawad** [comment]
I like it, go for it!

**Comment by nadirabbas** [comment]
@Yasir900aslam is this being worked on?

**Comment by goldyydev** [comment]
![image](https://user-images.githubusercontent.com/55450464/111883313-2fe38500-89c3-11eb-9f54-0ac3f84cd6f8.png)

**Comment by goldyydev** [comment]
Actually, we could take this *much* further

**Comment by HarrisonMayotte** [comment]
I think only the first objective on the list was completed since there isn't really a party popper or anything like the second objective (to my knowledge). It just shows the different times and the corresponding emojis (which completed the first one on the list).

**Comment by BronzW** [comment]
Just going through random issues to see what can be cleaned up and as of now you can now see how long a room has been up for   in the next.dogehouse.tv website. I also think I heard Ben talking about not migrating the galactic doge feature to the new website on a contributor meeting or something so I think this can be closed right now as it has been implemented.
