### ISSUE TITLE
Scrollbar was reset to default

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#423]
I think as CSS was removed, the scrollbar was reset to this ugly looking default chrome bar

![image](https://user-images.githubusercontent.com/38838675/109178311-8a196d80-77aa-11eb-8b43-494a8216f067.png)

**Comment by benawad** [comment]
This was probably lost in the tailwind conversion, we can probably just copy it back into `main.css`

**Comment by nadirabbas** [comment]
@benawad `vars.css` only has the variables defined for scrollbar style. I couldn't find where they are actually being used.
