### ISSUE TITLE
setup storybook

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#424]

**Comment by FotieMConstant** [comment]
Hey, @benawad sounds really good! Could we set this up for the doc? @nadirabbas just notified me of this issue...

**Comment by benawad** [comment]
sure

**Comment by FotieMConstant** [comment]
I think we will have to have the documentation written first, then we can set this up! Just checked on StoryBook and it's more of documenting the various components of the project(in our case react website). Once we are done with the actual doc we will see into setting this up. I think it's more proper this way, what do you think?

**Comment by benawad** [comment]
I'm going to be using it for building out the mockups, so if you are still working on the docs then I'll set it up

**Comment by FotieMConstant** [comment]
Awesome, please do, currently working on the structure of the doc, will propose that in a PR.

**Comment by joshrezende** [comment]
I can pickup this one

**Comment by nadirabbas** [comment]
@joshrezende please coordinate with @FotieMConstant I think he's working on this.

**Comment by joshrezende** [comment]
@FotieMConstant you already started? and if so your idea its to have a separated folder or to live inside the react one?

**Comment by FotieMConstant** [comment]
Hi, @joshrezende. Ben said he'll set this up, so we'll take it from there once we are fully done with the content of the doc... lately working with @RonaldColyar on the structure of the doc. all the same, you can still do that and present on a PR.

**Comment by benawad** [comment]
@joshrezende I wasn't going to get to it until the mockups are done, so if you want to set it up now, all yours

**Comment by benawad** [comment]
probably keep it in `kofta` to keep it simple

**Comment by joshrezende** [comment]
ok then \o
