### ISSUE TITLE
[Feature] Display user local time in user profile

### ISSUE THREAD

**Issue by mohammedgad** [benawad/dogehouse#427]
Save the user timezone and display the local time in the user profile.
Users can edit their timezone from the edit profile page.
That will help to display the time for chat messages if we wanted to do that in the future.

_I don't know if that is needed or not, it's just a good feature that I like in **slack** and will be useful in displaying chat messages time_

cc: @benawad @nadirabbas

**Comment by benawad** [comment]
I don't think this is needed. It's more of something to see what timezone other coworkers are on. We are going to store the timestamp in UTC and convert it to local timezone on the frontend by getting it from the browser.
