### ISSUE TITLE
recently the site takes like a 3-4seconds to load rather than 0.5s

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#431]

**Comment by benawad** [comment]
Can you open the network tab and see what is taking up the time?

I'm assuming you are talking about initial load and not just for the rooms to show up.

**Comment by Mudrank** [comment]
Yeah sure 
![image](https://user-images.githubusercontent.com/70035508/109340380-f40b4300-788e-11eb-8027-6181641e2062.png)
main page

![image](https://user-images.githubusercontent.com/70035508/109340517-2157f100-788f-11eb-8143-bf3bc5be651a.png)
a room

**Comment by benawad** [comment]
looks like something took 32 seconds on the room page, wow

can you scroll down in the network tab until you see a large time

**Comment by nadirabbas** [comment]
@benawad today we hosted a room, and there were 44 speakers. we tried to speak at the same time. and there were 20+ listeners too. I think that's when it happened. not sure

**Comment by benawad** [comment]
it might just be all the profile pics loading

**Comment by Mudrank** [comment]
Yeah we also tried we were like 40 people and the server crashed

**Comment by nadirabbas** [comment]
it did not ccrash btw

**Comment by benawad** [comment]
it didn't crash but it was slow?

**Comment by nadirabbas** [comment]
not slow, it worked like a charm

**Comment by nadirabbas** [comment]
there were a couple of users tho, whose voices were breaking when we all spoke at the same time.

**Comment by Mudrank** [comment]
> it didn't crash but it was slow?

Maybe , Yes I think but for me everything foze for few seconds

**Comment by nadirabbas** [comment]
you had a different problem, you had to leave and rejoin the room to get it fixed, right?

**Comment by Mudrank** [comment]
> you had a different problem, you had to leave and rejoin the room to get it fixed, right?
 Yeah

**Comment by benawad** [comment]
so is the 3-4 second load time when you load the website for the first time or try to join a room?

**Comment by Mudrank** [comment]
yes I think

**Comment by Mudrank** [comment]
@benawad @nadirabbas  should this issue be closed?
