### ISSUE TITLE
It is not showing loading screen

### ISSUE THREAD

**Issue by akash3444** [benawad/dogehouse#433]
When I click on followers or following to see the list of people, I saw that it is showing 'No users found' for some time. But then it is showing the list of people. 
It would be best if it shows loading when loading the people list and show no users found if there is no follower or following

**Comment by Gautam-Arora24** [comment]
I am working on this!

**Comment by Gautam-Arora24** [comment]
Thank you @nadirabbas

**Comment by nadirabbas** [comment]
@Gautam-Arora24 btw if you haven't already seen it, a `Spinner` component already exists. you can use that.

**Comment by Gautam-Arora24** [comment]
Sure! First of all, I will try to reproduce this bug on my local machine and then will use that component :)

**Comment by Gautam-Arora24** [comment]
@nadirabbas I am unable to connect with Github on my local development. Though, I followed the steps that were stated in the contributing guidelines

**Comment by nadirabbas** [comment]
Have you created the Github OAuth app and everything?

**Comment by Gautam-Arora24** [comment]
No, neither the test user is working.

**Comment by nadirabbas** [comment]
Test user won't work in case you're using Docker version cuz thats prod. You need to use dev `iex -S mix`

**Comment by Gautam-Arora24** [comment]
Then, how to create the Github OAuth app?

**Comment by nadirabbas** [comment]
@Gautam-Arora24 Create here: https://github.com/settings/apps and get the client secret and id.

**Comment by Gautam-Arora24** [comment]
@nadirabbas What's the need of creating this Github OAuth app?
I mean how will it benefit me to put down this issue of mine

**Comment by nadirabbas** [comment]
@Gautam-Arora24 You will be able log in with Github.

**Comment by Gautam-Arora24** [comment]
Then what should I need to add in URL? Will that be dogehouse.tv?

**Comment by nadirabbas** [comment]
That will be your local ip and the port you're running the Elixir API on. I think you need to revisit https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md

**Comment by nadirabbas** [comment]
Normally it would be `http://localhost:4001/auth/github/web`

**Comment by Gautam-Arora24** [comment]
Thanks @nadirabbas I am now setting up a full local development environment.

**Comment by Gautam-Arora24** [comment]
@nadirabbas Do I really have to set up the whole development environment to connect with Github?

**Comment by nadirabbas** [comment]
@Gautam-Arora24 Yup. It's not complicated if you look at the contribution docs.

**Comment by Gautam-Arora24** [comment]
Sure!

**Comment by Gautam-Arora24** [comment]
@nadirabbas How can I see the effect of code change in the browser? I mean after changing the code and saving it, I cannot see any change in the browser even after refreshing it

**Comment by nikkhilkharade** [comment]
@Gautam-Arora24  did you create a build?

**Comment by Gautam-Arora24** [comment]
@nikkhilkharade No

**Comment by wes337** [comment]
@nikkhilkharade I have also created a branch which has a fix for this. Do I need contributor status to push my branch and open a PR?

**Comment by ajhalili2006** [comment]
> @nikkhilkharade I have also created a branch which has a fix for this. Do I need contributor status to push my branch and open a PR?

@wes337 Not really. You just push your branch into your fork and open a PR, just like what you do in an usual open-source project. People with write access to the repo (`Developer` role in GitLab) can push stuff into unprotected branches.

**Comment by wes337** [comment]
@AndreiJirohHaliliDev2006 Awesome thank you! I opened a PR for this just now. https://github.com/benawad/dogehouse/pull/942
