### ISSUE TITLE
It shows a black blank screen when I click on my profile.

### ISSUE THREAD

**Issue by lebrancconvas** [benawad/dogehouse#435]
**Describe the bug**
It happens when I try to change my bio in the profile when I change it, then It shows me that I can't go to my profile. It shows a black blank screen instead.

**Screenshots**
Record Link: https://youtu.be/UVGUQaH-LrM

**What device are you on?**
Google Chrome on Macbook Pro M1 13'' (macOS BigSur 11.2.1 ARM64)

**Comment by nadirabbas** [comment]
What did you write in your bio?
