### ISSUE TITLE
electron crashes on mac when requesting mic permission

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#439]
This causes the crash `systemPreferences.askForMediaAccess("microphone");` 

probably related to https://github.com/electron/electron/issues/19307

but this didn't fix it: https://github.com/electron/electron/issues/19307#issuecomment-524314643

cc @Stancobridge any ideas?

**Comment by nadirabbas** [comment]
@benawad this should probably help? https://github.com/electron/electron/issues/19307#issuecomment-512783270

**Comment by nadirabbas** [comment]
we can do:
`
"mac": {
    "hardenedRuntime": false
  }
`

**Comment by benawad** [comment]
Tried that with the same result and I think we want to keep that on for security

**Comment by Stancobridge** [comment]
So bad that I don't use Mac here, am on Linux there is no way I can test it out...

**Comment by melnary** [comment]
The app is working just fine on Big Sur. Is this only an issue on Mojave?

**Comment by benawad** [comment]
I'm on Catalina

**Comment by amitojsingh366** [comment]
temp fix: 
- Pull staging branch
- Follow steps mentioned in https://github.com/benawad/dogehouse/blob/staging/baklava/HOW_TO_RUN.md
- Run the command `npm run build:%YOUR_PLATFORM_CODE%` 
- Install the app from the `.dmg` build
- The issue should be gone now 
> **NOTE:** this issue still persists if running on dev but on a built version it's fixed

**Comment by yummyweb** [comment]
I believe this issue should be fixed, since it does not error.

**Comment by TheOtterlord** [comment]
@benawad are you able to use the mic on the newest client? or is this still unresolved?

**Comment by HarrisonMayotte** [comment]
Marking as closed as this appears to be resolved.
