### ISSUE TITLE
In rooms, names can only be up to 9 letters long.

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#44]

**Comment by giuseppecampanelli** [comment]
@samarmohan it's actually 10 characters
https://github.com/benawad/dogehouse/blob/45bde51bc3a58845dc6398fc771432ef43bdb095/kofta/src/vscode-webview/components/UserNode.tsx#L73

With 10, it ensures that no name goes onto a second line. Would have to see with @benawad

**Comment by samarmohan** [comment]
Well the code may say that but in practice it doesn't work.

**Comment by samarmohan** [comment]
Ill attach a screenshot

**Comment by samarmohan** [comment]
![image](https://user-images.githubusercontent.com/71091489/107818817-c88c4280-6d3d-11eb-812c-222a970d5d90.png)

**Comment by giuseppecampanelli** [comment]
@samarmohan yeah my bad, I forgot the endIndex on slice is exclusive.
Nonetheless, I believe it's limited to this to prevent spillover to a 2nd line. But maybe it can be increased 1-2 chars.

**Comment by goldyydev** [comment]
As far as I can see, this has been fixed (with the HTML truncating the text to fit a user's screen instead of a fixed JS slice)
![image](https://user-images.githubusercontent.com/55450464/111882338-bac18100-89bd-11eb-97d2-7bb21e8e414f.png)
