### ISSUE TITLE
Send button/icon on chat

### ISSUE THREAD

**Issue by karankumar89** [benawad/dogehouse#448]
Send button/icon on chat box would be a nice feature to have. So we don't have to rely on the send bar on the native keyboard. Also, I might be wrong or didn't pay attention - couldn't find a way to enter a new line.

Device: Samsung s10+ (Android 11)
Web browser: Chrome

**Comment by nadirabbas** [comment]
@karankumar89 yeh that feature would be nice. Btw the chat uses an `<input />` instead of a `<textarea />` so there are no newlines.

**Comment by benawad** [comment]
I want this to be mobile only
