### ISSUE TITLE
Please add a feature to report people

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#449]

**Comment by kndri** [comment]
question @benawad: what does 'thinking required' mean? 

is it something that you would think through or is it something community-led?

**Comment by HarrisonMayotte** [comment]
I believe it probably means that some thinking is required on how the implementation of this would work and how it would be implemented in a way that makes sense.

**Comment by ghost** [comment]
I feel that it is best to make a mod portal where moderators can review reports, ban users, and more.
