### ISSUE TITLE
Can't change my username, without adding bio

### ISSUE THREAD

**Issue by liketurbo** [benawad/dogehouse#457]
**Describe the bug**
Can't change my username, without adding bio. Get the error: "length 2 to 160 characters".

**To Reproduce**
1. Go to [DogeHouse](https://dogehouse.tv) (log in, if you didn't)
2. Enter your profile, click edit
3. Enter new username and you'll get an error (if you have empty bio)

**Expected behavior**
If by default bio is empty, I think you should be able change username without adding bio.

**Comment by bgergely0** [comment]
Same, but I don't get an error message. The save button simply doesnt work.
