### ISSUE TITLE
Permission denied message covers the bottom icons (mobile)

### ISSUE THREAD

**Issue by PuckDan** [benawad/dogehouse#463]
**Describe the bug**
So when your on mobile and make a room without a mic and go to chat the permission denied message covers the icons.

**To Reproduce**
1. Go on 'mobile'
2. Go to 'make a room without a mic'
3. Click on 'chat'

**Screenshots**
![Screenshot_20210227-185314_Brave](https://user-images.githubusercontent.com/65829743/109404747-a0503680-792e-11eb-8f57-57d0966f76db.jpg)

**What device are you on?**
Samsung S8+

**Comment by demfabris** [comment]
can't reproduce

setup:
Oneplus 7 Pro
Brave browser with nav. icons on the bottom
