### ISSUE TITLE
No Sound ⚠️ 

### ISSUE THREAD

**Issue by SudhamJayanthi** [benawad/dogehouse#47]
We need to create a room and turn our mic on for the first time to hear others in other rooms! Comment if it's not clear!

Possible solution: 
Ask for voice permissions initially while signing up

Detaills:
Browser - Chrome
OS - Windows 10

**Comment by samarmohan** [comment]
There should be a button that you click that asks for perms. 
That was pretty smart adding an emoji

**Comment by creepinson** [comment]
> There should be a button that you click that asks for perms.
> That was pretty smart adding an emoji

I clicked the try again button to ask for perms (I'm on firefox btw) and it went back to the main page and said room doesn't exist anymore and did nothing.
