### ISSUE TITLE
chat won’t scroll on iOS PWA

### ISSUE THREAD

**Issue by tejxv** [benawad/dogehouse#478]
**Describe the bug**
the room chat won't scroll, instead, the messages get cramped together 

**To Reproduce**
1. add dogehouse.tv to home screen via the share sheet
2. open any chat
3. type some messages
4. they get merged together 

**Expected behavior**
chat should scroll

**Screenshots**
![image](https://user-images.githubusercontent.com/54097365/109409988-1602e380-79bd-11eb-9cd1-9a4883c822f5.png)

and i'm on iPhone 8 on iOS 14.4

**Comment by tejxv** [comment]
well, the issue persists on safari too

![image](https://user-images.githubusercontent.com/54097365/109410938-7e08f800-79c4-11eb-9139-81312ef24e99.png)

**Comment by benawad** [comment]
can you verify this still happens in latest release, I reverted some css

**Comment by tejxv** [comment]
@benawad yeah it's still happening but i found the culprit but it's breaking a few other things lol
but i can make it work and will submit a PR soon
