### ISSUE TITLE
glitch?

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#480]
https://user-images.githubusercontent.com/70035508/109414200-ab12d600-79d7-11eb-8b9e-c36df23a4d9e.mp4

@benawad?

**Comment by nadirabbas** [comment]
Are you talking about chat?

**Comment by KristofKekesi** [comment]
The rooms container I think.
![image](https://user-images.githubusercontent.com/64812024/109415241-dd144000-79b7-11eb-8b47-2f82da3ec4d8.png)

**Comment by Mudrank** [comment]
@nadirabbas @KristofKekesi  both of them the container and the chat

**Comment by benawad** [comment]
reverted this css, should be fixed
