### ISSUE TITLE
Visual bug: Rooms list overflow there container

### ISSUE THREAD

**Issue by ayoubmehd** [benawad/dogehouse#483]
A Visual bug in the home page

Enter the home page

The rooms container shouldn't have a fixed height.
or it should scroll

![image](https://user-images.githubusercontent.com/43169971/109416544-2ddb6700-79bf-11eb-8729-4d265060f43f.png)

Windows 10 V2004 OS Build 19041.804 Brave Browser Version 1.20.110 Chromium: 88.0.4324.192

**Comment by benawad** [comment]
reverted this css, should be fixed
