### ISSUE TITLE
Error Message I should never see this 

### ISSUE THREAD

**Issue by piyusharorawork** [benawad/dogehouse#486]
**Describe the bug**
Got an error message "you should never see this" but still seeing this  after multiple refresh

![image](https://user-images.githubusercontent.com/31386968/109421815-eaa0e880-79fe-11eb-8ba5-2c226520beb4.png)

**Comment by Mudrank** [comment]
@piyusharorawork I am getting the same issue. 
@nadirabbas  @benawad

**Comment by benawad** [comment]
is it on a specific room?

**Comment by Mudrank** [comment]
it's just this room called "Gagie"
