### ISSUE TITLE
UI Internationalization

### ISSUE THREAD

**Issue by JammSpread** [benawad/dogehouse#488]
The UI of DogeHouse is in English. This may be a problem for international users.

Ideally, builtin UI should be just as natural to non-English users as English speakers.

Solutions like those used by Microsoft (VSCode) could be taken with specified local translations.

**Comment by FotieMConstant** [comment]
I was just about to race this issue, Thanks for bringing this on, @JammSpread. I could add a french translation. once the react-i18next has been setup!
