### ISSUE TITLE
delete msg not working

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#492]
@nadirabbas

**Comment by benawad** [comment]
what is your permission level in the room and what is the permission level of the person who's message you are trying to delete?

Or are you deleting your own messsage?

**Comment by Mudrank** [comment]
Yes, deleting my own message

**Comment by nadirabbas** [comment]
yeah for some reason that randomly stops working.

**Comment by nadirabbas** [comment]
@benawad probably an error on the frontend. looking into it.

**Comment by nadirabbas** [comment]
Also, the whispers are working locally but not on prod so that's a bug too.

**Comment by benawad** [comment]
whispers not working might be because not everyone has latest version, have you tested it with someone who refreshed?

**Comment by nadirabbas** [comment]
yeah :(

**Comment by nadirabbas** [comment]
everyone has basically refreshed now. I think the code got lost if somebody resolved conflicts?

**Comment by benawad** [comment]
maybe my revert messed it up, you can add it back

**Comment by Mudrank** [comment]
Now the delete works!

**Comment by Mudrank** [comment]
Not working! @nadirabbas  @benawad

**Comment by nadirabbas** [comment]
There is another issue open for this
