### ISSUE TITLE
Add Screen Sharing

### ISSUE THREAD

**Issue by DGKSK8LIFE** [benawad/dogehouse#496]
**Is your feature request related to a problem? Please describe.**
I often find that developers, including myself, use Dogehouse to seek assistance debugging issues and getting suggestions for upcoming projects/projects they are currently working on.

**Describe the solution you'd like**
Often times, with platforms like Discord, developers screenshare their code to seek assistance, I believe adding this feature to Dogehouse will reduce the need for multi-platform usage and allow the user to be more engaged/active with Dogehouse.

**Describe alternatives you've considered**
Codeblocks could also potentially be added to aid debugging, but screen sharing covers a wide variety of problems (ex: design trouble shooting, UI responsiveness, animations, etc) 

**Additional context**
This could be added as functionality for Dogehouse nitro/premium users though I believe it would be better to make it available for everyone.

**Comment by benawad** [comment]
I want to be audio focused

**Comment by DGKSK8LIFE** [comment]
What features do you plan on adding to monetize dogehouse, then? @benawad

**Comment by MANTENN** [comment]
@DGKSK8LIFE fork this and host a video version but costs would be expensive for hosting really quick.
