### ISSUE TITLE
User(Bot) API

### ISSUE THREAD

**Issue by Atlas7005** [benawad/dogehouse#503]
**Describe the solution you'd like**
A public API to interact with DogeHouse programmatically, to create apps such as Music Bots or even ChatBots.

**Describe alternatives you've considered**
I considered trying to look into whether or not a public API was required... Let's just say, I gave up very quickly, as I generally dislike reading through code that isn't mine _(lol)_ And it just seemed easier if the people who know the code best would create such a thing.

**Comment by Mudrank** [comment]
I like the idea somthing which people can make use like nightbots on youtube/twitch streams using the api

**Comment by yummyweb** [comment]
I request you to close this issue since this is one of Dogehouse' projects.

**Comment by Mudrank** [comment]
hey @yummyweb  the project not completed yet

**Comment by yummyweb** [comment]
@Mudrank It is not completed but it is a work in progress and me and @overlisted are working on it. So I request @Atlas7005 to close the issue. Check dogehouse-js. Though, atm you can join rooms and leave rooms and send messages which by far is a lot.

**Comment by Mudrank** [comment]
I feel till it's completed we should have this issue open

**Comment by overlisted** [comment]
check out #1043

**Comment by goldyydev** [comment]
Since #1207 is much more active, I'll be closing this issue.
