### ISSUE TITLE
rename Follower.fetch_following_online/1

### ISSUE THREAD

**Issue by ityonemo** [benawad/dogehouse#509]
**Describe the bug**
Follower.fetch_following_online/1 seems to return follows that aren't online

**Expected behavior**
only online follows should be returned.

See test@ test/ad_hoc_user_test.exs:219

```
  1) test Kousa.Data.Follower fetch_following_online (KousaTest.AdHocUserTest)
     test/ad_hoc_user_test.exs:217
     match (=) failed
     code:  assert {[], _} = Follower.fetch_following_online(uid)
     left:  {[], _}
     right: {
              [
                %Beef.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, avatarUrl: "https://example.com/abc.jpg", bio: "a dogehouse user", currentRoom: nil, currentRoomId: nil, displayName: "okey.veum", email: "duane.leannon@hotmail.com", followsYou: false, githubAccessToken: "ntoaunthanuheoh", githubId: "kaleb_walter", hasLoggedIn: false, id: "da235391-a1b3-434a-9f8f-fa8b389bf929", inserted_at: ~N[2021-03-01 05:48:25], lastOnline: nil, numFollowers: 0, numFollowing: 0, online: false, reasonForBan: nil, roomPermissions: nil, tokenVersion: 1, twitterId: "keeley2006", updated_at: ~N[2021-03-01 05:48:25], username: "titus_rau", youAreFollowing: nil},
                %Beef.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, avatarUrl: "https://example.com/abc.jpg", bio: "a dogehouse user", currentRoom: nil, currentRoomId: nil, displayName: "trisha1912", email: "lisandro.balistreri@gmail.com", followsYou: false, githubAccessToken: "ntoaunthanuheoh", githubId: "georgianna_jacobi", hasLoggedIn: false, id: "fa642e30-55ab-4c08-a9bc-e91a72a10a41", inserted_at: ~N[2021-03-01 05:48:25], lastOnline: nil, numFollowers: 0, numFollowing: 0, online: false, reasonForBan: nil, roomPermissions: nil, tokenVersion: 1, twitterId: "alan1928", updated_at: ~N[2021-03-01 05:48:25], username: "pat1901", youAreFollowing: nil}
              ],
              nil
            }
     stacktrace:
       test/ad_hoc_user_test.exs:227: (test)
```

when you take `@tag :skip` off.

note that both of the returned structs have `online: false`

Posting here before actually fixing it just to see if this correlates with other unusual observations elsewhere.

**Comment by ityonemo** [comment]
note this won't be on staging branch until hyperhypebeast branch is merged in (and it may be a bit before the hyperhypebeast branch reflects this @9p PT 28 Feb)

**Comment by FotieMConstant** [comment]
@benawad @nadirabbas

**Comment by ityonemo** [comment]
https://github.com/benawad/dogehouse/blob/51421edff6162ba1fe08a18cf0b231d2dc55ebc3/kousa/test/ad_hoc_user_test.exs#L218-L236

**Comment by nadirabbas** [comment]
@ityonemo this is intended. I forgot to rename the function. Now it is actually supposed to fetch both online and offline users. The thing that makes this function distinct from other followers/following fetching functions is that this also returns the current room the people you're following are in. a PR maybe?

**Comment by ityonemo** [comment]
I'll de-escalate from bug and make this a rename/refactor task.

**Comment by ityonemo** [comment]
huh, gh won't let me de-escalate it, lol

**Comment by ityonemo** [comment]
seems to be done?
