### ISSUE TITLE
Username not visible

### ISSUE THREAD

**Issue by SinadShan** [benawad/dogehouse#51]
GitHub username not visible while joining rooms.

**Comment by giuseppecampanelli** [comment]
@SinadShan when you join a room it shows your GitHub name (note: not username) and only the first 9 characters of it

**Comment by SinadShan** [comment]
I do understand that, but in my case nothing is visible. Have a look at the image attached.
![image](https://user-images.githubusercontent.com/71889312/107840467-fbcfdf80-6dd8-11eb-9ed2-1978db50ea48.png)
