### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by Salman2301** [benawad/dogehouse#517]
**Describe the bug**
When the user click on the delete the message, the message can't deleted. 

**To Reproduce**
1. Open the chat
2. Add the message
3. Click on the name in the chat[ for that message ], it will open the popup
4. Click on the delete message popup in the popup

**Expected behavior**
Should delete the user message, once the button is clicked

**What device are you on?**
Chrome , Windows

**Comment by Salman2301** [comment]
@nadirabbas

**Comment by nadirabbas** [comment]
Yes, we're aware of that. It randomly stops working. There is already an issue open for this. I am looking into it. Duplicate #514

**Comment by nadirabbas** [comment]
It works and stops working randomly atm. I am looking into it.

**Comment by Mudrank** [comment]
not working @nadirabbas

**Comment by nadirabbas** [comment]
cuz it wasnt fixed

**Comment by ajmnz** [comment]
@Mudrank Are you still able to reproduce this issue?
