### ISSUE TITLE
Remove need for centralized voice server

### ISSUE THREAD

**Issue by ankemp** [benawad/dogehouse#52]
Use P2P WebRTC networking instead of connecting everyone to a centralized server.
[webrtc-swarm](https://github.com/mafintosh/webrtc-swarm) does this.
You can use something like [signalhub](https://github.com/mafintosh/signalhub) to do the initial peer connection.

Take a peak at this repo: https://github.com/tom-james-watson/p2p.chat - he got p2p chat working pretty well it seems.

**Comment by benawad** [comment]
I would like to be able to host +1K listeners , I don't think p2p can support that
