### ISSUE TITLE
Add google analytics?

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#520]

**Comment by DGKSK8LIFE** [comment]
Analytics for what exactly though? @nadirabbas

**Comment by nadirabbas** [comment]
@DGKSK8LIFE to see traffic data for Dogehouse 😅

**Comment by DGKSK8LIFE** [comment]
Ah yes. Ok lol thought you were going to be more specific but ok.

**Comment by nadirabbas** [comment]
Ben is prolly gonna close this anyway 😂

**Comment by DGKSK8LIFE** [comment]
> Ben is prolly gonna close this anyway joy
 
How it be :cry:

**Comment by Abogical** [comment]
Not really comfortable with having analytics from google. I'm sure there are better alternatives.

**Comment by DGKSK8LIFE** [comment]
> Not really comfortable with having analytics from google. I'm sure there are better alternatives.

This doesn't really make much sense, considering Dogehouse is already hosted on GCP, which probably already is internally storing data related to the application and its servers anyways. Analytics is just an app/platform to visualize and really quantify the data they are collecting.

**Comment by Abogical** [comment]
> > Not really comfortable with having analytics from google. I'm sure there are better alternatives.
> 
> This doesn't really make much sense, considering Dogehouse is already hosted on GCP, which probably already is internally storing data related to the application and its servers anyways. Analytics is just an app/platform to visualize and really quantify the data they are collecting.

Good point. However, I'd consider a server side analytics tool, not client side. This may be a stretch but considering ben's demographic, lots of people would use adblockers. Thus client side analytic solutions such as Google Analytics may provide unreliable data in the first place.

**Comment by DGKSK8LIFE** [comment]
> Good point. However, I'd consider a server side analytics tool, not client side. This may be a stretch but considering ben's demographic, lots of people would use adblockers. Thus client side analytic solutions such as Google Analytics may provide unreliable data in the first place.

I believe google analytics is server-side?? Not 100% sure.

**Comment by Abogical** [comment]
> > Good point. However, I'd consider a server side analytics tool, not client side. This may be a stretch but considering ben's demographic, lots of people would use adblockers. Thus client side analytic solutions such as Google Analytics may provide unreliable data in the first place.
> 
> I believe google analytics is server-side?? Not 100% sure.

It's client side. It needs an injected JavaScript from google for it to work.

**Comment by ermalsh** [comment]
10m records/month free, I personally use Amplitude. Easy to implement, nice dashboards, etc.. https://developers.amplitude.com/docs/sdk-basics

**Comment by ChannelJuanNews** [comment]
please do not use google analytics for metrics tracking. Please use mixpanel or segement or literally anything else.

**Comment by iamanalt** [comment]
I will stop using and recommending DogeHouse if GA are added.

**Comment by nadirabbas** [comment]
guess people really hate Google Analytics
