### ISSUE TITLE
admin can be banned

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#526]
as this happened with @nadirabbas  can you describe this @nadirabbas ?

**Comment by nadirabbas** [comment]
Well, I wasn't precisely an admin. I was a mod, I got banned from chat. Then the room ownership was transferred to me. but I was still banned from the chat *sad nadir noises*

**Comment by goldyydev** [comment]
@nadirabbas are you still working on this or can we open this up for contributorrs?

**Comment by ajmnz** [comment]
@Mudrank Are you still able to reproduce this issue?

**Comment by Mudrank** [comment]
@ajmnz  Nope it's fixed ,Just tested it
