### ISSUE TITLE
Toasts are hidden when a modal is up

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#544]

**Comment by ovibutt** [comment]
Is someone working on this issue? If not how do you produce this issue?

**Comment by benawad** [comment]
@ovbutt nope, you are welcome to try fixing it. Best way to reproduce is to create a test modal with a button in it that creates a toast and see if it appears

**Comment by ovibutt** [comment]
@benawad  I have tested this issue and toasts are working fine on my end please verify. I have attached a screenshot on this too.

The Steps I followed are
1) I created a test modal (covering all screen).
2) added a button to trigger toast
3) and toast was functional and I was able to close it.

![image](https://user-images.githubusercontent.com/31251140/110836537-fd020880-82c1-11eb-93df-8e12efc3d16b.png)

**Comment by komen205** [comment]
I tried a simple code and it works.

```
      <button onClick={() => showErrorToast('test')}>
  Activate Error
</button>
```
![image](https://user-images.githubusercontent.com/59452877/111816651-fd5b5e80-88d4-11eb-8aec-be128aab7108.png)

**Comment by TheOtterlord** [comment]
No problem with this in Kibbeh (as far as I know. please reopen/create new issue if it's broken in kibbeh)
