### ISSUE TITLE
Adjust positioning of login buttons and footer links

### ISSUE THREAD

**Issue by andrewroblesdev** [benawad/dogehouse#553]
When viewed from a desktop, login buttons and footer links should be the same width of the text above it in order to be more visually appealing.

**Comment by andrewroblesdev** [comment]
Quick mockup to illustrate what I mean:
![Screenshot 2021-03-05 083444](https://user-images.githubusercontent.com/70864612/110144913-bd04c800-7d8d-11eb-9b33-e530e522b068.png)

**Comment by andrewrobles** [comment]
Not sure if there issues need to be approved before anyone starts working on them. But I would like to work on this issue

**Comment by andrewroblesdev** [comment]
Not sure if issues need to be approved before anyone starts working on them. But I would like to work on this issue

**Comment by benawad** [comment]
sounds good, go for it!
