### ISSUE TITLE
Add Imgur API for automatically uploading images (links only in chat)

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#556]
If people want to share screenshots currently, they have to upload them somewhere and share the links. 

We can give our chat input the functionality so people can paste their screenshots (copied to clipboard) and it will upload them to imgur using the Imgur API. 

Then we can just show the image URL in the chat list instead of the image, which keeps the chat cleaner to, and makes it really easy to share images.

**Comment by benawad** [comment]
I don't want to hook into Imgur api
