### ISSUE TITLE
Kick people 

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#557]
@benawad

**Comment by nadirabbas** [comment]
use your feet to kick people. I've tried it, it works. 😅

**Comment by DGKSK8LIFE** [comment]
Already functionality that's implemented @Mudrank (you can ban people from rooms)

**Comment by Mudrank** [comment]
Yeah so I don't want to ban them just kick them out of the room

**Comment by DGKSK8LIFE** [comment]
Yeah but I feel like that functionality is kinda futile because they could just rejoin again. What would be more useful is a temp ban/mute for users that are acting up. @Mudrank

**Comment by DGKSK8LIFE** [comment]
@benawad what do you think?

**Comment by Mudrank** [comment]
I like they cannot join until the next session something like that

**Comment by DGKSK8LIFE** [comment]
Well I was thinking of the possibility to adjust the time more precisely (ex: 5 hour/2 days, etc). Though as of now I don't really know of rooms that stay open that long.
