### ISSUE TITLE
Show doge value 

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#558]
Since dogeHouse related to doge maybe show the value of doge right now at
 the top?

@benawad

**Comment by ZackaryH8** [comment]
Could be added using [this](https://www.cryptonator.com/api), 
[List of currencies](https://www.cryptonator.com/api/currencies)

[This](https://api.cryptonator.com/api/ticker/doge-gbp) returns JSON with the required data:
```json
{
    "ticker":{
        "base":"DOGE",
        "target":"GBP",
        "price":"0.03581547",
        "volume":"18929690.43329700",
        "change":"0.00042681"
    },
    "timestamp":1614965522,
    "success":true,
    "error":""
}
```

**Comment by DGKSK8LIFE** [comment]
I feel like it's supplemental functionality that really doesn't add much value to the application. It's also more data (JSON fetching, deserializing, component load, etc) (in @ZackaryH8's case) which really isn't a problem, but as the app scales up, it could lead to worse performance and longer load times.
