### ISSUE TITLE
Cannot speak/listen to anything

### ISSUE THREAD

**Issue by gdrose** [benawad/dogehouse#56]
I tried to switch browsers/check permissions but nothing works, I can't hear/talk.

My browser permissions are fine, and also it doesn't ask for any type of permissions

**Comment by goldyydev** [comment]
Ben has fixed this (it was an interaction-needed issue), as mentioned in dogeLog[0].

**Comment by goldyydev** [comment]
If you're still having an issue, make sure to re-open this
