### ISSUE TITLE
Profile Url

### ISSUE THREAD

**Issue by geekgonecrazy** [benawad/dogehouse#569]
**Is your feature request related to a problem? Please describe.**
When I want to invite some friends to check it out.  I'd like to be able to link to a profile link.  like: https://dogehouse.tv/user/username

This way they could follow me and I could invite them to a private room.  Otherwise I have to make it public get them to join.  Follow them.. And then create a private room and bring them all in.

**Describe the solution you'd like**
It could just show the little follow card over the channel list if need be.  Just a way that they could find me and then follow

**Describe alternatives you've considered**
Search would also work

**Additional context**

**Comment by rajpatil53** [comment]
@benawad Could you please assign this to me?

**Comment by rajpatil53** [comment]
#1426
