### ISSUE TITLE
Chat stays open after leaving room

### ISSUE THREAD

**Issue by 11ma** [benawad/dogehouse#573]
**Describe the bug**
When you open a chat in a room and step out of the room the chat remains open when you go to different pages. 

**To Reproduce**
1. go to a room
2. Click on chat
3. step out of room, click on profile, or anywhere else 

**Expected behavior**
Chat should close when you leave room

**Screenshots**
![Screenshot 2021-03-05 at 22 46 07](https://user-images.githubusercontent.com/33061753/110182432-a77eb500-7e04-11eb-8af6-60384302e9c2.png)
![Screenshot 2021-03-05 at 22 45 57](https://user-images.githubusercontent.com/33061753/110182439-a8afe200-7e04-11eb-993f-99e02c832beb.png)

**What device are you on?**
Mac

**Comment by nadirabbas** [comment]
When I leave room, the chat closes automatically:

https://user-images.githubusercontent.com/38838675/110184055-0a3a7580-7e32-11eb-9951-dd3cad0bde5b.mp4

**Comment by 11ma** [comment]
what browser are you using? I'm on firefox

https://user-images.githubusercontent.com/33061753/110187773-7953a200-7e11-11eb-95b9-8a0e2af83b3e.mov

**Comment by nadirabbas** [comment]
Chrome on windows

**Comment by nadirabbas** [comment]
You haven't actually left the room at all.

**Comment by 11ma** [comment]
Oh right, so unless you leave the room, the chat remains accessible?

**Comment by nadirabbas** [comment]
@11ma yup
