### ISSUE TITLE
Kofta: Look at profile of a scheduled meeting's author

### ISSUE THREAD

**Issue by melnary** [benawad/dogehouse#602]
Currently, the only two pieces of information about the author of a scheduled meeting is the author's icon and their name in the description.
I feel like you should be able to view their profile (for example to follow them), from the scheduled meeting.
Is this something desirable?

**Comment by benawad** [comment]
yeah good idea

**Comment by melnary** [comment]
Ok, I can work on this!

**Comment by benawad** [comment]
create a new route `/user/:username` to view peoples profiles (you can still use `<UserProfile />` component thing

**Comment by melnary** [comment]
Would it be better to create a new page that grabs the username from the URL, like you described, or actually reuse `<ViewUserPage />`, which takes the user data from the location state? Or should the new page just wrap `<ViewUserPage />` with some logic to get the user data?

**Comment by melnary** [comment]
I didn't really anticipate the redesign being started so early, the focus should probably be switched to that now instead of Kofta, so I'll close this issue!
