### ISSUE TITLE
Unable to toggle between Listeners and Speakers

### ISSUE THREAD

**Issue by jaipack17** [benawad/dogehouse#61]
Hi there,
First of all props to Ben Awad for making the web app. Its really amazing and has inspired me a lot.

Here's where the issue is -

When changed my role from a Listener to the Speaker. I am no longer able to switch back to the role of a listener.

Is there something I am doing wrong or is it a bug?

**Comment by selfrisingfloor** [comment]
I don't think there's an option to move back yet

**Comment by benawad** [comment]
fixed
