### ISSUE TITLE
Horizontal Scrolling on Schedule room

### ISSUE THREAD

**Issue by Subhom1** [benawad/dogehouse#612]
If schedule room description gets longer then it's creating a horizontal scroll.
![Screenshot_20210307-095054](https://user-images.githubusercontent.com/20743746/110228921-08081200-7f2b-11eb-9d58-98785aa80928.jpg)

**Comment by benawad** [comment]
fixed

**Comment by Subhom1** [comment]
I'd love to work on the new design @React part @benawad  count me in
