### ISSUE TITLE
make the links shorten

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#615]

**Comment by n3oney** [comment]
I don't think we need as many IDs as UUIDv4 can provide. I think a better idea for Room IDs would be snowflakes.
![image](https://user-images.githubusercontent.com/30625554/118515052-4ee96380-b735-11eb-899c-2f06092aeaa3.png)
They could also store the date of creation of the room!
Also, a 64-bit snowflake converted to a Radix-64 string would be just like... 10 characters.
