### ISSUE TITLE
Introduce language flags on chat rooms

### ISSUE THREAD

**Issue by ccoder1337** [benawad/dogehouse#618]
Language flags will then tell you which language is beeing preferred in the room.

**Comment by AkiraTenchi** [comment]
I agree with the language flags, but i don't think limiting the names to latin letters would be a good move given that there are many languages that do not use latin letters and why deny users from those countries the creation of rooms with names in their native language?

**Comment by ccoder1337** [comment]
I mean it isn't difficult to switch keyboard schemes

**Comment by ccoder1337** [comment]
For example every russian keyboard also has a lattin layout printed on it

**Comment by ccoder1337** [comment]
I guess language flags would be enough
