### ISSUE TITLE
Kofta: Make the language codes display in uppercase

### ISSUE THREAD

**Issue by ccoder1337** [benawad/dogehouse#619]
![grafik](https://user-images.githubusercontent.com/49637671/110237087-1d386d00-7f3a-11eb-86cd-0575d628e924.png)

**Comment by AkiraTenchi** [comment]
As you can see [here](https://www.andiamo.co.uk/resources/iso-language-codes/) the ISO standard uses lowercase.

**Comment by ottx96** [comment]
Yeah that's true. As of ISO 639-2 it's lowercase letters.
Although, I think this is a better source of information: [ISO 639-2](https://www.loc.gov/standards/iso639-2/)

**Comment by ccoder1337** [comment]
Maybe add flag icons or something like that?

**Comment by almandoro** [comment]
@benawad What do you think about small flag icon next to the language code?
I'd do that. Pretty simple task for the first contribution.

**Comment by benawad** [comment]
@almandoro sure

**Comment by SuperSonicHub1** [comment]
@almandoro Darn, beat me to the issue.

I already made the edit necessary, so I guess you should have it (it's in JSON though):
```json
[
  { "value": "en", "label": "🇬🇧 en" },
  { "value": "cs", "label": "🇨🇿 cs" },
  { "value": "de", "label": "🇩🇪 de" },
  { "value": "es", "label": "🇪🇸 es" },
  { "value": "fr", "label": "🇫🇷 fr" },
  { "value": "he", "label": "🇮🇱 he" },
  { "value": "hi", "label": "🇮🇳 hi" },
  { "value": "hu", "label": "🇭🇺 hu" },
  { "value": "id", "label": "🇮🇩 id" },
  { "value": "it", "label": "🇮🇹 it" },
  { "value": "lt", "label": "🇱🇹 lt" },
  { "value": "nb", "label": "🇳🇴 nb" },
  { "value": "nl", "label": "🇧🇶 nl" },
  { "value": "pl", "label": "🇵🇱 pl" },
  { "value": "pt-BR", "label": "🇵🇹 pt-br" },
  { "value": "pt-PT", "label": "🇵🇹 pt-pt" },
  { "value": "ru", "label": "🇷🇺 ru" },
  { "value": "th", "label": "🇹🇭 th" },
  { "value": "tr", "label": "🇹🇷 tr" },
  { "value": "zh-CN", "label": "🇨🇳 zh-cn" }
]
```

**Comment by almandoro** [comment]
@SuperSonicHub1 no worries 😁
