### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by Muhammadinaam** [benawad/dogehouse#623]
I came to know about this project from ben awad's video. I have subscribed to his channel. 

What is this project used for? I am not able to underatand. Taking voice conversation to moon. Is this something like zoom meetings?

**Comment by deijjji303** [comment]
Right now it is a bit like the app "clubhouse", but it's going to have a monopoly position in the audio-communication market with a ton features and ways to monetize your conversations actually already within the next few days.
