### ISSUE TITLE
Push to talk in Mobile

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#626]
![20210307_214616.png](https://user-images.githubusercontent.com/70035508/110246694-a8dbe900-7f8e-11eb-8e9c-9aa6c803486d.png)
This is not ablecable on mobile maybe something like double tap or shake something like that

**Comment by nadirabbas** [comment]
@benawad I can add push to talk on mobile when you double-tap the mic icon.

**Comment by benawad** [comment]
we will make it push & hold, but don't worry about this right now
