### ISSUE TITLE
Components not appearing together

### ISSUE THREAD

**Issue by SPARTACUS5329** [benawad/dogehouse#629]
**Describe the bug**
When the website is loaded, some components are loaded and then they suddenly disappear. Everything is loaded together after that. The webpage isn't reloaded.

**Expected behaviour**
All components should be loaded together

**What device are you on?**
MacBook (MacOS 11; Google Chrome)

https://user-images.githubusercontent.com/58896813/110247981-dcba0d00-7f94-11eb-8990-b67464233d4d.mov

**Comment by benawad** [comment]
fixed by d1421ca8bf8bc10b0acd6e2bd23634d6e2713b32
