### ISSUE TITLE
Disable clicking offline mentioned users in chat

### ISSUE THREAD

**Issue by ajmnz** [benawad/dogehouse#635]
**Describe the bug**
When you click a mention of a user that has disconnected it starts showing multiple errors on and on.

**To Reproduce**
1. Go to a room
2. Click on a mention of a disconnected user

**Expected behavior**
Disable clicking offline mentioned users in chat

**Screenshots**
<img width="385" alt="Screenshot 2021-03-07 at 20 55 36" src="https://user-images.githubusercontent.com/57961822/110252874-d40f0a00-7f87-11eb-8cbe-61369ffd960a.png">

**What device are you on?**
Firefox Developer Edition, Apple MacBook Pro (Late 2018)

**Comment by ajmnz** [comment]
I presumed it was disconnected users, but might be someone who changed their handle? It happened to me when clicking on `@horry`

**Comment by nadirabbas** [comment]
Yeah I did this, may be I messed up somewhere, will fix it.
