### ISSUE TITLE
[New Design] Atomic Components Implementation v1

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#637]
<h1>Atomic Components</h1>

(do not add margin on any atomic components)

- [x] Button: https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A731
- [x] Tag: https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A680
- [x] IconHeading - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A681
- [x] ScheduledTime - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A686
- [x] UserAvatar - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A679
- [x] BoxedIcon - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A704
- [x] UserBadge - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=448%3A725
- [x] SearchBar - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1619
- [x] SearchHistory - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1697
- [x] SearchOverlay - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1696
  - this is just the container
- [x] SettingsIcon - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1773
- [x] BaseOverlay - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1842
  - this will be used to make SettingsOverlay/NotificationsOverlay/Message

<h1>Compound Components</h1>

- [x] SearchResult - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A1747
  -  requires UserAvatar & ScheduledTime & SearchHistory ✅
- [x] MessageElement - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=499%3A2053
  - requires UserAvatar ✅
- [x] NotificationElement - https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=201%3A2146
  - requires UserAvatar & Button ✅

Put your component in `kibbeh/src/ui` and create a story in `kibbeh/src/stories`

Use tailwind for styling (see the tailwind config for theme info).

You have to use TypeScript.

Work on the `new-design` branch.

Please comment below if you start to work on a component, but only claim a component if you plan to work on it right away so it doesn't block other people

assets: https://github.com/benawad/dogehouse/tree/new-design/.redesign-assets

If you have any questions ask me or @ ajb on discord

**Comment by sahilmob** [comment]
I will work on the user avatar components.

**Comment by benawad** [comment]
I'm starting on `Button`

**Comment by Jackbaude** [comment]
Im taking a shot at Tag

**Comment by andrewroblesdev** [comment]
I got `IconHeading`

**Comment by benawad** [comment]
make sure to pull, I renamed the colors and actually got storybook working

**Comment by sahilmob** [comment]
@benawad The red circle needs custom bottom and right values to be positioned correctly with the different sizes of the avatar, what do you prefer?

1-An object to map the size to custom values
2-Normal css file with custom classes
3-css modules

![circle](https://user-images.githubusercontent.com/33333226/110343911-a2547c80-8035-11eb-89ea-4bf52777e563.png)

**Comment by benawad** [comment]
@sahilmob object map

**Comment by nadirabbas** [comment]
I'll work on SearchOverlay

**Comment by mayconbenito** [comment]
i will work on SearchHistory

**Comment by kleo-xhindoli** [comment]
I can take a stab at the SearchBar component

**Comment by jee1mr** [comment]
I'm gonna work on ScheduledTime

**Comment by jee1mr** [comment]
Completed ScheduledTime

**Comment by sahilmob** [comment]
I will work on MessageElement

**Comment by chancovsky** [comment]
I'll take `UserBadge`

**Comment by chancovsky** [comment]
I will work on `BoxedIcon` as well

**Comment by ermalsh** [comment]
@Jackbaude Are you still working on `Tag`? If not I have it complete and can PR.

**Comment by Jackbaude** [comment]
> @Jackbaude Are you still working on `Tag`? If not I have it complete and can PR.

No you can PR

**Comment by sahilmob** [comment]
I will work on SettingsIcon

**Comment by sahilmob** [comment]
I will work on SearchOverlay

**Comment by jee1mr** [comment]
I will work on NotificationElement!

**Comment by andrewrobles** [comment]
I got `BaseOverlay` next

**Comment by lenilsondc** [comment]
I'm working on `BaseOverlay`.

**Comment by sahilmob** [comment]
SearchResult PR submitted for review. #693

**Comment by sahilmob** [comment]
#693

**Comment by ajmnz** [comment]
Hey everyone, Atomic Components v2 implementation has started. Refer to #698 if you want to work on any of those.

**Comment by ajmnz** [comment]
All done, thanks everyone!
