### ISSUE TITLE
Federation?

### ISSUE THREAD

**Issue by Abogical** [benawad/dogehouse#64]
If you actually take this seriously, you could implement this social network as a federated decentralized network through Activitypub (What mastodon uses) or Matrix.

https://activitypub.rocks/

**Comment by mikestaub** [comment]
I would wait until Twitter announces the protocol they plan on using. https://twitter.com/bluesky

**Comment by Abogical** [comment]
ActivityPub is a W3C standard that is already established and integrated with many social media platforms. There's no need to need to wait for a protocol that hasn't been finalised for more than a year.

**Comment by benawad** [comment]
central server for now
