### ISSUE TITLE
Always sends 2 notifications

### ISSUE THREAD

**Issue by vi241** [benawad/dogehouse#643]
**Describe the bug**
Dogehouse always sends 2 notifications with error messages instead of 1

**To Reproduce**
1. Create a new *private* room
2. Open incognito with another user
3. Send an invite to the other user (normal chrome)
4. Join the room (incognito)
5. Reload the page (incognito)
4. See double notification

**Screenshots**
![image](https://user-images.githubusercontent.com/60016719/110306781-e2503b00-8006-11eb-92e2-e222f0271152.png)

**What device are you on?**
MacBook Pro 2019

**Comment by xiuxiu62** [comment]
This error is thrown in the join_room method of /kousa/lib/business-logic/room_logic.ex on line 296 -- not a clue how to read elixir, but hopefully it's a simple logic error.

**Comment by vi241** [comment]
oh ok

**Comment by vi241** [comment]
I will check, thank you
