### ISSUE TITLE
Spinner is off center.

### ISSUE THREAD

**Issue by ravinhwg** [benawad/dogehouse#645]
**Describe the bug**
The Spinner that is shown while the rooms are loading is off centered on desktop.
**To Reproduce**
1. Go to dogehouse.tv (You won't notice it if your connection is very fast  switch to low-end-mobile on chrome devtools)

**Expected behavior**
The Spinner is shown at the center of the page

**What device are you on?**
Desktop
**Additional context**
N/A

**Comment by ermalsh** [comment]
Closed. Merged and in prod.

**Comment by ravinhwg** [comment]
Closing the issue. :)
