### ISSUE TITLE
Incorrect values for following count

### ISSUE THREAD

**Issue by s3ansh33p** [benawad/dogehouse#650]
**Describe the bug**
Following count incorrect / reset.

**To Reproduce**
This occured a little while ago, where the user count was reduced significantly. I believe that at one point I was following 14k-15k users a couple of weeks ago (did some users get removed from the platform? or were the following/followed values reset for these?). I made a script to click on the "Load More" button on the following page and repeat, and then counted the number of users displayed there, and the value was **8092**, so I assume there are incorrect values for the following count.

**Expected behavior**
The following count to be 8092 not 3900

**Screenshots**
 - https://cdn.discordapp.com/attachments/446854611937263619/810097369470730280/unknown.png (6969)
Posted in the Discord server (https://discord.com/channels/446854611937263616/446854611937263619/810097372436627466) on the 13th of February
 - https://imgur.com/kxNyab8 Uploaded today (3900)
 - https://imgur.com/1JJl7lo Actual value today (8092)

**What device are you on?**
Windows 10 Desktop

**Additional context**

**Comment by benawad** [comment]
The db has you following `3896` users so it is a little off. I'll update that, my guess is for the 8092 the nodes got double counted.
