### ISSUE TITLE
save messages in local storage when leaving room

### ISSUE THREAD

**Issue by munetta** [benawad/dogehouse#670]
**Is your feature request related to a problem? Please describe.**
when i left a room and joined all the messages had disappeared

**Describe the solution you'd like**
add each message to local storage or something and when rejoin a specific room you had left, grab the messages from local and load them in before initing sockets. arr[{row}]; <- put this in local

**Describe alternatives you've considered**
none

**Additional context**
sorry if you considered this but didn't want to do it. /:

**Comment by nadirabbas** [comment]
I think @benawad wants to match Twitch, where the chat resets on reload/when you leave the stream.

**Comment by ajmnz** [comment]
> I think @benawad wants to match Twitch, where the chat resets on reload/when you leave the stream.

yep, he said that in the contributor meeting

**Comment by munetta** [comment]
oh.. /:
