### ISSUE TITLE
Can’t hear IOS brave Browser

### ISSUE THREAD

**Issue by ccm7676** [benawad/dogehouse#68]
Can’t hear even though ring tone is on and volume is at max

**Comment by benawad** [comment]
is this only happening on the brave browser on that device for you?

**Comment by Salmon-e** [comment]
I've also had to leave rooms and then rejoin them several times for audio to work. I'm using Chrome.

**Comment by Jirushi-I** [comment]
Sometimes, I only hear one person until I rejoin.

**Comment by hkirat** [comment]
Ios's webrtc support is limited to Safari. 
More here - https://stackoverflow.com/questions/39790639/webrtc-support-on-chrome-browser-in-iphone-ipad#:~:text=2%20Answers&text=No%20you%20can't%20use,web%20engine%20on%20their%20platform).

**Comment by goldyydev** [comment]
We might want to add a prompt to tell the user that webRTC is not supported in their browser; can also help with these darn IE11 users.

**Comment by ajmnz** [comment]
This issue seems to be fixed now. Audio working fine on iOS 14.4.2 and Brave.
