### ISSUE TITLE
Add more hotkeys and create generic Keybind component

### ISSUE THREAD

**Issue by andrewroblesdev** [benawad/dogehouse#690]
Add the following hotkeys:
- Request-to-speak: `Control + 8`
- Invite: `Control + 7`

Create a generic `Keybind.tsx` file to use for the following files that are extremely similar to each other:
- `ChatKeybind.tsx`
- `MuteKeybind.tsx`
- `PTTKeybind.tsx`
- `RequestToSpeakKeybind.tsx`
- `InviteKeybind.tsx`

**Comment by andrewroblesdev** [comment]
If this issue is approved, I would like to work on it

**Comment by benawad** [comment]
btw reason I switched the default chat hotkey is it was conflicting with people copy/pasting
