### ISSUE TITLE
daily dogecoin reward when people login

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#695]
There's this thing called Pi,  some new social network where you get rewarded crypto for logging in daily. 
To be honest it is really boring and ugly. 
But I like the idea of a reward system for pioneers using the app and think maybe adding something like that would be a good incentive for people to use DogeHouse and a way to reward early users if one day the token becomes valuable. 

Pi is invite-only, my invitation code is nmnjpsc if you wanna check it out, but I'd rather you spend time here.

Suggested by: @nemanjapesic

**Comment by DGKSK8LIFE** [comment]
How would capital be allocated for something like this though? @nadirabbas

**Comment by nadirabbas** [comment]
@DGKSK8LIFE this is an investment, and you don't give me them in huge amounts. Very little amounts just to hook them up, and you get regular users in return.

**Comment by DGKSK8LIFE** [comment]
Sure, but imagine as the user-base scales up, to say 5,000, 10,000, 100,000, etc.I don't think you should incentivize users with money; incentivize them with the best functionality, user experience, and new features. It results in a better user reception and is cheaper for the service provider.

**Comment by ccoder1337** [comment]
I agree with @DGKSK8LIFE.

**Comment by nemanjapesic** [comment]
> Sure, but imagine as the user-base scales up, to say 5,000, 10,000, 100,000, etc. I don't think you should incentivize users with money; incentivize them with the best functionality, user experience, and new features. It results in a better user reception and is cheaper for the service provider.

The Pi system actually works in a way that with more users it becomes harder to mine, so the rewards get smaller and smaller. The idea is to reward early adopters more because they were there from the beginning and helped the app by using it and having podcasts on it, interacting with the community etc.

**Comment by nemanjapesic** [comment]
> @DGKSK8LIFE this is an investment, and you don't give me them in huge amounts. Very little amounts just to hook them up, and you get regular users in return.

I think you got it wrong. It would be too expensive to give them dogecoin, which we would have to buy. This would work more in the terms of DogeHouse's own crypto token, like Brave browser is rewarding people with BAT for watching ads, the same way DogeHouse could reward daily users with its token, so you don't have to invest anything or bribe anyone into using it, instead just reward the users.

@arthurskydev , @DGKSK8LIFE , I agree with you on that, but I hope I cleared some things out now, and this was just an idea that definitely needs more discussion.

**Comment by nadirabbas** [comment]
@DGKSK8LIFE ofcourse we wont give me them a dime once we get more users

**Comment by nadirabbas** [comment]
@DGKSK8LIFE ofcourse we wont give me them a dime once we get more users

**Comment by MattLawz** [comment]
> There's this thing called Pi, some new social network where you get rewarded crypto for logging in daily.
> To be honest it is really boring and ugly.
> But I like the idea of a reward system for pioneers using the app and think maybe adding something like that would be a good incentive for people to use DogeHouse and a way to reward early users if one day the token becomes valuable.
> 
> Pi is invite-only, my invitation code is nmnjpsc if you wanna check it out, but I'd rather you spend time here.
> 
> Suggested by: @nemanjapesic

I think we should do something similar but reward with in-website points. And at certain points, they can buy like DogeNitro perks, etc.
