### ISSUE TITLE
Toast appears twice

### ISSUE THREAD

**Issue by ovibutt** [benawad/dogehouse#699]
**Describe the bug**
I logged in to the app, created a room closed the tab and restored it.
The warning toast stated "room doesn't exist anymore" appeared twice which should only appear for once.

**To Reproduce**
1. Login to Doge App
2. Create a new room
3. Close the tab
4. Restore the tab by pressing ctrl+ shift + T

**Expected behavior**
The toast should only appear once

**Screenshots**
![image](https://user-images.githubusercontent.com/31251140/110846768-fd080580-82cd-11eb-9895-1059b944988a.png)

**What device are you on?**
Hp Probook Windows 10

**Comment by benawad** [comment]
I deployed the code that should fix this now.
