### ISSUE TITLE
When you spam refresh, your profile picture disappears

### ISSUE THREAD

**Issue by MattLawz** [benawad/dogehouse#700]
**Describe the bug**
If your on the main page and spam refresh a couple of times, your profile disappears.

**To Reproduce**
1. Go to the main page
2. Spam F5 about 7-15 times
3. Error occurs

**Video of this happening:**
[Imgur Link](https://imgur.com/6qcdXB9)

**What device are you on?**
I'm on the Brave browser in Windows 10.
Brave Browser Version: `V1.21.74`

**Comment by TheOtterlord** [comment]
Cannot reproduce in Kibbeh, and as Kofta is deprecated this issue can be closed. If it occures to you in Kibbeh, please create a new issue.
