### ISSUE TITLE
Add a "deafen" button

### ISSUE THREAD

**Issue by MattLawz** [benawad/dogehouse#706]
**Is your feature request related to a problem? Please describe.**
A deafen that would deafen the current tab is useful for a couple of reasons, maybe you need to listen to something real quick and can't mute your whole PC, etc. 

**Describe the solution you'd like**
A deafen button next to the mute button will mute the whole tab until untoggled.

**Describe alternatives you've considered**
An alternative solution is to maybe add a slider for the volume of the current room, so you can lower the volume of the whole chat.

**Comment by aayushmau5** [comment]
Until someone implements this, you should know that you can mute a particular tab in your browser. Afaik Firefox, Chrome has this feature. :)

**Comment by alon-abadi** [comment]
It's actually not possible to mute a tab which is open in app mode (chrome) as I am running dogehouse separate from the rest of chrome. (chrome three dots -> more tools -> create shortcut -> open as a window)

**Comment by nadirabbas** [comment]
duplicate #41
