### ISSUE TITLE
IntegrateVSCode Stories with DogeHouse

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#713]
Use VScodeStories [Made by Ben awad] in DogeHouse. 

Support for use of VSCode Stories for profile info instead of github profile only.

**Comment by manaskhandelwal** [comment]
VS Code Stories is sold + It too had Github login.

**Comment by DGKSK8LIFE** [comment]
I think it would make more sense to build a custom story system for DogeHouse in this case; could be focused more on audio sharing. @Krishna-Ramasimha

**Comment by ghost** [comment]
Yup. A profile which features an audio based background instead of just a profile pic

**Comment by Mudrank** [comment]
#616

**Comment by TheOtterlord** [comment]
As VSCode stories also uses GitHub authentication I'm going to close this issue
