### ISSUE TITLE
Audio not working with media.peerconnection.enabled: false

### ISSUE THREAD

**Issue by jymaa** [benawad/dogehouse#715]
**Describe the bug**
Audio not working on Firefox with media.peerconnection.enabled: false

**To Reproduce**
Turn media.peerconnection.enabled to false on Firefox.
Join a Room :
![image](https://user-images.githubusercontent.com/61361551/110964198-3b93d380-8353-11eb-9c41-e0b56abae044.png)

**Expected behavior**
A popup to tell the user to turn media.peerconnection.enabled to true would be a nice addition.

**Comment by benawad** [comment]
I'm not sure if there's anything I can do about this, I think it needs `peerconnection`

**Comment by jymaa** [comment]
> 
> 
> I'm not sure if there's anything I can do about this, I think it needs `peerconnection`

Yes, it's not a big deal since most users have it turn on. But if there is a way to inform the user to turn it on, it could be great.
