### ISSUE TITLE
Chrome Lighthouse Performance slower on Mobile devices

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#725]
Chrome Lighthouse Performance slower on Mobile devices

Desktop :- 
![image](https://user-images.githubusercontent.com/73518700/110969050-3ef08480-837e-11eb-9f45-10ef46642dce.png)
Mobile :- 
![image](https://user-images.githubusercontent.com/73518700/110969096-4ca60a00-837e-11eb-815d-17a5101962f3.png)

**Comment by ghost** [comment]
Both the test have been made in Incognito mode

**Comment by DGKSK8LIFE** [comment]
Can you try doing it without browser extensions? Ty @Krishna-Ramasimha

**Comment by shareef99** [comment]
@DGKSK8LIFE I turn off all the extension and tested in incognito mode. I got these results.

Desktop:- 
![DESKTOP](https://user-images.githubusercontent.com/49097809/110975595-f341d900-8385-11eb-8184-bbe2fc365c98.png)

Mobile:-
![Mobile](https://user-images.githubusercontent.com/49097809/110975699-15d3f200-8386-11eb-98a4-f19f55d98410.png)

**Comment by DGKSK8LIFE** [comment]
I wonder what's affecting performance. I understand accessibility for now but not sure about client-side performance problems. @shareef99

**Comment by DGKSK8LIFE** [comment]
Maybe this is due to tailwind? (IIRC dogehouse migrated to using tailwind classes, right)

**Comment by shareef99** [comment]
IDK, maybe but I think this is not the tailwind issue

**Comment by shareef99** [comment]
I have fixed this issue, kindly review my pull request #765.
Thank you

**Comment by goldyydev** [comment]
Kibbeh should solve this issue (once it's released).

**Comment by TheOtterlord** [comment]
Kibbeh is released!
