### ISSUE TITLE
The last row of listeners are not visible

### ISSUE THREAD

**Issue by rinilkunhiraman** [benawad/dogehouse#738]
**Describe the bug**
Cannot see the last row of attendees

**To Reproduce**
1. Go to a room
2. In the listeners sections
3. Scroll down to bottom
4. The last row of listeners are not visible

**Expected behavior**
A little padding at the bottom so that the last row is clearly visible

**Screenshots**
![image](https://user-images.githubusercontent.com/50330315/110973743-9fa2a180-832b-11eb-87f8-12cc11c57c93.png)

**What device are you on?**
Device Lenovo Ideapad 
Browser: Mozilla Firefox

**Additional context**

**Comment by ccoder1337** [comment]
Yes

**Comment by SimonFJ20** [comment]
I have the same problem on a 1920x1080 Firefox on a Deskop Windows 10
