### ISSUE TITLE
Polish Language Support

### ISSUE THREAD

**Issue by Redseb** [benawad/dogehouse#751]
**Is your feature request related to a problem? Please describe.**
There is no Polish translation available

**Describe the solution you'd like**
To add Polish to the list of supported translations, as a native Polish speaker I can single-handily do this.

**Comment by piotrbadelek** [comment]
Doesn't the Polish language support already exist? (https://github.com/benawad/dogehouse/blob/staging/kofta/public/locales/pl/translation.json)

**Comment by Redseb** [comment]
You're right, it was such a recent change that I must've not seen it. Closing this issue
