### ISSUE TITLE
💡 Arabic language support

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [benawad/dogehouse#752]
Arabic language support, I can do the translation as a native Arabic speaker. Not weird Google Translate one 😂

**Comment by YazeedAlKhalaf** [comment]
I will be making a PR to close this issue 😎

**Comment by goldyydev** [comment]
What about RTL support? do we have that implemented already?

**Comment by YazeedAlKhalaf** [comment]
> What about RTL support? do we have that implemented already?

I believe not but we can work on it, 🚀. So now translation PR is ready. We could do the RTL if. It supported

**Comment by goldyydev** [comment]
Maybe it will be worth it to implement in kibbeh and leave this like that? 

I've looked at the code and it appears like it needs a lot of work for a proper RTL support *(aka. changing some components to start from the right)*. There are some components where it will be very easy to change to RTL though.

**Comment by YazeedAlKhalaf** [comment]
Idk, it is so late at my place so I will see tomorrow and reply 👍

**Comment by YazeedAlKhalaf** [comment]
Hello
