### ISSUE TITLE
Create Room or Comments or Account without anytext just blank space 

### ISSUE THREAD

**Issue by moamlrh** [benawad/dogehouse#753]
**Describe the bug**
create a room by using this special blank text "‎ ‎‎ ‎‎ ‎‎ ‎‎ ‎"‎  you can find this space on this site https://emptycharacter.com/

**To Reproduce**
1. Click create new room | or in the comment section
2. got to this website and copy the blank text: https://emptycharacter.com/
3. will be created without any errors

* check the image to see there is no name in the room 

**Screenshots**
![image](https://user-images.githubusercontent.com/63509020/110982888-22eae400-837a-11eb-8182-7a9909ec8432.png)

**Comment by moamlrh** [comment]
And at the same time created user without a name or desc
![image](https://user-images.githubusercontent.com/63509020/110983391-bf14eb00-837a-11eb-8d5a-e1350815342e.png)

**Comment by TheOtterlord** [comment]
Closed as Kofta is deprecated and the new site has filters
