### ISSUE TITLE
Chat does not automatically scroll to show the latest message

### ISSUE THREAD

**Issue by VictorUvarov** [benawad/dogehouse#759]
**Describe the bug**
Chat does not automatically scroll to show the latest message

**To Reproduce**
1. Go to any room
2. look at chat when there are a lot of messages
3. See error

**Expected behavior**
Twitch will always show the latest message in the chat if you did not scroll up

**Screenshots**
![Screen Shot 2021-03-12 at 11 18 06 AM](https://user-images.githubusercontent.com/35702719/110988042-dd4ffc00-8324-11eb-9204-515eabe2dd2d.png)

**What device are you on?**
Google chrome, MacOS

**Comment by anuraagbarde** [comment]
@nadirabbas 

It is a known bug?

I have the same problem.

**Comment by nadirabbas** [comment]
its a known bug

**Comment by andrewroblesdev** [comment]
Is it possible to locally reproduce this behavior by accessing the same chat room on two separate browser tabs?

**Comment by nadirabbas** [comment]
it is fixed :D
