### ISSUE TITLE
Adjustment to interaction modal

### ISSUE THREAD

**Issue by Brandin** [benawad/dogehouse#763]
**Is your feature request related to a problem? Please describe.**
The interaction modal is verbose and could be much more basic. 

**Describe the solution you'd like**
On the initial interaction, I recommend modifying the message to say "Connect to Room" and remove the extra verbose text, you could even place this inline near the top above Speakers, and remove it once you are connected. When connect is lost, you could display a "Reconnect" button before you display the Reconnect banner (which I assume is for the Websocket).

**Describe alternatives you've considered**
No action at all.

**Additional context**
I'll submit a PR if I have time, but wanted to document this recommendation :)

**Comment by ajmnz** [comment]
This relates to kofta and I believe error messages are now handled differently
