### ISSUE TITLE
The Language switcher doesnt show the current language if new to the Site and its already auto detected an other lang

### ISSUE THREAD

**Issue by taynotfound** [benawad/dogehouse#769]
**Describe the bug**

**To Reproduce**
1. Have your Browser in a Other Language than English
2. Go to dogehouse for the first time

**Expected behavior**
Language Switcher shows current Language

**Screenshots**
https://i.imgur.com/QWtVs86.png

**What device are you on?**
PC | Windows 10 with Opera GX

**Additional context**

**Comment by marwie** [comment]
![image](https://user-images.githubusercontent.com/5083203/111033869-8412c600-8413-11eb-9c9f-884c000d835a.png)
