### ISSUE TITLE
I suggest adding a function

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#771]
I propose to add a function like in twitter so that users can write something on their page

**Comment by DGKSK8LIFE** [comment]
Sorry? Can you elaborate please? @twepl

**Comment by ghost** [comment]
@DGKSK8LIFE  I mean to be able to write a message on my profile as a tweet

**Comment by DGKSK8LIFE** [comment]
Ah as in a profile description or something like that? Cool

**Comment by ghost** [comment]
just copy the twitter page to my profile section
https://twitter.com/twitter

**Comment by ghost** [comment]
we can maybe use an audio profile ??

**Comment by ghost** [comment]
@Krishna-Ramasimha  no

**Comment by DGKSK8LIFE** [comment]
@twepl @Krishna-Ramasimha I like the idea of that. You could use bucket storage for audio profiles. Maybe it could be a DogeNitro feature later on or something like that.

**Comment by ghost** [comment]
yup

**Comment by ghost** [comment]
you can get the frontend here so you don't have to do everything from scratch
https://github.com/Ali-hd/Twitter-Clone
