### ISSUE TITLE
String should be in locale translation.json

### ISSUE THREAD

**Issue by zohnannor** [benawad/dogehouse#774]
**Describe the bug**
[this string](https://github.com/benawad/dogehouse/blob/new-design/kofta/src/app/components/keyboard-shortcuts/ChatKeybind.tsx#L40) (and also [this](https://github.com/benawad/dogehouse/blob/new-design/kofta/src/app/components/keyboard-shortcuts/ChatKeybind.tsx#L37)) should be in locales/LANG/translation.json so it can be translated to other langs.

**To Reproduce**
1. Go to main page, profile, voice settings
2. Button and label of "set keybind to toggle chat" setting is in english only.

**Expected behavior**
It should be in locale

**Screenshots**
![image](https://user-images.githubusercontent.com/35764628/110999591-a95ef000-8391-11eb-85a0-209cbf49141c.png)

**Comment by zohnannor** [comment]
Also there is a lot of toast messages that are not localized.

**Comment by goldyydev** [comment]
Let's move all of this to #1234 so we'll have this in 1 place.
