### ISSUE TITLE
Button labels should not be capitalized using CSS

### ISSUE THREAD

**Issue by younesaassila** [benawad/dogehouse#775]
**Describe the bug**

Currently, all button labels are capitalized by using the `text-transform` CSS property with a value of `capitalize`. This property automatically converts text to Title Case. However, while Title Case is valid in English, it isn't necessarily in other languages.

For example, `Create Room` is valid in English but `Créer Une Salle` is not in French as it should instead be `Créer une salle`.

**Expected behavior**

I think that text capitalization - and text formatting in general - should be done within the translation files themselves.

**Comment by slendidev** [comment]
One way I can see this being solved is creating a translation class kinda how Android or Minecraft has, in which you call a function to get the translated text based on language, or a lot will need to be refactored for each individual language. Sadly, I lack the knowledge to implement something like this but someone smarter will probably read this and know how to implement it. Good bug report!

**Comment by juliankrieger** [comment]
I disagree. The Text-Capitalization property exists for a reason. A11y recommends using it because screen-readers scream at you if you don't. Even worse: If they don't recognize the word, they may read it letter by letter (e.g B U T T O N)

**Comment by younesaassila** [comment]
> I disagree. The Text-Capitalization property exists for a reason. A11y recommends using it because screen-readers scream at you if you don't. Even worse: If they don't recognize the word, they may read it letter by letter (e.g B U T T O N)

Firstly, why would screen readers read a word letter by letter if it's properly capitalized in the translation file? Furthermore, as of speaking, not a single string from all translation files is all uppercase, so a transition wouldn't be a potential problem for screen readers.

Secondly, as I wrote in the issue's description, Title Case simply is **invalid** in some languages (e.g. French). If the website wants to reach a broader international audience then issues like this one will have to get fixed, especially considering that others have pulled them off while still offering great accessibility.

**Comment by juliankrieger** [comment]
> Firstly, why would screen readers read a word letter by letter if it's properly capitalized in the translation file? 

Because some work that way. 

> Furthermore, as of speaking, not a single string from all translation files is all uppercase, so a transition wouldn't be a potential problem for screen readers.

I didn't realize this was the case. It should be fine then.

I'm not sure how other projects solve this issue, I wanted to make sure people knew about it. There are more examples [here](https://github.com/humanmade/hm-pattern-library/issues/75). Screenreaders read the text in the DOM, regardless of how text is represented via css. Even with that in mind, capitalization via translation files does appear to make more sense.

**Comment by milansusnjar** [comment]
This is valid for Serbian 🇷🇸  too.
It should be **Направите собу**, not Направите **Собу**.

**Comment by daloes** [comment]
Also german words can change meaning just by capitalisation
