### ISSUE TITLE
A secondary modal/popup to confirm entering/leaving a room.

### ISSUE THREAD

**Issue by aboveyunhai** [benawad/dogehouse#789]
**Is your feature request related to a problem? Please describe.**
The current problem with the simple interface is that when you click a room, you immediately enter without notice. This can be quite "unpleasant" and "scared" for new users because you are not longer "invisible" like traditional social app.
A simple confirm modal can ease out a lot of accidentally enter/leave, mis-click issue.
Same idea can apply to request speak, etc. 
I'm a little bit surprise no one brings this problem up. Exploring rooms are good in concept, but bad in UX. 

Maybe just make it as a default setting for users if they want to skip the annoying modal.

**Comment by acb5764** [comment]
I agree about the problem, but I disagree about the solution. Adding a dialog doesn't really solve anything in my opinion -

I think the default functionality for lurkers would be to just default usernames "Hidden" until the user wants to participate in the chat. This way they can listen to the chat before exposing their username. Exploring rooms should be allowed without necessarily showing the specifics of the users content.

**Comment by aboveyunhai** [comment]
> I agree about the problem, but I disagree about the solution. Adding a dialog doesn't really solve anything in my opinion -
> 
> I think the default functionality for lurkers would be to just default usernames "Hidden" until the user wants to participate in the chat. This way they can listen to the chat before exposing their username. Exploring rooms should be allowed without necessarily showing the specifics of the users content.

I believe we are talking about two separate features. My main concern is just to avoid accidental click and the unpleasant UX of accidently getting into the room and other actions as well. It has nothing to do with anonymous or not, it's more like giving a chance to "think before you act".

What you are thinking is so called the anonymous feature, which should be controlled by the host of room. The host can allow anonymous listener or not. 
Anyway, both features have no confliction.

**Comment by HunnySajid** [comment]
@aboveyunhai as per my understanding of what you are saying, I would suggest to have a join button on hover of any channel, that way user will be able to choose whether he/she wants to join channel or not. 
e.g.

![doge](https://user-images.githubusercontent.com/19255438/111075322-5445ea00-8509-11eb-8794-5967930c57a6.png)

**Comment by aboveyunhai** [comment]
@HunnySajid  Maybe a action button. Then when you click it, it display a small panel with a bunch of buttons right next to it, instead of modal (default hidden). 
There is not `hover` on mobile. 
I personally dislike as hover as a way of functionality other than visual effects for desktop user. Same for any gestures action to pull out any panels as a primary action (serve as secondary/convenient way for user to choose is the best). 
They are indeed fancy but create inconsistent control across different devices. And probably not friendly for `accessibility`.

This is just my personal experience, hover to display for Desktop is always cool. 😎 Then panel for other device to avoid annoying open/close modal behavior.

**Comment by HunnySajid** [comment]
@aboveyunhai agreed with the statement that it creates inconsistencies across devices. I think simply putting in a join button (not on hover) would be feasible.

**Comment by aboveyunhai** [comment]
@HunnySajid I just had chance to deal with wide age range of users in the past. Not just for elders, but also young people, a lot of this kinds of visual effect/toggling functionalities are void for them and bring confusion. Minimal and necessary function buttons on page works the best. Cool things used as secondary ways to speed up default behavior for heavy-use users.

**Comment by ajmnz** [comment]
This relates to kofta, which is now dead
