### ISSUE TITLE
Use Crowdin to manage translations

### ISSUE THREAD

**Issue by HysMX** [benawad/dogehouse#802]
It would be better and faster if we use crowdin to handle localization, so when you guys add a new key you don’t need to update each language JSON

**Comment by ermalsh** [comment]
just do npm run i18 after adding new keys.
This generates the type safe translation keys along with any new keys in each translation JSON.

**Comment by comradekingu** [comment]
@HysMX Why Crowdin instead of Weblate? For any of the reasons I can think of, I draw a blank there.
