### ISSUE TITLE
Automatic Translations

### ISSUE THREAD

**Issue by TheRealRaeed** [benawad/dogehouse#805]
Hello! I feel like a automatic translation system is a better idea than the current system. Because for each new translation, we have to add that each time we make a new UI element. If we have automatic translations using translate api for unspecified key value pairs this can be solved.

**Comment by nadirabbas** [comment]
automatic translations sometimes are ridiculously incorrect

**Comment by TheRealRaeed** [comment]
Although true, we could correct those as well and it is definitely better than having to individually go back and repeatedly change every translation. It also depends on which API you are using.

**Comment by ajmnz** [comment]
Translations/translators are no longer a problem
