### ISSUE TITLE
Add support for Meeting Code and Password for Rooms or even an Enhanced search button  ????

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#808]
Add support for Meeting Code and Password for Rooms :- 

We can introduce support for adding Meeting code and Password for joining the rooms. 

You may ask why ??? 
Answer : When DogeHouse starts growing on a large scale basis, it will be easier for people to join room through a meeting id and a passcode instead of manually searching for the room. 

The meeting id can consist of [Doge] followed by the owner name, say [Krishna] and then the id, like.... [2905]
Example : 
Meeting ID : DogeKrishna2905
Password : AngularJsIsTrash

Add support for Enhanced Search Button : 

Add a search button where the user actually knows the room name and can filter it based on : 
1. Number of Participants
2. Organiser
3. Room name
4. Topic

**Comment by ghost** [comment]
No one commenting on this ?

**Comment by nadirabbas** [comment]
@benawad this is an interesting one

**Comment by ghost** [comment]
The password in the example tho 😂

**Comment by benawad** [comment]
no passwords for rooms atm, but we you can see who is requesting to join a private room and add them in
