### ISSUE TITLE
Links inserted into bio aren't parsed correctly.

### ISSUE THREAD

**Issue by mohammedgad** [benawad/dogehouse#810]
**Describe the bug**
Links inserted into bio aren't parsed correctly check the screenshot.

**To Reproduce**
1. Go to https://dogehouse.tv/me
2. Click on Edit Profile
3. Enter two or three links in separate lines
4. Submit
5. Check your profile links now, all the links are combined into one link

**Expected behavior**
Links should be parsed separately and each link should be directed to the correct URL

**Screenshots**
![image](https://user-images.githubusercontent.com/8174938/111018651-b5af7100-83c2-11eb-9a61-85937856bc1e.png)

**What device are you on?**
Google Chrome on macOS

**Comment by mohammedgad** [comment]
cc: @nadirabbas

**Comment by nadirabbas** [comment]
yeah currently, the tokens are created by splitting by space, not by a line break

**Comment by xiuxiu62** [comment]
Just wrote a parser to fix this

**Comment by nadirabbas** [comment]
@justincremer I suggested some changes on your commit.

**Comment by nadirabbas** [comment]
@justincremer this has been fixed #839
