### ISSUE TITLE
Put Dogehouse in a Docker container and run it on K8's

### ISSUE THREAD

**Issue by ryandils** [benawad/dogehouse#811]
**Is your feature request related to a problem? Please describe.**
In order for Dogehouse to scale to the moon we need an easy way to make it scale.

**Describe the solution you'd like**
I'd like to containerize the application and all of its dependencies in Docker so that we can eventually run it on Kubernetes. This will allow us to handle a large amount of load and make it easy to scale as the application gets bigger.

**Describe alternatives you've considered**
EKS

**Additional context**

[Not sure if this counts but here's my LinkedIn](https://www.linkedin.com/in/ryanallendils/)

**Comment by ajmnz** [comment]
Check out https://github.com/benawad/dogehouse/pull/563

**Comment by nadirabbas** [comment]
As @ajmnz I think this is already being worked on
