### ISSUE TITLE
Remove this [emotes soon] from chat

### ISSUE THREAD

**Issue by manaskhandelwal** [benawad/dogehouse#814]
Should we remove this `[emotes soon]` from all translation JSON file?

Either we remove it from [RoomChat.tsx](https://github.com/benawad/dogehouse/blob/3e641894403598b6ecbc02410e4e66769c324579/kofta/src/app/modules/room-chat/RoomChat.tsx) or we make it `""` in JSON file, it might be useful for added some other feature/tip/note, Like `Beta`, `Alpha v2.3`, `Voice Bio` etc.

![Screenshot 2021-03-13 102853](https://user-images.githubusercontent.com/53651226/111019710-046f0200-83e7-11eb-8a9a-ff4212836a6f.png)

#### This is a simple one, If this gets approved I would like to work on it.

**Comment by manaskhandelwal** [comment]
@nadirabbas what to do with this one?

**Comment by nadirabbas** [comment]
the custom emotes are not here currently, so we need this text.

**Comment by sankalpmukim** [comment]
Can it be converted to `[custom emotes soon]` ?
