### ISSUE TITLE
Not able to start storybook

### ISSUE THREAD

**Issue by pratikmane1299** [benawad/dogehouse#824]
I am getting the below error when I do npm run storybook.

![Error-Image](https://user-images.githubusercontent.com/30666584/111025339-81ab6e80-8409-11eb-8c53-80c91e471b95.png)

**Comment by kprocks86** [comment]
can you share the node and **npm** versions, this might be useful. so i can check in the same environment and reproduce the bug.

**Comment by nadirabbas** [comment]
you may have to upgrade your `node` version: https://stackoverflow.com/questions/64907613/typeerror-object-entries-flatmap-is-not-a-function/64909657

**Comment by regisBafutwabo** [comment]
I am having the same issue but mine is related to the ``next/babel`` preset section in ``.storybook/.babelrc`` 

### Node Version

v12.18.4

### OS

Mac Big Sur v11.1 

<img width="632" alt="Screen Shot 2021-03-17 at 11 06 23 AM" src="https://user-images.githubusercontent.com/10329294/111403721-d18f7b80-8710-11eb-822a-6c6c7da831db.png">

**Comment by nadirabbas** [comment]
try running `npm i`

**Comment by regisBafutwabo** [comment]
I did before running ``npm run storyboard``

> try running `npm i`
