### ISSUE TITLE
Making private room public is missing popup field css

### ISSUE THREAD

**Issue by majksec** [benawad/dogehouse#84]
Make room private, then change try to convert it to public room:
![image](https://user-images.githubusercontent.com/65724849/107826226-d2856400-6d84-11eb-8043-f7a5ae77b71d.png)

**Comment by giuseppecampanelli** [comment]
The prompt box is a system object that is not subject to CSS, and hence can't be modified. A workaround would be to create a custom element prompt or use a library that provides one.
https://github.com/benawad/dogehouse/blob/88671cf8008d252a7631ad49ea7b3cb7b2afa2c1/kofta/src/webrtc/utils/renameRoomAndMakePublic.ts#L4

**Comment by MrMalloc** [comment]
Couldn't the CreateRoomModal component be reused for that?
It should be possible to detect wherther it is called within an existing room so the setPrivacy selectbox is hidden and the onSubmit event triggers the make_room_public.

https://github.com/benawad/dogehouse/blob/15b6ff81e75dcc6931aa6c66eff546d34ed032ac/kofta/src/vscode-webview/components/CreateRoomModal.tsx#L11
