### ISSUE TITLE
Unmodding in DogeHouse room does not work.

### ISSUE THREAD

**Issue by yummyweb** [benawad/dogehouse#850]
**Describe the bug**
Unmodding in DogeHouse does not work.

**To Reproduce**
1. Create a room.
2. Make anyone a mod.
3. After that, click on their profile and unmod them.
4. See error.

**Expected behavior**
The user will be unmodded.

**What device are you on?**
I am on Macos X 10.14 Mojave.

**Comment by nadirabbas** [comment]
fixed in #856
