### ISSUE TITLE
Meta description doesn't show up on Google

### ISSUE THREAD

**Issue by shreyas44** [benawad/dogehouse#857]
The meta description that's used in `index.html` doesn't show up on Google.

**Google:**
![Screen Shot 2021-03-13 at 8 23 22 PM](https://user-images.githubusercontent.com/46835608/111034068-f4344280-8439-11eb-9ae6-c3b97ff34953.png)

**Bing:**
![Screen Shot 2021-03-13 at 8 24 00 PM](https://user-images.githubusercontent.com/46835608/111034093-0ca45d00-843a-11eb-8d30-3886298e9d34.png)

**DuckDuckGo:**
![Screen Shot 2021-03-13 at 8 24 21 PM](https://user-images.githubusercontent.com/46835608/111034109-1af27900-843a-11eb-9aac-f9539c04c314.png)

**Some likely reasons for this:**
- Google hasn't reindexed the page yet, but as @goldyydev pointed out, the [cached page](https://webcache.googleusercontent.com/search?q=cache:2SnbkOaCUvoJ:https://dogehouse.tv/) from google does have the updated meta description. Hence, it's most likely not because of this
- The description is not good enough or is too short for google (ouch) - After doing some research, I found out that many times Google ignores the meta description provided if it finds that the description is irrelevant to the page content. An optimal meta description is also apparently between 50 and 150 characters and the current description is 41 characters, which could be another cause. 

**What's the solution?**
Probably try creating a better and longer description?

**Comment by goldyydev** [comment]
This is now fixed
