### ISSUE TITLE
Upgrade to Elixir 1.11 and use multistage Dockerfile

### ISSUE THREAD

**Issue by praveenperera** [benawad/dogehouse#861]
Plan

- Upgrade to Elixir 1.11
- Create multistage docker file for quicker releases 
   - Use[ hexpm elixir images](https://hub.docker.com/r/hexpm/elixir) which are more explicit on the Erlang, Alpine and Elixir versions used. Also they are locked to those versions to prevent breaking deploys in the future.

@benawad if you are good with this plan assign this to me and I will do it either today or Monday.

**Comment by benawad** [comment]
that would be great!

**Comment by praveenperera** [comment]
Closed by: #1020
