### ISSUE TITLE
@benawad Hey can I add a new language ?

### ISSUE THREAD

**Issue by b31ngd3v** [benawad/dogehouse#872]
@benawad I'm a native bengali speaker so I want to add that language to dogehouse. So just asking for your permission, if you say yes I would love to contribute to this project. Thank you :)

**Comment by nadirabbas** [comment]
Bengali has been added #860

**Comment by b31ngD3v** [comment]
@nadirabbas  what about hindi ?

**Comment by nadirabbas** [comment]
Hindi is also added #691
