### ISSUE TITLE
notification or sound on new message in chat room

### ISSUE THREAD

**Issue by MananDesai54** [benawad/dogehouse#873]
**Is your feature request related to a problem? Please describe.**
I closed chat section in chat room and minimized window but I asked one question in chat section, now when some one one answer to me in chat section by tagging me I should get notified if chrome is in background, also play sound when ever there is activity in chat room like discord and option to choose weather to notify every time or for only mentions

**Describe the solution you'd like**
Whenever user is mentioned in chat we can check window is currently active or not using chrome api and do according and same for other chat activity

**Comment by ajmnz** [comment]
I'm pretty sure you're now notified even with the room minified. Request to reopen if I'm wrong.

**Comment by MananDesai54** [comment]
> I'm pretty sure you're now notified even with the room minified. Request to reopen if I'm wrong.

You are 100% correct thanks for information
