### ISSUE TITLE
Chat could be a simple IRC server

### ISSUE THREAD

**Issue by slendidev** [benawad/dogehouse#882]
**Is your feature request related to a problem? Please describe.**
I think having this as a simple IRC server also allows easy bot development in the future.

**Describe the solution you'd like**
Make an IRC server

**Describe alternatives you've considered**
Something like WebSockets is not that reliable for bots in my experience with another platform.

**Additional context**
I got this idea from Twitch, not only does it minimize the delay a bit but the IRC protocol itself is made for this.

**Comment by goldyydev** [comment]
I am going to close this issue as IRC is ran on WebSockets in most cases (like twitch [wss://irc-ws.chat.twitch.tv]).
