### ISSUE TITLE
Got kicked out of the talk. 

### ISSUE THREAD

**Issue by Akorian** [benawad/dogehouse#89]
I got kicked out of a chill talk with the guys. Wanted to log in again but the thing is not working. Screenshot attatched.
![Screenshot_2021-02-13-01-04-34-649_com android chrome](https://user-images.githubusercontent.com/37375458/107834800-9dced800-6d97-11eb-8b39-273fc2ef3bf3.jpg)

**Comment by EmmyMay** [comment]
I am having this problem too. I think there is a problem right now. It is still in pre-beta so have some patience I guess. Maybe try back tomorrow.

**Comment by Akorian** [comment]
I mostly reported the problem here because it is a pre-beta. If its a bug or something Ben should know about it so he can fix it.
But since he has already closed it, he may already have done that or it was a general problem with something else. I dunno. 🤷
