### ISSUE TITLE
Amharic language support

### ISSUE THREAD

**Issue by liulalemx** [benawad/dogehouse#895]
Amharic language support. I can do the translation myself.

**Comment by HasanMdArik** [comment]
If you want to do it, then follow these steps..
1. Fork this repo.
2. Copy "translation.json" from "kofta/public/locales/en".
3. Create a folder called "am" in "kofta/public/locales".
5. Paste the "translation.json" in the newly created folder.
6. Do the translations in the Amharic language(in "kofta/public/locales/am/translation.json").
7. Then go to "kofta/src/app/components/LanguageSelector.tsx".
8. Alphabetically add `{ value: "am", label: "Amharic" }` in `options` array.
9. Commit in your repo and make a pull request.

> If this sounds hard, comment here. I can do it.

**Comment by liulalemx** [comment]
I have made a PR but it keeps failing. 
PR #900
