### ISSUE TITLE
weird spacing in bio links

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#897]
![image](https://user-images.githubusercontent.com/38838675/111042564-c661f480-845f-11eb-9db0-c4a4aa618fda.png)

**Comment by xiuxiu62** [comment]
Yo my parser deals with reassembling chunks on proper whitespace

**Comment by nadirabbas** [comment]
it has nothing to do with new parsing, that hasn't been deployed yet. it only happens in the modal.

**Comment by nadirabbas** [comment]
it seems to be fixed now
