### ISSUE TITLE
horizontal scrolling in chat (once again)

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#898]
![image](https://user-images.githubusercontent.com/38838675/111042709-76376200-8460-11eb-888a-a2b6c887fb7f.png)

**Comment by ermalsh** [comment]
I just tried to replicate this running staging locally, can't get it to happen. Do you know what may be causing it? @nadirabbas

**Comment by nadirabbas** [comment]
i don't know why it popped up randomly, i think it works now
