### ISSUE TITLE
I can't see the number of followers 

### ISSUE THREAD

**Issue by rampa2510** [benawad/dogehouse#9]
It's showing zero followers for every account. I noticed this when I clicked on my avatar and saw that the following numbers was right but the followers number is 0.

**Comment by jacobhq** [comment]
I think it shows the number of people you're following on GitHub but it shows the number of people who follow you on the platform.￼

**Comment by rampa2510** [comment]
No for me it shows the correct following but the follow number is zero. It's same with other accounts.

**Comment by RafaelPuerta** [comment]
![image](https://user-images.githubusercontent.com/20388984/107838262-d49af300-6d83-11eb-890c-0ab9b915c729.png)

Yes, the same thing happens to me, can I take this pr?😳

**Comment by ShahrozTanveer** [comment]
# Got same issue 

![image](https://user-images.githubusercontent.com/31120765/107862346-215af880-6e6e-11eb-92a7-601cd0cf163c.png)
