### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Salman2301** [benawad/dogehouse#90]
The Website log me out and can't login again.
When i click i the login button, 
it redirects me to a 500 Error page on this link 
https://api.dogehouse.tv/auth/github/callback?code=0266xxxxxxxx33e&state=web

After a reload got this response

```
{"error":"code expired, try to login again"}
```

**Comment by TSMMark** [comment]
#88

**Comment by Mipsters** [comment]
not sure what the code value represents, consider it's best if you edited it out for privacy reasons?

**Comment by Salman2301** [comment]
Just in case 🤣

**Comment by geisterfurz007** [comment]
You should also remove it from your edit history, otherwise it's still visible. You should be able to do so by clicking the arrow on edited and then remove it from there :)
