### ISSUE TITLE
Audio is not playing with WebRTC disabled

### ISSUE THREAD

**Issue by okass** [benawad/dogehouse#910]
**Describe the bug**
If WebRTC is disabled for browser audio will fail to play

**To Reproduce**
1. Disable WebRTC in browser (in this case Firefox)
2. Join a channel

**Expected behavior**
Playing audio

**What device are you on?**
Desktop

**Additional context**
It probably can not be solved that easily without reworking whole audio stack but for people who like to keep WebRTC disabled this might be annoyance

**Comment by nadirabbas** [comment]
is this a joke? 😂 DogeHouse uses WebRTC to consume audio.

**Comment by okass** [comment]
no I mean it just doesnt work with it disabled and I keep it disabled for reasons.

**Comment by nadirabbas** [comment]
you have no audio streams without WebRTC, what audio are you trying to play?

**Comment by okass** [comment]
oh well I didnt check how it actually works

**Comment by okass** [comment]
voice chat audio but if you say its how it plays audio it cant be helped
