### ISSUE TITLE
OAuth fail - wrong service used to log in

### ISSUE THREAD

**Issue by fzakfeld** [benawad/dogehouse#914]
**Describe the bug**
I was already logged in via GitHub. I logged out and signed in via Twitter, but got logged in as my GitHub profile again.

**To Reproduce**

1. Sign in with GitHub
2. Click your profile picture -> Log out 
3. Log in with Twitter
4. You're probably logged in with your GitHub / what ever you logged in with first.

**Expected behavior**
Should log in with the service I clicked on.

**What device are you on?**
Chrome 89.0.4389.82 (Official Build) (64-bit), Windows 10

**Additional context**
Not sure if it's a security issue, probably not. Just noticed it, didn't take a look at the code/requests myself yet

**Comment by benawad** [comment]
I designed it this way, if you use the same email, it merges your accounts
