### ISSUE TITLE
I need someone to help manage translations

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#924]
At the moment this mainly means spot checking they are on the `staging` branch and merging them in assuming it looks ok.

**Comment by HasanMdArik** [comment]
Hi @benawad, I am here to help. I already did a pull request there!!

**Comment by ermalsh** [comment]
I can help with this @benawad

**Comment by manaskhandelwal** [comment]
@benawad I am ready to help ✋.

**Comment by manaskhandelwal** [comment]
@benawad Check this: #940
