### ISSUE TITLE
Rewrite backend in DogeLang

### ISSUE THREAD

**Issue by NEO97online** [benawad/dogehouse#927]
As dogehouse is now clearly reaching escape velocity, and will soon be on the moon, it's imperative we get started rewriting the backend in [DogeLang](https://pyos.github.io/dg/). This will bring a number of improvements to the DogeHouse ecosystem:

- No static typing. This is a great feature; writing types is tedious and boring. The days of TypeScript are long over. It's time to start using dynamic languages.
- Compiles to CPython. Need I say more? All the greatness of python's interpreter with a Haskell like syntax! 
- Built-in exception system. No need to spend time and precious lines of code checking for errors when we can simply raise an exception and let the system handle it naturally.
- No memory management. Again, managing memory requires more lines of code.

![image](https://user-images.githubusercontent.com/28285686/111058151-6d439200-845a-11eb-9deb-27d654029322.png)

**Comment by theCow61** [comment]
Yea fr

**Comment by willdoescode** [comment]
based and redpilled

**Comment by xiuxiu62** [comment]
tru

**Comment by dhenson02** [comment]
is it not already?

**Comment by theCow61** [comment]
There should also be a dogelang interpreter in dogehouse built in.

**Comment by reqster** [comment]
🐕

**Comment by BoscoDomingo** [comment]
The only potential issue I see is down the road how many people are gonna be able and/or willing to maintain something in such a niche language? I love the idea of DogeHouse running on a DogeLang BE, but it may be too risky if Ben actually plans to make this a real business.

**Comment by willdoescode** [comment]
yes people are willing to write dogelang

**Comment by ghost** [comment]
> The only potential issue I see is down the road how many people are gonna be able and/or willing to maintain something in such a niche language? I love the idea of DogeHouse running on a DogeLang BE, but it may be too risky if Ben actually plans to make this a real business.

As DogeLang begins to 🚀 in popularity there will be no contributor shortages. Only real 💎🙌 will hold onto their great knowledge of DogeLang and eventually become millionaires.

**Comment by yummyweb** [comment]
DOGE!!!

**Comment by NEO97online** [comment]
Hopefully this code snippet is helpful to anyone who would like to pick up this issue:

```
░░░░░░░░░▄░░░░░░░░░░░░░░▄░░░░
░░░░░░░░▌▒█░░░░░░░░░░░▄▀▒▌░░░
░░░░░░░░▌▒▒█░░░░░░░░▄▀▒▒▒▐░░░
░░░░░░░▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐░░░
░░░░░▄▄▀▒░▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐░░░
░░░▄▀▒▒▒░░░▒▒▒░░░▒▒▒▀██▀▒▌░░░ 
░░▐▒▒▒▄▄▒▒▒▒░░░▒▒▒▒▒▒▒▀▄▒▒▌░░
░░▌░░▌█▀▒▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐░░
░▐░░░▒▒▒▒▒▒▒▒▌██▀▒▒░░░▒▒▒▀▄▌░
░▌░▒▄██▄▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▌░
▀▒▀▐▄█▄█▌▄░▀▒▒░░░░░░░░░░▒▒▒▐░
▐▒▒▐▀▐▀▒░▄▄▒▄▒▒▒▒▒▒░▒░▒░▒▒▒▒▌
▐▒▒▒▀▀▄▄▒▒▒▄▒▒▒▒▒▒▒▒░▒░▒░▒▒▐░
░▌▒▒▒▒▒▒▀▀▀▒▒▒▒▒▒░▒░▒░▒░▒▒▒▌░
░▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▒▄▒▒▐░░
░░▀▄▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▄▒▒▒▒▌░░
░░░░▀▄▒▒▒▒▒▒▒▒▒▒▄▄▄▀▒▒▒▒▄▀░░░
░░░░░░▀▄▄▄▄▄▄▀▀▀▒▒▒▒▒▄▄▀░░░░░
░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▀▀░░░░░░░░
```

**Comment by goldyydev** [comment]
Closing this issue so people wont think that it's serious

**Comment by theCow61** [comment]
But it is serious.

**Comment by willdoescode** [comment]
^^^^^^^^^^

**Comment by adhikary97** [comment]
Yolo

**Comment by willdoescode** [comment]
dogemoji

**Comment by theekrystallee** [comment]
but it is serious what do you mean

**Comment by thaierissa** [comment]
free dogelang

**Comment by theCow61** [comment]
I think this issue should be reopened for the distant future because on Ben's tiktok live he talked about how he is thinking about using DogeLang in some way in the distant future when dogehouse is established and more built.

**Comment by willdoescode** [comment]
this will happen

**Comment by theCow61** [comment]
It is inevitable.
