### ISSUE TITLE
Icelandic language support

### ISSUE THREAD

**Issue by mjkonko** [benawad/dogehouse#950]
I would like to expand on the language support for dogehouse and add a translation to Icelandic.

I'm not a native but have decent command of the language so I am able to translate the webpage.

**Comment by manaskhandelwal** [comment]
Go on 🤩...

**Comment by ermalsh** [comment]
@mjkonko 
1. Fork Repo
2. Branch out of staging to something like feature/#950_add_icelandic_language_support
3. Create a folder `/kofta/public/locales/{LANGUAGE_CODE}`
4. Create a file in that folder called translations.json and just add ```{}``` to it.
5. `cd kofta` and run ```npm run i18``` => will create the translation json template for you
6. Translate English to Icelandic in the translation.json
7. Add ```{ value: "is", label: "🇮🇸 Icelandic" },``` to `/kofta/src/components/LanguageSelector.tsx`
8. Commit, Push, PR

**Comment by mjkonko** [comment]
@ermalsh I started working on it a bit more manually but thanks for the instructions! Should be done soon :)
