### ISSUE TITLE
the voice server just crashed

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#953]
@benawad I guess the voice server crashed or something, there is no audio in rooms for hours.

**Comment by mobesa** [comment]
![Screenshot from 2021-03-14 16-16-18](https://user-images.githubusercontent.com/6242783/111073844-a6bee080-84e0-11eb-813b-24605ad2bec2.png)
^ happens whenever changing from listener to speaker

**Comment by s3ansh33p** [comment]
It has been dead for several hours...

**Comment by goldyydev** [comment]
It's fixed now, time to close this issue @nadirabbas 


@benawad what went wrong?
