### ISSUE TITLE
Banned or not banned? thats the question

### ISSUE THREAD

**Issue by LuanHimmlisch** [benawad/dogehouse#957]
**Describe the bug**
Hours ago I was banned from the chat of "Coders/Devs" room after some admin gave moderator to a bunch of people. After that I tried many times to get unblocked but it seems that for every other mod/admin I'm not banned from chat. Even when I try to chat it doesn't send anything (doesn't show me any pop up saying I'm banned from chat tho). I'm currently a Mod and still banned, doesn't make sense.

**To Reproduce**
1. Go to 'Coders/Devs discussion'
2. Make someone ban you
3. Make someone unban you
4. Cry

**Expected behavior**
Unban, just unban.

**Screenshots**
Idk if this helps, this is a screenshot of my browser.
![Captura de pantalla -2021-03-14 09-31-30](https://user-images.githubusercontent.com/46875694/111074648-99d2ca80-84a9-11eb-93d9-304bebc9a97a.png)

**What device are you on?**
Linux Mint 20.1, Firefox.

**Additional context**
I'm sad, the audio doesn't work and I can't use the chat :(

**Comment by xiuxiu62** [comment]
lol, yeah Will banned me for calling Rust a "Haskell ass language" and I had the same issue -- unbanned, but couldn't use the chat.  I could still join a speaker and use voice chat though.  Kinda funny, but yeah this could actually use fixing.  I'll take a look, but I can't read elixir, so fingers crossed the ban controller is in Kofta.

**Comment by nadirabbas** [comment]
duplicate #528
