### ISSUE TITLE
Room has only listeners, no speakers, No mod

### ISSUE THREAD

**Issue by FotieMConstant** [benawad/dogehouse#966]
**Describe the bug**
Room has no speakers nor mods but listeners. Consequently one can't request to be a speaker because obviously it won't be approved by anyone.

**Expected behavior**
I think room should not exist without at least a speaker or mod

**Screenshots**

![image](https://user-images.githubusercontent.com/42372656/111077739-80a23c00-84f2-11eb-92f1-0fbe8584891e.png)

**What device are you on?**
N/A

**Additional context**
N/A

**Comment by manaskhandelwal** [comment]
Maybe this room stays forever, so URL for history books 😵🥴 https://dogehouse.tv/room/ea5a7cec-d898-49c0-a2b9-2a753519e65b

**Comment by FotieMConstant** [comment]
Almost thought I was alone who noticed this. thanks for adding that @manaskhandelwal

**Comment by ermalsh** [comment]
Errors out now
![image](https://user-images.githubusercontent.com/19981656/111080541-4bd3bc00-84d5-11eb-9fea-e9fb94b59c1a.png)

**Comment by LuanHimmlisch** [comment]
I made this room, this bug happened (I think) because my slow internet connection. I created it and then left

**Comment by FotieMConstant** [comment]
@benawad

**Comment by TheOtterlord** [comment]
As the room is now gone, I'm going to close this issue. If this happens on the new version, please open a new issue.
