### ISSUE TITLE
Mic check page or other mechanism for checking the mic input

### ISSUE THREAD

**Issue by dko1905** [benawad/dogehouse#967]
**Is your feature request related to a problem? Please describe.**
Many people don't know if their mic is working, and often ask "Can you hear me?" when they unmute.
My feature fixes this problem.

**Describe the solution you'd like**
I haven't come up with a precise solution, but I have a list of possible solutions:
- (The complex) A page for checking mic settings which shows a waveform from your mic input.
- (The simple) A button in every room which when clicked shows the mic input as a waveform, this button should work while muted or unmuted.

**Additional context**
Discord has this feature, you can check you mic input by going into the settings.

**Comment by ermalsh** [comment]
The logic is sort of already there, with the blue ring around the speakers avatar.

Something else we could also do:
1. Make blue ring around the active speakers avatar more prominent. The blue ring appears when voice is detected from that user.

**Comment by dko1905** [comment]
You are right, but the blue ring only shows up when you are not muted, as far as I know.
My idea is more about a way to check without disturbing the room.

**Comment by ermalsh** [comment]
Yep, I figured that - I like the idea, I think Ben did too.

**Comment by dko1905** [comment]
Another possibility:
- Maybe a red ring when the user is muted

**Comment by MadanBhandari** [comment]
For muted user, I think muted mic icon with red border would be better, rather than just red circle.

**Comment by dko1905** [comment]
Well, since the project is dead, I will close the issue.
:(
