### ISSUE TITLE
Conventional changelog support

### ISSUE THREAD

**Issue by yvesnrb** [benawad/dogehouse#973]
**Is your feature request related to a problem? Please describe.**
The commit messages on this repository are getting a little out of hand.

**Describe the solution you'd like**
One solution is to adopt conventional changelog tooling. Conventional changelogs are a standard for writing git commit messages, basically they look like this:
```
[type]([scope]): [message]
```
Whereas type is the type of commit (feature, fix, chore etc.) and scope is the package this commit changes (kibbeh, feta, etc.).
An example commit message could look like this:
```
feat(kibbeh): implemented feed component
```
Adopting this would basically involve installing [commitzen](https://github.com/commitizen/cz-cli) as a command line tool to write commits and [commitlint](https://github.com/conventional-changelog/commitlint) to ensure no abnormal commit messages can be made in this repository. Also, we would also need to rebase the entire commit history to rewrite all the messages into the new format. I'm willing to take on this task if this is something that @benawad considers could be good for this project.

**Describe alternatives you've considered**
I'm not aware of alternative standards for commit messages, please let me know.

**Additional context**
[?????](https://github.com/benawad/dogehouse/commit/174745f0a567c77aec8c53d702f3bdabdff50315)

**Comment by demfabris** [comment]
Maybe consider [semantic-release](https://github.com/semantic-release/semantic-release)?
It has commit lint plugins, auto sem-ver tagging and changelog.

btw, i think you're refering to [Angular commit guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)?

**Comment by yvesnrb** [comment]
> btw, i think you're refering to [Angular commit guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)?

Oh yeah, you are totally right. I had worked with this commit format before in another project but didn't know it came from Angular in particular.

> Maybe consider [semantic-release](https://github.com/semantic-release/semantic-release)?
> It has commit lint plugins, auto sem-ver tagging and changelog.

Looks like the semantic-release tool is something you use on top of commitizen and commitlint to version the packages in the repo right? Or does it have it's own commit linting tooling as well?

**Comment by benawad** [comment]
yeah I want this, go for it!

**Comment by demfabris** [comment]
> Looks like the semantic-release tool is something you use on top of commitizen and commitlint to version the packages in the repo right? Or does it have it's own commit linting tooling as well?

Not quite, it is the whole solution. The commit lint and auto sem-ver are built-in but there are tons more.

[commit-lint plugin](https://github.com/semantic-release/commit-analyzer)
[more plugins](https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md)

This tool is honestly amazing.
