### ISSUE TITLE
Blocked users are able to delete their account and create new ones to undo the block

### ISSUE THREAD

**Issue by alon-abadi** [benawad/dogehouse#981]
**Describe the bug**
Blocked users are able to delete their account and create new account, to unblock themselves. Blocking works with user ID, but the user is being generated new one every time they create a new account, even if they're using the same github/twitter account to log in.

**To Reproduce**
Steps to reproduce the behavior: (this requires two accounts: a moderator and another account)
1. Block the user from the room.
2. Blocked user deletes their account (profile -> delete)
3. Blocked user creates new account
4. Blocked user can now get back in the room.

**Expected behavior**
Creating a new account using the same twitter/github account should either reactivate the same account, or be less convenient (maybe throttle create user requests by IP).

**Screenshots**
--

**What device are you on?**
Irrelevant, but win10 pc.

**Additional context**
--

**Comment by nadirabbas** [comment]
fixed in 292a839

**Comment by Nautman** [comment]
I actually know a possible solution to this. It is to store a hashed value of the data that they register with. As such, it is practically impossible to know who has been blocked [but easily verifiable].

EDIT: This is how you would stop someone from keep creating free trials. Simply store a hashed value of their email. I'm not entirely sure if this is GDPR-compliant enough, but I can't imagine it would be any problem. Is there any way that I can contribute to this?

**Comment by nadirabbas** [comment]
@benawad do it like Facebook, don't immediately delete their account, set a period (such as 48 hours), in this time period, they can undo the delete and have their account back. this way, they can't spam.

**Comment by Hasintha-Jayasinghe** [comment]
yes, add another column to the user table and call it 'deleted'. This value is a boolean. So then when they delete the account, it'll just set the 'deleted' column to 'true'. Then if they try to create an account with the same credentials again, all you have to do is set the 'deleted' column of the user to 'false'.
I hope that made sense.

**Comment by Nautman** [comment]
Isn't it somewhat problematic to keep storing the user data after you have requested that it be deleted? @nadirabbas @Hasintha-Jayasinghe

**Comment by Hasintha-Jayasinghe** [comment]
yes but as @nadirabbas mentioned, we can program it to delete the data after 48 hours.

**Comment by nadirabbas** [comment]
@Nautman while they have clicked delete, we don't store any data about them unless they undelete. whenever they log into their account, they just see the page _**you have requested an account delete, undo?**_

**Comment by Hasintha-Jayasinghe** [comment]
> @Nautman while they have clicked delete, we don't store any data about them unless they undelete. whenever they log into their account, they just see the page _**you have requested an account delete, undo?**_

But this only happens if they request undelete before the 48 hour period right? Otherwise they have to create an account again

**Comment by nadirabbas** [comment]
yes

**Comment by nadirabbas** [comment]
Facebook does it too, so its pretty reasonable.

**Comment by Hasintha-Jayasinghe** [comment]
This shouldn't be too hard to implement. Would you like me to try?

**Comment by Hasintha-Jayasinghe** [comment]
@nadirabbas Would you like me to try and implement this sort of thing?

**Comment by nadirabbas** [comment]
@benawad needs to give a go-ahead.

**Comment by Nautman** [comment]
I still don't understand what the benefits are of storing user data for 48 hours. Perhaps it lets people regret what they have done? Besides, it will also complicate things as you will have to set up deletion jobs.

But I like the privacy point of not storing data afterwards. After all, this is supposed to be the next big thing ;)

Have you seen #1249 btw?

**Comment by nadirabbas** [comment]
you are not getting what i am trying to say, just lookup how Facebook does it.

**Comment by bansalarnav** [comment]
Keep track of bans using Email ID/Username/IP maybe instead of ID. This way even if a user deletes their account and makes a new one their Email ID/Username will remain the same and they will remain banned

**Comment by Nautman** [comment]
You bring up a good point @ArnavBansal11. Although, what if someone changes their email or username? What if someone registers with their username later on?

**Comment by TheOtterlord** [comment]
I think it's more likely they change username/email than remake an account with a bigger provider (that they probably use).
I:P bans can be avoided with a VPN easily these days.
I think the provider ID makes the most sense. It takes longer to change it and it is less likely people will

**Comment by nadirabbas** [comment]
lets do favicon fingerprinting to ban their devices lol
