### ISSUE TITLE
Smashed landing page links on mobile

### ISSUE THREAD

**Issue by andrewroblesdev** [benawad/dogehouse#990]
**Describe the bug**
On mobile landing page the links at the bottom are smushed together 

**Screenshots**
![image](https://user-images.githubusercontent.com/70864612/111101109-74c07500-8506-11eb-8c7a-7e5eb48f4a57.jpeg)

**What device are you on?**
iPhone XR

**Comment by tylerveen** [comment]
Yes

**Comment by JDOG787** [comment]
@andrewrobles would you mind if i try to work on this, or were you going to?

**Comment by tylerveen** [comment]
Yes you can! 

T. Veen

**Comment by andrewroblesdev** [comment]
@JDOG787 Go for it!

**Comment by JDOG787** [comment]
@andrewrobles thanks!
