### ISSUE TITLE
This has to be a joke

### ISSUE THREAD

**Issue by proudmuslim-dev** [benawad/dogehouse#995]
Please tell me this entire thing is a joke and will be deleted shortly

**Comment by ghost** [comment]
Please stop negative comments. Contibute only if you are willing to. Kindly do not put down other contributors

**Comment by jonlambert** [comment]
> Please tell me this entire thing is a joke and will be deleted shortly

No.

**Comment by dko1905** [comment]
This issue should be closed.

**Comment by proudmuslim-dev** [comment]
> Please stop negative comments. Contibute only if you are willing to. Kindly do not put down other contributors

Sorry about that, I hadn't meant to insult anyone
