### ISSUE TITLE
Not showing proper error message when clicking on the user who has already left the room. 

### ISSUE THREAD

**Issue by maskeynihal** [benawad/dogehouse#999]
**Describe the bug**
Showing whole error rather than error message while clicking on the user who has already left the room. 

**To Reproduce**
1. Click on the user name or user tagged (`@`) on chat who have already left the room. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26411488/111112932-17213c80-8589-11eb-9789-c4d0b3114145.png)

**Comment by nadirabbas** [comment]
this was fixed
